### ISSUE TITLE
Error on Nameplate with Specific Unit

### ISSUE THREAD

**Issue by Snackadoodle** [WeakAuras/WeakAuras2#2012] opened 2020-02-24 17:49 UTC
## Describe the bug
Supposedly meant to not give me an error, even though the weakaura still functions as normal, the error makes it disruptive.

**Do you have an error log of what happened?**
```
Message: Interface\AddOns\WeakAuras\Prototypes.lua:5509: Usage: UnitIsUnit("unit", "otherUnit")
Time: Mon Feb 24 18:41:01 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\Prototypes.lua:5509: Usage: UnitIsUnit("unit", "otherUnit")
[C]: in function `UnitIsUnit'
Interface\AddOns\WeakAuras\Prototypes.lua:5509: in function `?'
[string "--[==[ Error in 'cast':'condition checks' ]..."]:13: in function `?'
Interface\AddOns\WeakAuras\WeakAuras.lua:5913: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:5878>
Interface\AddOns\WeakAuras\WeakAuras.lua:5995: in function `UpdatedTriggerState'
Interface\AddOns\WeakAuras\WeakAuras.lua:5761: in function `UpdateFakeStatesFor'
Interface\AddOns\WeakAuras\WeakAuras.lua:5731: in function `FakeStatesFor'
Interface\AddOns\WeakAuras\WeakAuras.lua:4380: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4268>
Interface\AddOns\WeakAuras\WeakAuras.lua:4395: in function `Add'
...terface\AddOns\WeakAurasOptions\ConditionOptions.lua:1115: in function <...terface\AddOns\WeakAurasOptions\ConditionOptions.lua:1112>
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[C]: ?
...terface\AddOns\Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:72: in function <...terface\AddOns\Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
...terface\AddOns\Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:290: in function `Fire'
...ue\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:442: in function <...ue\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:433>
[C]: ?
...terface\AddOns\Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:72: in function <...terface\AddOns\Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
...terface\AddOns\Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:290: in function `Fire'
...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:351: in function <...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:341>

Locals: <none>
```

### To Reproduce

1. Make a progress bar aura
2. Make trigger Status / Cast / Unit: Nameplate
3. Go into Conditions and select If Trigger 1 Caster = (or != gives same error) Specific Unit
4. Error appears

**Screenshots**
No screenshot, but here's a link to the aura:
https://wago.io/H-7mtUgs5

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, gives same error.

**Which version of WeakAuras are you using?**
v2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [X] Classic
- [ ] Retail

**Comment by InfusOnWoW** [comment] 2020-02-24 20:25
I belive this issue to be fixed with a unrelated rework of the Cast trigger that is coming in the next version. I can't reproduce it neither with your instructions nor with the aura linked.

**Closed by InfusOnWoW** 2020-02-24 20:25 UTC
Labels: 🐛 Bug
