### ISSUE TITLE
Get this error in wow Classic

### ISSUE THREAD

**Issue by Knakriktsur** [WeakAuras/WeakAuras2#2365] opened 2020-08-04 12:07 UTC
Hi, I get this error in wow classic. Also it says X-Perl I only use Z-Perl? And there is no X-Perl in my addon folder.

Date: 2020-08-03 20:49:08
ID: 2
Error occured in: AddOn: WeakAuras
Count: 16
Message: Note: AddOn WeakAuras attempted to call a protected function (XPerl_PlayerbuffFrameAuraButton1:ClearAllPoints()) during combat lockdown.
Debug:
   [C]: ClearAllPoints()
   ..\FrameXML\SecureGroupHeaders.lua:753:
      ..\FrameXML\SecureGroupHeaders.lua:728
   ..\FrameXML\SecureGroupHeaders.lua:1046: SecureAuraHeader_Update()
   ..\FrameXML\SecureGroupHeaders.lua:686:
      ..\FrameXML\SecureGroupHeaders.lua:682

**Comment by InfusOnWoW** [comment] 2020-08-04 12:59
That sounds like a duplicate of #2329

**Closed by InfusOnWoW** 2020-08-04 12:59 UTC
Labels: 🐛 Bug

**Comment by Knakriktsur** [comment] 2020-08-04 14:32
Might be. I`m not in a group or raid though. I just logged in an used my shapeshift macro bear which puts you in combat for short time maybe because of /startattack . But this doesn’t seem to be the case, cat macro doesn’t put me in combat.


Bear
#showtooltip
/cancelaura Raubtierschläge
/cancelaura Rudelführer
/cancelform
/wirken Terrorbärengestalt(Gestaltwandel)
/anlegen Blutdurchnässte Maske
/startattack

Cat
#showtooltip
/cancelaura Raubtierschläge
/cancelaura Rudelführer
/cancelform
/wirken Katzengestalt(Gestaltwandel)
/startattack

So, here is the deal, did some testing. Cat macro works fine.
If I use bear macro I enter combat. BSCT (Blizzard Scrolling Combat Text) sexy entering battle. After a second I leave combat because of no enemy and instantly the error triggers. It seems to trigger when "Furor" removes.


BSCT:
Dire Bear Form
Leader of the Pack
Furor

Starting battle
Furor fades -> TRIGGER
Leaving battle

Hope it helps.
