### ISSUE TITLE
4.1.4 Raid frames weak auras not working for aptechka

### ISSUE THREAD

**Issue by Pahweh** [WeakAuras/WeakAuras2#3848] opened 2022-09-30 23:13 UTC
### Description

4.1.4 seems to have broken raid frame weak auras for aptechka.  Going back to 4.1.3 fixes them

### WeakAuras Version

Weakauras 4.1.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

L

### Reproduction Steps

1. Trigger raid frame weak auras, notice that it doesn't show up on aptechka frames

### Last Good Version

Weakauras 4.1.3

**Comment by mrbuds** [comment] 2022-09-30 23:26
We need much better reproduction steps.
If i install fresh weakauras 4.1.4 and i don't know what version of aptechka, what is import string of aura you made, what do you do from login to moment problem happen to reproduce the issue.

**Comment by Pahweh** [comment] 2022-09-30 23:42
Aptechka 9.2.18.  Testing using these auras: https://wago.io/IhVJONWXu and https://wago.io/wfjlGgsWX.  Happens in group, haven't tested solo since I don't have Aptechka set to show any unit frames solo.  I'm not sure what you mean by addon profile, but I do have various other addons but I haven't added or removed any between this working vs breaking.  This issue has been noticed by at least one other person on the priest discord, who fixed it by rolling back to WA 4.1.3.  Reproduction is essentially:
1. Log in
2. Join group
3. Apply Power Word: Shield to anyone in group, weak aura does not show up

I don't think it is specific to these particular weak auras, but they are the only raid frame/group frame ones I use outside of raiding to test with.  A few days ago you fixed a different issue where weak auras like this would show on all the Aptechka unit frames except for the player's specific one.  Not sure if that is related in any way.

Apologies for lack of detail, currently waiting in queue to test further.

**Comment by mrbuds** [comment] 2022-09-30 23:46
Is it working with a simple aura trigger?

**Comment by mrbuds** [comment] 2022-09-30 23:56
Your aura works for me on wotlk beta 
![image](https://user-images.githubusercontent.com/189656/193370487-189e6129-bc99-4733-91e6-b633ed20924a.png)

**Comment by Pahweh** [comment] 2022-09-30 23:59
Still about 50 min until I can test unfortunately but will try something simpler when I am able to log in.

**Comment by Pahweh** [comment] 2022-10-01 13:52
I wasn't able to get it working with 4.1.3 like the other guy, nor by switching to a different raid frame.  Leaning towards some other addon update causing issues.  Is there an easy way in game to troubleshoot what frame libgetframe would be returning?

**Comment by mrbuds** [comment] 2022-10-01 13:58
I close this ticket until you can give a minimal reproducible example that doesn't use custom code

**Closed by mrbuds** 2022-10-01 13:58 UTC
Labels: 🐛 Bug, 🤷‍♀️ Can't Reproduce

**Comment by Pahweh** [comment] 2022-10-03 04:55
Did some more testing and it seems like it's this addon that is causing them not to show: https://www.curseforge.com/wow/addons/wow-pro v 2020.09.29.A

Here is my test aura: beep plus little bouncing icon when eating
`!WA:2!fsvZUTTrq4kOIMc1trP1biNecGnIDdmGLDsrlqpizlLOwzlvkABLwdiUK7qYTMAx2DxkBLJ6uoRhbDUN0tqBEcwi0NG8i4NGoljJlqbkQoOD5m78338ntLU1NwNwN(UgYBhegQaD)kY5f32DnHhelKdfmUED7bUUdo1P3RETRKeOzcU6LoknrQ3XrjY400d6X1GmKeax1IshWvxDjqUUvMKOU6uGYixnY(o1vVkHOu7pn9WfuXKCB9AZ4mDn)q8qfxBHwYIIaP6SDKLxF3JwsqpXjtb1tAE0Hh(HaXuFghgcYZrB92mLOdIb1OyXnd4Bu5hNYukgpYj3SAROGFwyO78uq(6o9h298(RSV74ebhuERyrCHeobi047YuqNBX6CukKK0JgVoTioNkOWcsyieObQdmd4A)xdKeD8A0ehcJ6isG406LoJPceCE(RJL4lodZeVfQcVQQ9bvMFUtgHjg721toU1i3jJCB54EVQHsav5mAyN(9BRXK3XIenFV9)ChXOQN408fnB2SDgMIorsrw6YmEj0vBnLP(1mo20MbnjjjPpKKF3TqVTK(9p5oMT7XjjxG4o2DVEjHZqmfV(sZNDHz72CeLwaefybqZbBOy8TQNyZjPcWcLQ8tLaYDw7JT1aeldiZFV1MrAjWJ0XpO9ucJ)Uh5hisesNQMdnhvCVD1IZxvDdItt0yZwLq0GNzB)GmLwm10eJ69Y7Ibi9pdZRlb)zPsregA1ZBKtkhxE(MN3GcjAY4YZ3SBTg4VerajPrzsYWxINn((gy9gVpYyU3Bn2RqwkRWojOZK8Yq04RB8S)Ll2RmA7(XW)F)gmtaoTMVcZeyEvhssAmPYIpIQpD)dRp)RQFBL)PIT4UFHZ8LcnkPsbK1QQ5BEG5fMtkC2TvnFrxZ2MdSsr81IBi3xr0wFJKZhIeIaSuGj5UbJwLviBZbISJ17TLz7n4N(KGRTujoneBNskiNOyVfQA2EPvBUK3xQipn(HkvQu9dLsMXum)eW7JMc0ii9HJ(TmIeA0nljPXLXmnSPuTiFLtf)yGffRFSPJx7ebHoBHLl8wK5fV0EJJteYyFnwLC9wotZs0SAob2fk74Bh1ta)Ho96mY1mElZV4LBejbj7ETXzLGTmJR12wf7y(5MAGBg31mXZjfBvZ9813GEDU3QIZqRv3PHBrydUussTdkPF5X9BD6q3bT7364FS1jN0ZT3fD8NYKsHmELmhcZ3WuA4see4uRPoT735StmrPF3)7Is3cBvxvGxtS4voCzAvDPcscZ3jB(0vArWSI51pF2F8ug1Vd2oXfE3WO64hVouIRBWrpIM8O7k2M31kYMGlp)SEUDDADAhNYUx1kvBMXORNMkMF93(tJf9pCdjtJgninFHFnKUXdzr1wzN1zfYwZ4HczXMIAlUNqvx5C0(hS)r1N9xJ)7d`

To reproduce, I login with only Aptechka and Weak Auras and eat some tough jerky.  Result is sound and bouncing icon:
<img width="122" alt="image" src="https://user-images.githubusercontent.com/88849481/193503808-12c9ed91-5379-419b-a25e-c2212b98bada.png">

Then I enable Wow-Pro and Wow-Pro Leveling and repeat the same steps, and only get the sound, no icon.  I tried with Vuhdo instead of Aptechka and had the same result.

**Comment by Pahweh** [comment] 2022-10-03 19:19
@mrbuds would it be better if I recreate this as a new issue?  I also have a ticket opened with the WoW-Pro devs to see if its something they can look into on their end as well.

**Comment by InfusOnWoW** [comment] 2022-10-03 19:31
you probably should install the bugsack and buggrabber addons to get lua errors displayed.

**Comment by Pahweh** [comment] 2022-10-03 21:45
> you probably should install the bugsack and buggrabber addons to get lua errors displayed.

There haven't been any errors caught in my previous testing, but I haven't tried a minimum addon setup with just those in addition.
