### ISSUE TITLE
GetSpellCost on Talent Node Swap

### ISSUE THREAD

**Issue by loIswirl** [WeakAuras/WeakAuras2#5143] opened 2024-06-12 16:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Changing nodes within the talent tree gives an error of GetSpellCost on a progress bar that has a trigger of power/player/mana with overlay cost of casts enabled

### WeakAuras Version

WeakAuras 5.13.2-31-gcf021a4

### World of Warcraft Flavor

Beta (WoW 11.0)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
1x Lua error in aura 'Mistweaver - Mana': Trigger 1
WeakAuras Version: 5.13.2-31-gcf021a4
Aura Version: 10.2.3
WeakAuras/GenericTrigger.lua:3815: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@WeakAuras/GenericTrigger.lua"]:3815: in function `GetSpellCost'
[string ""]:21: in function <[string ""]:4>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:687: in function <WeakAuras/GenericTrigger.lua:627>
[string "@WeakAuras/GenericTrigger.lua"]:866: in function `ScanUnitEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1157: in function <WeakAuras/GenericTrigger.lua:1153>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
```

### Reproduction Steps

1. Enable weakaura that has a mana progress bar with overlaying costs of spells
2. Change talents, whether it be specs or nodes within the tree

### Export String

```Text
!WA:2!nErtVTXXvXqGyaHCqIorWX1cvXOwnWfwwIYYUWifUCLifvRePYsQyNGaS7S7oK7yVCNjZmuIsUTgrOh8zg0ZTGNBbk4TEOxul65fe5xaJp0BfqaTxtFZml)q2cWrheN3BN33FozkLRvUGCbVSCpbdXF2JjbYWpOhXNgxJ2M7JVXm8ovB0qGLz4hNEOpk2pKY3NsILEBwSs9I2d0uBtLijHgNjFBEe7gHsjt8W7E3JqnPRqO39KTFwZOVsW8V7gBCUhY)zn502XbBsJO8FvMmzk)OVB91)LZmZv72GgllfHAk4vpO(U7uPOwJC813ml83qCmYlcVnhfqWXYWUcCudTcL8UN6H4gEw(r)JV5B(JF)3xP8J(3D68NMzM5k)O)ZlEbC4NMTxawGKT5ijo8mT2BSUppd7QntzBvU6)AtQx5Q278fvRuVWUwruuWlF)bTfyhgw6HKYiCyxfym(qmp06eAmopYZNLtH0pcjeoO4ahbd772DmoxloncVGDR2rsYSCfv7eiEhnJJrTWCmkQvixIIaTi)cjlo7WlYRL9eK4Mr4xnxYI3)BNZ9vZ5(pNZ1ZqG6(w6BLCZSjl(qxx3EbKgni(G4ow91tvcsj1qlb5eScfVbYxzUAI5iFnsBTub2yBxD7dkMS4c93QyH6L)1v2z7Y1D5GoabsM6QDzhYMi(HIwuQmCFoTjhd2lBoqIfcEABHehGd2Jeh2JJBcYR(Xmmhbrdi2XL4oqGbBVhokIyIn1nOyF8oXsSsjXF5MiHeKSfI)LhSZDMaDNAkcSqTLu3EsQpereGeUwM)YF1gfXcrznP6BojzYJYdWCliJmGtzwvaxINkPDNT6ooNTpkvVbT(3)ES5Vqc)E0aSvHdQx9ujN0SjiXklZtp(YBP9Z82XyxoepII2jWo)gp4bRnOfs6hIf1cPhvn(mH(NcG))q8zksui2KkKU99bjtB5escW2sslCW5QVhG9A3OXMQGtOcrXoqWRMrcH9gXHQXU2qAzS0EF6ryUoga5TqTDSKPWe2xFvdDUwQmV(LOCpmIdf6ylLMNDOpTLhjgVNrL7P48Ua1c5PnAhfj8rXUdb(STktakuBdfLdAIJXCIVX(skR9dTJjs3KFKrOskfs9zHMAjLYiHeb3Ek7AevwkuwkY6zmyDUs5c27v6GDv6MY2sEWzQShTrqcexpPKTYoex)STihcQ9s1KyCWqrBp91RbSH0PVZMfQv3Pw9c21pnq1kacL5wl52j)SUJvMmNM6zeZM46XIqhJ5J5Z(CmWh7A7xC3DzZRmIlyYUNnTF(65xB1vzFW0OCOQ0EjLF9CFsxWLzYywiXnjQFar802X6SH8O4JzZJ0NRBUJkJ7ppZ5ev5qmk6Zmj5)HHS0Ant37BFJzENUOyslTPDFBHeXLLsCSIHu8ZWibUMKJJBkdVYGroahLvZfyOHBG4u1Duo8KNB1crIbAtEEYV5kj)2KFxYlsEUxdsmre(6O1D3v1s7exId9YdhcvN(p74TsLripTQK2dCL26waIVyHeNba4KjdPiAqHMeAeVmxEeJeoe6s40c8arqJucZTV5Sq60w8Pta4NKzkGJZCMbObjc6Z6TE(F(gRUApdogsgY(iDKwCxehYMXMae4XKq7AiLxUsR8tyN84mCdWXtlKoVAUt5JMcM4CkO96pofHDgr4yTZ0vAGb4qIGat2cNIItgrrNmhM40v5I0nSgy(XXmoop4ugHHQhLL9Suq)rtyh1QBKuC7NcJdAIzZx7RAJ44Lkbf0l94qIep6ZQXdzF5Ty5uTMHUkOa6rpXmVml7d1i1)dIuqQMJi9qxlsZkTB5H5DhFh2C3ATvMUg4wS5MIRJxgi75gos6Gd0BL81SB)gc6ICYb55XXhsuJ07PJcy1CdRkvRuK9tEdIzqduFO0aI(C4GkDmdBLF4YWPfQZ890xDYIjxWf95gx0nMzGg5rGZ8XCe70hNEyqQCIL6sS3BcCnWHV4atGn1rNHT4Lyc6YcDjRDJikL)2Ds6Tk07xyRxx5sIFS0dEMGh7hFz8uZmdyYZzxv)v1qxvVgFDeZQaaMAePUImNPVNAskPXXjVBIdhsN15fgh3RzYR92SgpstNyTwMEb28fghHmQVO7y3QDfe9OWFa(OXE1K)2fuSrMbB53gls9m)93UjCjzH36TrJoHZnTYzQ1XT2TyP6Sp6sIOQ1gMiISxA9WB4mt(xdnPZJ3UUWLqO4Yi0eOh1NXletAgkVYG0D7mJNYVBT9gQxKYcwzmqntlFHT2AWOPhJxrB)SRUYgEcnrEKwmkxARPlSpj2irWOwUpC0hxunzweYUgPzmm5Okt9nHgBroNYfH5Btc6VwJ4nFYhh807B)PdG8wWdMEZzzZz8OL4qrI(FSp8Xy0ZkO2W4H7HIrlb7zUub9L6R1JYAZ7xK2)D0up4Ha0wz6QF7IqT7MTAH5EMT5uTMU5SGWMaEalaYA9AR)bg4prl2h6ldm0(ivD19U25uOWfwfrKUx81tU30VH5jz8e4wWv8wB1vYVY6CZs9I7NCYYEgXbsUBa1XaeAbtXLlN8FbSj)VWKVE8XuRJeeGJTRu8ZkAFtsaB(9ic5ryeiHLUZskhs)gkTewMajrzpFkfx1yRFTI7wCZ6LSlSxrlLZi81FiaQti8kc1ob4qZtj3Y86myoiDYJWsE)EQTsiMWu3rVZlpKIKjRh8PgKMZMtWYTXkRT(k5VZ6RDNM(nwn)AO7L7WV9j))
```

### Bisector Report

```Text
Bisect results:

report version: 2
addon version: v1.3.0
mode at print: done
bisect origin: cli
last test result: bad
Bisect took 1 out of (3-10) steps
Hints taken: 1
Addons ruled out: 3
Addons proved: 0

Narrowest set of addons that reproduces the issue:
|-- H:WeakAuras @ 5.13.2-31-gcf021a4
|  |-- D:WeakAuras Archive @ 5.13.2-31-gcf021a4
|  |-- d:WeakAuras Model Paths @ 5.13.2-31-gcf021a4
|  |-- D:WeakAuras Options @ 5.13.2-31-gcf021a4
|  |  |--WeakAuras Model Paths...(see above)
|  |  |-- d:WeakAuras Templates @ 5.13.2-31-gcf021a4
|  |--WeakAuras Templates...(see above)
|-- E:WeakAuras Companion @ 4.1.0
|-- A:Bisector @ 1.1.2
|-- A:BugGrabber @ v10.2.4
|-- A:BugSack @ v10.2.6

Libraries:
LibCompress @ 90083
LibGetFrame-1.0 @ 57
LibSharedMedia-3.0 @ 8020003
LibDBIcon-1.0 @ 52
AceGUI-3.0 @ 41
LibUIDropDownMenu-4.0 @ 90135
AceConfigRegistry-3.0 @ 21
AceGUI-3.0-DropDown-ItemBase @ 2000
LibDataBroker-1.1 @ 4
AceTimer-3.0 @ 17
LibCustomGlow-1.0 @ 19
AceComm-3.0 @ 14
AceConfigDialog-3.0 @ 86
LibSerialize @ 1
AceGUISharedMediaWidgets-1.0 @ 9004
AceEvent-3.0 @ 4
LibRangeCheck-3.0 @ 19
SpellRange-1.0 @ 20
LibSpecialization @ 10
CallbackHandler-1.0 @ 8
LibDeflate @ 1
AceConsole-3.0 @ 7
AceConfig-3.0 @ 3
AceSerializer-3.0 @ 5
AceConfigCmd-3.0 @ 14
```

**Comment by mrbuds** [comment] 2024-06-12 16:31
duplicate of #5142

**Closed by mrbuds** 2024-06-12 16:31 UTC
Labels: ⏱ Awaiting Response
