### ISSUE TITLE
Feature of the Pixel glow seems strange.

### ISSUE THREAD

**Issue by ILIKECHICKENTOOMUCH** [WeakAuras/WeakAuras2#994] opened 2018-12-02 12:32 UTC
**Describe the bug**
- Pixel glow seems strange.

**What steps will reproduce the problem?**
- With the pixel glow feature...

**What is the expected output? What do you see instead?**
- I think that the glow of all sides should be constant. But it does not.

**Do you have an error log of what happened?**
- No lua error occurred.

**Screenshots & Additional context**
![yqclj88](https://user-images.githubusercontent.com/33839642/49339841-b94bdd80-f67a-11e8-8c33-4426708f1dc8.gif)
![b844sgd](https://user-images.githubusercontent.com/33839642/49339842-bc46ce00-f67a-11e8-8089-82428915b2f2.gif)

- I am a character class hunter. So I set up a weakauras as a hunter skill.
In the image above, the red marked are fade and then thickened again.
However, icons that are not marked in red will look good on all sides.
I have copied the code to Pastebin.com Please check.

https://pastebin.com/96fgmecp
https://pastebin.com/WtX47MJr

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
- Yes, I only activated the Blizzard UI and Weakauras. 
Image of the screenshot will appear to have "Clean Icons - Thin" installed,
but the problem was the same even with "Clean Icons - Thin" removed.
https://www.wowinterface.com/downloads/info24559-CleanIcons-ThinFanUpdate.html

![honeycam 2018-12-02 21-53-52](https://user-images.githubusercontent.com/33839642/49339968-dc778c80-f67c-11e8-9dc6-010d648345e0.gif)

**Which version of WeakAuras are you using?**
- I'm using the 2.10.2 version. 

**Was it working in a previous version? If yes, which was the last good one?**
- This problem also existed in previous versions.

**Comment by InfusOnWoW** [comment] 2018-12-02 15:54
We are using a library: https://wow.curseforge.com/projects/libcustomglow to provide the different glows. We did forward that bug report to the author of that library.

The underlying problem is that the coordinate system in WoW is a bit strange, and thus your auras don't usually actually end up on exact pixels. Thus what you are seeing is the glow line falling on a exact pixel but on two pixels.

This can be fixed by setting the uiscale in a way that the wow pixel grid lines up with the real pixel grid, e.g. https://www.reddit.com/r/WowUI/comments/95o7qc/other_how_to_pixel_perfect_ui_xpost_rwow/ contains a bit more information on that issue. 

Thus this in essence a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/236

**Closed by InfusOnWoW** 2018-12-02 15:54 UTC
