### ISSUE TITLE
Allow copy-pasting of only positional/size data, or only Text/Glow/Display data.

### ISSUE THREAD

**Issue by PaterFrog** [WeakAuras/WeakAuras2#3145] opened 2021-06-11 08:21 UTC
**Is your feature request related to a problem? Please describe.**
It's often not feasible to copy-paste the Display tab between auras, as you may want texts/glow, etc., but not the positions, or vice versa.

**Describe the solution you'd like**
The right-click menu should allow copying only the positions/size, or only the other display settings like texts, or all.

**Describe alternatives you've considered**
Perhaps it makes sense to separate coordinates of the aura and other display options (like text, glow) into separate tabs?

**Additional context**
This issue was most annoying while creating a Hotbar replacement UI when I needed to move spells/buffs around.

**Comment by InfusOnWoW** [comment] 2021-06-11 18:25
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/1303

**Closed by InfusOnWoW** 2021-06-11 18:25 UTC
Labels: 🎨 Feature Request
