### ISSUE TITLE
Texture weakauras now have crop/zoom errors without any options to correct it.

### ISSUE THREAD

**Issue by UnaffiliatedGamer** [WeakAuras/WeakAuras2#4109] opened 2022-12-05 13:38 UTC
### Description

A good number of 'texture' weakauras now look very wrong. It looks like the texture has been zoomed out and the empty space filled with random lines and marks that look like visual glitches. There are no crop/zoom options so this cannot be manually corrected. This issue briefly appeared in version 5.2.1 of weakauras too, but was resolved by disabling the new 'Legacy Zoom Out' tick option that had appeared around the same time.

### WeakAuras Version

5.3.0, 5.3.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

New or existing weakauras of the 'Texture' type, with any trigger.
Choose Texture.
Dropdown list folders - Blizzard Atlas
Multiple textures are affected, for example "ui-hud-actionbar-wyvern-left"

### Last Good Version

5.2.2

**Comment by InfusOnWoW** [comment] 2022-12-05 19:19
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4101

**Closed by InfusOnWoW** 2022-12-05 19:19 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
