### ISSUE TITLE
Update Error in WA

### ISSUE THREAD

**Issue by Moefina** [WeakAuras/WeakAuras2#2448] opened 2020-09-07 18:57 UTC
## Describe the bug
I tried to update Weakaura "Queen's Decree Say Chat Announcer" V 1.0.7 which is a part of Azshara Decree Helper (https://wago.io/GrbGKhzKH/8). It failed, likely due to it being only part of the weakaura on wago. 

**Do you have an error log of what happened?**

```
1x WeakAuras\Transmission.lua:1282: attempt to get length of field 'controlledChildren' (a nil value)
[string "@WeakAuras\Transmission.lua"]:1282: in function `MatchInfo'
[string "@WeakAuras\Transmission.lua"]:1820: in function `Import'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:822: in function `func'
[string "@FrameXML\UIDropDownMenu.lua"]:895: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

### To Reproduce

1. Get a weakaura group from wago (older version for it to show updates)
2. Rip one child out of the group, delete rest
3. Try to update the single weakaura now with companion/addon

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, still same behaviour. Active Addons:
![grafik](https://user-images.githubusercontent.com/70914507/92412463-41aeba80-f14c-11ea-8a55-8b5079d9da9d.png)

**Which version of WeakAuras are you using?**
2.18.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [ ] Shadowlands

**Comment by mrbuds** [comment] 2020-09-08 01:41
duplicate of https://github.com/WeakAuras/WeakAuras-Companion/issues/68

**Closed by mrbuds** 2020-09-08 01:41 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate
