### ISSUE TITLE
Cooldown Progress (Item) Broken

### ISSUE THREAD

**Issue by Dday0481** [WeakAuras/WeakAuras2#4246] opened 2023-01-17 21:42 UTC
### Description

Any of my WeakAuras that used the Trigger "Cooldown Progress (Item)" are now broken on most recent update. It basically does not allow me to select that trigger at all. Any time I select Item, it auto selects the "Player" radio button. If I select  "Cooldown Progress (Item)" from the drop-down, it will not take. I think it has something to do with "Player" being auto-selected.

I have tried fixing my existing auras, and tried creating a brand new one to test to make sure the group wasn't mucked up. 

### WeakAuras Version

5.3.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Go to Triggers
Type = Item
Try selecting Cooldown Progress (Item)

### Screenshots

![Screenshot_20230117_023946](https://user-images.githubusercontent.com/122937993/213018432-eab2c01f-1634-499e-a5fa-8104ad96d238.png)
![Screenshot_20230117_023955](https://user-images.githubusercontent.com/122937993/213018434-792b893a-9ae4-4e43-ab42-7e177b53e58d.png)

**Comment by Dday0481** [comment] 2023-01-17 21:44
I have also imported some WAs that do something similar from WagIO and they all seem broken

**Comment by emptyrivers** [comment] 2023-01-17 21:54
duplicate of #4215, which has been fixed and is awaiting the next release

**Comment by InfusOnWoW** [comment] 2023-01-17 21:54
That's because blizzard has changed the item apis and they don't believe in doing that professional, so the old api is just gone.

The next release will fix that.

**Closed by emptyrivers** 2023-01-17 21:54 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate

**Comment by Dday0481** [comment] 2023-01-17 22:03
Thanks for the quick response guys!! <3
