### ISSUE TITLE
Pins/Prioritization for sorting auras in list.

### ISSUE THREAD

**Issue by Hekili** [WeakAuras/WeakAuras2#1274] opened 2019-03-31 22:19 UTC
**Is your feature request related to a problem? Please describe.**
The aura list (left panel in /wa) is sorted alphabetically, which leads to people using namespacing to try to sort their higher priority auras to the top of the list (i.e., starting aura names with exclamation points or other symbols).

**Describe the solution you'd like**
A dropdown/flag/tag/attribute on auras to impact sort priority (perhaps w/ a color flag) so that people can flag their "Retribution HUD" as priority 1 and have that aura/group show up at the top of the list vs. other auras.

I would recommend that this be a local flag on the aura that doesn't proliferate to wago.io or other sources, so that individual users' priorities are preserved and independent of one-another.

**Describe alternatives you've considered**
Quitting WoW, becoming a hermit.

**Additional context**
This seems suboptimal.  
![image](https://user-images.githubusercontent.com/9438134/55295986-72c87e80-53e1-11e9-8ea8-812727340b78.png)

**Comment by emptyrivers** [comment] 2019-03-31 22:21
Hey, that's not a bad idea. I'm marking it as a duplicate of #581, though.

**Closed by emptyrivers** 2019-03-31 22:21 UTC
Labels: 👯‍♀️ Duplicate, 🛠 Feature Request
