### ISSUE TITLE
Adjust the size and position of the progress bar icon individually 

### ISSUE THREAD

**Issue by Solor** [WeakAuras/WeakAuras2#3338] opened 2021-10-30 15:40 UTC
**Is your feature request related to a problem? Please describe.**
The icon of the progress bar can only be adjusted left and right, and cannot be adjusted in size and position 

**Describe the solution you'd like**
Add more options for individually adjusting the icon, such as the size of the icon and the precise position based on the XY axis

**Comment by InfusOnWoW** [comment] 2021-10-30 19:27
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/1813

**Closed by InfusOnWoW** 2021-10-30 19:27 UTC
Labels: 🎨 Feature Request
