### ISSUE TITLE
Event type trigger - duration does not update when changed.

### ISSUE THREAD

**Issue by BillWiegert** [WeakAuras/WeakAuras2#2428] opened 2020-08-28 06:32 UTC
## Describe the bug
When the hide duration of an event trigger is changed, the actual duration of the trigger does not update until some other change is made to the trigger.

### To Reproduce

1. Create a trigger with type Event -> Combat Log -> Spell Cast Start, Source Unit = player, Hide = Timed, Duration = 10s.
2. Cast a spell to trigger the aura, observe expected behavior.
3. Change Duration to 1s.
4. Cast spell again, duration remains 10s instead of the new desired duration.

**Which version of WeakAuras are you using?**
3.0.0-alpha9

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail
- [x] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Same bug occurs in version 2.18.1 on retail

**Comment by InfusOnWoW** [comment] 2020-08-29 20:37
That should already be fixed for the next releases.

**Comment by InfusOnWoW** [comment] 2020-08-29 20:48
Actually either I didn't fix it, or the commit got lost somewhere.

**Comment by InfusOnWoW** [comment] 2020-08-29 21:37
Duplicate of #2404

**Closed by InfusOnWoW** 2020-08-29 21:37 UTC
Labels: 🐛 Bug
