### ISSUE TITLE
Frame Strata of display button above title bar

### ISSUE THREAD

**Issue by nnogga** [WeakAuras/WeakAuras2#384] opened 2018-04-18 23:38 UTC
What steps will reproduce the problem?
Scroll the list of display buttons in Weak Auras in such a way that the top display button is barely visible.

What is the expected output? What do you see instead?
I expect to drag the WeakAuras Window by clicking on the title bar. Instead i am picking up the top WeakAura with the drag and drop function.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

What version of WeakAuras are you using?
WeakAuras 2.5.10

Was it working in a previous version? If yes, which was the last good one?

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

Please provide any additional information below.
Screenshot of /fstack: https://i.imgur.com/vuhpKV8.jpg

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by InfusOnWoW** [comment] 2018-04-19 05:59
That's a wow bug, not a frame strata bug. I'll see if we can work around it.

**Comment by Stanzilla** [comment] 2018-04-25 20:33
`[22:29:40] TheDanW: AcidWeb: we tracked down the bug with child frames of clipping frames not being clipped for mouse handling, will be fixed in a new beta build`

**Comment by InfusOnWoW** [comment] 2018-04-25 20:34
Stan beat me to it

**Comment by InfusOnWoW** [comment] 2018-05-19 17:04
I can't reproduce the issue on 8.0, so believe it is fixed in 8.0.

**Closed by InfusOnWoW** 2018-05-19 17:04 UTC
