### ISSUE TITLE
possible issue with trigger based on character stats

### ISSUE THREAD

**Issue by isanusi123** [WeakAuras/WeakAuras2#5049] opened 2024-05-03 15:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

trigger is set for hit rating <= 150 .  This is meant to pick up healing gear in dps spec.  Load is set for dps (ele) spec only.  It does not trigger when i am wearing gear without hit.  I have an inverse wa for dps gear in healing (resto) spec, that triggers on hit rating > 150, which doesn't work either.  I've tested without the hit rating, and it appears to load properly.  also tested with all other addons disabled.  I have a similar set on my druid, same behavior.  Bug sack does not show an error.  When i test this on a char that does not have dual spec, it works.

### WeakAuras Version

5.12.9

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

use a dual spec class, like shaman or druid, with caster dps and resto spec
make a weakaura that shows a text message.  my message is "low hit in dps spec"
set the load condition to class and spec (elemental for shaman, balance for druid)
set the trigger to player/unit info, character stats, hit rating , < , 100
test by switching gear sets from ele to resto.

### Last Good Version

worked before cata prepatch

### Export String

```Text
!WA:2!fs1tVTrru8yTIs7QkuQdeOPLY2wivqHqtkPvbQeXRLnPi3K01BBchG1ZUZSEh66zMoZSjX5eYcv1ZPNrc5Z9K)i0dC(jl(eKpc9taZ41eqveHp4D(Z79MFVFVFVxLhxvfV6slVYsRvTxvCv8ZVY4yuYtWsUOopNl)EhhNTDU1sRouZt2Jivuo7S)gCCmxIjs)PMkM1pNE4Hij2lKZZ1uXyuHoJl3sOnoOCJlTpt2FR0ufrxzOK01CtyFbjORKxigwArB6HK361uMMizO8hx(GVyu5LLiQsLkobQeuoXzQtnWDjIl0(PfijXRzrEU3ozuteqjtE97eO0iP2noLYOQmxFZhT7aTK2TR5bwyr50LpBiMexKMArLCJgT2U5JA5RTqevirRmqji553hRCpwvet2JW0Tnwtpyuu9ATdJAhwli0VWe8yroQprgWq9ik3GjMgVbbLRZoX1TLeJRbT3UrRwhvWMcb3riwIH42MB4G46n2mSrWRkZYsM7C(5CeUzS2K)m98b9km0TRVbAjZd30nijhPu2v(kdvAxCeIr7HSmXDGQnFfbPiT1scRRo7THl6Z4mYySj)SwezZwPIKWzy1aRPwUaw2VhIYAc3Y4aSmScCB4RmFN7np5AuCC7mupetEW0cDakxKHCEDzA1uAyeBiJBxpOrJnhLApWahKg5SsbfpAT72N)D708G(0hoTQFFMjoodn8wWenJY9ifjpDcdb3yOfQ0sv2iklLllZv3yZfP0UUvtw453WOW05uMHeFuyR7VzJGK)wC7iUjMQS1RqYb6Os)JerAApseUVPcstI0zsIkJNJ7pwLHW89)HYS7YZalc3q4D6rOCxfXSjfknVN1IhjWinbU6XMweUfSj7qX6m)AMTWfm1ixyox4DDH37DweM)poYiLTfhw3fwz5vVLHUVcCz4dHR(66ziReNi9ARrA1GcfjYQ(6axh(y4sUgd)ir1tCpIBkTinxUq17bEUJTMFYLDG3h(a4tCfxW20ShjSuo(aoM8Yzex70tWECCKjeKoIfpDJYjDrj9JsZ5CzgSES)wHHB9a)uotlMTPKEO3dlqyRiWlme(2fMhU4yt92ojYoCGHHp9zhzX7e1DNjlr5gy254jNeHy4iBlWIXktYKtcNfU58HZ2b(mBha8flc)yC7nQ9GABA2kQEsOoXXoWNpXYLS)pWcm7KOvNwU3TSC7aNZxBYo4UBS(mn(9zm)GV02u9MngR()3QiU0)jDvUiWYAyX1pDgvijju7SrhOM7G9nnk7irIb7mDbu3v(ZgfhnTVFRgndbhZqBt35XyHYRlbj9sYijpboJl8noWAWxdNDJ1)jVZ8l2u6EJ2l92P572K(000r)lmiMlNVVNrZ4rzE2izzUrLu0)mBEOzSgbprt)RNh8DHZ)IQ79N7(xd
```

**Comment by isanusi123** [comment] 2024-05-03 16:00
I think this is related to the translation of spirit to hit.  I had assumed that when i ask for 'hit rating' it would give me the actual hit on my gear.  I think it's returning the hit+spirit.

**Comment by mrbuds** [comment] 2024-05-03 18:08
I can't reproduce any problem with the character stats, switching gear correctly update the aura for me.
Please provide more details, i don't know what "the talent that uses spirit as hit" is

**Comment by InfusOnWoW** [comment] 2024-05-03 18:11
@mrbuds this one: https://www.wowhead.com/cata/spell=47573/twisted-faith

And I think that's a won't fix. The character stats should check effective stats, not stats on gear.

**Closed** 2024-05-03 18:18 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response

**Comment by isanusi123** [comment] 2024-05-03 18:28
perhaps you would be so kind as to point out how i would access the actual hit number, since it will not be a provided function?
