### ISSUE TITLE
LUA ERROR ON LOGIN

### ISSUE THREAD

**Issue by Japierdole123** [WeakAuras/WeakAuras2#4418] opened 2023-05-02 15:07 UTC
### Description

Hey,

Geting this error every time i login.
Any idea why?

### WeakAuras Version

10.1.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
Message: Interface/AddOns/WeakAuras/Types_Retail.lua:181: attempt to call field 'InitializeViewLoadout' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types_Retail.lua"]:181: in function `GetTalentData'
[string "@Interface/AddOns/WeakAuras/Prototypes.lua"]:1278: in function `enableTest'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:607>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2966: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2876>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3044: in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2502: in function `AddMany'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1154: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1125>

Time: Tue May  2 17:05:44 2023
Count: 1
Stack: Interface/AddOns/WeakAuras/Types_Retail.lua:181: attempt to call field 'InitializeViewLoadout' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types_Retail.lua"]:181: in function `GetTalentData'
[string "@Interface/AddOns/WeakAuras/Prototypes.lua"]:1278: in function `enableTest'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:607>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2966: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2876>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3044: in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2502: in function `AddMany'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1154: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1125>

[string "@Interface/AddOns/PersoLootRoll/Core/Addon.lua"]:595: in function <Interface/AddOns/PersoLootRoll/Core/Addon.lua:594>
[string "@Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua"]:151: in function <...dOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:149>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1202: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1277: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1228>

Locals: <none>
```

### Reproduction Steps

1. Login

### Last Good Version

10.1.0

**Comment by Stanzilla** [comment] 2023-05-02 15:08
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4417

**Closed by Stanzilla** 2023-05-02 15:08 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate, ⏱ Awaiting Response
