### ISSUE TITLE
No import buttons at the top of the weakauras window

### ISSUE THREAD

**Issue by johndolotko** [WeakAuras/WeakAuras2#4518] opened 2023-07-03 17:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Since the new vertsion, the import buttons seem  to have disappeared from teh top  of teh weakauras window.

### WeakAuras Version

WeakAuras 5.5.7

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
Message: ...ce/AddOns/WeakAurasOptions/RegionOptions/Texture.lua:134: attempt to perform arithmetic on local 'degrees' (a nil value)
[string "@Interface/AddOns/WeakAurasOptions/RegionOptions/Texture.lua"]:134: in function <...ce/AddOns/WeakAurasOptions/RegionOptions/Texture.lua:133>
[string "@Interface/AddOns/WeakAurasOptions/RegionOptions/Texture.lua"]:159: in function <...ce/AddOns/WeakAurasOptions/RegionOptions/Texture.lua:142>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:509: in function `acquireThumbnail'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua"]:259: in function `AcquireThumbnail'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:1060: in function `SortDisplayButtons'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:726: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:701>

Time: Mon Jul  3 17:45:34 2023
Count: 1
Stack: ...ce/AddOns/WeakAurasOptions/RegionOptions/Texture.lua:134: attempt to perform arithmetic on local 'degrees' (a nil value)
[string "@Interface/AddOns/WeakAurasOptions/RegionOptions/Texture.lua"]:134: in function <...ce/AddOns/WeakAurasOptions/RegionOptions/Texture.lua:133>
[string "@Interface/AddOns/WeakAurasOptions/RegionOptions/Texture.lua"]:159: in function <...ce/AddOns/WeakAurasOptions/RegionOptions/Texture.lua:142>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:509: in function `acquireThumbnail'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua"]:259: in function `AcquireThumbnail'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:1060: in function `SortDisplayButtons'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:726: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:701>


Locals:
```

### Reproduction Steps

Issue is always there when first logging into to WoW

### Last Good Version

Weakuras 5.5.6

### Screenshots

![Screenshot 2023-07-03 174654](https://github.com/WeakAuras/WeakAuras2/assets/49884783/e7fc328b-aa82-4854-96ac-29431241701d)

### Export String

```Text
No way to attach the zip file and the .lua file is too big to send.
```

**Comment by InfusOnWoW** [comment] 2023-07-03 17:07
We need your settings to reproduce that, please attach a zip file to the ticket.

**Comment by johndolotko** [comment] 2023-07-03 17:10
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/11939704/WeakAuras.zip)

**Comment by mrbuds** [comment] 2023-07-08 10:27
I can't reproduce issue with the data, import button is not missing and no Lua error

**Comment by InfusOnWoW** [comment] 2023-07-08 17:58
This should be fixed in the next release.

**Closed by InfusOnWoW** 2023-07-08 17:58 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
