### ISSUE TITLE
Can't update weakaura ingame with weakauras companion

### ISSUE THREAD

**Issue by dtrixxer** [WeakAuras/WeakAuras2#2003] opened 2020-02-20 13:10 UTC
## Describe the bug

I clicked the update icon to the right of the weakaura, expected it to install the update. Instead instantly get a lua error.

**Do you have an error log of what happened?**

Yes. Posted below.

### To Reproduce

1. Type /wa to open weakauras options
2. Click on the update icon next to the weakaura
3. ...

**Screenshots**

https://ibb.co/ZcyM4Dg

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Disabled all addons but **BugGrabber, BugSack, WeakAuras 2, WeakAuras Archive, WeakAuras Companion, WeakAuras Model Paths, WeakAuras Options, WeakAuras Templates**

**Which version of WeakAuras are you using?**

WeakAuras 2.16.6-4-g36d83ba

**Are you on World of Warcraft Classic or Retail?**
Retail

**Was it working in a previous version? If yes, which was the last good one?**

I've tried **2.16.6-2-g532a54e** and **2.16.6-3-ga2b63e6** still seeing the issue.

### Additional Info

WEAKAURA EXPORT STRING
```
!LR1cZPnss4)luvQY(oBIaSzDCTERIhcBsaHpKCCYT7cmGgaflK4gj5y8LJF7x3ZdjbiW4eN6YL1jXrAE0VNz65tDVc9S6zoRNPn(x4XG5e2D36yhoTNrbTEMKOWP(SoZdD89cGbyiMGJh(Kz4I50EMErZgszabOJjrUHqpfoTuHt7zEhDbsrQRRdq)zKh6z8g(pWCiZGz(LrnAOP1a(XmA2mFpQ9YbrEoHlhiN1xaYgesNZ52NLIvpGff3dXOCXFPS2VSjVS8dPZwoiK(qyeJISyfrJl1H4ySeJylIqjueeSoG6shfMI1fLKzSpBgb64EIBevA)mnblAi1JpQwe2ekqTucPqmVIsCdNUCGGcOqMM3NW5niEj6LMMKUN)f2YbfkwkFH3T8Tj9Y5KQVJo50YkH3MgmI5W9WOa7fA68i08mQTt0Svz7PPu55KruuXyoKHUurit1EMtPotMgkcEIcOxjETAmDkI0P8ldDqlUtWCxYclUP4vZ7zUOZ4Xbu(elM)eWHw6S3u(KZobcL9gbgOR9D8GHwt3WsVRmEVRFiHR(giZyUa3ddNhC(RF9Njt8Z74)6QUKr315btyCr0RU(1NbKBKAnbeEqyHWdaDh745emv8m8i2Q5OOGq)z4AjgPp17(8JIymQheLFXYbAlFBC7qyOQTuTc(NWlVPzDExEoUR0zq0q97bAfW79Fd9nq8NFpN5TnnUSF9kTRCPEU)K3)4ipUuFapE8OLdYNp)HWOJNL6pU(JiUlhqM5hjLtri(bfkQM1gZHtt(yLpDCmb2ySmkSWYlEK)kQZdiE28)3NP6iEEup7J2u3UsVsRDQzFF0R)(ERx)gmYvCUCvC1M2dTTBfJl13hp5ZqFp9hc)OqZEj9JN(dSFu349n72PnS1tLwVWUZs)q4oxrbFj9QL(b2RAETERw)uU6uOz)vz1PqBVwVBZo1Bw7NyhASk(ZTN9)SsIsI8OZqxtjXoJHeS8dJzpsAmlv1ahS8lW0ZjUOroOVPuVezg4AkfAfIMK5NV3yNjjcdqUcs6SHTaNyID4nQF22W30CheYC8um7GCVkFXXvZDKCeVUGM6Nm8zu3aAw8)BI5T3G5hUUX6j4)3a7h)Uv5((Q0FdSSWZNN)kp7)9MLAzqqCfsQLcs6VRiWIF3IabRG9rVsRuQFL7WZLwOXU((Sd2iyeSyz0ZHVcFiJ(I7G30Rk89kEEvvzNAXHVSI5xHmUDX7WNPi8Yeq(2mFj5Pv32)TIrX)dCdF)(YlqxvCLFeIIgUKjb9m7CJvRMg6WvTHW6(J8D9zcmwW)wK)7s8FFIaadZp7ZSVLrM3Z824Ngsy12Ym1sMjClC4U)msiT3qHm0ZSbZ5XLd(hreBODYYbwka0eyq8roEcU(eoYAWEdm)O5CCRICdD4yeaejK4c3FNdJamexkcF2AdzKljii1imB3X4DRnMG50rRqK16N5dTUoVJcO9L8VkILY4XoJG(xSXaziinR34ybeiB0(87NNOuBWpHYuv8cxQRQmcf3ycbiuuR1OGovS)eevqTP2TD8qxcJobegloOs4UDGBvarghbVlDXuoyNiDqXi710lKYafH(h1ibHGTRkH9h3084K3o2eNGCEiJc9hDpLfWXl6mTsAikPUZNs42C(OQ90bIJDEGAlXzTisc)OqxhpAQy6ursFGhjThX3Ivkc0WItZj1QCz(BtLGlEr6dguGs9BjzvUw2thS(GpuKJuU66vQNBZLZs2KE9SAvDIGEZCBCrLjfHXId4SpWkNrcJJzf4DWMZCMmbm6XiqlBaFCc1JYCgzo1)ZD8aZg))RaQ(9ubSQbc44SPdJgpweGCLERRBCtlfiKke6I8sjfaPIgYF)Agf8x9m5PpN0SjqoS5(1QyA130QsxRy1qaFRIY9LyDIWhgOASoUBIa01m8ukB46M8Jwn)x41qMCptXske)CCjLsNIjoxY2ilDCVEEpICbYDDRkFuVBFRow6T7FZ11RyPNtgnatCBNeOUxaBcpOch52gZuY9uoc8GOGENJWmNiSqlh(Z2sRc8iUPoNCxsd5ZOP3y)daECy2PQetzP8kN)fBM9tA09FQd3INBAbpUrPgKGhBkvjbb3eDkUTyL7zApEA50XZMkWrgDhBD8s3rYz33aboIW22KhoihcRoClhyj(Fd2qi)P7bNZoen5QFhTXn1229)eX0Bl3KnuvPUUVEYelK2(Rv794tJI)tn2mW2)Ri9P41WxCrUADAxTIv)wDUSV(71nS6FJrJMTS07Qxp3tS6Tp4FGDlditqpf(waBekDY3u)tj0R1S8t2T9naYEvRKJYTFeiuyEtBifh1(osP4IlULsURcy6cYpBHWQj6pMXzSupUZDhB8d5QHSdtIFz3Xk72QNbP3ld0QFVPm(muBLaixJh2Vl96)P0fMsbV4Rq425A2nz6bz4JYg7QN3(t70p8CxiRoiUs3l1T6x7k8lLup36jM9uwiKIyOS(dobHbhKle)kWHyC8UTOQ5H0ozwxCXlMRjRLfjR5sy5rBSumwfEP8wYtvwxD)FMs)uQ(lUby)cxx5w58Smnf7kc5AoLo6U4CF5B520wM2nVriP3msSC5GAT0V580FO6Zt(YUNN(ZEEEYxk8CXxzYyLVJ2AnYhx6pmZ5jFlJZZeO)ZZaB8LdYCryCw9tDSHS6dHe1S53k1l1Ts2i97DLBFQ8y0ePYRkUHpXNoEtgI3crrhaPlkytBFBQ8EFo41y9iUVxDX0ILXz4mJOUHUQgfmvjuQUtcfoOe8vQIOX3JxokZio8PXVZz30vzdoGTse7470SCGCYvf3lgo9GUG)O8YYWfAFG)7fjxU1ALBJXB6s(C4pwj5XgGzPNjIQriE5rdnj2c8BipuYUhIVRTSMm2pDpeHeA0D2m)5n9AWqKEqkcxj9UfX3zdAjbea(vc7YXFi5gQd9z2uwFocggfkh3GOmu4Wof3MVSMvonULDFxFibeUykg79obodD54sjBHApb0hdURsQQrdf9fx8uHPrkPpknX10eCXO(btj2(F(dXvttkcjQ7i(Oep(QrYx3dek4JtaFMMMgScRH5)kIWOq0AW1m)JBll7OucrA4u04uvBD05sn6pQe5JlOAN6oww2pvUXQJSvLvRAkzse)jTByJRuZqnnmG9c628YRSuvtumZ0KtabLYz8IKcmseHkqKXOdIRJyMFy9zgx5vgf1wPeVEwUcCz3FzCfT0B891tuOysvV9Sxue8)XEIH7VNOwhJ(kt83BxrysDbEQMeH0QUW5L8JcnRuV(6ydtEqbxFmzmtP6kb6rF4ahKRiglyCOyZY07)tNDpMQtH8A5pr(bhc4N)lIcftOQ8GJEMvDDE8rcdYv3Y33n0bAkcRc2rlM)PlR(4DLUTTubKL2OrjT1khrPsX9oc7tdgzgv4pmR1vx3qCuf(Hf8S3DeH8iJyxHCTdIZzvLG4yBtHJUn0FpAtqPLx3Jlh0bsoru7JlhC11G9eLdZq8RESszXE6BY)M0LCPS6mBIg14YXvD4AT95iohp8ywEajxgRl(mm8g8zoqQLY8nUQt3M)ZoyYFykcE2oQQZeiYdXr)LkCwEyfw5cALoTawcScucWf4Ys1flkxvjlhxiZRunWkfr8bk6zwmFHY5lF8jhpPuz7ZknKaPgat9KI4IWE)3d
```

ERROR
```
1x WeakAuras\Transmission.lua:1257: attempt to get length of field 'controlledChildren' (a nil value)
[string "@WeakAuras\Transmission.lua"]:1257: in function `MatchInfo'
[string "@WeakAuras\Transmission.lua"]:1795: in function `Import'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:781: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:778>

Locals:
data = <table> {
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 authorOptions = <table> {
 }
 yOffset = 300
 anchorPoint = "CENTER"
 borderColor = <table> {
 }
 url = "https://wago.io/BlackOxStatueHP/10"
 actions = <table> {
 }
 triggers = <table> {
 }
 internalVersion = 26
 selfPoint = "BOTTOMLEFT"
 version = 10
 subRegions = <table> {
 }
 load = <table> {
 }
 backdropColor = <table> {
 }
 scale = 1
 border = false
 borderEdge = "Square Full White"
 regionType = "group"
 borderSize = 2
 _table = "d"
 borderOffset = 4
 semver = "1.0.6"
 tocversion = 80300
 id = "Black Ox Group"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 uid = "xEDdn5d)x46"
 borderInset = 1
 xOffset = 0
 groupIcon = "627607"
 conditions = <table> {
 }
 animation = <table> {
 }
 config = <table> {
 }
}
children = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
target = <table> {
 sparkWidth = 10
 authorOptions = <table> {
 }
 displayText = "%p"
 yOffset = 102.499939
 anchorPoint = "CENTER"
 sparkRotation = 0
 url = "https://wago.io/BlackOxStatueHP/8"
 backgroundColor = <table> {
 }
 fontFlags = "OUTLINE"
 icon_color = <table> {
 }
 wordWrap = "WordWrap"
 barColor = <table> {
 }
 desaturate = false
 font = "Friz Quadrata TT"
 sparkOffsetY = 0
 load = <table> {
 }
 useAdjustededMin = false
 regionType = "aurabar"
 texture = "Glamour4"
 sparkTexture = "CastingBar\UI-CastingBar-Spark"
 spark = false
 tocversion = 80300
 alpha = 1
 sparkColor = <table> {
 }
 fixedWidth = 200
 outline = "OUTLINE"
 borderBackdrop = "Blizzard Tooltip"
 color = <table> {
 }
 customText = "function()
    local health = aura_env.current > 0 and aura_env.format(aura_env.current) or "DEAD"
    return health
end






"
 customTextUpdate = "event"
 automaticWidth = "Auto"
 triggers = <table> {
 }
 internalVersion = 26
 animation = <table> {
 }
 backdropInFront = false
 stickyDuration = false
 version = 8
 subRegions = <table> {
 }
 height = 50
 sparkBlendMode = "ADD"
 backdropColor = <table> {
 }
 fontSize = 12
 config = <table> {
 }
 auto = true
 sparkOffsetX = 0
 actions = <table> {
 }
 borderInFront = false
 xOffset = -318.000610
 icon_side = "LEFT"
 useAdjustededMax = false
 zoom = 0
 sparkHeight = 30
 icon = true
 width = 159.999939
 justify = "LEFT"
 semver = "1.0.4"
 displayIcon = 627607
 sparkHidden = "NEVER"
 id = "Black Ox Statue HP"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 sparkRotationMode = "AUTO"
 uid = "cypjGBzk3WM"
 inverse = false
 sparkDesature = false
 orientation = "HORIZONTAL"
 conditions = <table> {
 }
 selfPoint = "CENTER"
 preferToUpdate = false
}
oldParent = <table> {
 sparkWidth = 10
 authorOptions = <table> {
 }
 displayText = "%p"
 yOffset = 102.499939
 anchorPoint = "CENTER"
 sparkRotation = 0
 url = "https://wago.io/BlackOxStatueHP/8"
 backgroundColor = <table> {
 }
 fontFlags = "OUTLINE"
 icon_color = <table> {
 }
 wordWrap = "WordWrap"
 barColor = <table> {
 }
 desaturate = false
 font = "Friz Quadrata TT"
 sparkOffsetY = 0
 load = <table> {
 }
 useAdjustededMin = false
 regionType = "aurabar"
 texture = "Glamour4"
 sparkTexture = "CastingBar\UI-CastingBar-Spark"
 spark = false
 tocversion = 80300
 alpha = 1
 sparkColor = <table> {
 }
 fixedWidth = 200
 outline = "OUTLINE"
 borderBackdrop = "Blizzard Tooltip"
 color = <table> {
 }
 customText = "function()
    local health = aura_env.current > 0 and aura_env.format(aura_env.current) or "DEAD"
    return health
end






"
 customTextUpdate = "event"
 automaticWidth = "Auto"
 triggers = <table> {
 }
 internalVersion = 26
 animation = <table> {
 }
 backdropInFront = false
 stickyDuration = false
 version = 8
 subRegions = <table> {
 }
 height = 50
 sparkBlendMode = "ADD"
 backdropColor = <table> {
 }
 fontSize = 12
 config = <table> {
 }
 auto = true
 sparkOffsetX = 0
 actions = <table> {
 }
 borderInFront = false
 xOffset = -318.000610
 icon_side = "LEFT"
 useAdjustededMax = false
 zoom = 0
 sparkHeight = 30
 icon = true
 width = 159.999939
 justify = "LEFT"
 semver = "1.0.4"
 displayIcon = 627607
 sparkHidden = "NEVER"
 id = "Black Ox Statue HP"
 fram
```

**Comment by emptyrivers** [comment] 2020-02-27 02:13
Duplicate of WeakAuras/WeakAuras-Companion#68

**Closed by emptyrivers** 2020-02-27 02:13 UTC
Labels: 🐛 Bug
