### ISSUE TITLE
Item Set Equipped trigger not working as intended.

### ISSUE THREAD

**Issue by maedas** [WeakAuras/WeakAuras2#3882] opened 2022-10-15 18:12 UTC
### Description

Wrote a WA that I want to load dynamically if I have 4set equipped. Added a trigger for this (the option didn't exist in Load) that throws the Lua error below when mouseovering the option, along with not being responsive at all. Expected it to work (duh) but I'm assuming it is a retail functionality that's not working properly in classic?

I would also expect it to be working as a load condition, IF it was updated to a working state.

### WeakAuras Version

WeakAuras 4.1.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

Message: Interface\AddOns\WeakAuras\Prototypes.lua:7418: attempt to call field 'IsWrath' (a nil value)
Time: Sat Oct 15 20:05:10 2022
Count: 1
Stack: Interface\AddOns\WeakAuras\Prototypes.lua:7418: attempt to call field 'IsWrath' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\WeakAuras\Prototypes.lua"]:7418: in function `member'
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:214: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:163>
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:505: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:494>
[string "=[C]"]: ?
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:66: in function <...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:64>
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua"]:51: in function <...ibs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua:50>

Locals: <none>

### Reproduction Steps

Make new WA.
Go to Trigger.
Make a new trigger (type Item -> Item Set Equipped).

### Screenshots

[
![image](https://user-images.githubusercontent.com/19661397/196001868-17a5f593-bb5b-4b62-82c9-127f068409d1.png)
](url)

**Comment by InfusOnWoW** [comment] 2022-10-23 17:17
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/3852, which we already fixed.

**Closed by InfusOnWoW** 2022-10-23 17:17 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
