### ISSUE TITLE
Anchored Weakauras to Personal Resource Display

### ISSUE THREAD

**Issue by searent** [WeakAuras/WeakAuras2#5067] opened 2024-05-08 20:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I had a previously created weakaura i made before. When i tried to edit it, the positioning of the icons got reset and it stopped anchoring to the personal resource display and instead, it showed on middle of the screen

### WeakAuras Version

WeakAuras 5.13.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I have a Bisector Report

### Reproduction Steps

![image](https://github.com/WeakAuras/WeakAuras2/assets/169306292/e73f3266-94ba-4ff3-bd3b-8e8f097381ab)
1-Normally, i have this weakaura group which is anchored to my personal resource display
2-After my first combat, when the combat ends the positioning of the weakaura group stops being "anchored to personal resource display" and it becomes static.

Like this:

![image](https://github.com/WeakAuras/WeakAuras2/assets/169306292/9481cc8f-09c9-4c47-a148-877bd92e5ecf)

3- When i try to check the positioning on /wa options section the group anchor looks like this:

![image](https://github.com/WeakAuras/WeakAuras2/assets/169306292/8670554a-9a4e-4b51-96c4-47bb51138174)

4- It only gets fixed if i click one of the position change arrow buttons showed on the screenshot. (Which is not a permanent fix because the next time i get out of the combat it becomes static positioning instead of anchored to personal resource display again.)

![image](https://github.com/WeakAuras/WeakAuras2/assets/169306292/36105c66-0a1f-484f-ad0a-8883c6aa1aab)

### Last Good Version

WeakAuras 5.12.9

### Export String

```Text
!WA:2!TEv3ZTXvv8QOgcOuCCKtmUUHunPKqWqY4Oe7wyyggjBzKDLTmRKZhmf8(1vAVXR2D79UsYYqGw10wtd0POa8edpOhj9j9apZ4h45ZOH)c8Fcz6FaCo3DL)k0H(a5bR7E3Z9UN753hNBsC30sZ5U5TU9nNnDJ02PT3929mewLyE1dDE8K7B6lSzI8gwBzl8dcgpVlFNDme2zQ677gYdeBxUwnjl8ZFjrNOrf)Nxw7hS4IlwCGHNLJVyDFUxOz(YvRwE1brB3c(U(IvsKirsnzGHf70cdRqUVNCEnzOHimvEUhpmLzn8hPtQUHcE96mHC6RjIh(r9TzMnRvRANaMOyHsRV0gLYhIpOz0uyKTRmG56USTm1(YMMSwmVWky08ThS5c5QuDZkvZPvnFt8Jyg4A0HjoiS1fmmmTkRxOujn1mMfzgUHoAEgnyYu9A6fNcPgy572SHxf6eK0uyyZBkF8R0ZWJ3WGonZdVYsWe5989y7XmKSkHcvv9mdTXCKIytkJfsMLVNTSlfdDEG3iFddUhUw4nGVZzGRcxd(U4WXo5mAgU86EMluyTQf062uYkXBWdDeynKsWe9XdLgRovyt1tYCRPGI8LkSu18U(g2lLxY3HnPwJMisMkpwZSMeYMsZY1qkPrMHgUyfGg(CCLmHNH7DXeg3XNo0mMtebMjtMC9KZEZ56k8BhvrerfcMt(64CAAl)tlwvtAH7yY(wmA3Od7vkPzgrkC6h9Bb76SGZx5DBAiyzwQPRBM75Wdz9fQtcTM9S7GGb3c33MbXRQcEsoDEPVi00PJPGBR5sfJZgZ4w2dzMjZ2KBpO08V9SRuYFXIRD9GZhrrxsGy7643ZluFFemWcOx4siN0xyQLBXL3OcwQdCmsUx0Ufr0)gdQrRdHvJqJK9d9TAfvBMkXh7FfUDWf1YSixsemuTeC9InPd9375uswuLJvnmDztgm1c(42Y9WILDMCsPbIhzce(w69QJrDpUDOZzF(rsvQiKDDTf7jdzb58Q7YEDtmTRXRNAOrZqmSYbk9uQU0gOQZAl2VgwmxGlSCz69jkhpkMbCVA(Iio7KdWHwSceXxQJGzOA6ePTwz3z6ZXvvXVjgWLEj4bPGV26V8C3(MZbNbMzOf6hy732RsBEatpyCRMYq)gvzBhUrGnEYmBQ(zVrXrWSdCwuKKcglf8ntbNBSRbJVB6GZJm5nRZ8ycUvfh)2L90hESh3xQ(zH4DcU80bt8FPecNhsJkMl8CC)kSnIMvImf0HPHxdPKEL9C7OdxAGA(mVThTxtbV6qbk4vZTgwRtmKsh5Oh1Hlo9uVC6xR3bZKypYYr9i3woT5TNF2F4CzHjHVvpALi7WAl9(Kzvu2Vxu2NdD8AXGxpfscvdRgzRSQVnljm)t3hja1fmPmQGpZLEPtb3eMzFzi3ARolg7G4a3y6jHjgIkDspskcpBthgVUt4BcZU74IDq7h0i8uIiTCwsmVVsHVPHNnDWSUMPKtKOV4Cq2j)IZPdZrbfKMs)JhPoCNRb)AZIBqooymWTXhpdoO3bXQ33MJoTwia0H2M845Nrd6gxhrwDqRGdDwe1Im)Jc23vfSatisDtJHBPsNXX1NZ(HiTIzZSx1yBhydZklOvOWAN8DCSUKlpXwX2esJqQyXC6oI6P)8TyOUHYLqnQm6axrzwt(QXwSKH71FHzg7KZOznY9ljSIduCWdBPTs9g8SxxwcwnzWfg9njHaAgqcEBN8Oi1xhwp2OaCGYjvL7ruAKeGjgtxRnP9Ft40jG7t1eYGbnu3X3Vrc4t0H3jf8lUg8l1dMcBe4lyXYEL8TGq4lK67Edq)KQ1VoyOdMGv2Mc3tP0GtkS93SURFBhsjI6XZDzsmorwbRr6SI42PloBpIRR6eo9Wkmra(DYujebRHO)HLdtgXXhgXXxLljMfmf2iruNfUhvY5i5ydQZl53AKfoVOyoTvX(3cSaejXqTdCj4Bt6u4H6Ga(BWfX2TkhLnD42mTqEdM9am5kJnqnqF60)y0ga(R5PClVgZZMu(O6cpf)dycn1baWT(sWwKghCtan0voe1G6btqCtg5rCuL(7QdEt9Yx9ZXTbcjnj8hIyk3vXaicbYgmdqvkle(reL460RE2OxbptlOPRKrVzSJTi4zMsheq3IE1tCeXDosc3yguodT39cbPdrkZMshdKqC)Oooj6PMJ(t6mbJFKao8gv7hn7bD7ZTr1YbtOMKyDKnVLQJs(C4Jpx9c8gpSO2mV)WO2mpi(dUN69KWIxRdmtFvdbgrMZVw51katiqNhkM(QapuneLP189c7xyBQcjBB05yNPrFIHQ5AJ233tye09EXdgEWgOUJx5nQwA51keFOpYnlHzIYXwCjhfx6hUo6kbxn(8mQagNbh)qcBtwLtaF0KJCY8WB(jCuMDWVHSG(T6W7R8I66ezhb7O(7VcJ442MdO13I5WX2SoJ8hN8m6W7PwWJ0HhRg05u9vEM(nmnc1Hpun5hO(7h7aFMdy7a)ED43HozWNmWo6EelJwAbF)LP7rGUMS3HEw(o5m5U8WoBUa24c96yBIgn0Lj3C2SuldOPQ5X9troup9nHE6WFob8hp0)jyCLeotSCnJXDq)i09c9xxyJk412j)NIdMT6Tk6UHBl77wh(toWNUsYef)j)9PP)9QjpQBe8x0Hwo7oJY45tJmhpYvfInFOdiUivx))LsTsY(hQRu(KeLeNrnBvgbO82b8J6Vo)8aN8fKhknJoKr(4telYo0h)eZm2lmtR4oPq7i2W5JydhNcebsD1rW7lf)pOLyeGh11dzIoXGlXEA1TMlBBfDTReVlSHG7R3fV5vyNggE6zdzE69dBJMRDQH3mq3mASUwa(FocVYYJgXgF8i(ccRrmfcQoaeq7QN4qw)iWJWpcQhh47H3YXq4WmSjsbb4WUiqZFWob)CJTw(HU3Ja6pB010I6mGOmYlrE1xfa(Ol8iincEFfa636TM9oZPyf))ePFYjq6X)FiOFbIWhEKs)b(cFWiQX7DCsWJuKLJHqiP)aeIKNiI9LGp7vbHDUhZnt52UhbIAr30iy1zBVIiul71)zXOec3rGZdsLU1)(()Nd
```

### Bisector Report

```Text
Bisect results:

report version: 2
addon version: v1.3.0
mode at print: done
bisect origin: cli
last test result: bad
Bisect took 1 out of (6-104) steps
Hints taken: 1
Addons ruled out: 51
Addons proved: 0

Narrowest set of addons that reproduces the issue:
|-- H:WeakAuras @ 5.13.0
|  |-- D:WeakAuras Archive @ 5.13.0
|  |-- d:WeakAuras Model Paths @ 5.13.0
|  |-- d:WeakAuras Options @ 5.13.0
|  |  |--WeakAuras Model Paths...(see above)
|  |  |-- d:WeakAuras Templates @ 5.13.0
|  |--WeakAuras Templates...(see above)
|-- A:Bisector @ 1.1.2
|-- A:BugGrabber @ v10.2.4
|-- A:BugSack @ v10.2.4

Libraries:
LibCompress @ 90083
LibGetFrame-1.0 @ 57
LibSharedMedia-3.0 @ 8020003
LibDBIcon-1.0 @ 52
AceGUI-3.0 @ 41
LibUIDropDownMenu-4.0 @ 90135
AceConfigRegistry-3.0 @ 21
AceGUI-3.0-DropDown-ItemBase @ 2000
LibDataBroker-1.1 @ 4
AceTimer-3.0 @ 17
LibCustomGlow-1.0 @ 18
AceComm-3.0 @ 14
AceConfigDialog-3.0 @ 86
LibSerialize @ 1
AceGUISharedMediaWidgets-1.0 @ 9004
AceEvent-3.0 @ 4
LibRangeCheck-3.0 @ 14
SpellRange-1.0 @ 18
LibSpecialization @ 8
CallbackHandler-1.0 @ 8
LibDeflate @ 1
AceConsole-3.0 @ 7
AceConfig-3.0 @ 3
AceSerializer-3.0 @ 5
AceConfigCmd-3.0 @ 14
```

**Comment by mrbuds** [comment] 2024-05-08 20:47
duplicate of https://github.com/WeakAuras/WeakAuras2/issues/5060

**Closed by mrbuds** 2024-05-08 20:47 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
