### ISSUE TITLE
Labeled text, glow, border etc. elements

### ISSUE THREAD

**Issue by EmElw** [WeakAuras/WeakAuras2#2236] opened 2020-06-19 15:04 UTC
**Is your feature request related to a problem? Please describe.**
Conditions are pretty nice to make easily customizable weakauras, but its unclear for the end user what "Text 1" and "Border 2" etc are unless they check the display tab, and even then it can be difficult to see what it does.

**Describe the solution you'd like**
Being able to label these elements with arbitrary names such that they appear with their labels when building property changes in the conditions tab.

**Comment by mrbuds** [comment] 2020-06-19 15:20
duplicate of #1302

**Closed by mrbuds** 2020-06-19 15:20 UTC
Labels: 🎨 Feature Request, 👯‍♀️ Duplicate

**Comment by InfusOnWoW** [comment] 2020-06-19 18:11
That's not exactly the same ticket.

Though I don't want user nameable sub elements, that's imho too much complexity for too little gain.
