### ISSUE TITLE
Bug latest alpha/s

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras2#3572] opened 2022-04-02 15:19 UTC
### Description

With latest alpha when i am trying to setup particlular wa i get lots (maybe all ) wa show up.Its not like release that if you selcet one WA its only showing that WA.

### WeakAuras Version

g437b333

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

no

### Reproduction Steps

open wa
click on wa you want to setup
see lots of Wa

### Last Good Version

3.7.16

**Comment by InfusOnWoW** [comment] 2022-04-02 16:10
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/3566

**Closed by InfusOnWoW** 2022-04-02 16:10 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
