### ISSUE TITLE
Any weak aura with the spell frozen orb  - mage doesn't load in raid or dungeon

### ISSUE THREAD

**Issue by Foarfeca** [WeakAuras/WeakAuras2#5496] opened 2024-10-25 07:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello,
I noticed that any weak aura that contains the spell spell frozen orb  - mage just disappears when entering raid or dungeon instance, in world pve or pvp it works fine, i tried on 2 different computers, same result, the weak aura just doesn't load, don't know if its a blizzard bug or application bug

### WeakAuras Version

version 5.17.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
no lua error
```

### Reproduction Steps

no error, just the weak aura icon just doesn't show

### Last Good Version

it was working before latest wow patch

### Screenshots

![image](https://github.com/user-attachments/assets/0f976773-5ba9-46d6-8f4d-25fc99130802) - outside
![image](https://github.com/user-attachments/assets/718179e1-e613-489f-93e1-9d9f61d74fd2) - in a dungeon instance

### Export String

```Text
!WA:2!Dv1ZVTrru4KAqvyHkXwutqeqHceGiHtJrjGqCaVP2PnnPjS2GAPqZo7UpV70SEMTZmRtC4xQ(aIZ(ox8z4IL4FG8xWGfN4youj4ypWjoWBg)JcDp4DEV9nFZB(EFVNNVEX2fdlg(JV3aAaN1GNjcGLMZ)yse)gxRF9q2Ep4OQzDgrYuXCX(PkkNjZpKeE)mPcc3JCYfEIbLDbr39B1scQR)jK)8FMdFgsyb4opGtzk)TQDRM1ChfW5jH8JznoMMcENn1Swyee7yYdVEkbnkceY7TIyYY)2vjibh1BA0oQUPGRmfssoxM5dDaMQrwRw0tgE4wvB08WgnR62Cqi4JoBIXkUETDpO(NTBAHmjCyeWabnOrm)49zEJ(FMdL2xUajS7mSpqai2UnoO2U7osaKKgMJ(wK2WG6c(PaB59f(JmqlN(bVE2L3iuM31Ir6lV1KSF5de8ibiLl)owCExxgUbzENmgv5NMq6cI(gWSxAV(ZWCX535V6NXMqk5xrFPhPFb9c2dwaTjugLf5PxXexAXzEoKJearXff)y9INp((nnx0VH(n1lPF1(ZI(kRVHUGUO(180lRFD9l5PFlp9L1L0VD(HHu59ZybkAhOcH1nTaXUU54eApEi8ZZ9ySydcgj5ZXsiQy(PhFeaPvXlrGYLGAO4(siPLvuOFoSgjjQmm9GyrNX7i3aK3DHiJCB1s6cJqtFKjIe8mw4JgfLWpUUaEqgWc6EWZC1YvWmwGbz(WzizSn(ElEcxe3Z4Yiag5NPuC2(4rG8RfIMX0GJyyzi3qJ5DglENVF00DVto85mJ51mjOjZSrE7)BKncijqohZY4bMF3fyrQ4lB)4Uue)cw3oCriiI9JbAuSABNeoj8hSv5GeIu61BI6jW7CRJdjSqR9k(sSQKap0TDwIIw6HE(k8izQs6BM3XgHENlIRDT7dnC2R621qhPfNb)m08CK0tbmi3uIq1vFZsAxV0fWaRoPt22yh7lTJd8PTt5c1thaLfpqylqgUv)89jmABldTPRuHax)mGiHgkHLmUOUGdJZGrHt4Xdn9VcjGT7HYEMqT4CxhJgSU(lWnOVR(l1FL(E6763c1LY4N29qkRfxm(ulnexga1m9zsVkzIK0xjwPsLF0ARzgNvMYxB28S1w3nyw5TsgnC4MzFkDR4n24dxVQLZM2CGcAuXcEUhtdvXBN(ItN)0eorDnQK4NaHivbTrzL76LVA5RoqXdMiJxC(F5xVcn8SNmHy5kUKK0ysUHTey7mspefj3JhpLSUXLHg8BSLBTA3Y5uoV98(if1IgLxqzgybpXjthY6)h)MziRW0dIDkBQVtETxEhKSu5hyywQ1)QR4gedbhTP(s561HiOMS2XmfWTdjjdYjcIjSiadu)TE9sfMPfQUMEWYvkBKU4GMtXD)S6Vw)n6VnN(7SrQ)EDL86f8opDY0SX)bYQln3fkk93O86Fq53VyNF)2)l

or

!WA:2!LA1sWTrszylRewYaSRTITXz3WwkzjbswIDSdjS7YR4XwkwzTL0osjobylREMP1mT94zg3ZmwsMN2a7AEdMDbwGfOeCGTaUOQ2IJKYCKd8xQ4auCZhwQcUfQItue(7EgjBNlCGlA6()r3)p(()AL62zc0V6et9HM4kzwlJzgZDEQ9194MuUkXyvtUNV)qQoSn3KWnZw1ZZjK5R3Gy5vyUDxyUvN5Ugn9MQljk02JxYpK55gOWBvQE9aA48xNDVb)d)QB)YDiUgO(YEm3q9zZvSAoToXxYSEoE8BMkvQ0thXD8Fc7Wq)GNBYjf3WemVj7FftonNyip(RPfes4Hk61zUSaBfv8tOY2HCMLfLh84NNNS8LABs1JQxVAlFkF(Cluo)Twqne3OrI4KP3oWN64uWmqz)GiD6gu3WkO1SMDwE2zQuD5kvNrRAFvL5uuLwLY5wyb1i8g19DiTOCnPw95PeNqBnxYA0aLDJCtcbL7JzmL7sCUngAy0)67sCzRrejY1Ghn)EusaTsiN6AfA)iWOQUEU0UMy4jSyzrWYdOgEUMbBlmvKkW5uxJWCZdVx0b4CW5H3h8(XVp2dlHVr8DE82ysOrTK9gvhpIzE1a2M0X0wlcBNkQyHWymycfndhsqGyLEiXbtlXYU6j4G4wv60PlN(YtCv9aViUbvNTMVhpulWaDO8XMAIlFv94oRD74V5mTO(dxz9icNMnFKJt2LSzH02CzajsinlUxKFI5vWa747fVogfDc9a6AyQOHh(et1o0ZijVgp1V5nplZ0)m9XNpD28CVnPUzlX1Zo7CzdrmZQmxRo15yJbRZKqs67hdgZlejUE9kZQLlxrnIJVnjTowSRZSu4ntWW3RXB(HFXCRxy6iMzN5n9wmAw)v28tOUBa1PUerdNOTOdXIb)DyU194XTyLeuEbx8KsNX4I7CP2m02kYA3PhaogCC4TP0HyUsuqi1CrM7GWJm)9(iLUYF(320dE7Wj6AGZCMEnCR0G5tRbVd4DQkoIAWWfppKzNr8hjkGUmZY1JtRiq0pVlATT)WcXwuxkNzuX2Rrj3ADpY2obYpAuIzl40W7PJWbHmldtB4KWiWOAYreyC4u7kxvelzJp4F7vKMAyt4w0aB4j7oJCYm7Tci6ou)tk0sBIJRl33l7UCCcPsVTB3RL1vEP9exdE3ksjCQaIJDoBnzpufjy8GS4KfQukPg84WtaNrPJjlyLixma2GonXTL)We56QXdGl6zs)1daN9133N7zXPbbX1(lE6bgekGDotAajumVrTHlEC4PFUXGr7IZlcuVax6AIL4mH0MyYytWgXDIXfP8pLuO8N4g(YbjlGZTBFDN9Cb(dDi3pGWB)yP9qrQZCRQL8pPuOiBfiiJLyMH2QZGBVF8fXAsnLc3QBmm(UjHZEs9cyeRElmV4EHyovffQwSuXCWOCmPe20wAOrVH507MKbUH(dLNZ2m7lermfdkzRw9ijEVBQRuwdeyVeN4V9sjl62)CK8TLUv1fkumxsUFi(F)HluSyoTLvlvTAPf1kCJ5REGRIP)tLKz35iz2gSagcUQ9wDTC8AKNtxpI6A0Q8XU8etF14StOypeGCdNKYS92crIWPREuyONBjK5azTBleVGKZD0oI19sTDT65QS0SNy7CjKXPLwENdBzfbPxAzav1MzSQlcVsRk2wtQFbgkzy5TPgZjQBtzw24dJLVYFCGbgid8b2OTeslPBT3xsaJvltXmHX51dWrah6winmmLGmgMu(7Lf)6NrofEepQbxsQAiu1mjKkiTcPPnCf4dc5N)6QT(hzQ5)gpSfmxB4zHYB3JTPg8UW3NuGhtbgszVEsfC52qof)r6jraWMJjN7rsdvywyU0QB65Twk4JcFm4J3JJ(q)hcX0lLlJ(ztofCkvdrR1GzsR1qGUN)6LEW)(39Gh8p1oaOc3OZM6fCxV1DFHkEoCMR4zaATdipjnh8(RsP(ZiQeHAIUMnCtf45vGNs8y7d)G5f(F)e6oxcwSpnnumMCUWyN5V8FgxqodLKeYqzKn(rr24)fSm8AO)3wqzkPq1QbvGQsUQpzB8vjAwlQZV)nGxuq1bpjCxKutq(cKAWsJN6M)DKsdmLmwqFskO(bCtG1oJa2PaggKRGKlWQsYeWbwdCbpWFly9uahDkacrZJGnIREnGMqRuWMWNg(mWNf(CWNh(cNc2kfSDT3c(I9MJGVe8LTHxcEzyNrHVsk4Rg78xln81tbFJ0W3mn8TQbF7HHVJnS7wi8f(U2WRCE4v7JrhB8uplV2HbQW3lbwcF)(WWp11(RnUWZ8lHFGe2bV2rWBWpuaYGFupaf8JFi0uMd9mFcEc(jc0d8tFv4N1dTWN6zw8cARe2SSo0Ug8Zhe(f))IhYSXF6o)3d
```

### Bisector Report

```Text
none
```

**Comment by mrbuds** [comment] 2024-10-25 09:22
I couldn't reproduce the issue while zoning in/out of ragefire

**Comment by Foarfeca** [comment] 2024-10-25 22:16
Hello,

The problem is related to war mode I think, frozen orb weak aura does not appear active in any non war mode instance, I have attached the script( only the frozen orb wa is bugged, the rest are fine )

**Comment by InfusOnWoW** [comment] 2024-10-27 13:36
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/5490

**Closed by InfusOnWoW** 2024-10-27 13:36 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
