### ISSUE TITLE
Use the condition logic tree builder for custom trigger conditions

### ISSUE THREAD

**Issue by seanpeters86** [WeakAuras/WeakAuras2#2666] opened 2020-11-03 02:07 UTC
**Is your feature request related to a problem? Please describe.**
Often times I find myself building "ghost" triggers that I only intend to use for a condition specifically. For example, if I want my Fel Rush aura to glow when I have the Unbound Chaos buff active I create a second trigger and use that to trigger a glow condition. To keep this logic separate from the main tracking of the Fel Rush aura/cooldown I use a Custom trigger function as such:

```
function(trigger)
return trigger[1]
end
```

This is _fine_ and works perfectly, but does require custom code.

**Describe the solution you'd like**
The conditions tab allows me to do "if trigger 1 and x or y" so building this same thing in the custom trigger section would make it a bit more convenient for these simple cases.

**Comment by mrbuds** [comment] 2020-11-03 03:05
duplicate of #1236

**Closed by mrbuds** 2020-11-03 03:05 UTC
Labels: 🎨 Feature Request, 👯‍♀️ Duplicate
