### ISSUE TITLE
Spec tree cut off in trigger menu

### ISSUE THREAD

**Issue by pjaws** [WeakAuras/WeakAuras2#3970] opened 2022-11-02 05:10 UTC
### Description

When creating a trigger of type "Player/Unit Info > Talent Known", the spec section of the talent tree is cut off by the window after clicking "Select Talent". There does not seem to be any way to expand that section.

![image](https://user-images.githubusercontent.com/53156002/199384443-00f02adf-5c66-4aac-9253-56110eafff73.png)

### WeakAuras Version

WeakAuras 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create a new Weakaura
2. Click "Trigger" tab
3. Edit Trigger 1
4. Select Type "Player/Unit Info > Talent Known"
5. Select any Class/Talent Spec
6. Click "Select Talent"
7. ?????
8. Spec Tree is cut off

**Comment by mrbuds** [comment] 2022-11-02 17:30
It looks like an issue caused by an other addon that change the look of weakauras window.

Did you _really_ test with only WeakAuras enable?

If you manage to find which addon is breaking weakauras options i would need it's name.

**Comment by InfusOnWoW** [comment] 2022-11-02 20:12
Please provide a screenshot that shows a unstyled window with the bug visible.

**Comment by InfusOnWoW** [comment] 2022-11-03 22:09
I'll close this until you do provide that screenshot.

**Closed by InfusOnWoW** 2022-11-03 22:09 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
