### ISSUE TITLE
Dynamic group attached to nameplate tracking stopped working in 2.17.10 (combine matches per unit on further testing)

### ISSUE THREAD

**Issue by Saxayone** [WeakAuras/WeakAuras2#2254] opened 2020-07-08 20:45 UTC
## Describe the bug
Dynamic group attached to nameplate tracking nameplate buff/debuffs no-longer works/shows in 2.17.10.
Combine matches per unit seems to be at fault on further testing.

**Do you have an error log of what happened?**
None

### To Reproduce
Dynamic group attached to nameplate tracking nameplate buff/debuffs no-longer works/shows in 2.17.10.
https://wago.io/2Nw_EO8m2 - example using Blood Plague

With some more testing I'm guessing it is a change to auto-clone + combine matches per unit being both selected?
My main usage for this before was counting Bolstering stacks, Auto-clone for multiple nameplates and combine so it isn't shown multiple times per stack per nameplate. This seems to now just not function.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, no-change.

**Are you on World of Warcraft Classic or Retail?**
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
2.17.9 and previous.

**Comment by emptyrivers** [comment] 2020-07-08 21:26
This is (probably) a duplicate of #2255, so I'm closing this one. For more updates, check ticket 2255.

**Closed by emptyrivers** 2020-07-08 21:26 UTC
