### ISSUE TITLE
Error when I try to update an aura in game

### ISSUE THREAD

**Issue by jwilliam87** [WeakAuras/WeakAuras2#2210] opened 2020-05-24 23:59 UTC
Date: 2020-05-24 19:58:27
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WeakAuras\Transmission.lua line 1262:
   attempt to get length of field 'controlledChildren' (a nil value)
Debug:
   [string "@WeakAuras\Transmission.lua"]:1262: MatchInfo()
   [string "@WeakAuras\Transmission.lua"]:1800: Import()
   [string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:803:
      ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:800
Locals:
data = <table> {
 grow = "LEFT"
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 xOffset = -195
 yOffset = -13
 gridType = "RD"
 borderColor = <table> {
 }
 rowSpace = 1
 url = "https://wago.io/2Yx9Dn2Y9/22"
 actions = <table> {
 }
 triggers = <table> {
 }
 columnSpace = 1
 internalVersion = 29
 useLimit = false
 align = "CENTER"
 desc = "Author: Chrissinger (Chrisidari)                        twitter.com/chrissingr"
 rotation = 0
 version = 22
 load = <table> {
 }
 backdropColor = <table> {
 }
 stagger = 0
 animate = false
 config = <table> {
 }
 scale = 1
 space = 4
 border = false
 borderEdge = "1 Pixel"
 regionType = "dynamicgroup"
 borderSize = 2
 limit = 5
 anchorPoint = "CENTER"
 arcLength = 360
 constantFactor = "RADIUS"
 radius = 200
 borderOffset = 16
 semver = "1.3.1"
 tocversion = 80200
 id = "T25: Azshara's Eternal Palace"
 frameStrata = 1
 gridWidth = 5
 anchorFrameType = "SCREEN"
 sort = "none"
 borderInset = 0
 authorOptions = <table> {
 }
 selfPoint = "RIGHT"
 conditions = <table> {
 }
 uid = "DWVd(neWSJv"
 animation = <table> {
 }
}
children = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
}
target = <table> {
 authorOptions = <table> {
 }
 yOffset = 0
 anchorPoint = "CENTER"
 cooldownSwipe = true
 customTextUpdate = "update"
 url = "https://wago.io/2Yx9Dn2Y9/8"
 icon = true
 triggers = <table> {
 }
 internalVersion = 29
 keepAspectRatio = false
 selfPoint = "CENTER"
 desaturate = false
 progressPrecision = 0
 version = 8
 subRegions = <table> {
 }
 height = 52
 load = <table> {
 }
 authorMode = true
 xOffset = 0
 regionType = "icon"
 conditions = <table> {
 }
 color = <table> {
 }
 cooldownEdge = false
 actions = <table> {
 }
 cooldownTextDisabled = false
 uid = "lN5Ki3qvsEQ"
 zoom = 0
 semver = "1.0.7"
 alpha = 1
 id = "01: Barrage Timer 2"
 anchorFrameType = "SCREEN"
 frameStrata = 3
 width = 52
 auto = false
 config = <table> {
 }
 inverse = false
 animation = <table> {
 }
 displayIcon = "1412208"
 cooldown = true
 stickyDuration = false
}
oldParent = <table> {
 authorOptions = <table> {
 }
 yOffset = 0
 anchorPoint = "CENTER"
 cooldownSwipe = true
 customTextUpdate = "update"
 url = "https://wago.io/2Yx9Dn2Y9/8"
 icon = true
 triggers = <table> {
 }
 internalVersion = 29
 keepAspectRatio = false
 selfPoint = "CENTER"
 desaturate = false
 progressPrecision = 0
 version = 8
 subRegions = <table> {
 }
 height = 52
 load = <table> {
 }
 authorMode = true
 xOffset =
AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  ACP, v3.5.7 
  AdvancedInterfaceOptions, v1.3.4
  Altoholic, v8.3-006
  AngryAssignments, vv1.13.0
  AnnounceInterrupts, v1.7a
  AstralKeys, v3.25
  AzeritePowerWeights, v8.3.12
  BadBoy, vv8.2.5
  BagBrother, v
  Bagnon, v8.3.5
  BlockChinese, vv1.8
  CopyPasta, v1.1.2
  CorruptionTooltips, v1.8.2
  DataStore, vr67
  DataStoreAchievements, vr49
  DataStoreAgenda, vr31
  DataStoreCharacters, vr45
  DataStoreContainers, vr61
  DataStoreCrafts, vr84
  DataStoreCurrencies, vr40
  DataStoreGarrisons, vr26
  DataStoreInventory, vr55
  DataStoreQuests, vr48
  DataStoreReputations, vr45
  DataStoreSpells, vr34
  DataStoreStats, vr33
  DataStoreTalents, vr63
  DBMCore, v8.3.21
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DBMVPVEM, v11.0.0
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyDelete, v8.0
  EasyScrap, v24
  ErrorFilter, vv3.7
  FastGuildInvite, v66
  ForTheHorde, v
  GlobalIgnoreList, v8.2.5
  GreenWall, v1.11.0
  HandyNotes, vv1.5.10
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionTreasures, v1
  HandyNotesVisionsOfNZoth, v38
  HideSocialChatIcon, v
  Incognito, v1.4.1
  Informant, v8.3.BETA-4-4 (NzothsFolly)
  LibSpellRange10, v1.0.13
  MasterPlanA, vA
  Narcissus, v1.0.9a
  OmniCC, v8.3.5
  Pawn, v2.3.26
  Postal, vv3.6.2
  ProspectBarLives, v4.6
  RaiderIO, v8.1.0 (v202005240600)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  RareShare, vv1.0.0
  RareShareUldum, vv0.6.0
  RareShareValeofEternalBlossoms, vv0.1.1
  RareShareMechagon, vv1.0.0
  RECrystallize, v1.7.0
  SellJunk, v3.0.20
  SexyMap, vv8.3.0
  SimpleILevel, v8.0.1.8
  SimpleILevelGroup, v8.0.1.8
  SimpleILevelSocial, v3.3.10
  SimpleSpellsteal, v1.0
  Simulationcraft, v1.12.5
  StatWeightScore, v8.1.1
  Stubby, v8.3.BETA-4-4 (NzothsFolly)
  TheUndermineJournal, v5.5.20200523
  Titan, v5.18.7.80300
  TitanBag, v5.18.7.80300
  TitanClock, v5.18.7.80300
  TitanGold, v5.18.7.80300
  TitanLocation, v5.18.7.80300
  TitanLootType, v5.18.7.80300
  TitanPerformance, v5.18.7.80300
  TitanRepair, v5.18.7.80300
  TitanVolume, v5.18.7.80300
  TitanXP, v5.18.7.80300
  TomCats, v01.05.00
  TomCatsNzoth, v1.4.23
  TomTom, vv80300-1.1.2
  WeakAuras, v2.17.5
  WeakAurasCompanion, v1.0.0
  WeakAurasOptions, v2.17.5
  WorldQuestsList, v92
  ZPerl, v5.9.5
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=a44)

**Comment by emptyrivers** [comment] 2020-05-28 15:17
Duplicate of WeakAuras/WeakAuras-Companion#68

**Closed by emptyrivers** 2020-05-28 15:17 UTC
