### ISSUE TITLE
More options for subcategories

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras2#1944] opened 2020-01-30 13:07 UTC
**Is your feature request related to a problem? Please describe.**
too longlist of WA or grps of WA and i would like options to sort them  and make subcatergories to shorten that list

**Describe the solution you'd like**
More options other then loaded and unloaded.

**Describe alternatives you've considered**
would like to have ability to sort them-like class,expansion,raiding,party,utility,  ....  WA
**Additional context**
No.

**Comment by Vardex** [comment] 2020-01-30 13:09
That seem like a duplicate of #581

**Comment by InfusOnWoW** [comment] 2020-01-30 13:11
Indeed.

**Comment by Addonman** [comment] 2020-01-31 11:39
Too bad  soon is not shorter then a year since 581 last post is from year ago.

**Comment by emptyrivers** [comment] 2020-01-31 13:59
Well... you’re not wrong.

**Closed by emptyrivers** 2020-01-31 13:59 UTC
Labels: 🎨 Feature Request
