### ISSUE TITLE
Load - Instance Size Type: Battleground not working

### ISSUE THREAD

**Issue by theoriginalmre** [WeakAuras/WeakAuras2#3806] opened 2022-09-10 07:33 UTC
### Description

In WotLK Classic, having a WA load in a battleground via "Instance Size Type: Battleground", does not work. 
Instead, it needs to be set to "5-man Dungeon" to activate in a battleground. 

### WeakAuras Version

WeakAuras 4.1.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Load any WA in a Battleground
Select "Instance Size Type: Battleground" for the WA
(It will not load.)
Select "Instance Size Type: 5-man Dungeon" for the WA
and it will load.

**Comment by mrbuds** [comment] 2022-09-10 07:58
> ### Reproduction Steps
> 
> Load any WA in a Battleground Select "Instance Size Type: Battleground" for the WA (It will not load.) Select "Instance Size Type: 5-man Dungeon" for the WA and it will load.

Did you test only in Alterac? Blizzard API is bugged in this one

**Comment by mrbuds** [comment] 2022-09-10 08:00
If you can replicate in a battleground that is not alterac, can you show result of this command `/dump GetInstanceInfo()`?
Otherwise this ticket is a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/3300

**Comment by mrbuds** [comment] 2022-09-11 11:32
No reply from reporter.

**Closed by mrbuds** 2022-09-11 11:32 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
