### ISSUE TITLE
Trash On Cooldown

### ISSUE THREAD

**Issue by C00kie-M0de** [WeakAuras/WeakAuras2#5269] opened 2024-07-29 14:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have used this for ages but after the latest patch and changes to talents it stopped working. I have tried make a new aura, changed some options but it will not trigger and show when on cooldown.

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
No error.
```

### Reproduction Steps

Premade Auras, Progress Bar, Horizontal Bar, Cooldowns, Thrash

### Last Good Version

No

### Export String

```Text
!WA:2!1v1ZUTXntCVrhsGsrGTsQruGrHRXxmskqstCJDkkqoOvw(FqrYFRKJDksRe3DP0YKvKeKu2w(weAb8HEs9qURZFf4d6bOhYtaJqFc0JGFc6qUBKJdI9b5zMD4Wz(nZ8JoBKRtUWCHN(0Hsos8M9jHQOV(9w5QTAjXQdCehNi5mcf(6Usfo85OJVY5ke6ve9sC5pMBeIgeXe7YiuLFXsvQxYBSnAEmfsryuh(Cxq)5SqSBH9Qx9mFuWBAlyDPHfzXmXoooo7M5rpC1(kbPDBSqEJLfPINERbHeboWearXTkuzZsRZNRRe3OnMIfKGArSJQsBo(cQtK2)vKXIdzhr9OOoyz2XMJnnAnhgI972Qv9ECSyRsL3DJ9kZNnicjAJLnyGrKIjw6zpZvbE4j5444jYU(4dXuvn4GKJh1OyHA1BuREbV6tmb36urOWurEw)45)yoS4UcwBbwkx8E1mEDFB2iWDqekH2oAAO3vGHq7vB3sLlpEAqRavqZ(wXTdLzhz(qAUgnyQh3257)B3UuIYNhJ6HfdmUPeaC3uK6DUhnasVeWnlFoeGfhIRNOB6q)Vzgscy0gb2otg4VZGgmwqrXVa6maW9Uj80sPgRRia)DlmZvgGOKo2U8AEsfsO2qN3LYO43JrsCnLatBRIU64WUcRxnmyQqIHBku234JPnOxX1ahWz1RO)HRQFIEv9A6v8BbqKm6ZnpQLakzi2ifktFFKiDykJtgO1krkZDHJ(0r8x6meGzpCBifK7mVo)yq98PXudTycCIHtZZ)wf(yvd7pGDOgBWBOiDWn4WCeXGhzgm1LLUlNpRvtgHGU(0X7mtsSIJBzxy0xNFtRfuxfZaCb29r3cG6zjxg5yCO14BhNSP9Y0LZ3B)UzLK0QN(AdfM9lCDWOBLQvkX)pxwghJBJc61OvmJjI05fqPA8IF)l7aH9Gfhsqdve0TJG54EdTED(SXG0tbt6ZUHGCYI)3UOqtdzX6155)cXnrWZe(qEUpbQsRUfMHV4LLoDyHnmT0MJTF8iMiCFbI3F)uHXttgZWKBfy8lTB8juvd3UsLsEnkxAJ68V5YUPeTuK(qOl7hJJop81iNGZN2voiTRCHIj1yMtVLUrgDHLUlv7Ahd0f1xxVUUKEJ3Q30rVL(A6T17ad2L1vSaQUQExDTfMrVN(f6xfPF5OK81B7n36lHO0ubyZ4xYR)vh9(6d43STafsaUKQcZV2nUHBv1B7FUAL6fkBlKUcCY67kLR9C3ygkS1KGyKucGvOHZjyzFjqmfJ)GxNUXkY8FOPVcfdXBEnz(B78N)EtEoln0fovtpRo4twxJEIaaygHj2DrxiiHgUMvkS(68zHyui9fg7dorcKLGwUM(XzDHvFvw9pMDWhxWxbWjNmJHfha9RYTEMDW5BwxBISdJPI(iFBZp)gi0OHclfGL6hb0eqSNGPiOlVzkYf5EcJ1XzGLluscXE2oqYBNfNo)B5ktWXfMzK9JBHjTJuptKcY9DJjNCcseEwY8YggslZf7xROxPsvsONQN4m)EBB4ABHcWVQicwWPTDrIxT32p4CThuZ(OQ9yrdvSGdtOLVTZF9)xIe6xhWpzKFKnnUVhkMhHY4DKHj53(Q0uKegIPEvk9IsER0Leo61v6X790JwRdMkiutaXn9HkRfPD2rSZhI0bdnm2elOFNL9cIWbVznVdrXDXo9pejigmCK99O9Kgz9nYyE5HcV8CNL1VBh7782FYKPp8oc0au90)0icnzogcm0ZHljkN0F1h(4vF4tYD4)CW)(
```

**Comment by InfusOnWoW** [comment] 2024-07-29 14:28
That's a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/5246. We'll probably change how we use the spell id and will make that work better. Until then enabling the "Exact Spell Match" option on the trigger page fixes it.

**Closed by InfusOnWoW** 2024-07-29 14:28 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
