### ISSUE TITLE
Stagger weakaura (trigger not custom coded) not updating when stagger goes down

### ISSUE THREAD

**Issue by Jackseltje** [WeakAuras/WeakAuras2#342] opened 2018-01-29 00:13 UTC
What steps will reproduce the problem?
My current idea is that Stagger going over 100% (so completely filling the bar) triggers the issue. Not 100% sure though. It seems to start updating again when I either take damage or purify (or use the T20 4pc purify effect)

What is the expected output? What do you see instead?
I expect the bar to go down again when stagger naturally drops, but it sticks as a full bar. When this happens, the (condition) color of the bar seems to bug out too, the (custom coded) text always updates and gives the correct value.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
No

What version of WeakAuras are you using?
2.5.4

Was it working in a previous version? If yes, which was the last good one?
No, it's been doing this for a long time already

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
No errors reported

Please provide any additional information below.
[This is the bar bugged (after resetting a boss):](https://cdn.discordapp.com/attachments/323117933234618378/407277167190212610/unknown.png)
[This is what it should be at 0% stagger:](https://cdn.discordapp.com/attachments/323117933234618378/407277527573200918/unknown.png)

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

https://wago.io/SJ90eynBf

**Comment by InfusOnWoW** [comment] 2018-02-04 16:39
Hmm, I couldn't reproduce that in a few tests, but I can't easily test that.

Can you change the left text to "%p / %t" and post a screenshot of what that shows the next time it bugs out?

Also when it is bugged, try casting "Detox", I'd like to know whether the bar updates after that.

**Comment by Jackseltje** [comment] 2018-02-06 17:57
I tested in proving grounds:
https://imgur.com/a/wRwe3
So what I learned, it doesn't always bug when it goes over 100%, it took me several times of going over 100% to get it to act up. However going over 100% does seem to be the way to make it happen like this. 

Detox does make the bar update. 
Using Expel Harm without having T20 4pc equipped (I unequipped to test) makes the bar update.

Also I noticed and screenshot the green one with 111% as well, since it might be related? The bar should be green under 30%, then yellow until 60% and then red, with the right text going purple and big at 100%, so it somehow skipped the yellow and red conditions while stagger went up, and it skipped the text condition, but the bar itself did fill correctly there (since it's clearly completely full). I haven't really noticed this happening before (but that doesn't mean it never actually happened obviously), I did notice it several times during testing now (in different variations, sometimes yellow bar, sometimes red bar, but no big/purple text).

**Comment by InfusOnWoW** [comment] 2018-02-06 19:24
Thanks, I'll see if I can rerproduce it now, or figure out where it breaks from the new information.

**Comment by InfusOnWoW** [comment] 2018-02-10 17:59
I couldn't reproduce that in the proving grounds, but I only tried for 10 minutes or so. I think I found the issue anyway and will push a potential fix to the next alpha tomorrow. 

It would be great if you could test that.

**Comment by InfusOnWoW** [comment] 2018-02-11 18:47
Hopefully fixed now.

**Closed by InfusOnWoW** 2018-02-11 18:47 UTC
