### ISSUE TITLE
Add Support for using class color

### ISSUE THREAD

**Issue by syndenbock** [WeakAuras/WeakAuras2#2934] opened 2021-02-13 21:09 UTC
**Is your feature request related to a problem? Please describe.**
No, this is a new feature.

**Describe the solution you'd like**
I would love to have the option to use the characters class color for elements which would dynamically get loaded on login so it adapts when switching characters.

**Describe alternatives you've considered**
I currently use animations with custom code to use class colors which propably causes a massive overhead as the color gets updated on every frame while the frame is visible.

**Additional context**
[Example WeakAura using animation](https://wago.io/vxECAxAcs)

**Comment by InfusOnWoW** [comment] 2021-02-13 21:43
Duplicate of #2013

**Closed by InfusOnWoW** 2021-02-13 21:43 UTC
Labels: 🎨 Feature Request

**Comment by syndenbock** [comment] 2021-02-13 21:59
Sorry for creating a duplicate, I searched existing issues for "class" but should have searchedmore general for "color".
