### ISSUE TITLE
Aura (debuff) - Multi-target Unit doesn't show most recent debuff's duration

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1316] opened 2019-04-30 10:54 UTC
**Describe the bug**
when applying a second unstable affliction debuff to the same target, I assumed that the bar would update and show the most recent debuffs duration, instead it showed the remaining time of the previous debuff.

**Do you have an error log of what happened?**
no error

**To Reproduce**
1. import wa from below
2. cast unstable affliction twice on the same unit and notice how the bar doesn't show most recent UA's duration
3. change unit to nameplate/target and notice how it does update properly

Applying it to a different unit with multi target unit does update it however

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
2.12

**Was it working in a previous version? If yes, which was the last good one?**
no idea

**Additional context**

``` !nw12Yjooq0VM5XKY3WgEzRciqfQnXKfzM9snLZiSLnAJrYRSCcKhY3(2TKnMKzVKQOm2T6w60DF6JsDttsj80yx)qpVXPKMuI31UEx7KsoKsYXFGdA2r9YkAjSASuWa300SNAi8xzqOqyhxxu0W0PXEHx7666m2FY4a)Or9E(UGp158YRcI8D89JM474fm2DYK0IRccsjur2EP6bjxOtjZxeNSydSr1u1tBKAQMlfPXaav4hSeaBWoVoEbeygUydcz4CvA4fynUG39wb8AZEZ7O9mP4XmzLubwIDn)8mp9npdWNGFnSQIpaMDu18HaxoEsK74OWjobrEEbooqEmYFyZwc5wq04rEob(U((Ht6wV)aYznuDRcsM0DDjQTe97M8SssnDHMAwg()H2knVpjYQOnn)G1gSZ8bJGzn)a7sG3LXogqokCK7OOqhhVjrqJXdb5OlQchKs9(huYsfdoraOTnSP5)zBJMLZYVNlqBkwj0bsovd9zkKsqHQNdGlJePwfSg4o)aTI3O7yxsS8U4ynU5VqpLsEvkpysFt9WemI(F0rAv9EkcsslhiS3u6nz6FffW)5BTB9)w(g65ggbDdhFpOR5gI5B0q(UtQYzQzaYZvY6uYSk(RVsv5V99ePeQQGPmi3Lhqc426CS7rA7(pN3uxrpHlDhRa2TTtF77h)YbQoB)CzlMcAfVSKPASil5Sb8vOYEp6kWorFNzRLc6bwN7Ka)rEEM(V8WoUG9atTfP5GRYxeRfvNWxBA3XEMj0pOyf8JPeYdlU7UZXCVmhhL3lF5wE5EwJHjURTOW2(UD6M7xU9oRhZRGrxBl8CV1B4aiqu4b848PKKhjjt3azHzfyFy0k9EGlErgrCE33RRza7h6sKFYqZRQwL3yhzHsrmK3y20IjyhLM0xmalLkzB9)WgDHD8aXntmuKndeOGXZSeRrt9i(kxhROHMPe0QVcTiJGJRryciTg9Nluy6QicJ2woogdo8O1ydd0yGubXnLl(8EFwP6Z5pYx7yQRelv4ms30MHgO5zpD6MUGnAmwvzZS0sf)13((V0sZH1Pa9oPN83lQdY47zafbKSdDMmEueOsmomY1Zdfjcg3pAEPi)7fhOhpRSnRIjYTuVP3CZaUN)Fke7C9OZcyykHA34)wGUsyWPR7GbBry27Kt)nJEI1dep23wKxY6r9l8CGQgJs4DR2Dhxy)3FkyAUzPHJ54DlwMytsKokYVmENb1i85q8gm)RwS42lbERTfe7F2appNjaOV4R4Ds0wnCR566(Ra19T55))xXDHE1gZPq(sTzhLMIDUvaBgkMBAbDvLjarvbdIG2fqDmct27UxIwTYiK5BwSi(d3F31)3MS2Ysh2pU4zyIB4IWK(BmwHdKf0m23MtbcTOeqZ32U6QHVUIyUPGivCq4XY1j3UEZQ)yDCYuJUNiNFz5b9)tuDG4k4L9AgpJAbE4cP)9 ```

**Comment by InfusOnWoW** [comment] 2019-04-30 14:22
That's a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/916

**Closed by InfusOnWoW** 2019-04-30 14:22 UTC
