### ISSUE TITLE
Choosing icon causes error with latest update 

### ISSUE THREAD

**Issue by komxela** [WeakAuras/WeakAuras2#3512] opened 2022-03-01 07:39 UTC
### Description

Unable to choose fallback icon, nothing showed up and it causes LUA error.

### WeakAuras Version

3.7.12

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

34x WeakAurasOptions\OptionsFrames\IconPicker.lua:69: bad argument #1 to 'pairs' (table expected, got function)
[string "=[C]"]: ?
[string "@WeakAurasOptions\OptionsFrames\IconPicker.lua"]:69: in function <WeakAurasOptions\OptionsFrames\IconPicker.lua:33>
[string "@WeakAurasOptions\OptionsFrames\IconPicker.lua"]:101: in function <WeakAurasOptions\OptionsFrames\IconPicker.lua:101>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = "table expected, got function"
 = <function> defined =[C]:-1

### Reproduction Steps

1. Opened weakauras
2. Under icon settings
3. Fallback icon
4. Choose icon
5. Use "search"
6. Tried typing in icon id or any icon name
7. Nothing showed up and causes LUA error

**Comment by mrbuds** [comment] 2022-03-01 07:55
duplicate of #3511

**Closed by mrbuds** 2022-03-01 07:55 UTC
Labels: 👯‍♀️ Duplicate
