### ISSUE TITLE
Multi-target unit restriction

### ISSUE THREAD

**Issue by Hyperion29** [WeakAuras/WeakAuras2#1122] opened 2019-01-24 21:23 UTC
There are certain buffs/debuffs which can be applied to both friendly and enemy units (Kelp Wrapping), and the only current way of restricting multi-target scan is using Nameplate as the unit. This is a problem if the player used friendly nameplate.

Feature: When selecting Multi-target we could have the option of scanning Enemy, Friendly, or Both types of units.

**Comment by InfusOnWoW** [comment] 2019-01-26 11:41
That's a duplicate of #883

**Closed by InfusOnWoW** 2019-01-26 11:41 UTC
Labels: 🛠 Feature Request
