### ISSUE TITLE
WeakAuras-2.16.6 not loading

### ISSUE THREAD

**Issue by D0nk3y** [WeakAuras/WeakAuras2#2064] opened 2020-03-23 19:49 UTC
## Describe the bug
After install of WeakAuras-2.16.6 the addon is not loading and producing multiple LUA warnings. I already tried to delete and reinstall, clear the WTF folder and install both alfa and Beta. And disabling all other addons. No joy on either.

``
  ERROR HERE

#LUA 1
Message: Interface\AddOns\WeakAuras\Locales\zhTW.lua:8: unexpected symbol near '<'
Time: Mon Mar 23 20:39:26 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\Locales\zhTW.lua:8: unexpected symbol near '<'

Locals: 

#LUA 2
Message: Interface\AddOns\WeakAuras\Locales\ruRU.lua:8: unexpected symbol near '<'
Time: Mon Mar 23 20:39:26 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\Locales\ruRU.lua:8: unexpected symbol near '<'

Locals: 

#LUA 3
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:3813: attempt to index field '?' (a boolean value)
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3813: in function `Modernize'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4297: in function `PreAdd'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4432: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3966: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3973: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1624: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1596>

Time: Mon Mar 23 20:39:28 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:3813: attempt to index field '?' (a boolean value)
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3813: in function `Modernize'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4297: in function `PreAdd'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4432: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3966: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3973: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1624: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1596>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1679: in function `Login'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1752: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1703>

Locals: <none>

#LUA 4
Message: Interface\AddOns\WeakAuras\Locales\zhTW.lua:8: unexpected symbol near '<'
Time: Mon Mar 23 20:39:29 2020
Count: 4

#LUA 5
Message: Interface\AddOns\WeakAuras\Locales\ruRU.lua:8: unexpected symbol near '<'
Time: Mon Mar 23 20:39:29 2020
Count: 4
```

**Comment by emptyrivers** [comment] 2020-03-23 19:50
Duplicate of #2063

**Comment by emptyrivers** [comment] 2020-03-23 19:50
Oh, wait there are multiple reports. Sorry, didn't notice that there are other bugs in here.

**Comment by emptyrivers** [comment] 2020-03-23 19:52
@D0nk3y can you please provide your saved variables? Your installed auras can all be found at `WTF\Account\<Account #>\SavedVariables\WeakAuras.lua`

**Comment by D0nk3y** [comment] 2020-03-23 19:55
cant upload it to this field, which format do you want it in ?

**Comment by emptyrivers** [comment] 2020-03-23 19:57
A zip file is fine, thank you.

**Comment by D0nk3y** [comment] 2020-03-23 19:58
roger that, fyi i tried deleting the WTF files too. And reinstalled WA, that did not work either.
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4371642/WeakAuras.zip)

**Comment by mrbuds** [comment] 2020-03-23 20:25
I don't have any error using your file on a mistweaver monk

**Comment by Ghalleonn** [comment] 2020-03-23 20:26
I encountered similar Lua errors with the Locales of zhTW and ruRU , tho these went away after reverting back to the released version. I do have a different Lua error showing up that I do not see here which also probably links to the region.

**Comment by mrbuds** [comment] 2020-03-23 20:31
@D0nk3y can you clear your errors in bugsack and copy which error you still have with last alpha please ?
I tested with your file and don't have issue with english locals, so i think the only issue you have left is duplicate of #2063

**Comment by tsoxos** [comment] 2020-03-23 20:31
It seems to be connected to the classic version of it. I deleted the automatically downloaded version, i downloaded manually from https://www.curseforge.com/wow/addons/weakauras-2/download/2881333 and it worked, just displayed an error about being downgraded. This may be just a workaround but it works for now

**Comment by didallwrong** [comment] 2020-03-23 20:39
tried that and  i get regiontype not defined      

https://cdn.discordapp.com/attachments/517622768741777410/691728462939160676/WoWScrnShot_032320_145153.jpg

**Comment by mrbuds** [comment] 2020-03-23 20:41
what's the context ? did you revert from alpha to release ? can you share your savedvariables ?

**Comment by tsoxos** [comment] 2020-03-23 20:41
Weird, since it worked for me. On the error about the downgrade did you press cancel or repair. you need to press cancel.

**Comment by delle7** [comment] 2020-03-23 20:45
same issue =/
[WASavedVariables.zip](https://github.com/WeakAuras/WeakAuras2/files/4371831/WASavedVariables.zip)

**Comment by didallwrong** [comment] 2020-03-23 20:46
want the  lua file or bak ?

**Comment by Hfdseue** [comment] 2020-03-23 20:47
I'm having the same issue
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4371836/WeakAuras.zip)

**Comment by mrbuds** [comment] 2020-03-23 20:49
@delle7 can you include your WeakAurasArchive.lua ?

**Comment by delle7** [comment] 2020-03-23 20:51
> @delle7 can you include your WeakAurasArchive.lua ?

all 3 *.lua files included or you need something else?

**Comment by mrbuds** [comment] 2020-03-23 20:52
WeakAurasArchive.lua

**Comment by delle7** [comment] 2020-03-23 20:55
> WeakAurasArchive.lua

its already included in my attachment or you want another file from another directory? :D

**Comment by mrbuds** [comment] 2020-03-23 20:56
indeed i'm blind sorry

**Comment by Ghalleonn** [comment] 2020-03-23 20:58
Btw, It could be related but the error in my post is different from any posted here. Not sure if that one counts as a duplicate tho.

**Comment by D0nk3y** [comment] 2020-03-23 21:03
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:4401: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4401: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4365: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4268>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4395: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3928: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3935: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1606: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1578>

Time: Mon Mar 23 22:02:50 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:4401: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4401: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4365: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4268>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4395: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3928: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3935: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1606: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1578>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1661: in function `Login'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1734: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1685>

Locals: <none>

**Comment by Ghalleonn** [comment] 2020-03-23 21:04
Alright, nvm. That is the same error I am encountering. Issue is the same then.

**Comment by D0nk3y** [comment] 2020-03-23 21:18
> @D0nk3y can you clear your errors in bugsack and copy which error you still have with last alpha please ?
> I tested with your file and don't have issue with english locals, so i think the only issue you have left is duplicate of #2063

Message: Interface\AddOns\WeakAuras\WeakAuras.lua:4401: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function error' [string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4401: in function SetRegion'
[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:4365: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4268>
[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:4395: in function Add' [string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3928: in function load'
[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:3935: in function `AddMany'
[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:1606: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1578>

Time: Mon Mar 23 22:02:50 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:4401: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function error' [string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4401: in function SetRegion'
[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:4365: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4268>
[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:4395: in function Add' [string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3928: in function load'
[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:3935: in function `AddMany'
[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:1606: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1578>

[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:1661: in function `Login'
[string "@interface\AddOns\WeakAuras\WeakAuras.lua"]:1734: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1685>

Locals:

**Comment by didallwrong** [comment] 2020-03-23 21:38
Ive been going from release to alpha; the error goes to region not defined to error at "<"; i even tried to uninstall it  a bunch of times too

**Comment by D0nk3y** [comment] 2020-03-23 21:50
Tried rolling back to earlier release, not using alpha. Still get the same error as above.

**Comment by Hfdseue** [comment] 2020-03-23 21:51
I just updated to the most recent version (2.16.6-55-g9519f6a) and now I'm getting this error:
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:4439: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4439: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4403: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4306>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4433: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3966: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3973: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1624: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1596>

Time: Mon Mar 23 17:47:01 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:4439: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4439: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4403: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4306>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4433: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3966: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3973: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1624: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1596>

[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:733: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:693>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1679: in function `Login'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1752: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1703>

Locals: <none>

**Comment by emptyrivers** [comment] 2020-03-23 23:11
Hey folks, sorry for this chaos. We've identified the root cause of the issue, which will be resolved in a future release (at which point this issue will be closed).

If you are receiving an error about `regionType not defined` like this: 
![image](https://user-images.githubusercontent.com/24878501/77371409-3946fc80-6d31-11ea-82ad-574bf2f24972.png)
Then unfortunately you will need to recover your data from an external backup. If you are unsure about how to do that, then visit our [discord](https://discord.gg) for help.

If you do not have a backup, then unfortunately you will have lost some of your auras irretrievably. In this case, you may paste the following macro into chat to get WeakAuras into a usable state:
```lua
/run for id, data in pairs(WeakAurasSaved.displays) do if not data.regionType then WeakAurasSaved.displays[id] = nil end end C_UI.Reload()
```

My apologies for any inconvenience this has caused.

**Comment by noiseuu** [comment] 2020-03-24 15:27
I have weakauras there, when i do that code line but all groups are gone :P

**Closed** 2020-03-24 19:33 UTC
Labels: 🐛 Bug

**Comment by hatermajt** [comment] 2020-04-15 16:25
/run for id, data in pairs(WeakAurasSaved.displays) do if not data.regionType then WeakAurasSaved.displays[id] = nil end end C_UI.Reload() after doing this I can add new weakauras but i can't see them or move them and they are loaded

**Comment by InfusOnWoW** [comment] 2020-04-16 17:27
Then your settings are probably even more broken. If you have a backup (by e.g. running the companion, restore that.)
