### ISSUE TITLE
Add a trigger check for opponent's specialization in arena

### ISSUE THREAD

**Issue by Knbi** [WeakAuras/WeakAuras2#4691] opened 2023-11-04 23:44 UTC
A lot of WeakAuras meant for use inside arenas have to either use custom code to use GetArenaOpponentSpec or use custom combatlog triggers to check if a certain spell is cast.

It would be extremely useful if we could get an additional "Arena opponent spec" toggle under Player/Unit Info->Unit Characteristics->Specific Unit that pops up inside the tab if/when we use arena1/arena2/arena3 as specific units. Kind of like this: https://i.imgur.com/T6ZjpSX.png

And if checked it'd offer the dropdown of available specialization inside the game.

It'd be a massive quality of life improvement for all arena players IMO, I'm sure other players would agree with me because it'd open doors to a ton of new useful auras. F.ex. it would allow better auras when making timers for enemy cooldowns, or you could create reliable warnings when certain specs use something which is otherwise a longer cooldown for another specialization.

**Comment by InfusOnWoW** [comment] 2023-11-05 09:32
No one in the team has any interest in arenas, thus this will require a PR to come.

**Comment by mrbuds** [comment] 2024-01-27 08:29
This seems to be a duplicate of #4683

**Closed by mrbuds** 2024-01-27 08:29 UTC
Labels: 🎨 Feature Request, ⏱ Awaiting Response
