### ISSUE TITLE
Allow us to add note or namechange conditions to keep track of what's inside.

### ISSUE THREAD

**Issue by wazerstar** [WeakAuras/WeakAuras2#4190] opened 2023-01-03 06:07 UTC
**Is your feature request related to a problem? Please describe.**

[Having many conditions, you can quickly loose track of what conditions you made as overview.](https://i.imgur.com/RceoMA4.png)

**Describe the solution you'd like**
Let us allow to set a note / name change conditions

**Additional context**
[Example of how it could be.](https://i.imgur.com/dcUisdj.png)

Also letting us hover mouse over conditions if note/name change is too lengthy to be shown by default to see the entire note/name as popup.

**Comment by InfusOnWoW** [comment] 2023-01-03 09:40
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/1302

**Closed by InfusOnWoW** 2023-01-03 09:40 UTC
