### ISSUE TITLE
Adding borders to a group of icons

### ISSUE THREAD

**Issue by Kaszz** [WeakAuras/WeakAuras2#2021] opened 2020-02-27 01:49 UTC
## Describe the bug
When i add borders to a group of icons, instead of giving me 1 border shared border in the display tab that i can change the entire groups borders with im given multiple borders. It seems like it splits the group up into chunks and adds a new border for each chunk. This both happens if i select the group or all the icons within the group when doing it.

**Do you have an error log of what happened?**
No.

### To Reproduce
Here is a short video of it happening:
https://www.twitch.tv/videos/558443154

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of WeakAuras are you using?**
2.16.6-29

**Are you on World of Warcraft Classic or Retail?**
Retail

**Was it working in a previous version? If yes, which was the last good one?**
It has been a problem for the entirety of 8.3 for me. I havent tried before then.

**Comment by emptyrivers** [comment] 2020-02-27 01:56
This is working as intended. The display tab edits child auras, and in this case you are adding a border to every icon individually.

**Comment by emptyrivers** [comment] 2020-02-27 02:02
Ah, when I looked at your video more closely, I see the actual problem you're having. Can you provide the aura you used in that clip, so I can take a look?

**Comment by mrbuds** [comment] 2020-02-27 02:32
Is it this that you search @Kaszz  ?
![img](https://i.imgur.com/5O2sjCD.png)

**Comment by Kaszz** [comment] 2020-02-27 02:52
No, im not looking to make a border around the entire group.
Im looking to add a simple border to every icon in a group. However when i do so i have to edit multiple borders in the display tab for every icon to have the effect applied. I assumed this was a bug on the discord and was told to inform you here.

**Comment by Kaszz** [comment] 2020-02-27 02:53
> Ah, when I looked at your video more closely, I see the actual problem you're having. Can you provide the aura you used in that clip, so I can take a look?

https://wago.io/bfaraid5
It has however happened to every group ive tried.

**Comment by InfusOnWoW** [comment] 2020-02-27 23:26
That's working as intended. Subregions options are only merged if they have the same position in all children. That's not entirely optimal, but hard to change.

**Closed by InfusOnWoW** 2020-02-27 23:26 UTC
Labels: 🐛 Bug, 👺Working As Intended
