### ISSUE TITLE
Request Trigger (Name) Future

### ISSUE THREAD

**Issue by Xpatro** [WeakAuras/WeakAuras2#4959] opened 2024-03-26 18:26 UTC
In weakauras we got something called "Triggers"
-. Would be really nice if we could give it like a short name (BR / Bags)... something with 10 letters.
- This would make it easier to see what it is if an Weakaura has like 30 triggers to keep em seperated but fast find the "issue"

**Comment by emptyrivers** [comment] 2024-03-26 18:28
duplicate of #4617

**Closed** 2024-03-26 18:29 UTC
Labels: 🎨 Feature Request, ⏱ Awaiting Response
