### ISSUE TITLE
All Loaded auras always shown

### ISSUE THREAD

**Issue by mucomuco** [WeakAuras/WeakAuras2#3588] opened 2022-04-17 15:05 UTC
### Description

When we open WA first time it show all loaded auras right? Then when we select a single wa in it, it shows that single wa on screen and hide all others. Now everytime i open WA  it shows all the loaded auras all the time and they dont go away when i click on one of the auras. 

### WeakAuras Version

3.7.16-28-g5186602

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Open WA
2. Click on an aura
3. All auras are still showing on screen.

### Last Good Version

3.7.16 probably, not really remember.

### Screenshots

![WA bug1](https://user-images.githubusercontent.com/74419406/163720323-7c5abbdb-e6fc-46b0-a2d1-78c6d8647d24.jpg)

**Comment by InfusOnWoW** [comment] 2022-04-17 15:21
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/3566

**Closed by InfusOnWoW** 2022-04-17 15:21 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
