### ISSUE TITLE
bfa - error on loading imported aura from live

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#419] opened 2018-05-17 09:51 UTC
What steps will reproduce the problem?
import ```dK0)iaGiQWJevQlrOOgfvKofveVIqrMfaDlcL2fvYVKIyyIk5ysflJqHNbGmnPiDnrfzBurLghvLI1rvP09Gs)tuboivLQwOukpKkktukPlsOYgPQK6JeQAKsrDsczLantQkHBkQO2PuPFcOgQOc6PqMkv5Quvs2kvLOVcG6TsP6UaWEP8xOObJoSelwuLhdvtMixg0MbKptLA0sHtl0QPQu51urvMTOCBPQDl43sA4uvTCI65ImDsxNGTdf(ovfJxkX5fv16fvO3tfvCFQOQ2VARJ5zOEdjzijZZqkSfTJVUguumhHw3oaKHWfsAT3d2IAObh0qfCnIb0to62nuoNRsqRRy7KldjiNzOgQ6p5BBst8P4U6kwBIVa6owdTkeCdRHwlb3q5Qqc5hMLLAstBQHk4ASgsMNHsArwnpdLQcbjdnXfsAT3q4cjT2BObh0qsvmXfsAT3YZqsvmtvHGKLNPgkgIQ5ziCHKw7n0GdAiPkM4cjT2B5zQHakgIPgMNHWfsAT3qdoOHKQyIlK0AVLNPMAOyqHYHsMVekNI1G1fGmKkhD7gkBEgsZ3p0q4cjT2BiCHKw7XuZ3p0qjTOqb)sffAiigWGMmeQzGbymBtK4f5mG7c4SzrTkomBtK4f5mG7AiCHKw7neqcbCnwdonPffMaCcXaguaNUC5YjdoNZPF5yqDQdFuGYboCYGZ5CgbAcXag0jwSthOMbgGXSnrIxKZaURJP2aggCoNZ5CoZQ4LSzeVgaCIxsQijaNscYfnwdtStxUCn4CoNZ5CkwX2E7doNZ5CoN(LJb1PdoNZ5CoNZ5C6i3OMbgGZ90bGdoNZ5CoNZ5C6iIxdyDa4mIxdao4CoNZ5CoNZPJjEjPIKW6aWjEjPIKaCW5CoNZ5CoNthtjb5IgRbSoaCkjix0ynm4CoNZ5C6KbNZ5CoNtaaGbNZ5CoNZKwuyQD8ssfjbGj2PZX5p4CoNZ5CMvXlzZKwu4e7mPffMAhVKursayW5CoNZ5mPff6k1O6Ze7uLfGdoNZ5CoNjTOqxr8AyIDgXRHbNZ5CoNZKwuOl8gLGBO0e7uLfGdoNZ5CoNjTOqxfbT2CucoXovzb4GZ5CoNZzslk0LF5QBzyk5LVF4e70Hg7HsogCoNZ5CotArHUKeKlASgMyNscYfnwddoNZ5CoNjTOqxWw8hLlASg8I9Wj2P4HQxSh6uNmfttjb5IgRHbNZ5egKgCoNZbNZ5mc0eIbmOtSyNoAwuRIdZ2ejErod4UoMAdyyW5CoNZ5mRIxYM4LKksAID6YLRbNZ5CoNtXk22BFW5CoNZ50VCmOoDW5CoNZ5CoNth5UzrTkUCpDa4GZ5CoNZ5CoNoM4LKkscRdaN4LKksAW5CoNZ50jdoNZ5CoNaaadoNZ5CoNzv8s2mPffoXotArHP2XljvKeagCoNZ5CoJantArHtTbmm4CoNZ5CoNZzslk0vQr1Nj2jqLSeCW5CoNZ5CoNZKwuOl8gLGBO0e7uLfGdoNZ5CoNWG0GZ5CcdsdoNZ5GZ5Ckdvb5WuLfGdcdsgcVbe35ziigWGAOuJQpahmuQr1hGd(ECnIb0udPWw0ooRg0sm0ddQHa2x5He1Q4mKcBr7KdRXGAO2a2Zd4C2qnGr3nuRBNCkxgkRwKmpdfdULRc(npd1lKPrZZutnKqcIzaIbu2YZqAjdguZZq9czA08m1udjfbcOiUqMMV5zOEHmnAEMAQHKl4qZZq9czA08m1ud5hd)AjdguZZq9czA08m1udjxZGMNH6fY0O5zQPgcOcUgRbZZq9czA08m1udPLmyqfdZZq9czA08m1udLI5i08mukgCNbnK)ISMVH6fY0O5zi)fznFRntn1udPWw0oIluYldkz5zOGqVNC0TBOCY62XqYq3XAWlF)qdfXRbd5tusByD7Kt5Yqajx6HivUOfRRZ1qkSfTJHeZ4gkkzO2IUfHxdtFAadtTi7gQqPPyyiPyY3jeW1igqdvYYmu(adeqjOADbiFtUmumevmtArwHsw3ogcVwZKQ(eS8m1qjd1keddHH1TttfJoMAg```

close weakaura options => raise error

```
1x [string "--[[ Error in ' BigIcon when targeted' ]]re..."]:13: table index is nil
[C]: in function 'xpcall'
WeakAuras\GenericTrigger.lua:508: in function <WeakAuras\GenericTrigger.lua:502>
WeakAuras\GenericTrigger.lua:650: in function 'ScanAll'
WeakAuras\WeakAuras-@project-version@.lua:1513: in function 'ScanForLoads'
WeakAuras\WeakAuras-@project-version@.lua:1560: in function 'ReloadAll'
WeakAuras\WeakAuras-@project-version@.lua:1240: in function 'ScanAll'
WeakAuras\WeakAuras-@project-version@.lua:1190: in function 'Resume'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:1362: in function <WeakAurasOptions\WeakAurasOptions.lua:1339>

Locals:
nil
```

What is the expected output? What do you see instead?
i expect no error (no error on live)

What version of WeakAuras are you using?
8.0 from git

Was it working in a previous version? If yes, which was the last good one?
no problem on live with master branch from git

**If i redo the exact same aura from scratch and copy the custom function, it doesn't raise any error
So my guess is that there is a migration problem going on here**

**Comment by InfusOnWoW** [comment] 2018-05-19 17:09
That's a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/418 TSU Auras need to cope with fake events in 8.0.

**Closed by InfusOnWoW** 2018-05-19 17:09 UTC
