### ISSUE TITLE
Glow block text

### ISSUE THREAD

**Issue by Sanluli36li** [WeakAuras/WeakAuras2#1526] opened 2019-08-07 09:45 UTC
Glow effects always block text
I want custon the frame level of text on icon.
![批注 2019-08-07 174307](https://user-images.githubusercontent.com/5201743/62612850-e3a51780-b93a-11e9-817c-f6f8d3e1b9fa.png)
![批注 2019-08-07 174320](https://user-images.githubusercontent.com/5201743/62612851-e3a51780-b93a-11e9-829e-dc841258676f.png)

**Comment by mrbuds** [comment] 2019-08-07 09:54
duplicate of #1519

**Closed by mrbuds** 2019-08-07 09:54 UTC
Labels: 🛠 Feature Request
