### ISSUE TITLE
"WeakAuras has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI."

### ISSUE THREAD

**Issue by GLopez12** [WeakAuras/WeakAuras2#4379] opened 2023-03-25 17:59 UTC
### Description

I get this error seemingly at random, although more often after I go through a loading screen or change zones: "WeakAuras has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI." It makes it so most of my keybindings stop working and I can't click any items in my bags without getting this error. It's fixed when I reload.

The only WeakAuras I use have no manual coding. They are also simple, showing Slice and Dice, Blade Flurry, and Roll the Bones buffs when they're up.

This has been going on for months, but it has become much more common with 10.0.7.

Here is what the error looks like:

![WoWScrnShot_032523_135702](https://user-images.githubusercontent.com/126917411/227733723-2c99b6f3-c3b8-4a18-85ee-99a1722429c7.jpg)

### WeakAuras Version

WeakAuras 5.4.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

It is really inconsistent, but the bug usually goes like:

1) Go through a loading screen or into a new zone.

2) Try to press any ability or click on an item in my bags.

3) Get the error: "WeakAuras has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI."

4) Realize that my UI basically doesn't work anymore until I reload.

### Last Good Version

This has been going on for all of Dragonflight, since prepatch.

### Export String

```true
I use just three WeakAuras for rogue buffs:

Slice and Dice:

!WA:2!Dr1tVTTnu8y4vumpSGeVUG1IDWRdlxkqqqABqVA5y3KcxBhjLLSdd2usuMSwMuLKYooxgMhWqp7pc(YUSt(WopKpbccd7dq(iKpb7rk50MPdsV)qY373p94VsTQoUAq1Gp89lP(CMdpr4J)2nYqjkcx0nwr5mzfXSUHHsS64)gFZ3Tb8ScX8H894uMYRrZoUnTZ858Oa(uMZuAmEW1RDBgmeteiFZjDOTuHeQkwugvvXle(ijvMRe0HdXc5M7kkm)ll1SySnkrGoyH(ndnglFYnoruFCnelO2rGr2yKYNGLoe(0USLs4t9OPOzsB8em0zhJrrkYnYepJFpboKEPTtVMTBpxgJJIojqw5U0ojHq6v9Bu3XTVJBDBxrIe3bk8aBt5RyLaTTxCeAgwSma7bBWfAtXXnB3R1zTxKWkA)kXBRr8eSBU)B5b4)CJBb2clyOOFeWkqh)2TJW446qN4RSrabrwiXrHgwn9bqbKifaDfMSe6rB8qnf(MDs3mdC9q(Jgk4jSGp8O4Qk8LQ(sccy8lY)xvk(XMGMxHCbqv9LfgwmodV4U0p9hKXB9jNqdEex8MsLkv(M8ORBkR6N52n(RmbHjeoCuu)ZPbkIvDW928ArVehyc(Rz5Jj)urhDTj)7sKkA4maGcUcaNle0Qt3ont3ua4sVMLMf6BAJYWZIcqWuXB1sqVQ2PjOaGyq1CDVh2xxPmtSPCrW5cu88ZlmYBGjuj1lctkW8NmkhV9jD600UVvxx3UV1(KxFSB2DL2HEf(Xfi6I7vhDwZCq3ZCBFsNM)B2Wi(0wc87tWm)z9(S937GxMJoDIv6xRpH5Ah9MZ8sukoR7eSaMVwQd3gZgQiFTz9Rr2cTtJ7yMRHj0xVocXsNKywIJpkcx20iUeQ)igwklBY0Mc2BBkGfWlybjCLNXOVeG4ds3CHE8Ye56Ie(FCIOisbjoy9wXW184TDEFcsGR1kjkQ25eQcqvEAEE37rW0He1PwrCuq4n(riPe(be0xFhyh7Xjrk6HhT1a3Tg8ITg4PamWu7K(ZvIRcaT)9xpX24RtBz2VXaGG2yPWCDrZSwALT4hTwqspVDevIGUpGiUCTY25zcTY281lBWceJQhW5Sdt)8wPBM(SRXij2rjm)wEywG(UjKUVwQsiXqvcKZ1Rrx10NzngrzMnMsFy67shLgbMFX)pI1vC(4EL3FVNVkuaYmqbGj7YlvC)j56eFtPF)pEkniDB7pELWgfftqLVnFESLEJ6Q650WUzZoEqVeshw5GeAWQEV6vx0E)ZgjQ3wqz6ZeM918zJcOcQtG8dOYnvFR90LAGqn61pzxBqF1F0HPFz55tqcQM1806E4a7jOOeCjHpbXgcAZ7M(ldMhl4axOMLU7kklxSboNkPbdQkTF5EVyVNxDY)CX)n

Blade Flurry:

!WA:2!DrvZUTTrqylOguuc0Iy1uJ6GAa3uuJcuaJaNgF3uwk2bksYK0wUNKwsosCJP2Lz3Lsw(srvbkYz9iOl9spPd9CGEciek6dGV3l(jOZUKYjP6G48hN5B(4mtP6vgwjSs4B)U50aoZLNkcGVzdX1T63xcQtExN)D4g4pXK1g6n)BF3gBuAbHfeXfT5uMYVATME1CwfW5XH8Xm3X0eO3Y1Q1charcsGIYzYdDKkIqz53NYOYilB8HYAQsqhmaeYVyprH4FjsLqtYqO3TYuFyeWuUP97tVEr3Qh561117ihVvdjQGiq6gXh3InxIpokEmzI0X8c(NaKyv09jOTaWe442UwJgtLjqC8PHsRzKubHHvs(4L2XKqy36XPcXe7ueA(jXKjGWX43YwnjbC0XFW8qWhXJhAqCsTgTRFEJzPScWBLSPUFhbE56VIhc)5g3HCfiyK4lWofjJF7URai5ieibkhcsprZKqCFdNM9aSasIclLcIMJDGdmqtGVCRSDwHQ(KGRgi4PSW3(OKkk4Avxzeb57lZ)svkzBJrZF95cKP6kleSzCgm7E3p57Ljp8dYqvEmx8YsLkv(2CRRbL9rN71k5lngjPkoMkAqhAOkY(iu9U8ArVgcng)1v5dj)CbIwA8)6uPI2Fc2GcUcBop0ODZwnRLTJa7lDmZnbgyGrz83SIMGPsEyDb9MDplLeIedzxpVpQ3xxPvgBJ5IWocsY0ofc5ayevs9JHOIE(dgKt280MnR501ULNxRx5C6loXB19L2LEdSDrhD5hvhTxZCqRZ9ACAZA)ZQbX8X1fWBsbwWK2FYt3)GNN3DAhlXb7xexqZrt1M0V9k)uLIZAnce4i3CT5gaBGk6RwOLx3AZgS(vnuJX3A4yRvImv3lIgCfdKYYMxWnGed5InOO5nn53g5fqe1FLVrOlppnlkuLyh)GLfkbVFOOWsbp2BD4aUNNSP7BsjcCfknoE3orufKTZm94Qjg)iGoisDMDmNe2)2GyIuIFac7Q3b2YxszdIHJFOVcrltTLZW0yf1kPcYyD)4G7zBELSUwoghAjBnG1cZfMDfnRARpRL8O13I0dBhtLee3HrZimQEeMZom7ZQVeisWvjmC(NMTt2pUkuV9HU7Qx7fsatvOCQooDQZ(r7HekREwE0z0SxNDf(06)BzbLLV3HPYAfU4GtqTsmNdTSVHZh2U8t3)zoVFEFUIhmk)gXxx63)JNqdZ2(GuA4IlyJU54FWnT6fDw0xGNKq8IRbLDgR33o7U8PZ6ApAe67w1PwTM(iU7thyjOmDwHihsCsePCg0BUULOgO849CWtPbxDy2NxE6iIGQjjF9noi0zejofkjcIiSb4DY9Y(LEtteCKvutY2B6A6TN5tv1cn8QhEwd6vr6889)P9FwLr)9L)3p

Roll the Bones:

!WA:2!TJ1xZTXvv8OresytBi2jXKykGBsQjDyW4yxhgkp0XRSCSYilPSsoonqR0(NR0EJxT7M7DxlBZFJsiyOqbeqBAhAliMoDykVGEOp3XFcoJgM8bWFe8d8A4CV7kz7ehkomthMb8dR29U37EpNZV)C21jU6GCTPg7fgBYbRpO1GwRpElDMzwIBTa77m0MgEmlctv3CjlMNVAopxsx9WaBpwE)aQNlxHTA(Qv5KG5(yBJN9LEWdEqhDxt8(f8OUbgPsNRuATorpMuEoESlNirIKACFDtYbz6MYhYf14b6SafvQlnqXOk(d3wPzaJwRgHXhEuw8P3TTfXiSA1sR6tyZLoBHzxiRAaEHMEitFIMCFIJtglUYM8qdYYe3GI4SPR0PCQPlwQCXstRvsne3edFh9vjmnx96eUIMCQgZr0DcS7V0cmcUuTIfsNnBRq34qqPJPNtyD3IImi5wyssyU6oxfJtmvUDlDxADDrwDr4PMfoUQlwY2GOZjfdyYQ6H6AHXQygLfroJtm9CT4nfZrKxWzvRRtDX1cNfo3HGNdgf(Q4Ph9Hhrt3HwZfomdlEIilrBmY1i1KWIMdTon4iQoE6wZQYPRrgsREOtavrflsMdbFdfnthDoxCMrGUdMWIt7AeJ1rGvYKjlKC8XMIfLwKkTQX8c9ZGH8PoX)4(ACtCLjBBseLbr0FMSAgrOTD7OFtBvJ4pqXBgQZiJmBOJZilAtdiTzYivSMnSwfXbQP8rhVQIyeFqvUhlaHCo(8TOU1my6w0q(DEQMHCswrcA3K5filMjAxfF2POmthsLnX4dRkUbZImmpMH20ZKzHIX0WmUiDn5grxerE)CnRXOwY4xBM2bEMlhbNNkXD)GZqT2uZdd7aBYiQiAYBjM8IuRa7J0Pkdzqi0QhONCRiM)SIHeplJIP0sNohgInIyltesT6mXe1Yn3stpU7QtzGHzvAnfvmZBCMfkWwjwl9sVbCaXFTfudAKqRd1TQhlIBP0ItCQgjXuZxQu(5h0CT1pxBko)IEHmtYZCa4ZMaoeC4UMEEowEnCl2G6tQSrVlfWInCeKLQahvbEAf4ZF0rHJ9rmS0MdtGkTeskP(yy)tuCjbWP7AnskMhNBikdDXyX0MWlA71iV7gC5ptJk6LjWxeEg4lbFz4KkWqWxaofCAyyfK)Ecyayq4RO4pGUCILIevZ7zr(RhaE2BV1seI)0cgAGMitTHfHdlya6bcrdgXFTlpeC8UitxqufmgxR1pH)GbKvckZT1Xu7ArfXe(NwoO8quLRmp(e4ST6FVZ8CC)JTJLVTl1MrJ2RsRo9cLY7FC5GOhONakmL0a1PXl3kAJORqI4g3QBeD4LJdNnK3)gH8aA1vXKssCjLWbvZLpxA44mmPeZPTCIM90FjBfNbUb(hBwgDTrUsOULGWnsPs7kX7TtDLJ1a53lY09BUy8jrbWYuo1WHyhNZ7WS2FGm5YLwRCeHslZLMRu3(BTqpE64m6A7AFe3v6hNFHszZKl997wZXRXSmYndjUMRw4Zm(ytmvu2jUrhXHEpHMIlelURryqGNBEu3HgZTfdh1d6KY53lZAjUOVZuYnqU6L6nITQ4M2YDVKn1CjKIYtkxrrPlL80SuC4bKBGAKnv1UrobL9I2d44TeSl5yXMeXGHKtepsCzSsSNszckNGxS3vc)2dAytO1SdUc81RUP0Qfl2wLLUVgC0nZHmZXGjeMU(dIjs5DpNkW4IBbxqECm5XVTQqGlNDQyzmQC0e(YWbvGRQalOa3RcCgzVhStHOHrV(hN)rg5Op8i(NON7GGwodLRJPOLnuOtUuUtsAm)8ZUWmqMyxr4v12MKInJ8T1tQ1qq9VcmpKd0uyuxHrkQAZMuDnpV6IEjt2XIYfTF71ePzVnTcuAUpw)IFKW5B9ZbVm6HHzvKngC9kW3PNF1tlTSI8RGVBfPftzOYoDDELHBPYWEFCQfr67G2pcxOi7hqx62ag2X1QhQx75)K7(cMXEra6)aKeqvCSAOzcyljkafUbSe4a1Vf4Ma8WuWhUjoDgWLvmiacHLtanGvGvTH1GVh89pn8dsa)q4hDF4h3t3a3cw3gUnCh4NCs4UjGFA0IBMa(z2WRLe(5jHFXaWV0Uko1Ff8Bpi8RJ2(FtfOf8IWRNa(Dcgi87hcEJE8TyQ1Bwz3Sl4EWBvrWFAxb(tcKbEB7DajWFucFiUUnf4pJiReSF3RGSKZpXLCnEHAzVP68W7zdVts4pefTlijNOvEmSgp8EaT7SvKaAFLH3OeleB8s0r2uThgM3ZMlpc6U)vcFkIUis(iOlI4i6Iq7R1hDrKfXYDdUceFpq33Cp9oq0fbKDaN9TlEBHcpDQLC1j(zQnX3AB499fcqKteJWiY)EcTCpMqejbzlBJS)hiy9hud)Ych01Ee8vVnPIxa7FP0f31)7tfIGKaw2nqHG3(rfIv4DQcJvl7H87d2jEIO77g58wOt(6p)fwHNE8BONsazVLeKJuHpPgEpgagd0pbCTZLyIxCCEId5)vSI3hI1hljaHZ(mGDGY7uqThmI)sp2Y2Q2cDM662QxHU0mx)cnIfW9zdpzEYBPgYOeRrkXWVAnKr2V2YF6QC)30HDF0)8X6WIv9iB1yOPN76LUqHRU4K5dF(vMCBS6dfIPS9vTrUR72JUVd7tAJmb4My)GT3aPqFiAS8(WRID3l3n6Z6MNYfVY6)hJrmgbubgp8OA4x)AU0fHJLS5Y4BNiEzzvr5sBzDNqssMPTUBn8ZNhf(BvA6Z8WVrkyvW8j)LsE03fRqN5(MRDZmfwPwgUtFMLQ4)xHGC9oj3DRBKEI8T(KQ7vzWL)7x7F(
```

**Comment by InfusOnWoW** [comment] 2023-03-25 18:07
These errors are very unlikely to be caused by WeakAuras.

Unfortunately the game was released in a pretty bad state, and such the game spread taint everywhere. This might be caused by other addons you have installed, but also happens without addons.

And also unfortunately the game does not allow addon authors to easily debug those issues.

Both of these issues are known to blizzard for months, at this time there's no point in investigating those issues for us.

You'll have to contact blizzard for support as it is on them to improve the situation.

**Closed by InfusOnWoW** 2023-03-25 18:07 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response

**Comment by GLopez12** [comment] 2023-03-25 18:54
I don't doubt what you're saying to some extent, but this simply does not happen to me if I don't have WeakAuras installed. And I mean it literally never happens without WeakAuras. So I'm skeptical WeakAuras doesn't have something to do with it.

**Comment by InfusOnWoW** [comment] 2023-03-25 19:10
That's still a blizzard problem. For example using a slash command can lead to addons being blocked. Fixing that is on Blizzard. The issue was reported 3 months ago, as far as I know it's still not fixed.

At this time, you really have to ask Blizzard for support. As it's on them.
