### ISSUE TITLE
Load condition for Instance ID

### ISSUE THREAD

**Issue by jcai1** [WeakAuras/WeakAuras2#2772] opened 2020-12-02 02:22 UTC
Currently, there isn't a load condition for Instance ID. This is different from the Zone ID and Zone Group ID load conditions that are already present.

My specific use case is that I want my WA to only load in Torghast, which always has an Instance ID of 2162. However, the Zone ID varies widely depending on floor layout, and the Zone Group ID does not exist for Torghast maps. While it is possible to use Zone Name, this would make the WA locale-specific.

A more minor point is that the Instance ID is logically distinct from the Zone Group ID. The Instance ID is the most suitable for distinguishing a specific dungeon, raid, or scenario, whereas the Zone Group ID is more related to which maps Blizzard wants to show the player in the world map interface.

**Comment by mrbuds** [comment] 2020-12-03 10:01
duplicate of #2770

**Closed by mrbuds** 2020-12-03 10:01 UTC
Labels: ⏱ Awaiting Response, 🎨 Feature Request, 👯‍♀️ Duplicate

**Comment by InfusOnWoW** [comment] 2020-12-03 12:01
It's actually not a duplicate, but it doesn't bring enough additional benefit over the zone load options, which are by far more flexible.

**Comment by jcai1** [comment] 2020-12-03 21:42
> It's actually not a duplicate, but it doesn't bring enough additional benefit over the zone load options, which are by far more flexible.

So you don't regard Torghast-only WAs as a sufficient use case? Torghast has dozens of possible zone IDs and no zone group ID, but uses a single `instanceID`.

Another possible use-case would be continent-specific WAs. For example, you'd be able to make a WA load only in the Shadowlands continent by simply specifying an instanceID of 2222. Doing this with a list of zone IDs would be quite tedious (and wouldn't cover any future zones released in the continent).

**Comment by tiff79** [comment] 2020-12-14 17:15
Ah this answers my searching for why i can't set my weak auras to dungeons and torgast only... would be nice if we could
