### ISSUE TITLE
Texts in Display being updated even if they are not shown. 

### ISSUE THREAD

**Issue by Krytos** [WeakAuras/WeakAuras2#3682] opened 2022-06-17 10:04 UTC
### Description

Texts under Display keep getting updated, even if "show text" is unchecked. The more texts you add, the more resources will be required by the WA even if you aren't showing any of those texts. 

This is a simple Feign Death WA: https://wago.io/mgdZokNEE
It does three things: 
1 - Show FD CD, once it's on CD. 
2 - Show FD duration, if it's active
3 - Show Resilience of the Hunter conduit duration, once FD buff is removed. 

It does not show any text at all, if none of these conditions are met. Yet all texts are constantly being updated and "wasting resources" for no reason. It's not in issue if you only use a few of these WAs but if you start using a lot of them, it will become an unnecessary waste of resources.

### WeakAuras Version

Weakauras 4.0.2-9

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1: Create WA with a bunch of texts added in display
2: Start profiling and check CPU usage
3: Disable "show text" for all texts.
4: Start profiling and check CPU usage. There should be no change in behaviour.
5: Delete all texts in display. You can remove the checkmark from "Hide Timer Text" in display as well.
6: Start profiling and check CPU usage. The WA will not show up, since it's not using any resources.

### Screenshots

![image](https://user-images.githubusercontent.com/3797846/174276583-ee1d696e-f472-4c43-9109-a9b3f33b9d11.png)
![image](https://user-images.githubusercontent.com/3797846/174276624-c1b22da8-edd3-4df8-acb2-9d777906a6b7.png)
![image](https://user-images.githubusercontent.com/3797846/174276689-85468507-3d32-42f1-bf27-a28dd2ad01a6.png)
![image](https://user-images.githubusercontent.com/3797846/174276737-cc15a104-8f80-4362-8bc9-1412a6eff60c.png)

Check for "Krytos Feign Death 3" WA.

**Comment by mrbuds** [comment] 2022-06-17 10:11
duplicate of #2598

**Closed by mrbuds** 2022-06-17 10:11 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate

**Comment by Krytos** [comment] 2022-06-17 10:14
> duplicate of #2598

That issue is nearly 2 years old. Any ETA on a fix?
