### ISSUE TITLE
Shaman's bugs

### ISSUE THREAD

**Issue by w0lner** [WeakAuras/WeakAuras2#4122] opened 2022-12-06 23:34 UTC
### Description

1) PVP talent id204330 spell recovery/charges is often does not show
2) shaman's charms on weapons id33757 and id318038 wa stops seeing when entering the arena or bg

### WeakAuras Version

5.3.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

in the "export line" I put 2 icons for 1 and 2 bugs. The 1st icon sometimes works correctly, I don't know what it depends on, maybe also because of the arena or bg

### Last Good Version

-

### Export String

```true
1) PVP talent id204330
!WA:2!1zrZUTXXzXYAKc2GcjkBvzzhdA3AvBJuvh1kDSjALj1pqIsDjDTBpeU)nK7yTCNXZmRKO7fBEiq3AabAUuu0cEmOfnHnXW2jofqpbFIiOpa6qFa8lG73mljLvQnpWDMV)))BYukFZ8b5do4QDP(S4kSeHp5IJz7ZIyI1ZI)eT2QEDjrLPNBSFitSnJgR8wUy5QfT77ZyrbS9IRShLtCoC41IbniowAb60wjOnAqeYpCwXGJhCHoUjc3y3Me5m8RbDHV5O2WxcFDb454Nph(YJEeE6BGNw4O)4rpeX(ie)t6Nij1umfPzzKtN(niXeb1VsiBVTIpwA(S8adWkjMQ84rUTiIocstxAmnUr(BAPAXj2ATp)XYepYUKy12csD6(2v2U4gByBmQCcuvPkzKoRImg2rYjrrAmzARXO1sknJ0HdpV(URNKj8wL4gTjlG4mszvsQJkRxTLxQs1AvQUKD1JpHCdPDdiEirA9jwT4gBx62ByBy1UQ2o6mkcaVDFbk)kJmjJHmYcDABoUwGmh)SNk0TTRsreXH8j0Gpvy0Hp(3Lm(LXG)Oe0ZW0YZHVaV8Cmj9zh9rWtGN0XiEHR)oO3pksuJHEGRIjY)R7Kepi3NBwi3bZyBi2YnrXGB4a)OU6S3sr752scJ7PCfniQEgVbH3WpWHFUH3IysjRowzPeSihtWtAkAVTox09KZWeWLHRaZmD2lDdysBtWaUyi8ooWLe1U1sBU0kfHcoW5SRCN1kVc8t4NFy1tHTfSgcIuw4AMO715tQ1dzFxF1ReGHznY(N5axlNjeG10yDVT5ZeWpoh8ZDGl4a)IC9cOY7Le7RO7sM3nUfFcxZ5QPbfDE)Vp2lW(kmE7g9BXUfkl(p8IDie(sO(8v2UkklSJBmTP(u8I2smkPkbtAfZIjhsCLKkkbjUHk8T6hG13AQQPR2fscgTcKT10ORQGsw6meYlucw5TGvH1G1HsE1XSMm87cglhLUkTajHDXQyBsduYYF)uWK9XREyESHGLeh8F63iITxjb5(jKy)wB)9V5CZVamPajsJON(V7oyusB9fTT03lrPyXBTlrG9QD1G3W4eNZq)VBa9D0xwE0iPdXG9kdHeAPrgAiPIVBejRXqQgs93jgZHzny2GINNWOalMiGicp4S88kY(ycn0n4etJFEdqZF1zcmCxto4auQZiCx5QsSv5e2tnUmzYK94uOKO6MjLwlD7QBXN0auxVRZF(3HgOcTwcV(Iufr3Neya(O(Ptzh65hAWFVePIwVfCMUcMcZevrGwL3QCX04RMMUgcpzSDNbEqSIpEjb9bf(njUbyw0Tq1QNYXhQP(gy7HbN7iC5TVZGdPgWUuj1lI4mWNFLnb8jwRC5I21S2QA1T20ETvwTA)rQUc9bKZpWJU7P0JgRze3w3U6gRvUyDyYo6YjtUPx6NAsK9F4HdUK6AR(()3p5t(BJn2yR((hm90FWyJLfJ4dOyGrgoKDcUfIprL7N4kifkLefv4oHufwZLIMLAphCb(L))s58AkAtsnUG4t19IzbNRCvoVWBIWMSGA6wehWd8HaGa1Fe)N(MOoI0W1VvT6rmS8fcHZau4EqJmWUzETmfGwrt3OtmNmyt6oWhMbIm5AOje)AQB5doyRvAaWYa7b7dC4(GWbKWz4x6nzGP3YaUMkAi568R)MinOfUYK6xtfIdmdX5Nz4VZRHwZicZ8ilFcnYlKqBeQw9dk9WX(3V8LV0kI5g8yZcm9gy9ETMoDgDKFw4VGlAEk(yGpd(xMvq4)4IIiCV4u2ntIu0Cw6jLtbFCUJhThCNyCAEOTFKRuQXyMshJBtXPg46dsUJnOW65and(Z6jXfxre14WhpLACCDYiPOh1BPli1YPRWmf0mn9hyVNUXDKR0zuRpCM2dFqKJEdG(5iRHZIN(7L)pj0laW5OlcfZzHdEv5GnY5HiRtBmLhJRrgYp7q(1n83IkDXY7GqZlmgURc3DyRl86Qy(7MU4y6mFu3RqdG3wS)WNUvxGHsCbb2)N9fP9JL0G0EGxLLTlwSSTBep0D7S3CUfMpHg07bB(EpyXgLxX2lwqJ1IgvcQ4QOIvuEO1dySM6P83CHU6fmuJ)S(S2(He)DweY9UJ1ExxbvBZZVu5B5zGlxhXCXXGETPX(SMEy15UUrjKmdaZhhF1bUtrZv67aGhRXDgOxx2ON3Lcll0Zs)Ka8MWpuV0voZS4L2CH(PhQwWNUi85PmJvppoRxenEhmacptt3GnuFf8PZAOcfh8uKk4z3aX6aFf)S4eP5(vZD6XlAoXG08iJ)ZugFx0UX6XVyMtjK1NcP4FO)BZbIlVwClm3RoqDGWwuBf9OXPTlyCC2E4rFsr97(KH8PPnIzcYwMYcPbArHGjKH9XDkyYCaMzWXOEkwdSew)e2BrK(HZVdPf0f9G6UyBsOLUPINh(R4J30DtFn(A72h9WcVh8NZMxAVWC)Y5Uz(D)27()(d

2) charms on weapons
!WA:2!nErxZTXv1SrP4IMwWwj11jHwuCsm0MIXrP2fkHzQxx5y3Al5Usj2TbgTFDL2B9QDV9U7AB5cLevAhptFt95(acO8cmKrqPUPnLzYVGJ1WWdmdV4HFb5nEJZ9UsY2jsZGMXsN79E((BRmFQQPStzVZfAsT89k4hXTik8A5lxoGeU234YzUYKV00Tm8SC85R4t9cnNlBUIz1AB577A7VPxHnPmI(97EmRDfIo3WkK67fmJwqObpmPk1JgM0Sm(tGtY6HCALkeEW7nbVd4oP5euegEHSZbFc8zWU7D79QdFn0s(Bl4RtJF9z7vFVBb3PonKunNrvIcBKOasPkepcNAvWXFZ8E6nmI4gE4RbNb(wAKniEH7VkXG57LoBSi2xqKHzGp3CzFBIE7JWG9dK)mxh7z)GitjtwHtkt3sRWkzxAjnj)t2GtQAG2KxLXNzQMcUUPuq6MX8OD8pltdcqC4iccTwNLQhDL8zeUrOpp1vvJqFKjZ1OgH3iGrCDLMyDbBfpP3wa1JsKlhyglqmCLMspTTquzuBBvAUzluSuHIZQvuQFXkKElbChhU(9fh66s1Bx1i0YHee7mUFmbZIHZniT5Oyk0tZK6tpfvVUeCr7GKQH1yevbhv5rEeLM2etuDkI3Yxi7sRm)1xQHG2qmnzDDZyFMQWUAe51jHi5eWtStA4jzpn8NHpFVpcUBA4VdFjCh4RWSJ7b7cFBf47M6QWiNb(XWPtcNshEkyu4PHXGNxhodgqGZQdFh4zGNthUe8cWW6W4kW51HPGldxuhMa(EW3xhEwDifCsinCo4hOatQd)WKWf0HmkWvGxeMwhMjJF5YWpsOq)nyknPvkygkn2jL(XTWS9d5i6Whb5PAjDxPFDpmtskdKHJ)4V))Uh)GFshEbx9iec)0EOp2j(x3aXVLnn4TJ8KrImgE1yJyiHlg7WeH))4XEawGs4EgU3alVWkW39bRtiSzrLZkuZaRjDAeqClllKHtGbMaJqSCjK40eZC0ivevTV1OWuTXJMy4Pc3pYZENtXsfs2cTshdSOyT4UdkStlVu(vzFoM5ukOdGQNVhPrVNh)IbSHpehMZ31N)Akkkj2p(2UkL6SxVyE2jLxAef6JSIATk1o0rDw84dILfDlIT8YB3oUZ0B2rJUV893okiKwUgAGC)q04kIxQMlFUSWuC0Ue40uIOLunsGFA0XiWgqdppNUD63iYWgDmgPlw8i2Exj1wE3M(C7v5gS6R2biwb2GgqnDXk9yB(qDpzJSyUCz1kPMVyX8lRT41wOy7EIUaDBYP7yrRDe5iEvw)K)6fxAXCz)NTR46V58CY7eHLX1w5etnzMPJToXdIs6R52Xn7uxCLG62MrHH(E53GWX2mnfxVeXRsOZt1sa310AuPlPsxJ8TUQJQ4GJeJcwgUKesfPOd1ADpsqqc5llrr4rK8xf9leUZoxKDUhjxHvkKwLuIXjwurYAc41uV4LNKXoBFqTILDjlJGqh41L5nWk3ML(rWdPoMPXNvyxyqs1LuXWQwPYU(Ohckaf7lQ2OQv1W9aDuHDMbOC4F6WnKEm2ZoidaB46rCDG3ubEl4MGby2hJigxhQnP02eUVdu60GUc7z6dIYQZsI(TAslHnXGDjhXI7tPlRdGMaBByjyzihKhEdfqdob78dMXhkaofCDyvyn2Lgm221WHNuRsHoCcoDX1wH9Cdki9O4c)mh4NJQt6brsvF7sIgA69niCKCJZ2xLmgeEp4AkSXhSz0to7Cj4Ds0hmZ8iy2hLoZdLVcbDZV7tKmtFJKyHaGegjtIHnuGn7MgcBD4enOwNejyB4DHFHd8lrB8Obz4xLOpoLmh2PicWyvkENmoF(bRKhkR4wk9jHiZGtiGpqh9(WVgLhgRH3xbQRlc83wX0HqR4eEtvxFd7pvUbIyvmXIjv1B0dKDkCjYDHVqSTi8xW1iVN4BZqSHLx4OAvJCdPjvftfhf(4K73BrM1fZPD0SCnccKViHW(32I3TMWuShNljCy4JhnCyD5wmE4(wCC8zp6)pxvnaBKlOVjxorTOCFiC96wL5OkwiumyjbFR4EQl8kl)kh)y4N6D3H2rmRxSj4IinJD8HUtddpQysOV3mWJppgew8(eJabJKTVhQTTyio(SSvapGG0zhuxGJq2WIWljPc(Tdb)o43dFkcM8HVPnoVfh8KNjxDpP62((vvmrovMwjzZqFRnI3PymLpS54uB2iWFaUZE3AVpkn8NG7T3hKoJ2bZtLBN2DhAC3enrbG2MIz238bXt4Mx4leQNzH50YMnxMiQDl6cVyTqtEubRSCQNqIehndxMJXkjMAYPzNQRpsmt)vPbg4ywB9Mc7Lk17xEcnC9vR1NbEIx4y13WGtfOKz2CVQP8(GNx(cS7451G7koKa2vvSMR2ggUref8MHWCNVe(kLhgZh7G7)MDa5Iw6vW)xJjWd1zCX(8H1G)6eWN3HA4lG7(YhW0e)FW0yLsInCpbNhBON8)IzX)MhLRjoGKhBac4qO01W6W1JN6dfCTf1lUMe9FjHprpvG20tELjNk1g)J1(Fd
```

**Comment by InfusOnWoW** [comment] 2022-12-06 23:44
Appears to be a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4114

**Closed by InfusOnWoW** 2022-12-06 23:44 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response

**Comment by w0lner** [comment] 2022-12-06 23:50
> 

Yes , but I not only have pvp talents , but also buffs on weapons
