### ISSUE TITLE
Getting LUA Error on Sign In with Latest on TBCC

### ISSUE THREAD

**Issue by Gogo1951** [WeakAuras/WeakAuras2#3438] opened 2022-01-19 18:29 UTC
### Description

Message: Interface\AddOns\WeakAuras\GenericTrigger.lua:3537: attempt to index field '?' (a nil value)
Time: Wed Jan 19 12:26:46 2022
Count: 3
Stack: Interface\AddOns\WeakAuras\GenericTrigger.lua:3537: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:3537: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:3518>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3216: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3198>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3302: in function `GetOverlayInfo'
[string "@Interface\AddOns\WeakAuras\RegionTypes\AuraBar.lua"]:138: in function `propertiesFunction'
[string "@Interface\AddOns\WeakAuras\Conditions.lua"]:418: in function `?'
[string "@Interface\AddOns\WeakAuras\Modernize.lua"]:1354: in function `Modernize'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2547: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2529>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2706: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2237: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2244: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1033: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1005>

Locals: <none>

### WeakAuras Version

Too many things to fill out.

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

Too many things to fill out.

### Reproduction Steps

Too many things to fill out.

### Last Good Version

Too many things to fill out.

### Screenshots

Too many things to fill out.

### Export String

Too many things to fill out.

**Comment by mrbuds** [comment] 2022-01-19 18:32
duplicate of #3436
we need your savedvariable file as asked, please copy it in the other ticket

**Closed by mrbuds** 2022-01-19 18:32 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
