### ISSUE TITLE
Condition tab does not render/output triggers ui properly

### ISSUE THREAD

**Issue by wazerstar** [WeakAuras/WeakAuras2#4274] opened 2023-01-23 16:20 UTC
### Description

From early days of using WA I feel like this issue is getting more and more annoyed now, I searched for other issues related and Failed to find anything related to it?

I have recorded a small video that shows what actually happens.

https://streamable.com/es760c

### WeakAuras Version

WeakAuras 5.3.6

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
N/A
```

### Reproduction Steps

Shown in video under description field

### Last Good Version

N/A

### Export String

```true
!WA:2!LJXsVTXX5WqyOegu0ifBNuHaKn6GROLJIevKIRrKmiPOSuQSK8szP(w7S7oK7uTC3nZmK6rqouvGKGERkTb5upWd9Ab4H0EPaPk(sBAAMqK42C1Oh6z9lOFFZWhIwo5spwciX5X3R579htT0i1gXFe)3TyRAX(0Wve3nIjdAY8IJkhxN7rF(hlhjHfW3F9kveu5Z)y8dmRs1Ie5feZ3iMfjDlwATnlz3YnM7t5fJdJ5VE60P3i9utoBbKyoNUlLMKxKq9K2ejlo4ybnSIgz1qn9PcISoNiPbhXJLiarPkegt8F7JRlO74fsecNcCIhnJ(GiAdkpWvscPrYR4kyrvdPFQDT6Hs2CVJZN4STtteodabfqgFz1fZyRP0vupJ9I23DLfvx8Y8TZBBVY62ofeSdPimNkP7dcdDBoj52Gwj5Ifxn)T3yZ1lSA(IF)8lU4kBUYwLosqFJ60ipAABHhWL0n50QGyV5bjuEhkyuQ7iK7uxChLL70Zn7Ct9QCZPhMQPm2dEgcaRNOXFXMeMeqs5cARkSQBDKma0eYqkQeNboTMlbosYzvRs5PT5KOQ0lvqcS7cT8zIKqYbRa4(49zQ8WupWyrkq821NhNK80fczhEiH7BTzCmORsS90gRLV5)5d0Fw(M)XNv)z5B(L6p3pDh5D)uT9aC8J3lQ8ESeQZjD3wYVky36izI)0Z84xrL9DhwBNsI3dSt2rKAurMJ17qjoD7ExIBdAHBRfxpss9dutuOo4f(arDxWkhjlxVsf2(T2Py(YBUt5nZBVPg8g0aMxinWwduZIXr(m0Vr0dXn4uar7YBuA1vv3Wf1qu(rGRqy4k(ImpqZ)DIb7frgZhBH5T1Nm2mZPLDsiRb15iCjkpoGxQlikAd8YLwDJLU7QhdsS5zNbEZnutOUHAz1kACQeZR5OULtbCXLvpZqQfsE6YsiQH(Ylbh9Y5bhEa(cQxhr(dvtyRfTKHrSRsJOCMx5G49wpYrTq78E4JZ6UcIBifrRnNsclJySgODp52emeWA8IezwT2v09khuKabP9a08bc9xf7yd1VyjeGTRZX9W8j(ZFypHtTMADqos(oDXWAdECvoviSgxlfz1VL7OSvLDuBJOElh1Mnr2KpCpYbc1wgjrtX3wVe0xpq7i33k8AZRff9PbGvts4vPs1cTSXtSkgq92vD1rUos9EY2nuLg7vMsTiydvZgOwWEd0qIG8QdLCrn9GOvgNQphTGbAP96NrI(9g6mYSQfh510ur9Z0u4jphOAwQZVea2azqWPMVpRVuByPhM7rFtHPMCQPvl4USEhqWFIR5IrMg4HXKpacbjxEG9NL09fK3hCAiGBuUJX)RJYUQYUDxFHcucpB7AePxavym7QFi8U8rbGd2W1JcpWHdm34NaV2L5lN3(2GRDxga(WSrlyt2LQ2TdYayHoGkq)oaHjQNWahXgnNnlPhSieaW1meVpO1cofyBP9jEYYMashnoOQoezP9StnZmVcsYtW3M2NK5lWZZn9mdOcaUkgvX7H)BOLVAOSaNEoilmBUCFVhfWULI4KQ0(y0aLBei2ONumeuMEeHek1GyG4J0BqGXDSrBvM0aiKLDmHFwy7fSJVFJKm9SpKKy0H2qW1EH9j(91H0ObgJ6bKbhWJ7T1ElIyxceCErS8neJqGazjeRdsRNW4DHvazvyEMCzQVDWd6MyJjmhvmtZ(Bb55gNyI96eboxgJjS3ZDcxV6czCn1VC)lKuPEKob14KWqbuaNkYMXc(WQyfflTqt4o0OgtcLFLwXCRBrLBYQrhpR1l9qxUq)9MsHt2TsOfelePPk(zqSMVpf7brVfHXqfAlpS(ca4u9oheUZXli3G18ZBLBqMHFG84wma)PVM1RmLLF8ax2NnO2dGAm06aLCK0XMCs25GfynARksIYdkyVDhFmt5PXUMMazTohgKiFRXhqx2rKnTgGkvKI5Rub6XcCslQpECn1Y(iP22uYUyriXK6SQ6eSA4V254HoD81SGSZJL168Y250vD)0vNB(EcRPphu0i)mp0((0NgkONZgOvWSiRTZVZksmPi9w846j3MwZfA)a8OEeMMoUHOcY0JBN3zxT(xJ(Upolsj(RZVvqSOJk9)JTpzEuRbnSHilm)5dQm9iDEXOxYIF8yJ9tbXyW9Gg7nX2hGlK86036Rh1jfymKO7d5BaqVaut53HKdaiNc9Shn45OdiMLya56B(zmzhrUc5HDE)Fts6ORXVH)AzY9UdMVQLMQ1t8H)B7HUkUMn6Ykqg7tnaVfHZWUhfjp3BQPvpTgYPRL5TYKbYTJdt8Z1zZBqZrIoizyIE9MgJioru6tHX2O8is4wMXx(fCIFdSZ2GJjrSA653MZgipxU0juIGwwYPrvLbdbn3hfhrB7Jt7bqPFaCbf8u8fhHGIDNPEVc1iSOLuhdiOEp1Vr9BvVV69CRWIyIGh(4ZmXZbPsggKFpqdc981DsYZaW(PAcJhyRhvtm6Lvt0g26cQHQqoKiFORmw1a5WUACPoTD7m50dnt7HXX1s5AgUkOP5BCmOcRbpUJ6oyu3Bkdtw(I9fc(bPogmdr(OU0UWQLwBXZC5HPoXGLzo7NQZq1RebBE2C1z(TMzRP2WnR7u)OeU9EmFzWlGL7Xh0CQFDg1hKPaOMKzAAOzcm2yYlQ7Fs8YylmruZGpAVMDWwdLtwl3ym)KNtp9GvN2hJ5vTIJQcJOxTZiGhKQvfouwdSMej5Po18laSeEeA1Clx0UuP1sUy33)MWyWlY0tS4hCMN4()7NMZIWrFPbU1yCEmp4eZ1vyH0v8DNgArBUR30R3qDJEf17mNk71ESJA0Xlox(1w0v7TloeUjT6JkGrE2niH1PPHtUG6JuFS6E4YH6V8jvFuZ4EJ9OUxQLuzFk46RQU3ixFS4eifka13coPeUB(5VIz3hZnbSIrZ0IfHZ0P9TUClyPhTeoVPWPnPUe0iRNOL5F195I4kYBZIqNMPbx2RYDzvllPj6dYvJS)Lki6Uv9hsNRwhyZTl9a13fS7vi1dL6FcadTi7pubDNfdFxDiUvfU53H4GBG9XViv45uWh(FYlUmKgcqHgzb6L6H(yEllSEILj7Wn3spYjXJ2URoDB0BYr97sJZGTSouiaeR7R(Bya3vvFsA1F)VQ(00WzQ)XqQpdosDj1NFhvBxD1PBO(ch1xM8siR9cJfqlBXA2AkZcvMToiUU1EeOobCJ26HIH6FQ(xiBvFvh2LQh7Utx2LcyxwLkT6ZVKQDYiDshzThKm2kc6nVdVNc5DniVLUpbbCfKJf4LlvdfUuNGURY4mS)cQVYby1BJSBcxbneku7QDNex1gZpKajXO1yub8E1LK188ZacOUaW6xOOUaOgsRAM2rWIyDq6MylZY4QqSLsHVtv7MRezz6dOdLghiJnovwNIPAu7(uKbqBeeofB(X0uXnTg3pMkW(ucGWuJYOcNb5wG08wMNa1p7ic7zNCMjNBKgFXp4)c
```

**Comment by InfusOnWoW** [comment] 2023-01-26 20:57
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4276

**Closed by InfusOnWoW** 2023-01-26 20:57 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
