### ISSUE TITLE
Unknown difficulty if found

### ISSUE THREAD

**Issue by Tasten4** [WeakAuras/WeakAuras2#4988] opened 2024-04-02 22:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I just updated my Weak Auras mod through WowUp for WoW SOD, Phase 3. and when I logged into the game I received 5 notices in chat stating 
Unknown difficulty id found. You are probably running an outdated version, Debug information: 184 Normal party
Unknown difficulty id found. You are probably running an outdated version. Debug information: 185 20 player raid
Unknown difficulty id found. You are probably running an outdated version. Debug information: 186 40 player raid
Unknown difficulty id found. You are probably running an outdated version. Debug information: 197 10 player raid
Unknown difficulty id found. You are probably running an outdated version. Debug information: 198 Normal party

Not sure which weak aura is causing this, so here is my weakaura.lua file. 
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/14844355/WeakAuras.zip)

### WeakAuras Version

WeakAuras 5.12.6

### World of Warcraft Flavor

Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Logged into any character and see the noitice in the chat window

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/159084590/736d8300-6fde-47a8-a358-ff833bccfd76)

**Comment by mrbuds** [comment] 2024-04-02 22:30
duplicate of #4986

**Closed by mrbuds** 2024-04-02 22:30 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
