### ISSUE TITLE
dynamic groups into a group

### ISSUE THREAD

**Issue by Celuldor** [WeakAuras/WeakAuras2#1314] opened 2019-04-29 13:57 UTC
I would like to be able to group 1 or more dynamic groups together with other individual auras in a super-group

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by emptyrivers** [comment] 2019-04-29 14:00
This is a duplicate of https://www.wowace.com/projects/weakauras-2/issues/64

**Closed by emptyrivers** 2019-04-29 14:00 UTC
Labels: 🛠 Feature Request
