### ISSUE TITLE
TBC Arms Warrior Sword Specialization resetting swing timer incorrectly

### ISSUE THREAD

**Issue by Jeff425** [WeakAuras/WeakAuras2#3141] opened 2021-06-09 08:09 UTC
### Description

In TBC, when the Sword Specialization talent for Arms warriors procs, it should not cause the swing timer to reset. Currently it is.

### WeakAuras Version

WeakAuras 3.4.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create Swing Timer Trigger WA
2. Get an Warrior with Sword Specialization to auto attack with a sword
3. Get the proc of the Sword Specialization with a special ability (middle of the swing timer)

Swing timer will reset incorrectly.

**Comment by mrbuds** [comment] 2021-06-09 13:20
This should already be fixed since 3.4.2 release.
Replicating the issue for rogue sword spec was tedious, can you check you have that version and add a video showing it's not fixed ?

**Comment by Jeff425** [comment] 2021-06-09 18:10
I have not been able to reproduce this solo. My thought process is that there is some weird behavior with the sword spec and windfury totem, multiple different extra attacks happening at once. Will see if I can verify

**Comment by mrbuds** [comment] 2021-06-09 21:49
if you can't reproduce the own issue you report i'm gonna close this

**Closed by mrbuds** 2021-06-09 21:49 UTC
Labels: ⏱ Awaiting Response, 🐛 Bug
