### ISSUE TITLE
Weak Auras Conflict with Neat Plates Timers

### ISSUE THREAD

**Issue by Saarak7** [WeakAuras/WeakAuras2#3024] opened 2021-04-14 23:35 UTC
For some reason with Weakauras now installed the timers for auras on neat plates do not work.   Something in weak auras is conflicting with those timers.  Both worked together before but they don't work now. So with weak auras loaded I can no longer seas my timers.

**Comment by mrbuds** [comment] 2021-04-15 01:12
duplicate of #3018

**Closed by mrbuds** 2021-04-15 01:12 UTC
Labels: ⬆️ Upstream Issue, 👯‍♀️ Duplicate
