### ISSUE TITLE
Shift select not selecting offscreen items

### ISSUE THREAD

**Issue by hianick** [WeakAuras/WeakAuras2#5121] opened 2024-06-07 07:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When shift selecting a list longer than the height of the screen, auras not on the screen won't be selected.

I recently put a ticket in for shift select not selecting properly if there was a current search filter, https://github.com/WeakAuras/WeakAuras2/issues/4994. I don't know if it has to do with that bug fix because that works as intended now, but the issues are similar. I attached a short video of the bug.

### WeakAuras Version

5.13.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Have a list of individual auras longer than the height of the game's window, dont have groups between them, so they can all be selected.
2. Select one at the top, scroll and shift click the one at the bottom.
3. The ones off screen at the top, not the original one you selected will not be selected.

### Screenshots

Short clip demonstrating the bug with and without a search filter, https://www.youtube.com/watch?v=KaYSpdD0DGQ

**Comment by InfusOnWoW** [comment] 2024-06-07 07:40
Duplicate of #5113

**Closed by InfusOnWoW** 2024-06-07 07:40 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response

**Comment by InfusOnWoW** [comment] 2024-06-07 07:41
Thinking about it you might be right that the bug was due to the changes #4994, meaning that I need to take a look at whether that has regressed now.
