### ISSUE TITLE
[WOTLK] Context Menu Broken

### ISSUE THREAD

**Issue by Runkel79** [WeakAuras/WeakAuras2#4071] opened 2022-11-28 01:17 UTC
### Description

When updating a Weakaura in game that has been imported by Weakauras companion it usually shows only the options "Update" and "Ignore". 
(Works if Weakauras the only Addon active so my guess is it's causing a conflict with a library)

After updating Weakauras to Version 5.2.1 the context menu Bugs out and shows a bunch of options that shouldn't be there.
(I only updated Weakauras, i even rolled back to Version 5.2.0 to verify it's a Problem with the latest WA update)

### WeakAuras Version

WeakAuras 2.5.1

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [X] No

### Lua Error

No LUA Error to report

### Reproduction Steps

Updating an existing WeakAura via the Weakauras Companion
Open WeakAuras ingame
Left click the "Ready to update" WeakAura

### Last Good Version

WeakAuras 5.2.0

### Screenshots

Screenshot (Working/Version 5.2.0)
![WowClassic_GbLiEMPLKb](https://user-images.githubusercontent.com/22620131/204170851-2b917d62-7472-4169-93ed-13c491d45bb2.png)

Screenshot (Broken context menu/Version 5.2.1)
![WowClassic_kVKWgrPtps](https://user-images.githubusercontent.com/22620131/204171140-a369ed6e-21ac-46dd-aaaa-feb164dba565.png)

**Comment by mrbuds** [comment] 2022-11-28 02:14
I can't reproduce the issue

![image](https://user-images.githubusercontent.com/189656/204176967-1fe674e2-b6c4-4d98-b9f0-713611103198.png)

Can you:
- make sure you installed bugsack+buggrabber and don't have any lua error
- add you settings to the ticket (weakauras.lua in savedvariables)
- explain exactly what you do, step by step, from login to what lead to this issue

**Comment by Runkel79** [comment] 2022-11-28 02:38
- make sure you installed bugsack+buggrabber and don't have any lua error

I have Bugsack+Buggrabber installed, no lua errors.
- add your settings to the ticket (weakauras.lua in savedvariables)

Here you go [WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10099975/WeakAuras.zip)
- explain exactly what you do, step by step, from login to what lead to this issue

I log in and open Weakauras

It worked fine with version 2.5.0, my guess would be a conflict with an ACE or another library from another addon, but since it worked up to 2.5.0, WA's the culprit. (Weakauras was the only Addon that has been updated.)

**Comment by Runkel79** [comment] 2022-11-28 02:52
I just noticed When Weakauras is loaded it breaks context menues of other Addons

Here's Titanbar for example:
WA on

![WowClassic_BzxKeeC1d7](https://user-images.githubusercontent.com/22620131/204181353-33d0bf34-03f8-4d6d-9d2b-658d2c3a1f2d.png)

WA off

![image](https://user-images.githubusercontent.com/22620131/204181394-c9c70476-509f-42b6-8ce0-a7f823a1d70f.png)

**Comment by mrbuds** [comment] 2022-11-28 03:09
Can you identify which addon is interacting like that with WeakAuras?

**Comment by Runkel79** [comment] 2022-11-28 03:11
So far i noticed it on Titan Panel and RestedXP Guide

**Comment by mrbuds** [comment] 2022-11-28 03:12
You said it work correctly with only weakauras, if i install only weakauras and titan panel it reproduce issue?

**Comment by mrbuds** [comment] 2022-11-28 03:15
If i install titan panel it change aspect of weakauras dropdown, which is not normal, but do not exactly reproduce your issue 

![image](https://user-images.githubusercontent.com/189656/204183819-5ddf27ad-0488-4fdb-b5ea-78a6f3c4dbec.png)

**Comment by Runkel79** [comment] 2022-11-28 03:27
Looks like Spamblock really doesn't like the new version of Weakauras
https://www.curseforge.com/wow/addons/spamblock

If Weakauras and Spamblock is active at the same time, it bugs out the context menu.

**Comment by mrbuds** [comment] 2022-11-28 16:58
After investigation, this issue was fixed in LibUIDropDownMenu but it does not upgrade correctly if older versions are loaded first.

Both TitanClassic and SpamBlock are using outdated versions of LibUIDropDownMenu, respectively Rev 78 and Rev 100 while current version is Rev 111.

**Closed by mrbuds** 2022-11-28 16:58 UTC
Labels: ⏱ Awaiting Response
