### ISSUE TITLE
Dynamic resizing of Icons in a dynamic group to fit a fixed size defined for the group

### ISSUE THREAD

**Issue by psyquest** [WeakAuras/WeakAuras2#2878] opened 2021-01-08 01:32 UTC
**Is your feature request related to a problem? Please describe.**
When adding icons to a dynamic group it is impossible to set a max lenght for the group so that adding icons does not enlarge the group. Since unit frames are in set places on the screen, players usully set their icons between the player and target unitframe. Unfortunately, there is no way to control the size of the dynamic group (depends on talents/spells selected) and thus we end up with not so nice UIs with varying lenght of dynamic groups.

**Describe the solution you'd like**
When creating a dynamic group, depending on talents choice there can be X icons or X+n icons
Ideally one would like to have all icons in a dynamic group fit a predefined maximum lenght of the dynamic group.
So that adding extra icons to a dynamic group, the lenght of the dynamic group does not change but the size of icons dynamically change to fit the predefined dynamic group lenght.

This makes for visually pleasing UI.

**Describe alternatives you've considered**
yes, tried using code such as the one used here https://wago.io/kib-dh-hud
But would rather have it done natively by weak aura, especially this would be used by many classes.

**Comment by MikeCook9994** [comment] 2021-02-18 07:24
+1 I was coming here to submit this same feature request. Typically, my talent selections will give a UI looking something like this:
![image](https://user-images.githubusercontent.com/6856899/108319298-0c37df80-7176-11eb-8727-73879ee77053.png)

But worse case, with talent selections I can get this (soothe icon collides with barkskin icon):
![image](https://user-images.githubusercontent.com/6856899/108319618-85cfcd80-7176-11eb-842d-4890f1499b61.png) 

If I could specify a max width (not simply an icon limit) for the the top row of icons, the dynamic group as a whole could scale down to fit within the max width (or even scale up to fit within a min width)

**Comment by pschultz** [comment] 2022-04-02 18:22
It took quite some googling, but I finaly found [a post on Reddit](https://www.reddit.com/r/WowUI/comments/oj7739/help_dynamically_resizing_weakauras_based_on/) that suggesting using a custom grow function for the dynamic group. In the grow function one can change the width and/or height of the group's children. The following code reproduces the native "Centered Horizontal" placement and changes the width of the group's icon to perfectly fit 180 px horizontally:

```lua
-- https://github.com/WeakAuras/WeakAuras2/wiki/Custom-Dynamic-Group#custom-grow

function(newPositions, activeRegions)
    local totalWidth = 180
    local width = totalWidth / #activeRegions
    
    for i = 1, #activeRegions do
        -- Changing only the icon width. I prefer to have constant height,
        -- which means that icons may not be square. To keep icons square,
        -- add `activeRegions[i].region:SetRegionHeight(width)`
        activeRegions[i].region:SetRegionWidth(width)
        
        newPositions[i] = {
            i*width - totalWidth/2 - width/2, -- x
            0                                 -- y
        }
    end
end
```

Here's part of my UI using the custom grow function above. The picture shows three distinct dynamic groups: one below the player unit frame, and two groups between the player and target frames.

![wow-wa-dynamic-icon-size](https://user-images.githubusercontent.com/607733/161396267-8af92dc7-b213-4b9a-9b21-3bf516b11518.png)

**Comment by Gollumeo** [comment] 2022-10-26 12:46
I dunno if I'll ever have an answer given the late comment, but how could I possibly change the spacing between icons/auras with that code?

**Comment by Gollumeo** [comment] 2022-10-26 14:42
It works, ty! It asks to change some parameters (like the total width) to actually fit the initial pattern, but that's what I needed! Thanks a lot ♥

**Comment by InfusOnWoW** [comment] 2022-12-09 00:04
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4057

**Closed by InfusOnWoW** 2022-12-09 00:04 UTC
Labels: 🎨 Feature Request
