### ISSUE TITLE
Error when trying to create new WA. Now it won't open when I go /wa

### ISSUE THREAD

**Issue by bread24** [WeakAuras/WeakAuras2#2178] opened 2020-05-07 15:14 UTC
I was helping a guild member create a logo based WA and when I told it to create a new logo WA, the options window closed and now I get this error message when I load into any character in World of Warcraft.
[WeakAuras_lua.txt](https://github.com/WeakAuras/WeakAuras2/files/4593826/WeakAuras_lua.txt)
[WeakAurasArchive_lua.txt](https://github.com/WeakAuras/WeakAuras2/files/4593828/WeakAurasArchive_lua.txt)

8x WeakAuras\SubRegionTypes\SubText.lua:195: Usage: <unnamed>:SetFont("font", fontHeight [, flags])
[string "=[C]"]: in function `SetFont'
[string "@WeakAuras\SubRegionTypes\SubText.lua"]:195: in function `modify'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:572: in function `modifyFinish'
[string "@WeakAuras\RegionTypes\Icon.lua"]:547: in function `modify'
[string "@WeakAuras\WeakAuras-2.17.4-22-gc31eeac.lua"]:4550: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:4445: in function <WeakAuras\WeakAuras.lua:4348>
[string "@WeakAuras\WeakAuras.lua"]:4480: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:4008: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:4015: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1643: in function <WeakAuras\WeakAuras.lua:1615>

[string "@WeakAuras\WeakAuras-2.17.4-22-gc31eeac.lua"]:1771: in function <WeakAuras\WeakAuras.lua:1722>

**Comment by emptyrivers** [comment] 2020-05-07 15:26
Hi, thanks for the report. This issue has already been reported, so I'm closing this ticket as a duplicate of #2177.

**Closed by emptyrivers** 2020-05-07 15:26 UTC
