### ISSUE TITLE
Abilities are considered usable even though they are not [Monk]

### ISSUE THREAD

**Issue by GermainP277** [WeakAuras/WeakAuras2#3610] opened 2022-05-03 16:43 UTC
### Description

When doing a Roll (id : 109132) all my abilities are considered usable until the roll animation ends. These actions are considered usable, when I have sufficient resources for example. But when I roll, so a spell that launches an animation and which during this animation should prevent me from doing any action, in fact makes Weak Auras believe that all my actions, some of which were basically not usable, that they are.

### WeakAuras Version

WeakAuras 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Play a monk lvl >~= 5
2. Set up an icon ability, and in the conditions for example, ask it to shine when the concerned ability is usable
2. Or just simply import the string I have put
3.  Make the capacity unusable, by consuming your resources for example
4. Make a roll and notice the icon shines

### Export String

!WA:2!1vrtVnXr7SDbHWvTnXaPac1KgPgv6bRqmyesTkYBQtDIstCxBk8(cV1E8UJ3DAwp70zM1oohQA9PGc0d(NGpZPCUhO5xWileNR4hqpKFb9zM12eAFzoS7ZZZ889xJ1gzBN1pR)HlnK4ftRgNW9W3ygxV4Oy(w2WH3B3wTeyz5xeUYV8IzMX6ye1lmMxjMqLnxV0o1k5oYlooYpUlTAxcd34KjOL8dWn4ipjjMkk4kKiUmJdHsKzA2c(jcZ0xYjbbyU4dxMpg8Wp2vccTNdkrgpaLWruuBS46URwy17Dx2CjcC9amfZjEvdJ7UlTXO3cDOa(vmQlQNWjbSvtweQhMFSwo9vbE(novJySIxiIhGdh6JBM0QvTEmmVCPTRSX93Md8Sdy5uMtVF9iKqeQjuAFiUQYWrrB6h6A8WmosqCxHMOlUdMkzxB9XPIfRWJd4yHyXp3i0nzxsRvSwl1nsym1iogfvDc6vTEYZhzC7Pm0xKAsrMxlsAAmsvWVi7FC91lwTw9Q1k6wBG4SAykJv4yGr3QvkT92dMMaAOTWMb0yUjAdhKqhxiYWMtx76GRLI)TX(4NpZPqDhZPOOVhQAqHn409WywrWKEsxeuQdhGOK2AiAb1f3qTGdnMIpbJe4QsoMgidVWiFOSQ5OUoLXfyO5Zx0xZJUeOY70grOGSQ8QBFb1Dufu3faF))jfOSjqsTUWngcXPloq3RT18QfgbOnH4lGhNq9p8QSpvI3xw38PvmhCW6S6ssBCDgh7r0HIn7A)lEeJbu5hm9UL(mgBwdMiebv31ntlwww2VoLkoQLz(WP49RTl7sgI6UzDwX7beFzOtra90udr2h7Bi(RJsNT(pPJCwNyU)htessREQZpKhlHaTgq0zND3PKAboeJAEgAyC8qB51(RF2CkVMQI5ypyCebDKZUbNCWIFxcYhsAOfRvJL9mrYdhB53I4e3HDZ3vg0Vhmaq8QldHw8qOJ)cJmC1nM7)aoI1)bJbsJOoq2UzeUX4K4zwOOop7tExgjfZ6)tnIngWvZN)OPbBvYb4fgNtNezV5wZS(U3V22BUtPxnkikU7gC8pLGPE9QCUvYT6DsZV6lobgr(MOXf6W(AsAPh1mrkJP72bZHvmd1K320FFLJ1WtYBdcMiQzJQ5UjUJJgj0Wrvpue224i1cjE7rHTf2MB2MaWZz0VdKiX8WxPEuf7vYDBLFO6)1q9dUvGMOivJROqwQMBvETxEzZ5nnd2WKZJvEwkSTQvLZvi3k3rf8rQWWMHysqO8rorXi)oM1n6Tz6frTdhmfSFXEry8EeAtj4Mu58UTtIKKmMfjuy)cp01tVDCEflJJEBqkauc0ad5MjtDwZr)sJQtJ(tEMOXXT4GzGLdqhPTZbXXTTyxEYT629VMiqqdJFJHYyVoP7DUQvJhUeXV)o4UlER8lMVjO1wKGmUOiwiY(00Y(gAnRTAZQR7wQ0o89N8C2JV49MzMzo3Qje)JV1bUBIkVEYE(f5eQ2a4WrWalOGDzMxVY42vpH(OH6fvedP)7YUEHyV9kO(a7(DqCI2fpjD)m1frdWUDqrjylo8gdGjU(YQJ2Y2Q8A)XC6ZS29z8yOhu2t9ElRouRh1tyxHqf6n6Eeil7IfMNKfQJSvp1OGYR9NZAotbSTvp7mAyymDYRoQJSup9lMhU(EWhwwODo3Q5o7mii1ggPEnEFgjDNCnykAPy2sF5xPokB(XMv73)(n0NfbZXM9mQYS3zQ5v)MXQAHAOEMEPCU850TUhtOPJPGjYmy6os15ZkAMp3DZDRcz78Yh(3

**Comment by asaka-wa** [comment] 2022-05-03 17:39
Roll (also DH movement abilities) start a global that isn't *the* global making the normal check against 61304 (GCD) not applicable. 

I don't entirely follow your description of issue you're ticketing, so just chiming in with what I know about the spell and the way it differs.

**Comment by mrbuds** [comment] 2022-05-03 17:53
> Set up an icon ability, and in the conditions for example, ask it to shine when the concerned ability is usable

That's not what you do in your example 

![image](https://user-images.githubusercontent.com/189656/166510987-8acb9c84-5c23-46e2-8897-3123ecedcb72.png)

duplicate of https://github.com/WeakAuras/WeakAuras2/issues/1366

**Closed by mrbuds** 2022-05-03 17:53 UTC
Labels: 👯‍♀️ Duplicate, ❌Wontfix

**Comment by GermainP277** [comment] 2022-05-03 18:16
> Roll (also DH movement abilities) start a global that isn't _the_ global making the normal check against 61304 (GCD) not applicable.
> 
> I don't entirely follow your description of issue you're ticketing, so just chiming in with what I know about the spell and the way it differs.

Yes but wouldn't there be a way to ensure that spells that are not considered usable by default remain unusable during the roll ?

> > Set up an icon ability, and in the conditions for example, ask it to shine when the concerned ability is usable
> 
> That's not what you do in your example
> 
> ![image](https://user-images.githubusercontent.com/189656/166510987-8acb9c84-5c23-46e2-8897-3123ecedcb72.png)
> 
> duplicate of #1366

"Insufficient Resources" is a sub condition to "Usable spell"  for some abilities.  So i took the example of it. But yes u can just choice "Usable spell" if u want
