### ISSUE TITLE
[UX] Custom Triggers should default to a Custom Hide

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#299] opened 2017-11-09 19:04 UTC
_EDIT: My ideas present in this ticket are somewhat premature. See [this comment](https://github.com/WeakAuras/WeakAuras2/issues/299#issuecomment-343650308) for a better comprehension of exactly the reason for the ticket._

In nearly every case I’ve come across with Custom Triggers (not including TSU, of course), the user wants the aura to hide as soon as the trigger returns false. The default behavior defaults to a timed hide, however, which requires a couple extra clicks to change and can be confusing to new users who don’t notice the option right away. I suggest either switching the default to custom, or (I prefer this idea more) adding a new option which would be default, “automatic”, which just sets the untrigger to trueFunction. I think this would be much clearer to understand, and would reduce the average # of clicks required when setting up a new aura with a custom trigger.

**Comment by krazyito65** [comment] 2017-11-09 19:07
I would also think we should change the 'hide' text to be called "untrigger" or "Untrigger / hide"  to hellp people understand what its for

**Comment by emptyrivers** [comment] 2017-11-09 19:07
This would also reduce the likelihood of an inexperienced user creating a complex and potentially expensive custom untrigger that reduces down to `return not TriggerFunc()`, which is of course redundant.

**Comment by asakawa-k** [comment] 2017-11-09 19:15
I disagree actually. 

For `custom - event` triggers I think the most intuitive and common untrigger _will_ be timed. 
`custom - status - event` is the intuitive route to a custom untrigger.

**Comment by krazyito65** [comment] 2017-11-09 19:19
I can see that point.  The default option may not matter too much, but I do think having an 'automatic' option in the dropdown would be significantly useful.   Especially if we can maybe have tooltips or something somewhere that could explain what it's used fore.

**Comment by emptyrivers** [comment] 2017-11-09 19:22
@asakawa-k are you responding to the idea of switching to `custom` as the default for hide, or the idea of adding a new default which would be called `automatic` (and possibly reverting [this](https://github.com/WeakAuras/WeakAuras2/commit/b03a0202f0dc31647d659f8f85bd0b010683444d) and leaving the Custom untrigger as doing nothing, just like timed does currently if you don’t give any data)?

**Comment by asakawa-k** [comment] 2017-11-09 19:32
I think that defaulting to timed is by far the best way for an event trigger to be. I'm not convinced that anything really needs changing but changing some wording or tooltips to guide people more/better could be okay. 

Catching up  on the recent Discussion on the Discord (that I think has prompted this?), I would argue that the issue there is that they were adapting something that made reasonable sense being an `event` trigger into something that really ought to have been a `status` trigger. 
I think that difference between the two types of custom trigger isn't super intuitive to people and I have seen people ask about that on the Discord, but I think that this is it and they each do their jobs. 

I guess that if some adjustment were to be made then I would suggest removing the separation of `event` and `status` and roll them into a choice of untrigger under the same `custom` header, if that makes sense.

**Comment by emptyrivers** [comment] 2017-11-09 19:41
I guess we’ll have to agree to disagree on the timed not being common thing. I rarely ever see a use for it, and I certainly see lots of situations where people have created massively complex untriggers that don’t actually do anything. Certainly, this at least should be remedied somehow (either by making it clear that leaving the Custom untrigger blank causes it to fallback on trueFunction, or by moving that behavior into its own option). 

As for the status - event thing, I’ll grant you that the difference between those isn’t clear at first. However in the discussion that prompted this ticket, switching to from event to status - check on event simply would not have done anything useful, and as I said before, I just don’t buy that it’s intuitive that an event check is timed and a status one must be custom.

**Comment by asakawa-k** [comment] 2017-11-09 21:39
(See the long and probably very boring discussion in #alpha-testing for more of us bickering on this topic)

**Comment by InfusOnWoW** [comment] 2017-11-10 18:54
There's a semantic difference between status and event triggers and that's why imho the current defaults are perfectly fine. Event triggers are supposed to care about the event that they receive and use the parameters that the event caries. Most event triggers should be using the timed option. If that's not your experience, you are most likely using event triggers for cases where status triggers are meant to be used.

Whereas status triggers are supposed to use other information (e.g. calling wow api functions) to figure out their state. There are only slight differences how these types actually differ, but that's the semantic difference.

I'm not sure how to better explain to users that a custom untrigger is mostly not used. I was considering adding a "help text" above the custom edit area, which could also contain descriptions of the parameters that a function gets. Since that's also pretty opaque.

**Comment by emptyrivers** [comment] 2017-11-11 08:50
There is no functional difference between a custom event trigger and a custom status trigger. None! You can specify events, you can have it execute every frame (via `FRAME_UPDATE`), you still get event args passed in. Given that, the distinction between them becomes nothing but a formality. You could merge the two together tomorrow, and the only change would be in the complexity of the menus (which would decrease). The only difference whatsoever between the two options is that if you choose a custom status trigger, then you are no longer allowed to choose a timed hide. To me, the only reason there is any distinction at all is because the prototype generic triggers are separated into status type and event type, and has little to do with any functionality considerations.

Given that we are talking about the custom trigger option, which is for when the prototypes aren't flexible enough to meet the user's needs, I don't think imposing a standard for the sake of the standard\* is useful at all. There should be a meaningful difference. I can imagine scenarios in which I would need to both grab information from an event and query the API or some internal data structure for information (say, for example, there's a spell that I want an alert for, but only on every third cast of it, or if the boss has a buff for this spell). How would you classify this? It's not purely an event trigger, but if I were to follow the design choices and use custom - status - event, then I've made the wrong choice - I need to use the custom - event, so I can make use of the timed hide.

I regret the title of this ticket, now that I've had time to more fully flesh out exactly what it is about the custom trigger UX that bothers me. I should have named it something along the lines of  "the distinction between status and event custom triggers is unnecessary and arbitrary". I'm so used to ignoring that initial selection and going straight to event, since there's never any point using the status one. I'll grant that if you accept that there is a real difference between status and event, then it makes sense to have timed hide be the default. I don't accept the premise of that argument, however. It seems too much like adhering to a standard for the sake of having a standard. 


\* _If there's a better reason that I don't see, I'd be happy to hear it._

**Comment by InfusOnWoW** [comment] 2017-11-11 11:28
There is a fuindamental difference in sematnics and small changes in how they are treated internally. Just because you don't know what they are, doesn't mean that they don't exist. It's not a huge difference, but there is one and merging the two would not be possible in a backwards compatible way.

Import this:
dCtEfaGAkbRxPWRPeQzsjKzt4MefUTO2PsyVWUjz)e5Nkjmmkj)wKHQePgmLA4KQdQevNsjvhtL6WQyHusTuLswSsKSCkEirrEkYJvLNJIjQeHPs1KrPPlDrsrxvjkUSW1r1gvIOTsuuBwPA7QKpQuQLrjAAeL6DkfnkLKwKskJwjrJxjkDsIk3IOKtR48KsRKu4ZQQ)su14goOdCuqmGwI4kej9COkOmiwqSWbXomwGREDUcqhHaKj(ts5A1dqFtIRd686CfUz()WiJeBGfY62kqXYQFuSblSg0WcYnZ)hgjBxREWaIje7lDAufK1RW9vidlsZL0bP4z3m)FyyWIBqI0HfoOEeHQwchuMl6ahffupIqv4GYCrh4OOGmjrahuMl6ahffe7SVppUOAHdkZfDGJIcYCEbCqzUOdCuuqJ6BsCD4GYCrh4OOG0V07reQchuMl6ahff0(51jPGdkZfDGJIcIZeY)ehggSuOOGEWXIB4GoVoxHBM)pmYiXgyHSUTcunZ)hg4GQw9a0JZ0ugel3C6KuGUbfxHQmGKjqpottz5Rw9auCfQc6XzAkdANREDsQvxxsdjBjBDZO6QRPPmR5cxY23sUT3wZTwB9nL0qYwY2eLBus27hbtSPKgHIvYg0JZ0uw(voSbOo5GffKiDyHdQhrOQLWbL5IoWrrbTrsfYXc62QBzdQhrOkCqzUOdCuuqMZlGdkZfDGJIcID23NhxuTWbL5IoWrrbXzc53iPc5yH1Gg13K46WbL5IoWrrbPFP3JiufoOmx0bokkO9ZRtsbhuMl6ahffKjjc4GYCrh4OOOGmXFskxREaAEjfifp7M5)dddwCdAybP5vOQKTBM)pms27jJKTmbIDySax96CfGocbkwyjCqNxNRWnZ)hgzKydSqw3wbQM5)ddCqvREa6XzAkdkUcvzaznO3kJNfdkUcvb94mnLLVA1dqm9uodOhNPPmODU61jPwDDjnKSLS1nJQRUg5l3xgsY23sUT3wZTwB9nL0qYwY2eLBus27hbtSPKgHIffKiDyHdQhrOQLWbL5IoWrrbTrsfYXc62QBzdQhrOkCqzUOdCuuqMZlGdkZfDGJIcID23NhxuTWbL5IoWrrbXzc53iPc5yH1Gg13K46WbL5IoWrrbPFP3JiufoOmx0bokkO9ZRtsbhuMl6ahffKjjc4GYCrh4OOOGmXFskxREaAEjfifp7M5)dddwCdAybr9uoJKTBM)pms27jJK9YbXomwGREDUcqhHaff0fwClBlVrba

That's a event trigger triggering on event "C" and a status trigger triggering on event "B". (Which are on purpose events that never happen.) Both a set to load only in Dalaran.

Notice: Opening and Closing the options window will run the status trigger but not the event trigger.
Notice: Flying in and out of Dalaran will run the status trigger but not the event trigger.

**Comment by emptyrivers** [comment] 2017-11-11 11:52
Alright, fair enough. I didn't realize that there were minor implementation differences. That doesn't change my main point, however. Leaving aside implementation details, there is no concept that distinguishes the two that doesn't seem arbitrary to me. 

As an aside (not relevant to my main point; the following assumes that the status/event split remains), I would classify the options pane behavior as either vestigial, or a possible missing feature for event trigger (there's no way to set an event in a custom trigger as forceable by ScanAll()), and I would classify the flying in and out of Dalaran as a bug on the status trigger - it is not registered to the zone changed event, so why should it execute?

**Comment by InfusOnWoW** [comment] 2017-11-11 11:55
Both are because status and event triggers are semantically different. A status trigger is supposed to be capable of returning their state without needing the event parameters. Thus it can be trigger on e.g. closing options or on being loaded.

**Comment by emptyrivers** [comment] 2017-11-11 12:07
I understand that thought. I am saying it is a completely arbitrary distinction. It would be more compelling if the idea was enforced more strongly (by, for example, not passing in event parameters to status triggers, since they should be able to complete their execution without the information). But this is not the case. Register to `UNIT_SPELLCAST_SUCCEEDED`, and you get unit, spellname, lineID and spellID, just like if you use an event trigger. Once a user figures that bit out, and learns about `FRAME_UPDATE`, any reason to actually use a status trigger vanishes, since event can fill the same purpose.

**Comment by emptyrivers** [comment] 2017-11-11 12:10
With an event trigger can register to the event that triggers loading if you with to run on load, and as I said before, not being able to register an event as forceable is a possible missing feature for event triggers.

**Comment by InfusOnWoW** [comment] 2017-11-11 12:13
That status should be able to run without event parameters does not imply that they must. They can optimize what they do based on the event they get.

Event triggers not being forceable is by design. They are supposed to care about the event parameters. Those parameters cannot be known when e.g. closing the options window.

**Comment by emptyrivers** [comment] 2017-11-11 12:32
You continue to not respond to my claim that the distinction is arbitrary:

> Event triggers not being forceable is by design. **They are supposed to care about the event parameters.** 

In bold is exactly what I am disputing. I am saying that the design choice to separate custom triggers into two types does not serve any benefit (since anything one can do, so can the other*), and that dropping the distinction would reduce the current trigger type sub-menu to a simple check button to enable/disable the TSU feature (which could then house a tooltip explaining briefly that TSU can be used to create customized clones). That kind of UX improvement, in my eyes, vastly outweighs any possible loss of functionality (since there would be none).

\* _barring minor implementation details which can be redeveloped if necessary, or major ones which you have not mentioned._

**Comment by InfusOnWoW** [comment] 2017-11-11 12:44
The difference isn't minor implementation details. The difference is the semantics of the triggers types. I have tried to explain that multiple times now, and that you claim that there would be "no loss of functionality" and "barring minor details", is baffling when I demonstrated to you a very real difference.

How exactly should a backward compatible change look like? Should event triggers now get extra events?

**Comment by emptyrivers** [comment] 2017-11-11 13:21
> The difference is the semantics of the triggers types.

Precisely. I'm saying that the semantics are arbitrary, and complicate the GUI design without adding value.

> I demonstrated to you a very real difference.

You showed an example of some small differences in behavior. I responded that these differences can be reconciled. An event trigger can easily trigger on load, as you well know, and the only reason that you cannot force events for a custom event trigger is precisely the same design choice I am claiming should be changed\*. You haven't showed any other differences, so I'm unconvinced that there's any real barrier to changing this.

> How exactly should a backward compatible change look like?

I'll grant you that it won't be backwards compatible. But it wouldn't be the [first](https://github.com/WeakAuras/WeakAuras2/commit/aaeae1d3115ecbfa5861b48d1eb22d09db9b31aa) backwards incompatible change this expansion. And it needn't happen just at any time, either. It could be reserved for an expansion patch, where any disruption would be minor, in comparison to the changes already happening.

> Should event triggers now get extra events?

I have no idea what you're talking about here.

\* _Namely, if you imagine a world where there never had been any distinction between status and event custom triggers, it wouldn't be an unreasonable feature request to be able to force custom events._

**Comment by InfusOnWoW** [comment] 2017-11-11 13:40
So yeah, since there's no way to change this in a  backwards compatible way and it would be a major breaking change, my judgement is that it is not worth it.

**Closed by InfusOnWoW** 2017-11-11 13:40 UTC

**Comment by emptyrivers** [comment] 2017-11-11 13:45
If that's your decision, I won't push it. But "major breaking change" is a tad exaggerated, in my opinion.
