### ISSUE TITLE
Support for combination of multi unit triggers

### ISSUE THREAD

**Issue by Flowy** [WeakAuras/WeakAuras2#3973] opened 2022-11-02 14:08 UTC
**Is your feature request related to a problem? Please describe.**
Currently all possible combinations are added only for buff trigger, which makes it long and tricky to work with. Also the most basic triggers that are already implemented (ie combat log, unit info) needs to be remade into custom triggers if combination of their results is needed.

**Describe the solution you'd like**
It would be nice to have ability to define two or more triggers that prints multiple states (ie multiple units having buff) and have activation work on each state separately.

With ability to use multiple multi state triggers, there could be one simple buff trigger, and other trigger that gives units that are in range, other trigger that gives units with selected raid role, and so on

**Comment by InfusOnWoW** [comment] 2022-11-02 14:12
I think this is a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/1236

**Closed by InfusOnWoW** 2022-11-02 14:12 UTC
Labels: 🎨 Feature Request

**Comment by Flowy** [comment] 2022-11-02 15:16
I don't think its duplicate, but it can be done by appending trigger watcher, so fine

**Comment by InfusOnWoW** [comment] 2022-11-02 15:18
Well then you have to explain the problems you are trying to solve more or the solutions you are proposing more clearly.

**Comment by Flowy** [comment] 2022-11-02 15:24
The point was, to be able to create one trigger with buffs, other trigger with current unit 'raid role', and use activation to define that given unit should display if both triggers are active (for given unit)
but as said, such thing can be done in extra trigger watcher, instead of activation

if I remember, current behaviour is that it takes unit list from first trigger, and counts second trigger as active (if it has any units) or inactive (if it has no units), without comparing units themselves

**Comment by asaka-wa** [comment] 2022-11-02 16:07
Watched Triggers can achieve this in code for now.
