### ISSUE TITLE
First aura within a Dynamic group may not display Cooldown strata/masque proprely

### ISSUE THREAD

**Issue by NavaresEU** [WeakAuras/WeakAuras2#641] opened 2018-08-13 09:02 UTC
**Describe the bug**
When using WAs as showed in the screenshot inside a dynamic group, the first aura of the group will most of the time have some weird issues with Masque: like the custom text going behind the border while it is suposed to stay on top. While this is more noticeable on a WA with a custom text inside/outside the icon as on the 2nd screenshot, I can also see the cooldown animation not displaying proprely with simple %p WA not using any custom code (screnshot 1)

**Do you have an error log of what happened?**
The auras can be anything (Buffs,debuffs,cooldowns)
1. Create a dynamic group
2. Create at least 2 auras inside the group
3; The first aura from the group needs to display stacks with the following custom code as text 1
```
function(_,_,_,_,_,_,stacks)
    local text = WeakAuras.regions[aura_env.id].region.stacks -- for text1
    text:ClearAllPoints()
    text:SetPoint("CENTER", WeakAuras.regions[aura_env.id].region, "TOP")
    return stacks
end
```

**Screenshots**
![desktop screenshot 2018 08 13 - 10 20 09 17](https://user-images.githubusercontent.com/42326632/44021555-6b7d3078-9ee5-11e8-85fc-ede822b7d9e0.png)
![desktop screenshot 2018 08 12 - 23 09 26 02](https://user-images.githubusercontent.com/42326632/44021560-6e0f3bce-9ee5-11e8-9e7e-5fd679da63cc.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, 

**Which version of WeakAuras are you using?**
2.7.0

**Was it working in a previous version? If yes, which was the last good one?**
Yes, 2.6.6-87

Here is the string to a dynamic group that should reproduce the issue:

`dS0qDaGifcxssj6tiIsJsH6ukvwLcOxPamljv3ssXUiIgMuYXuILHi9mfIMgc11qezBkvPVjPegNuQ05KsjRtkL6EicDqPGfsuEOsHjkLkUOuOnkf5Jsk1ireKojIGyLeHzIiWnLsv7eOFQanuLQAPkf9ustvrBfru9vjL0yjsolrQ3kLc3vkfTxXFLedgQddAXsr9yPAYi4YuTzeYNPuJgrDAjwnIO41kKMnHBRK2nf)gPHtjhhrqTCipxLPJ66a2UsPVRGgVK05jQwVsvSFvDwYmkmZWrVOKkzTqYwrxJsikHmJAJOdJUjjKAtcDgLq5izamDUS1JcfIOYhKiIoNdynllehf25YwFIk22oQ9ucEaRzPv0Zc29asC0ZfeTpTy4OKGgBAgLrfBBhLz0MbiIiLmD4GMOhz6Wbnn05YwpCubfsiZOfJnIcyLz0vabxYmC4OqIiQu1VmJUci4sMHdhLHc3WzgDfqWLmdhoAxaVlZOxXyl8OTVHA3y4Omu4gM0mJUci4sMHdhf48kDb8UOmcWJIGDpZORacUKz4WrruHNz0vabxYmC4OwBTyOWnCMrxbeCjZWHJseSZfQjZORacUKz4WrjuiIOshqWYZm6kGGlzgoC4OqtzfYEKff52fQzk3YJsqUbUw62ikGvuVQf0qWjezrleI2EOT)4AECtfKhT6Ger05CaRzHyskkri4QRmcYWasC0IHDKbki5o6kuta3BuGcHOE7kNBMey1ij18WOftHRCmeXoHaUeoApZaUKzu2RYlnrnSw2JhqsBRODGJPRtVkhLiatNluZ4k1RuVs9k1RuVs9JH9rVDVep(Xp(XcAhkEm7v5htIpUwD4OnaGGNKi3UqnxBabqWkUzRKfcTPKi3UqnsEmSp694AQ5XerrpM9Q8YlXJF8JFm7v52EdHdrnie7tlg(gV7L4Xp(XpM9QCBRoVpTy4XJyJgbNnU5iQ)4A1HJ2aacEsIC7c1CTbeabR4MTswi0MsIC7c1u)XJyo4(Jy3lXJF8JFmYzaK5Xhd7JEVeUHquadJk22okZOhz6WbnrpY0HnigcLFrplxiaHREaxA1UTljnYWrHDUS1NOITTJApLGhWwrzuX22rzgf48k2UXrLUsMoCqtKf12noQ0vY0HdAIEKPdBqmek)IcCEfatHJSOSClp6Xqg4Icy8TUHJcbyAuGZRCKPdh0ezr9TUHJUbLkiqhAE8(iQnYV7XJvlxi2f1ax9lZaUeDtaJ)4j0kCuKdfQLleGWvpAtfK)yzc4XrboVYz5cbiC1JSONLleGWvpGlTA32LKgzu6qZGgH8ilkW5vGnFuuZTNsWJSWrTquBKF3(iVxUc1eWwrzVkVSpTy4OB0i4SXnJs2l2K5asmXrfuiHmJYqHBysZm6kGGlzgoCugkCdNz0vabxYmC4ODb8UmJEfJTWJ2(gQDJHJEwEpZOxXyl8asA0vabxYmGlrw4WrrWUNz0vabxYmC4OaNxPlG3fzrruHNz0vabxYmC4OwBTyOWnCMrxbeCjZWHJcCELZY7rwuIGDUqnzgDfqWLmdhokHcrev6acwEMrxbeCjZWHJwm2ikGvMrxbeCjZWHdhTyyhzGcsUJUc1eW9gfAkRqUqnzg9yiIZmkl3YJ2boMUg96qH3eGPh9Xp(XpMiatNluZyle1g53v)XhdrSu1F8XqelD9hFDOWLQ(JVou4sV7L4Xp(Xp(Xpg5maY84JHiwQhpGhp2crTr(DpEGpE81HcxQhxZJpgIyP2TR(JpgIyPF8aE8yle1g5394b(4XxhkCPFCnp(yiILE3UxIh)4h)y3q4L4Xpo61HcFk3YJEmcwSjZAhk8OeaqqUqnrBjjPrVou4Yd4IKehfkSiddyRODQGI2mGlrLhWwrRgWwr7ubfv7aUeTtfuKSaUeTtfuudbCjkIYq2dyROxhk8QbCrsIJcCELRdfEKfo6kSyYmANkOOnd4s0Rdf(uULh9yeSytM1ou4rboVY1HcpYIcfwKHbSv0QbSvu5bSv0ovqrneWLODQGIQDaxI2PckswaxIEDOWBcW0J(4h)4hteGPZfQzSfIAJ87Q)4JHiwQ6p(yiILU(JVou4sv)XxhkCP39s84h)4h)4hJCgazE8Xqel1JhWJhBHO2i)UhpWhp(6qHl1JR5XhdrSu72v)XhdrS0pEapESfIAJ87E8aF84RdfU0pUMhFmeXsVB3lXJF8JFSBi8s84hhfrzi7bSv0RdfE1aUe96qHlpGlHJsuXuoYzg1c5NZrpYOIz0OSClpQfYpNdhoANsfeOdntVk3Ob2SWjKMJYEvEPjQHJoNBqxxPMRgzubHOi3Uqnt5wE0sNAIYEvM0MOgo6CUbDDLAUA20Tbequu2RYK2e1WAzpEajTTIsecU6kJGmmGKuu2RYlrRL9OfcrBQG8hltap(XB0orhwiWKdiXehfOqi6MJxBCuY1c7AtYSNOftHRCmeXoHaUeTtnekCHAUmd4sMr7K9(OzgLrfBBhfWwr3crfyZcpANmez7x0TqbGhTvuQvusKedhTtgAS9lZaUKz0TqbGhzrTqulhXYJsWpidGGShoGKMz0TqbGhqIBf1crTCelpkzVytMdhWrMz0TqbGhqIBf1crTCelp6WcbMC4WHdhTtPcc0HMilCajnZOSxLxAIAyTShpGK2wr7ahtxNEvokraMoxOMXvQxPEL6vQxPEL6hd7JE7EjE8JF8Jf0ou8y2RYpMeFCT6WrBaabpjrUDHAU2acGGvCZwjleAtjrUDHAK8yyF07X1uZJjIIEm7v5LxIh)4h)y2RYT9gchIAqi2Nwm8nE3lXJF8JFm7v52wDEFAXWJhXgncoBCZru)X1QdhTbae8Ke52fQ5AdiacwXnBLSqOnLe52fQP(JhXCW9hXUxIh)4h)yKZaiZJpg2h9EjCdHOaggvSTDuMrpY0HdAIEKPdBqmek)IEwUqacx9aoYL9U3LWrHDUS1NOITTJApLGhWwrlg2rgOGK7ORqnbCVrzuX22rzgf48k2UXrLUsMoCqtKf12noQ0vY0HdAIEKPdBqmek)IcCEfatHJSOSClp6Xqg4Icy8TUHJcbyAuGZRCKPdh0ezr9TUHJUbLkiqhAE8(iQnYV7XJvlxi2f1ax9lZaUeDtaJ)4j0kCuKdfQLleGWvpA7GG2udj79yzihYKJcCELZYfcq4QhzrplxiaHREah5YE37su6qZGgH8ilkW5vGnFuuZTNsWJSWrTquBKF3(iVxUc1eWwrzVkVSpTy4OB0i4SXnJs2l2K5asmXrfuiHmJYqHBysZm6kGGlzgoCugkCdNz0RySfEaxin6kGGlzgWfsJSWHJ2fW7Ym6vm2cpA7BO2ngo6z59mJEfJTWdiPrxbeCjZaUezHdhfb7EMrxbeCjZWHJcCELUaExKffrfEMrxbeCjZWHJAT1IHc3WzgDfqWLmdhokW5volVhzrjc25c1Kz0vabxYmC4OekeruPdiy5zgDfqWLmdhoAXyJOawzgDfqWLmdhoCuOPSc5c1Kz0JHioZOxhk8PClp6XiyXMmRDOWJEDOWBcW0J(4h)4hteGPZfQzSfIAJ87Q)4JHiwQ6p(yiILU(JVou4sv)XxhkCP39s84h)4h)4hJCgazE8Xqel1JhWJhBHO2i)UhpWhp(6qHl1JR5XhdrSu72v)XhdrS0pEapESfIAJ87E8aF84RdfU0pUMhFmeXsVB3lXJF8JFSBi8s84hhLLB5r7ahtxJsaab5c1eTLKKg96qHxnGlssCuOWImmGTI2PckAZaUevEaBfTAaBfTtfuuTd4s0ovqrYc4s0ovqrneWLOikdzpGTIEDOWLhWfjjokW5vUou4rw4ORWIjZODQGI2mGlrVou4t5wE0JrWInzw7qHh96qHxnGlrHclYWa2kA1a2kQ8a2kANkOOgc4s0ovqr1oGlr7ubfjlGlrVou4nby6rF8JF8JjcW05c1m2crTr(D1F8Xqelv9hFmeXsx)XxhkCPQ)4RdfU07EjE8JF8JF8JrodGmp(yiIL6Xd4XJTquBKF3Jh4JhFDOWL6X184JHiwQD7Q)4JHiw6hpGhp2crTr(DpEGpE81Hcx6hxZJpgIyP3T7L4Xp(Xp2neEjE8JJIOmK9a2kkW5vUou4rw0RdfU8aUeokrft5iNzulKFoh9iJkMrJYYT8Owi)CoC4OSxLxAIA4OZ5g01vQ5QrgvqikYTluZuULhT0PMODkvqGo0m9QCJgyZcNqAok7vzsBIAyTShpGK2wrjcbxDLrqggqskk7v5LO1YEu2RYK2e1WrNZnORRuZvZMUnGaIIwieTDqqBQHK9ESmKdzYpEJ2j6WcbMCajM4Oafcr3tThKeEKKGMavWrgL9Q8sJgyZcNqAoAXu4khdrStiGlr7udHcxOMlZaUKz0ozVpAMrzuX22rbSvuQvusKeJUfIkWMfE0oziY2VOBHcapARWr7KHgB)YmGlzgDlua4rwule1YrS8Oe8dYaii7HdiPzgDlua4bK4wrTqulhXYJs2l2K5WbCKzgDlua4bK4wrTqulhXYJoSqGjhoGeNz0TqbGhqs3Bule1YrS8OSxLjTjQH1YE8WHdhoANsfeOdnrw4aoYmJYEvEPjQH1YE8asABfTtPcc0HMPxLB0aBw4esZr7ahtxNEvokraMoxOMXvQxPEL6vQxPEL6hd7JE7EjE8JF8Jf0ou8y2RYpMeFCT6WrBaabpjrUDHAU2acGGvCZwjleAtjrUDHAK8yyF07X1uZJjIIEm7v5LxIh)4h)y2RYT9gchIAqi2Nwm8nE3lXJF8JFm7v52wDEFAXWJhXgncoBCZru)X1QdhTbae8Ke52fQ5AdiacwXnBLSqOnLe52fQP(JhXCW9hXUxIh)4h)yKZaiZJpg2h9EjCdHOaggvSTDuMrpY0HdAIEKPdBqmek)IEwUqacx9asmXets1IWrHDUS1NOITTJApLGhWwrzVkV0Ob2SWjKMJYOITTJYmkW5vSDJJkDLmD4GMilQTBCuPRKPdh0e9ith2Gyiu(f1ax9lZaUeDtaJ)4j0kCuwULh9yidCrbm(w3WrHamnkW5voY0HdAISOaNxbWu4ilQV1nC0nOubb6qZJ3hrTr(DpESA5cXUOaNxb28rrn3EkbpYIICOqTCHaeU6rjbLTfJ9JLrxBokW5volxiaHREKfLo0mOripYIEwUqacx9asmXets1IWrTquBKF3(iVxUc1eWwrzVkVSpTy4OB0i4SXnJs2l2K5asmXrfuiHmJwm2ikGvMrxbeCjZWHJYqHB4mJEfJTWd4s7gDfqWLmd4cPrw4WrzOWnmPzgDfqWLmdhoAxaVlZOxXyl8OTVHA3y4OiQWZm6kGGlzgoCuGZRWqHB4ilkHcrev6acwEMrxbeCjZWHJIGDpZORacUKz4WrplVNz0RySfEajn6kGGlzgWLilC4OwBTyOWnCMrxbeCjZWHJseSZfQjZORacUKz4WrboVYz59ilkW5v6c4Drw4Ofd7iduqYD0vOMaU3OSxLxAIA4OZ5g01vQ5Qrgvqik0uwHCHAYm6XqeNzuwULhTdCmDn61HcFk3YJEmcwSjZAhk8Oxhk8Mam9Op(Xp(Xeby6CHAgBHO2i)U6p(yiILQ(JpgIyPR)4RdfUu1F81Hcx6DVep(Xp(Xp(XiNbqMhFmeXs94b84XwiQnYV7Xd8XJVou4s94AE8Xqel1UD1F8Xqel9JhWJhBHO2i)UhpWhp(6qHl9JR5XhdrS0729s84h)4h7gcVep(XrjaGGCHAI2sssJ2PckQHaUe96qHlpGlssCuOWImmGTI2PckswaxIkpGTIwnGTI2PckQ2bCjANkOOnd4s0RdfE1aUijXrrugYEaBff48kxhk8ilC0vyXKz0RdfEtaME0h)4h)yIamDUqnJTquBKFx9hFmeXsv)XhdrS01F81HcxQ6p(6qHl9UxIh)4h)4h)yKZaiZJpgIyPE8aE8yle1g5394b(4XxhkCPECnp(yiILA3U6p(yiIL(Xd4XJTquBKF3Jh4JhFDOWL(X184JHiw6D7EjE8JF8JDdHxIh)4Oxhk8QbCj61HcFk3YJEmcwSjZAhk8OaNx56qHhzrHclYWa2kANkOOnd4su5bSv0QbSv0ovqr1oGlr7ubfjlGlr7ubf1qaxIIOmK9a2k61HcxEaxchLOIPCKZmkl3YJAH8Z5Owi)Co6rgvmJgoCuKBxOMPClpAPtnrhwiWKdiXehL9QmPnrnSw2JhqsBROSxLjTjQHJoNBqxxPMRMnDBabefL9Q8s0Azpkri4QRmcYWassrleIsckBlg7hlJU28J3ODIcuieL4QntcxRTJSg3SSF0IPWvogIyNqaxI2PgcfUqnxMbCjZODYEF0mJYOITTJcyROuROKijgDlua4rBfDlevGnl8ODYqKTFHJ2jdn2(LzaxYm6wOaWJSOwiQLJy5rj4hKbqq2dhqsZm6wOaWdiXTIAHOwoILhLSxSjZHd4iZm6wOaWdiXTIAHOwoILhDyHatoCajoZOBHcapGKU3OwiQLJy5rzVktAtudRL94HdhoC0oLkiqhAISWHJUnGlet6s4e`

**Comment by NavaresEU** [comment] 2018-08-13 14:32
Hi and thank's for you response, but as I said in the inital post, this issue appear even withtout any custom code as you can see on this screenshot where the text1 %p is displayed behind the cooldown animation: 
![desktop screenshot 2018 08 13 - 16 27 46 69](https://user-images.githubusercontent.com/42326632/44038100-42e56d2a-9f16-11e8-8e8c-4f07e5fb55ff.png)

And again, this is ONLY on the first aura of the dynamic group.

**Comment by emptyrivers** [comment] 2018-08-13 16:26
Duplicate of #639

**Closed by emptyrivers** 2018-08-13 16:26 UTC
Labels: 👯‍♀️ Duplicate
