### ISSUE TITLE
Question / feature request: Global Group Scaling

### ISSUE THREAD

**Issue by Yama1291** [WeakAuras/WeakAuras2#149] opened 2017-02-08 13:38 UTC
I was wondering if it was possible to implement scaling on a group basis?

Quite often when importing a custom weakaura I'd love it to be just a tad smaller. ATM all I know to do is to manually resize all the group elements. It would be really neat if there was simple scale option for the whole thing. 

Cheers!

**Comment by InfusOnWoW** [comment] 2017-02-08 17:06
That's a duplicate of https://www.wowace.com/projects/weakauras-2/issues/827

**Closed by InfusOnWoW** 2017-02-08 17:06 UTC
