### ISSUE TITLE
Would like to be able to rename triggers

### ISSUE THREAD

**Issue by raysmith59** [WeakAuras/WeakAuras2#3532] opened 2022-03-09 23:02 UTC
Simple request, would like to be able to rename triggers so I don't have to try to remember what trigger 7 does.  Probably via a new button on the right side of the "trigger #" line.

**Comment by InfusOnWoW** [comment] 2022-03-09 23:21
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/705

**Closed by InfusOnWoW** 2022-03-09 23:21 UTC
Labels: 🎨 Feature Request, ⏱ Awaiting Response
