### ISSUE TITLE
After reset today - WA no longer works

### ISSUE THREAD

**Issue by travman1900** [WeakAuras/WeakAuras2#4897] opened 2024-03-05 20:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

WA was working fine last night. Loaded after reset and WA was not avail in the bubble on map or via /wa

tried to unload and reload WA via radials and reload No go.

tried a reinstall via wowup No go.

### WeakAuras Version

5.11.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

See description for my troubleshooting.

### Last Good Version

Yes - Whatever version was last night. Wowup is set to autoupdate

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/46836974/dc17ecb5-5340-4364-997c-7e785c9c80e9)
![image](https://github.com/WeakAuras/WeakAuras2/assets/46836974/f36cc78d-7b4b-4d28-ad64-769f36acd9d6)
![image](https://github.com/WeakAuras/WeakAuras2/assets/46836974/04b22fa0-f078-4c8c-8d64-d476fd3264b9)

**Comment by SpatenLa** [comment] 2024-03-05 20:21
your weakauras is outdated. update to 5.11.1

**Comment by emptyrivers** [comment] 2024-03-05 20:21
duplicate of #4896, upgrade to 5.11.1 to fix the issue, thanks!

**Closed by emptyrivers** 2024-03-05 20:21 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate, ⏱ Awaiting Response
