### ISSUE TITLE
The last maj 10.1 does not work on European client

### ISSUE THREAD

**Issue by Seb-Dupuis** [WeakAuras/WeakAuras2#4423] opened 2023-05-02 16:44 UTC
### Description

WAs are not available in games and the /wa command does not work either.

### WeakAuras Version

5.5.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Installing wa with a UE client and launching the game

### Last Good Version

5.5.0

**Comment by Stanzilla** [comment] 2023-05-02 16:46
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4417

**Closed by Stanzilla** 2023-05-02 16:46 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
