### ISSUE TITLE
Error "regionType not defined" 

### ISSUE THREAD

**Issue by Ghalleonn** [WeakAuras/WeakAuras2#2066] opened 2020-03-23 20:53 UTC
## Describe the bug
I logged into the game and tried playing just as general. I noticed my weakauras were not showing and tried to do the /wa command in chat, which failed to bring the weakaura panel up.

**Do you have an error log of what happened?**
1x WeakAuras\WeakAuras-2.16.6.lua:4401: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@WeakAuras\WeakAuras.lua"]:4401: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:4365: in function <WeakAuras\WeakAuras.lua:4268>
[string "@WeakAuras\WeakAuras.lua"]:4395: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:3928: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:3935: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1606: in function <WeakAuras\WeakAuras.lua:1578>

[string "@WeakAuras\WeakAuras-2.16.6.lua"]:1734: in function <WeakAuras\WeakAuras.lua:1685>

### To Reproduce
I only logged into the game after updating.

**Screenshots**
Screenshot only shows the error listed above. No additional information.
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4371850/WeakAuras.zip)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I went to an alt on a different server to test if other addons had any effect, I still got the same error.

**Which version of WeakAuras are you using?**
Version 2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X ] Retail

### Additional Info
Included the WeakAuras savedvariables in the post.

**Comment by mrbuds** [comment] 2020-03-23 20:53
duplicate of #2064

**Closed by mrbuds** 2020-03-23 20:53 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate
