### ISSUE TITLE
About a function of automatically removing redundant lines of code from the weakauras.lua file in WTF

### ISSUE THREAD

**Issue by 1575819749** [WeakAuras/WeakAuras2#3726] opened 2022-08-03 17:09 UTC
For a patient with severe obsessive-compulsive disorder, this function is too much needed (obsessive-compulsive disorder is so severe that it needs long-term drug control)
I want to remove the redundant code in "weakauras.lua" in WTF. (I'm a Lua rookie)
I delete "weakauras.lua" line by line, and then re-enter the game to see the transformation, and then delete, re-enter the game to see if it will break... Infinite cycle
Because the "weakauras.lua" file will be automatically generated every time I restart the game, I will replace the newly generated "weakauras.lua" file with the one I am deleting, and then continue to do "delete redundant work" on the basis of this file
It will take 10-16 hours to do this every day
At present, more than 3.9 million lines of code have been screened
It will take more than two years (I have been doing this since 2020)
In order to clarify the function of each row and the consistency when deleting redundant rows (some empty assignment fields will also appear in "weakauras.lua"). I wrote comments for each line of code
The pain is that my mother tongue is not English. I have to look up every word in a dictionary, and some of them may not understand
Then after annotating each line in my mother tongue, every time I re-enter the game and exit the game, the file will be overwritten by the automatically generated "weakauras.lua", so every time I enter and exit the game, I will back up the "weakauras.lua" file I am writing comments on, and paste it back after the test.
Then I found that for each group or content, the order of the code lines of "weakauras.lua" was inconsistent
I spent a lot of time and energy again to sort all the contents. The order of sorting is exactly the same as the top-down fields in the game setting interface
After finishing these, I found that because it took too long to do, some descriptions of the notes I wrote for the same fields were not the same (my interpretation of them changed two years ago and now)
Then, I exposed them all, compared them, and tried to modify them into the same
... another round of collapsing workload
Then, the game version has changed, and many new skill monitoring and copy monitoring are needed. Many previous skills have also changed
Then I write the new one and spend a lot of time (I add an aura, which is written line by line from the "weakauras.lua" file, not from the interface in the game, because there are many redundant lines of code added from the interface in the game)
In the process of writing, because of obsessive-compulsive disorder, I have doubts about all the contents I have done before
Then they will recheck one by one line... Unable to control themselves
Today, when I visited GitHub for the first time, I saw this problem. Because my English is poor, I'm not sure if it's the problem I described
But I've burned my life on this matter. I look at "weakauras.lua" in the editor every day
I've been doing this for nearly 10000 hours without exaggeration
I know it's meaningless, but I can't be happy anymore. I was diagnosed with depression last month

**Comment by InfusOnWoW** [comment] 2022-08-03 17:09
Duplicate of #803

**Closed by InfusOnWoW** 2022-08-03 17:09 UTC
Labels: 🎨 Feature Request, ⏱ Awaiting Response
