### ISSUE TITLE
Some icons without cooling show timers after closing the WA control panel

### ISSUE THREAD

**Issue by Sanluli36li** [WeakAuras/WeakAuras2#2039] opened 2020-03-12 18:44 UTC
## Describe the bug
When I close the control panel, there are always some icons with timers, even if there is no relevant content in their code
These are Wa's that show errors, but not cause them:
https://wago.io/TalentSetup/43
https://wago.io/Rh8IFmqMl/16
This could be this wa that caused the error:
`!TN16UnUXv43LaeG1ancI6MTlAkGKTuwTWwYqdvZLFq7rKJKMyksfoK2wgl0BrrFb6FBrb6F7JttEo65CgEvs0wsjDBsHH3vMC0zMZTVZL5yldltlMYIvRIrRkTSylSyo4)GvNf4)Of79dh1)7goWS9vwSj(boIGoC77Dc8xAX64kF(zEGZ67m99DdLWspnC6uLi0Aqvl2QKNR1WIX9SN7hCJV0l0IDr3bMDhLCGx476haCCGbUTb1OpRtF2axe2aikSLCBb(kJBhk99uKKhYdcHhasKEY4NMcpQMtpdVfgiNnteO0mWmDb8rhXKOPtnxTuakA3RUP3yqldPx5rb8AadwkCD77O0NSkAI4bHxid2L8jl2Tx0MzElZS9i4WIqbGT0LVco8usVjqqKYUP7vWHtRbmtWDdNBX84leQejnYlt0c1lz77gTWlt1bRNiWJ7(NafcSbGXQfAALl4OjjVfjwn889GpDaLbj4w9IkHTVhOtadwWLE7p1Pw29JEyhCx5mVmhoiDKcIWdWcnsml2tIhEaymaVdpKJGaMRpNWHrkXT2UCLYAc5pSXfxeb4TedN(B3CvL8zXMlclpjg(Mh1zqOodc1zqOUQvAsNHFq47xnjq6yYN4sh3aqkbNCOy9DF8JaYNhmteU(UljOKvhsPjhIaEbf(RKlaGb8SYM7gJG1bdIGXeMzq7R7EZvTn7MerGAQ(PUoZatk7hI4bad7f56U(UVEUeoCwaz80GxNvassAdHSrqq4CsIVXxjjur879KbQyvkzjWitc3GZWqSqnic9nAM33JcFnsiNbB9AFhKFcLTWZr6ndXOEGB1lShexcwu2O2x2FmduYa7ReEZay(G6TspZKCcnWemGzLe)rxcikF7hsq1NvTEvyhOaoUV2oNZS3bn0qaAiydhUmmdbHh4xlDqo2mXi3drvAUWUyu3UdqaQ70nsefHS6QMk24V9Xto)5UKwnvoloSxh)vprhyiYcHOiqxMtaaVD7cUwWRhWDKrkGCqJqSAAEO8PkTJuH(lmfpHXbrEucU3DY6pS(o9pYPRVdZiDRW7HkG1gndCpNnxScMdk(Bq(3xHF(UDq0VB9DF2cFqE9bJ(NDY67cNl8Y4xYpP7ud2(9uqZ7mGDN()CsPWvjoMZOALtBM)yaX)dWh5QGuTKci2qDhh)h9ypkbp8K8gYXlDWyqwu8VtiLIOa)IeCE4VFP6dQ5(pEHlKKtruwOWWlvkayZqp3v4M2iHFjLfkwMjRQqCrfVeW)gLSAp6ASK1oQDWCKQVNaspGYS3kDzZheMAYOWyDT1Dwt5EHyzBmzB4imRaL(A7WginapeZ(t2(Lb(ZcekfOB2svsQKcP5JTW66ertIZ2fhwDlLXEGrZ0fS3kh9wDget5dadXe0Dsxrqzo3rlkXFVFm0QUf2Hc1WJR)J9ce)qKWZEfwcOwt9IOYbHkFf8OUQb8EiaXsLVqnDjP7mQQF)BZbFNLU5Yk5yKCmAN7KOWqFVHq4j0rroBgjqeDFZghV5CP99awvrPSXvyPvCiXtIazmxp(wNKknKnWmwJuZ5o5ozJ4LdPmtF(YcuTh9TPPEBGJoyoV9HO87HOx50vz0rfLe68IdgoOBo7GwKOTPpTTeA7x3Ct0n1hfT)9)6V(J)9)5p9N)h)4F7VuqntLYVWi3g0oPHJnVQpjwzYrSQAo8MclNDm1YDm6sjgPni)nBAsYa2urZ9Zpz)5Q38u7TNQZqtZHxVBN1o8v12lFf2JLqoBoEgvZAM9a6Ff771dkweqjF3DZS57bKkObnCVCoNSSW(tY5nPSlnL7QszxGkmRyj6pVuQWEFDqX4zF)fyMX6u)xuzHs6B7LBtUq7vfA8he8h1TWLDRXD0dh1W2PRwDY4Ngj)UtMGIpkguHOD0A4EGWk0mNUqL9CH9957jafVh4bs6YaOH0(EfUIBe8k8D4TI)dFjDAZ5EZezhfuCCPiiCffruPrLcagT3uxf6v4PU()feIjHX2rOItm)l3jZ10rV17SZp14StBDE1gNwRwdWDn9lA2ilNqzFFIvQOEyuPqL6y9O(rQhqplc(VaAszFtXmE7JM0OunjweFfns4fWNj(z6souHU5rA(xWNjT3tJFHYighM816iLVL(sfMI7aeWEToTrRMTo7SM1B20O65TqtB9JWOMlNiM0B3JCPKbHexjCj0BSim73t5oI8JG5L3nnQLcJG5O4wwEM3U(5)tV(5VCdX8fUKk2cr(iPoVY9wNkcTNN00WrE5188ZmjPsN0uHDoOl4gpt2DCbxnioNziokaGyrQxrntICOs2X64yc6EXCEa4zebsO9wBvPQCHzsIVWNO8dMq3Qwp1VBJIN)tXXch5fZpQ9PpnxC)LMpCs6HYsMuwYQJBEXhi3cp6jmu2afYU0F5JyyRgdp8rmS5aoEBcdVnHH3MWWBty4)VNWW236ozg75gBqztw44gNG(pfenmG5N2RlRZ8p4DX9h3ifYpsICdtypqo7auF8dtiEeczdv4t1WeYUrBUHk8BWHjSHEKmuHFBmmH8tnOef8x5dtydDr3))VIgMWgYx8qf(KomHbNUBHgRBNj1ThCzmrBFTVniD4Om9QSDuyd270wC5OX9VCR7wTp789JP0EH74Qz7VRiDyzHL7o6SPbUwfQD1yoF2)fmS)CmODVE4GuBZHBwVU9x1nR75dyJ3mQFxMzwdD526guYEF7RBpy7t8aDLLmcXJ3tE(EexlEAPuFrst5crQq0cBAafH)4Rx7S(UQDwCyF07pGTqxddWT(pp`

**Do you have an error log of what happened?**
no

### To Reproduce
Close the interface after displaying any icon using custom anchor or group on nameplate in the options interface

**Screenshots**
![批注 2020-03-13 022207](https://user-images.githubusercontent.com/5201743/76555569-d94f8b00-64d2-11ea-8d5b-cb1708b7c4b9.png)
This is a wa showing the error, but it should not be a wa causing the error:https://wago.io/TalentSetup/43

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I tried

**Which version of WeakAuras are you using?**
WeakAuras 2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Not tested

### Additional Info

```
  ERROR HERE
```

**Comment by Sanluli36li** [comment] 2020-03-12 18:45
This bug seems to work for all TSU auras

**Comment by InfusOnWoW** [comment] 2020-03-12 18:51
I think this is already fixed for the next release.

**Comment by InfusOnWoW** [comment] 2020-03-14 19:04
I mported those 3 auras and couldn't reproduce any issue. We fixed a similar issue recently, so I believe this is fixed in the next release.

If the next release doesn't fix it, you can comment here again and we'll need to figure it out.

**Closed by InfusOnWoW** 2020-03-14 19:04 UTC
Labels: 🐛 Bug
