### ISSUE TITLE
Issue with Outlaw Rogue Cooldowns that are reset by Restless Blades

### ISSUE THREAD

**Issue by Urliq** [WeakAuras/WeakAuras2#1195] opened 2019-02-21 04:42 UTC
**Describe the bug**

Having issues with tracking cooldowns that are affected by Restless Blades as an Outlaw Rogue. The main culprit being Between the Eyes. If the cooldown is made active by Restless Blades it takes a second or so to register as being off cooldown.

**Do you have an error log of what happened?**
 

**To Reproduce**
 
1. Create a WA for Between the Eyes using preset with Cooldown Tracking option.
2. Use Between the Eyes.
3. Wait until the ability's cooldown has 5 seconds or less left and use a 5 point finisher.
 
**Screenshots**

![image](https://user-images.githubusercontent.com/47842001/53144146-1a43cd00-3569-11e9-8c50-492a0d4adbae.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes.

**Which version of WeakAuras are you using?**

2.11.5

**Was it working in a previous version? If yes, which was the last good one?**

Unsure but it was much worse in 2.11.4 and would not register the ability coming off CD at all until timer expired normally.

**Additional context**

!Lw13pkUnq4)AQu7d90ch317ECHl0UsuGIdvQ9bdgNHeR1Xo12bw2h4V9oJDcWUAv3tQsiIXz(X38nFZaFapNZu85d(4N(8G74mpNn8ddg8HpXz1Cwb9bniapfgU0QmboBs288SvP7gm1Acm1ZaF(q0Jtl2V3db(CmqcJSY6ELpsRvxypAyhvnaFmErRpyRZXqTUPqeaoRT7zVPzfLaFhgpzqznEcn(GWfWdyG3RmkFv6mEmDlEU1dLA7XjwT1rEF9h5yTg)mm(9hJFpI(o0vtzgXonuqW7raAU33aYWkbMEksEqV)1mHtvwcoFk25xUGoAe1GpHVWjSMjWhArwgJQwphFl6Zx)6xUBecAdCaOalAdw0I2DXFV0b7vpXzSLzZMflTnLGbCkjRYECHHa6lVG5XN3Rpko5POI0cRrloHiI5aHMDj1SXq4iaMZBdvW5TzNaFkbxr34oO(qrxz0dlw7(iS2m5Ew(gw(9RWYTO1refcHbCwx1mPRtEE7sNT0bE)5T)yed)ukzbNq(iLOcyhg08ip9BzZwoD9SyZ0CLqJDxslCaYtx(72cKd)zu823aNGIsHYuhZ(dZzp8TmKa6YnYMsLNGiPsJ2)gc7HKWEQwuI8XI15ZEyogIkqvwHQ7rFHGQh7JosQIIcTveNtOQrQfEpvnD8OS)S0wVteIQ(OjKswzk1yXUAXVUgtqDRoO6lYORxTb1RV690yx(lVK4gJQo1cUzs5sFztNieKwd2q70KgRbiFRrw7736lZEFF2hUHz5SPo1ZN3(hTIc0vX5T550iVzVQSByHm9nBK0OCsISRneSMfhahkUVzH0Bh9oPX7Ud4OQiuLAYDG4DDXbLy1NaLssQ)9oC2b3dGzNSH9u)MXFz4n0q3MZr0URa4mc9FIRrIAZbOtcDtvY9i25SFOjv(KK7zRT(IeEy6DX9gK(69HSQ4Th(VqIVw8htt)QXD973Ns1zQWztwLLnpcc8flA6xxtdWu2cl(Rp7(N)U0mYr1l218XTlrcB81f(0FgCZkyskP6JvA9QScW9f4HdcDlejOdcNICHISNwmjvOOzf4TTozSU62GKQEzLWucxJykqjc7o8)(ikl(8LKgUdPbCHt9mCAKdn(9aL10Ve8)dsIp)VXs4kpg3ChuYhp9T(LY7O3FadWOHum4)l
``` HERE ```

**Comment by Micrologist** [comment] 2019-02-21 22:26
I can reproduce this on 2.11.5 but not on 2.11.3. It seems to be related to the recent GCD problem that was supposed to be fixed in 2.11.5 as the aura doesn't update until you stop casting on GCD.

**Comment by InfusOnWoW** [comment] 2019-02-23 15:23
Fixed in the latest alpha and next release.

**Comment by Stanzilla** [comment] 2019-02-23 15:23
Hey @Urliq could you please test again with our latest alpha version? That would be https://www.wowace.com/projects/weakauras-2/files/2679109

**Closed by InfusOnWoW** 2019-02-23 15:23 UTC
Labels: ⚡ Regression, 🐛 Bug

**Comment by Micrologist** [comment] 2019-02-23 21:12
I can confirm this appears to be fixed both with 2.11.5-5-gf29a283 and 2.11.6-beta1-1-gaaa7ddb

**Comment by InfusOnWoW** [comment] 2019-02-23 21:19
Thanks!
