### ISSUE TITLE
Dynamic Group, animated expand/collapse setting not working correctly.

### ISSUE THREAD

**Issue by Kalrell** [WeakAuras/WeakAuras2#1394] opened 2019-06-12 10:39 UTC
**Describe the bug**
I just updated to 2.12.4.2 and I'm getting some issues with Dynamic Groups. Occasionally the group isn't expanding correctly and there are gaps between Auras and overlapping. Upon asking in the Discord it was traced to the Animated Expand/Collapse setting being enabled.
When the Animated Expand/Collapse setting is turned off in a Group the issue doesn't happen.

**Do you have an error log of what happened?**
I have three screenshots i took of the issue.
https://gyazo.com/a77c819fbc416138e3e8d285acca9a59
https://gyazo.com/dc5a55db98dce1ef7f14745827f30b0c
You can see the Necrotic Wound and Festermight auras overlapping in the same Dynamic Group.
https://gyazo.com/bbea8c195bd9348b4323994bce9fba4e
You can see the Ready aura for Death and Decay overlapped by Soul Reapers timer Icon and Soul Reaper and Dark Transformation Icons are off centre compared with the separate group above.

**To Reproduce**
Create a Dynamic Group with Animated Expand/Collapse enabled.
Fill the group with Auras doesn't matter what type of aura. Got screenshots of it happening with both Icons and Progress Bars.

**Screenshots**

Screenshots:
https://gyazo.com/a77c819fbc416138e3e8d285acca9a59
https://gyazo.com/dc5a55db98dce1ef7f14745827f30b0c
https://gyazo.com/bbea8c195bd9348b4323994bce9fba4e

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Nope haven't tested with only Weak Auras enabled but seems a issue confided to Weak Auras.

**Which version of WeakAuras are you using?**
2.12.4.2

**Was it working in a previous version? If yes, which was the last good one?**
It was working previously, unsure of which version though.

**Comment by mrbuds** [comment] 2019-06-12 11:31
Can you test with other addons disable, and export an example on wago ?

**Comment by Stanzilla** [comment] 2019-06-15 17:17
@Kalrell can you upload the auras please?

**Comment by Causese** [comment] 2019-06-15 17:42
1. make a dynamic group
2. add 2x progress bars to it and enable animated collapse thing
3. enable auto clone in trigger - aura - buff
4. close option and check how its supposed to be
5. convert both to icon and back to progress bar
6. notice how there's a gap
7. disable animated collapse thing

2a. (optional, master only) left clicking the bar inside options after enabling animated collapse causes
```
2x WeakAuras\AuraEnvironment.lua:160: attempt to index upvalue 'current_aura_env' (a nil value)
WeakAuras\AuraEnvironment.lua:160: in function `ActivateAuraEnvironment'
WeakAuras\WeakAuras-@project-version@.lua:3735: in function <WeakAuras\WeakAuras.lua:3680>

```

**Comment by InfusOnWoW** [comment] 2019-06-15 18:33
The aura_env thing is fixed by https://github.com/WeakAuras/WeakAuras2/pull/1403, the gap is due to not creating the right clones after conversion. Since I'm rewriting that part anyway in the big Rework text replacement, I didn't want to invest time into fixing that. It's unrelated to the original issue.

**Comment by iElsha** [comment] 2019-06-19 19:02
Hi,

I'm getting the same issue on dynamic groups.

I've got an overlapping when I have more then 3 auras on this one :  https://pastebin.com/wAi5tqXT - Buff (the first one)
I don't have error message or screenshoots, it's the same than @Kalrell (URL:https://gyazo.com/bbea8c195bd9348b4323994bce9fba4e)
It seems to happen in raid or dungeon only.
It appears since 1 week not more.

Secondly, I also have troubles with clockwise grow : https://pastebin.com/wAi5tqXT
I'm trying to reproduce this behavior : https://www.youtube.com/watch?v=GtkRdzKvjTI&feature=youtu.be&t=39

Feel free to ask me anythings.
Thanks you.

**Comment by mrbuds** [comment] 2019-06-20 10:44
I can reproduce the issue on my resto druid with this group
```
!TZzwZjossa4FnBe27UDpaIREJyFWgdTzggShk8m29dYiKkGABHKwDyB6h43(MzvsGUTeTm2Xgerh2Is1zwzM1xMUOLRlpvMOa)WvM4itUI(KmzTmrd)h8ML2Mpltg1Fa88l3SyHd1vE8NQxRMmzZ(p2OfwtM20nwuzYKRKjqZiwkQu5X1LjZvu)o0rEgqVo20aQIIQlZ0WbhbhxfBxX4VGzWCwjEgEuuk8SRnB5sQnw9X85RFb8h5dPINTc0vEZPprnCjElwWErM8yVlitFKm9Ijqf5VrMCnvr3DLmXd7FILUYgOFiowuD9HAoIXEo0EYkZNVXaEd)3xaZ3NO7hHBTP8rGCB)rJKjgkRP(TvJITwiiUU)OBhC3iSypJ9Zz(AsH3Jtff(7MACjfuUQPU3AJ9YoBfnMNJ84gOi3HQV4wtgUoMm8RxJ7C6SLWSSx)Xt7pbf7UkOKvEmuBDtf(EORIomLBGpU2t3LTtSYlprXGSqnrHQ6koITlMXsDyTD1K7gEvSkPXa5UkuYMeT32eAuIcXfz8cxi0nsuU1twzmH9COpkMFGIHhf1DqTnRKRm2psmE4wHbBTIlv(sOgQWqWL7QMglyl91hmT1qTeHURnDjm)e7WABGTEMQy4iR2mhmcU10HXxb(FEKIdo2MGwUFj8P8i2AqdCEWW7VKdSg81Rn4JOgODJv4rrHouyYb6Qq)TwHzu8AVZ(Qy13nSL7qdUTETG1abwpC1wqJ3rLAObcDUudwbgUdGnrtqIn5IRgEhbuf5l2XTcKLbUoQ3gw)2QJOglbJYXsTH(31u9jWyNRf3Tg3vdkYUemReEz(lMgwzOZwydgEWMUIRcFttXqDLP9aSuX(dP3K(9hJ(hCHxCJvGxhuRb70n)N7gY(RF4A3WmO1(2xbwu4(218v8uL5CDyUjc38SfFbRXc1RqBP2gk6)zWkaxHGiHB6dsp0uANBSL6GZ15PUIDPV4wFGj4ld1zfYPKRbET6BGtmnu9f)CJylGDUPBwlJLi4YX0wmPg0TZxA1ODR6TA2UXxAk1vEXNAjbEFWxowI)ZM78uzQRz(Sb5zMf34Hlr)Tb3OTUZzpnY9bOkEoUMRNcZQ7S0qtmIN)VdACFTLuueWabjFfKJREFN0YK6TB2QzlHx)axV42FNonfgfUQROoLYdo6dXfMtUmlC6K9jaqfhddjF9cTr4UVh37Z8x5eOOh5al(Bm03GDu8JMCOFfDO8Oky4XDrS)qUgIHnquCz8JUclogAOQa6IO(Y)A7SERmDOgBNzUy7S(6EGLpSRs6r1PoUmf9TZUapkznot87hq4yQRydvFTL5ZuB(7GDU1Zzg0FxiKfINrWRDY4WpFLGhxXqNfUS1GQAzoqmDuHD4bHHg8TiAG2nYKb2SFSD2F4POH(h2oBQVf39bge1YY3BgEed71mKVxU5ZeUeNF8XlWJFUgQEQBTsrim4pERNUd1V(x4Fid84xfUUWAmWZqfwrWpXH)mlBZL2uhN)52z85g8BnQURY5B)1TZ2ot3uf33uWdK3o7FVD2UgSD2FF7Sg8FclVvF2ID(2zFcQG)N2o7xG373n2uxpBd)Hy7S)buTZeveoR)mEVFoV46N)lqBWonywaU93(Rcns(8F3rOIvTLybZvy5hSo3)1BIiIGDIp3oBP(g(o1l8FYB9RiLUp4HhWhWgCFWdp8gk5UVyIUZeZiENw)8Z3nxltRFiO172b4ksxYvKcF0ohhKYLCbsxW75NHpAblwQBWwue2GcP97MZHTW(nAN1JFSYCFBszYFZIZkO4I9pxxiqOd(IvzobyR8d18pIA6n3gYMEGUYsyICZDthnCCFGeHYwUcmKLGw9Dk16ceD1Dco7XU)14Fr9sdW3RysMpmSp2lkGdEp88LLaoEpL6Lzq(Mf2AweXPYuNnMCo05zaghkCJawbCJDGn9)6rnurdZpZd9dkCeCMaeMsx)TREW2f4FuCKXWXKHx1xupHQYCpxxtJBazpCAO)lwXu)o0hoiHXE(hzsF9NUBiE8K7Nef470O(UHAh(c(V0qvcJSZjnaF9WOT5QaJI5I5qb6QDkJcWSgWC9zbpkQfghiLVmeQ(8hJiwa9yHCX)vHOWKas4onBxdiWaOMo7OWG30PU0xA)LwnBwRTKuD)3eDo(dtZ14EdhrY1ev4WvhzxWniOgoV4BC(S319n9AeWt6ltEi0XL72v8TeNE9WE)2oZXWHmXmqIwUvEaQhIbEfZzxNNkQCCE6xcn64S5srOyZH3nMBrNgY7pfp9RqpGZ8xhPo80obNCCPCXPKRU0MKGLoj0zia13rO5uOhthZmgeDeK5SPzpkW0rb)ZdGoEenD)Iu7xlKMYatN2rZHdGSy8XLl3eNy2sNzlcw8Pyfel4OCPfiAbFE2WbjekGSWAQHyKdXfhnKTQm3zHofoi7gPEEA6mbhj24SyolcBCHWElea9RZgNd8A2eVLcCoROe(jzJtLYPsqKdJBfnUQpgyXzNm2i87(4XjJHipqZ0jkZb2Tr(HueNBpesFvdNlY7SzZ7pxsYsF5WiSYPcKleqXjJpWS2ghIwQ6seDfkKEFtKDCQO340yNl6Du2XctCNiJXLH5odC)CZREYCyhq8hNPTzxC7ij7D2q6vfhEu6(JDIS5g(SVFB3V17B01FJ8ENS6yeuNiqfl4SKNXitdZIgLH8u(QRI8vN9F0Gdlz1L)VIK4y3uJy(ThzpvSXQaA)yMq7SqQF3sODkbcLk0EkW9vcYE8SzMa17GG2JhvzkbdeLmVGm9XHGfge7P3JISFaq5sPfWr8SJMzye5XZNrQOZpSIqbShh2oE8bXPOBwEk6dewn74jlnUCUjPoSe8dAcQZLh9a5MFVZuDue1JpHC6K)LjL1ssDAlH91(GyQYmuNIl8u8wh3EniUSSCs9tL3JYF6ECY(OEspL093oWZS4fpf9tAjCpNyEIWNFWzFpwmOrcK6Gs6EQ4CvXfb5dsYUl)TJovO6sEdPRe434aVL7YfKe79GIeRO5OoofAia4K41h)7UrHVHmHy4Z6oqFlR7nK7h2ASejbSCJIM6)0ZrDbsWvyk6whnk6qs5dJDoUYCc(5OAjh5lcDJADK62(0DH()7Ul0z5Uk1OcFJZF8P7Vqw8t7sf8bD9foHU)ZEhNZp19hH8hhp8Z4b1MmCZQm3XPDPU2hD5XnhO5rP8X6(zN3xEX3HBRDKOeYalpCo6kl9CYB4qw3m5dl5X5aq)kuHvnr9bKy6wPslhnZ3XdDPiOYCEBZgp8sJ6lDV4pNKK3E)LHjXL9PW3l62v(9IoeUCXVd0v6TXiD1Zt3C6t3C6msdD9AnKAvVsV70OXlPZF0DQZQ5NDD7k6(BCkVUvbC4PV5LvYTPoVV7LLkXUrcomAWohuEDt97uyi8IG0M82swNzy2FKXR)yCfVllEDe(3kkR3L8kEN6)7kCq3qJSqqpw3uJ3KRNR)GKnfD7OyQPDhk(P)YfMzgXEDe60(7recJgQXtWlA2axXY)V)
```
The issue seems to start to happen when 2 animations happen at once

https://clips.twitch.tv/LightAwkwardGoatWTRuck

**Closed** 2019-06-20 15:24 UTC
Labels: 🐛 Bug
