### ISSUE TITLE
Feature Request: Sound Picker for Custom Options

### ISSUE THREAD

**Issue by Peter-Day** [WeakAuras/WeakAuras2#2440] opened 2020-09-02 08:06 UTC
Since we already have sound file pickers in WeakAuras, could be a nice thing to add them as an option for Custom Options. We can already allow sound file inputs through text inputs or dropdowns, but a built in way would be an easier and better implementation.

**Comment by emptyrivers** [comment] 2020-09-02 09:37
Duplicate of #1102

**Closed by emptyrivers** 2020-09-02 09:37 UTC
Labels: 🎨 Feature Request
