### ISSUE TITLE
Cannot use "%" in the Display text immediately after a variable

### ISSUE THREAD

**Issue by undidish** [WeakAuras/WeakAuras2#210] opened 2017-06-18 12:02 UTC
I have an aura which display a percentage from a custom function
`%c%`
It used to work but now it returns a nil if i don't insert a space like this
`%c %`

**Comment by InfusOnWoW** [comment] 2017-06-18 12:48
Yeah some unexpected change. Will be fixed soonish.
Also duplicate of:  https://www.wowace.com/projects/weakauras-2/issues/980

**Closed by InfusOnWoW** 2017-06-18 12:48 UTC
