### ISSUE TITLE
Lua error in dynamic group with condition effects: Sound and Run Custom Code

### ISSUE THREAD

**Issue by jcai1** [WeakAuras/WeakAuras2#220] opened 2017-06-28 07:27 UTC
What steps will reproduce the problem?

- create a dynamic group containing two default icon displays
- in the first icon display, add the Condition: If Trigger 1 [Active] [True], Then [Sound].
- in the second icon display, add the Condition: If Trigger 1 [Active] [True], Then [Run Custom Code].
- select the dynamic group.

What is the expected output? What do you see instead?

A Lua error occurs.

```
1x WeakAurasOptions\ConditionOptions.lua:132: attempt to index field '?' (a boolean value)
WeakAurasOptions\ConditionOptions.lua:132: in function <WeakAurasOptions\ConditionOptions.lua:130>
WeakAurasOptions\ConditionOptions.lua:442: in function <WeakAurasOptions\ConditionOptions.lua:211>
WeakAurasOptions\ConditionOptions.lua:1106: in function <WeakAurasOptions\ConditionOptions.lua:815>
WeakAurasOptions\ConditionOptions.lua:1506: in function `?'
WeakAurasOptions\WeakAurasOptions-2.4.5.lua:6098: in function `ReloadTriggerOptions'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:715: in function `finishPicking'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:751: in function `PickDisplay'
WeakAurasOptions\WeakAurasOptions-2.4.5.lua:6880: in function `PickDisplay'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:301: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:276>

Locals:
data = <table> {
 grow = "DOWN"
 controlledChildren = <table> {
 }
 disjunctive = "all"
 yOffset = 0
 anchorPoint = "CENTER"
 activeTriggerMode = -10
 space = 2
 background = "None"
 actions = <table> {
 }
 radius = 200
 selfPoint = "TOP"
 align = "CENTER"
 rotation = 0
 height = 63.999938964844
 load = <table> {
 }
 animate = false
 border = "None"
 regionType = "dynamicgroup"
 sort = "none"
 expanded = true
 constantFactor = "RADIUS"
 borderOffset = 16
 id = "!TEST dgfail"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 width = 64.000122070313
 xOffset = 0
 numTriggers = 1
 untrigger = <table> {
 }
 animation = <table> {
 }
 backgroundInset = 0
 trigger = <table> {
 }
 stagger = 0
}
object = <table> {
 samevalue = true
 property = "sound"
 referenceCount = 1
 references = <table> {
 }
}
variable = "value"
subvariable = "sound_type"
blueString = "Differences"
normalString = nil
(*temporary) = true
(*temporary) = "value"
(*temporary) = "attempt to index field '?' (a boolean value)"
```

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

No, but I am fairly certain this problem is internal to WeakAuras.

What version of WeakAuras are you using?

2.4.5

Was it working in a previous version? If yes, which was the last good one?

Not sure.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

Please provide any additional information below.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by emptyrivers** [comment] 2017-06-28 15:19
If I'm not mistaken, this is a duplicate of [#986](https://www.wowace.com/projects/weakauras-2/issues/986), which is fixed in the alpha build.

**Comment by InfusOnWoW** [comment] 2017-06-28 16:53
Yeah I would say so too. We just tagged a release. Update and try again.

**Closed by InfusOnWoW** 2017-06-28 16:53 UTC
