### ISSUE TITLE
[Suggestion] Mass duplicating/moving of auras

### ISSUE THREAD

**Issue by sMteX** [WeakAuras/WeakAuras2#254] opened 2017-07-22 23:01 UTC
Hello. Not really a problem I'm reporting, more of an idea. When dealing with larger amounts of auras, one might find handy to Ctrl-click to select several auras and then move them around, perhaps to a different group, or duplicate them all with one click instead of doing it separately. Definitely not gamebreaking, but a nice quality of life improvement if that would be possible. Using latest 2.4.15 version.

**Comment by InfusOnWoW** [comment] 2017-07-22 23:07
Duplicate of https://www.wowace.com/projects/weakauras-2/issues/693 and https://www.wowace.com/projects/weakauras-2/issues/873

**Closed by InfusOnWoW** 2017-07-22 23:07 UTC
