### ISSUE TITLE
WA wont load after updateing and new patch

### ISSUE THREAD

**Issue by P1G9** [WeakAuras/WeakAuras2#1909] opened 2020-01-16 17:11 UTC
## Describe the bug
just loged in after updateing in twitch app and installing 8.3 and tryed uninstalling WA and reinstalling tryed disabling all addons  

EDIT--- works fine with out updateing reverted back to WeakAuras-216.0 gameversion 8.01
-->

```
  Message: Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua:185: attempt to call field 'glowStop' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua"]:185: in function `SetVisible'
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua"]:342: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:543: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Icon.lua"]:541: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4417: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4318: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4227>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4348: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3887: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3894: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1568: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1554>

Time: Thu Jan 16 17:49:05 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua:185: attempt to call field 'glowStop' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua"]:185: in function `SetVisible'
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua"]:342: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:543: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Icon.lua"]:541: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4417: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4318: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4227>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4348: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3887: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3894: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1568: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1554>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1623: in function `Login'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1695: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1647>

Locals: <none>
```

**Comment by Vardex** [comment] 2020-01-16 17:26
Duplicate of #1908 

Can you provide your WeakAuras SavedVariables file like it was asked in the template?

**Comment by P1G9** [comment] 2020-01-16 18:42
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4073146/WeakAuras.zip)

**Closed** 2020-01-17 08:06 UTC
Labels: 🐛 Bug
