### ISSUE TITLE
Can add third or fourth text support to the icon?

### ISSUE THREAD

**Issue by secondline** [WeakAuras/WeakAuras2#1362] opened 2019-05-27 08:01 UTC
Now the WeakAuras icon already supports the display of two text content, but in many cases this is not enough. If can add more text display support for the icon. That icon can display more information. Ideally, icon can be added to five display text support. E.g:

            ---------------
           |  1              2 |
           |          3         |
           |   4             5 |
            ---------------

**Comment by InfusOnWoW** [comment] 2019-05-27 08:25
That's a duplicate of https://www.wowace.com/projects/weakauras-2/issues/934

We do have plans to introduce such a feature in one of our next releases.

**Closed by InfusOnWoW** 2019-05-27 08:25 UTC
Labels: 🛠 Feature Request
