### ISSUE TITLE
[beta] Anchor to nameplate via trigger update breaks anchor after update

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1528] opened 2019-08-07 18:05 UTC
**Describe the bug**
the anchor is broken whenever trigger update's anchor code fires after initial one

**Do you have an error log of what happened?**
no error

**To Reproduce**
1. import https://wago.io/FRQLmNt2Y
2. discover nameplate
3. start moving -> it breaks anchor

**Which version of WeakAuras are you using?**
2.14.0-beta-2

**Was it working in a previous version? If yes, which was the last good one?**
2.13.4

**Additional context**
buds pointed this out https://github.com/WeakAuras/WeakAuras2/commit/5f15834d0dc7c444f4643ca3c3c10263f40f0b52

**Comment by emptyrivers** [comment] 2019-08-08 13:56
Duplicate of #1525. But since OP of that ticket closed it, I'll leave this one open in case we want to actually do something.

Do note that we support this particular feature natively now, so I do encourage you to drop the unsupported code and use our new features.

**Closed** 2019-08-10 21:01 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate
