### ISSUE TITLE
LUA error while in M+

### ISSUE THREAD

**Issue by Moowalker** [WeakAuras/WeakAuras2#2079] opened 2020-03-31 15:01 UTC
## Describe the bug
The moment I get into a M+ (the key actually starts) I get the error

```12233x WeakAuras\BuffTrigger2.lua:1016: attempt to perform arithmetic on field 'stacks' (a nil value)
[string "@WeakAuras\BuffTrigger2.lua"]:1016: in function <WeakAuras\BuffTrigger2.lua:962>
[string "@WeakAuras\BuffTrigger2.lua"]:1288: in function <WeakAuras\BuffTrigger2.lua:1283>
[string "@WeakAuras\BuffTrigger2.lua"]:1623: in function <WeakAuras\BuffTrigger2.lua:1616>

Locals:
Skipped (In Encounter)**12233x WeakAuras\BuffTrigger2.lua:1016: attempt to perform arithmetic on field 'stacks' (a nil value)
[string "@WeakAuras\BuffTrigger2.lua"]:1016: in function <WeakAuras\BuffTrigger2.lua:962>
[string "@WeakAuras\BuffTrigger2.lua"]:1288: in function <WeakAuras\BuffTrigger2.lua:1283>
[string "@WeakAuras\BuffTrigger2.lua"]:1623: in function <WeakAuras\BuffTrigger2.lua:1616>

Locals:
Skipped (In Encounter)**
```

**Do you have an error log of what happened?**

### To Reproduce

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, I did not. The only enabled addon where WA, Elvui and Details!

**Which version of WeakAuras are you using?**
 2.16.6-65  (Alpha)

**Are you on World of Warcraft Classic or Retail?**
Retail

**Was it working in a previous version? If yes, which was the last good one?**
Ye it was on a the stable build which is: 2.16.6

### Additional Info
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4409903/WeakAuras.zip)

**Comment by mrbuds** [comment] 2020-03-31 15:09
duplicate of https://github.com/WeakAuras/WeakAuras2/issues/2049

**Closed by mrbuds** 2020-03-31 15:09 UTC
Labels: 🐛 Bug
