### ISSUE TITLE
Start animation seems to prevent timer text application.

### ISSUE THREAD

**Issue by gotex007** [WeakAuras/WeakAuras2#5274] opened 2024-07-31 00:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Buff/Debuff icon doesn't have timer text when it first appears but will have it if it is refreshed while active. I personally am looking at sunfire specifically, though it applies to all buffs/debuffs from what I can tell.

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
No error triggers when this occurs.
```

### Reproduction Steps

1. make simple debuff tracker for sunfire on enemy target that has a preset "grow" animation
2. use sunfire on target
3. icon grows into view with swipe, but no timer text
4. use sunfire again to refresh while it's still on target
5. timer text now appears

### Export String

```Text
!WA:2!Dv1pVTTvqCBRwKc1fz1gJGIme0bJMoO)4y5uKHciklfNczlbs1i3Iwi(i5jYxe17X8EpAjLrpLPoOLUR5wGcn0paAVOmkDQJEOFa8NGEpkjB3UiY73DV7o97D3pUDJ8dZ7L37TfMrD5mlESWfE4woJi(8xC8uXeJOsvo(KZxsIvbCrRifLZKzNt8EvSubENsz7iM0QFFjO2EoH5Ib1MtzkNA1pRtDZLUCEOhFeZAencSxSXSUNpyBOlP9Lkb13heYFAFX6xFBURKXoWfat1wa9PJnTAxVztd1KiWKelihyeZOkhfr4dQPAegzii)mNYhD4xvUIaRqlw4e7Ldjk3aqAfWh1ITqM(OQRIEbyMMENtasOkWm94zNPZA9XuPsgiILWziQ9LYiim8fEYS30uwX9XMAEVAvT60ZQtvZoZtlupxEmtLVu0NChZwrGGO4I8F9vykp9wh2Z8ahmtDW)vItQAEAJVT5ueFfhKDUhv(QywAZEaHnjkVls58HDw5Vj3N6Ut0UK0awdEk3d(LTUg5FqWiHVezv8(6NVksW9fGuU6(9lF4w7mLWOytIEpYuI8O6Lj5CIWya1Larc6MYGXzWspKD1X1tZ(cjG3zEYKIoifrzdwOd2sjaMVk4EgdjuwJKk3ljxs5KdsEssPKYo9PmQmalqsrTDkEXKdXWqgqsu6cabIlw1TVBgsZMGVEq7z7LKBjA6qCh4lqsZR)shUWde94RM5sYnv7pfBXAxU8qU4BYKjZ2xTg5cQK6ec2ZxBd44x0UwVoMiGh1iom8rDdOkyJBj9nWh(pl9d5JAiGxhdm3jT)GsfoOssobwoTJf4L5ZXN10fl4snukN1wWDtpzNaQ7ags6zMRn)U1ljt93CiDhMzH2841u8Qip)UrA5scHmg6xdMP)TzktF)uNnPy(3nf2iTZdCcaQFGIyeYjE)(sSh7fbkhIsfcbt1MmCcgJtHPLP2ZCyCOIMnkV2LBirk7ryE9WrEx7P3GzRNC7LUhmGH7w2MPW77iPm)qW40QpVEs39s(r7R(V5y)KF49jDB8N2VZ(pSFVTHgBVKUzNDBUEW2H)THMW14r5WcvDT2cQUqgh4itNzDOdJ4O(W4nAnuwFUy1e8EZXxDH66vtP9)phuwWmr64K((j5JVEaarv1DIYuFC7BfZiJ35Gyry0JduQi5ZkwuldwGYl2mEmk)jpwet96seDPQakRy5shEacmFqnYO4jT((toA88(cuZa3hiksgC5mvqSHgRnoQXqLMrupvajLWRTwme3AXob1dFdNpSDMsfEIJegIxtoLlxOuHNotXDxVC8GT)1F7ZPEr33kM1NIdVFHjGIcRgFEC0NUrFTdmwDmvsWHEVatsyuajZ13PB0uHJvnZ61pZbxO7t9ZIBZ6IabM3S)KrOvxW9WJskKn5PznWfzv2zAfa6QpeC5McApvcH9tL(t(O8sNkfkxPWH5V4Vo)F)
```

**Comment by mrbuds** [comment] 2024-07-31 00:49
I can't reproduce the problem, did you really test with only weakauras enable? The screenshot you have show on Discord seems to use elvui or omnicc to show cooldown timer on icons

**Comment by gotex007** [comment] 2024-07-31 01:38
I did not but there wasn't an option to say otherwise. It's a huge pain to do that and most often not the problem. Addon devs are quick to blame everyone else too so I'm very reluctant to bother.

I have now tested it with ONLY weakauras enable and as I do use elvui's cooldown text I guess it's some problem involving that addon. I wouldn't even know how to address it though and I hate interacting with Repooc and the elvui discord.

**Comment by mrbuds** [comment] 2024-07-31 02:13
So you confirm this happen only when enabling elvui cooldown text? If so we can work with that and try find who is to blame ^^

**Comment by gotex007** [comment] 2024-07-31 02:34
Yes. When it was just Weakauras with Blizzard cooldown text it worked properly.

**Comment by AcidWeb** [comment] 2024-08-01 05:32
Issue will be fixed in next ElvUI release.

**Closed** 2024-08-01 18:56 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
