### ISSUE TITLE
Anchoring WA to LFG does not anchor on initial game load

### ISSUE THREAD

**Issue by thespags** [WeakAuras/WeakAuras2#4519] opened 2023-07-06 07:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have a WA that's position is anchored on the LFG panel. However, when I log into a character initially the WA is not anchored to the LFG panel until an event has fired from one of my triggers such as mouse click. The events
PLAYER_ENTERING_WORLD and WA_DELAYED_PLAYER_ENTERING_WORLD do not seem to work on load.

### WeakAuras Version

5.5.7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Create a WA with a dynamic group.
2. Add some groups
3. Anchor the group to the LFG tab.
4. Log into a character

I see the WA floating away from the LFG until I open/close the WA menu.

I've created a simple reproduction WA here https://wago.io/8sYmh8I6S

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/5769875/5321d7b6-abbd-44c9-ab63-f6958afe47de)

### Export String

```Text
!WA:2!fN1xSTTXz86ku0g2U1e3gx000vcT2SgSefB3gJ2aK0P)qzRuzBvkz741wiEK8K41qrYCK02YnzatRTiaddyWaddyBfRtyByyypu433aMXEzVDWyadya7fJ962dbf959DhPOKLKx(ZYW4dsK33397(DFFF3DFFKt0yYwtAoPV6fZCXmZnP5TFDA7LB0WhhmbDdm1N46KQRb2jatR12dNUS6DqogwU0IuulmVPDRQuwjFTIQzxuzhKdPfka60C5AHiofZfaAKZX1bVVziviPoVjQp2W1X0Vdg5lqHjTh)2QbuStZaRhx1pardkYogtI9KSNI9vG))QpUEdIdX3A4MvTjTibp5o(y7gvCjob5kRuS2SHuBVxWkiWZ)sx4cBIA6MH4EH3WF9wwVrP5QEHz2brnklgUpAQoH(4YCuS2v3LAIP5DTDPxDIjMiv3OgumBI9or1BeIOy5IH22YRzraZs0ugBTpkmaSll7XNK(s0TInJ68rUuHDsg4zdjM7E11QnRXQBT1zVX1paSeWS1jOiYiWLQRMTqPvQ2PjLykm5Qf0bnAqAk1nW1i2P8eBSxmVQs2g)yD9d1vXnfJCAI5(zf(i5ax5YfNNcO3SjMoHQVhYa)y7RJmUUj11lAoMkvQkPMoZfVdH7LDq2RgneFSE0aO1H6giCDtO7JBbeqDMmtNz6dIeNlgmVJNZMS92iQPCnxx7aINQVbYgNAVi9ImhhBh(8AnIzG1tc4UzvoJsLZ3LgWK2TbpOcIbqbOuDPI5d3eSNzBhulIrtQBONofzsc9)ONQlpcIeBTbth)M5YbbibsSNwIDCPDJIufre65vwQMIASZTKdqLu7A4Ah2YjMc2UiZI6baJDcMsTvimdKunSr((tXkkLZhmZr34Hn43OISjnDyz7eqjCRR)PoZoHoXpirJV5t6a6BBxY0xIDmveSgy2CHaf19SrTbljEdy40xaJSdS6AI1dB0GpJPlOuUsXvkFa4xfQufeq2A365ZwTw9Q1YQwlrufkgePwTIs5YQGDc7l1TbeFMNqnSXAEhFGfSIFoaIjQarXqeh)XCGzDtv1sZVqTDjonCPrRGLMCJ)Y1M04u3Eo2J(NbdFGnXb8IRuRCPLuyPsX0oZUGYgyfoj816WzFZYUnT8Knj(85xn8wb1JaSUx9aslC8ttKRHRtG3XlsjBl)oHitUhxUwn2JPNFLQ1wEr2Jph7jwv3JIbhvxKTNfQsOTpgwSFO1(p9WBfWo(iTmjT2Yv4Bi49YJHxgZuhPRtXBqGfX1BH26eSNLDsVxAmQA72gzh)aa9l(fs7ze6h42kA1M3)SrOJim8vpRKmCj(H04v5E96yNnYeTmotK)aCcNvoWc7iuJFLOxuK)LQIdIw0mcc2nAgj5ANt(iLT(ztqMIdcPoY1N)DtFyFF63xOdgmTYJt7vkfPCp9CmJMzWnEFZJ2lhVETEGf4aTCTnBZo9N98RsDCxetBI1yht3cJGfIQBY3jiff29DjGoA5caWOfcDAIHzdZp1Sxh327KagBMDdeXgPBJJL6dGe42SPnM37cyFdRC8OFVNRkOTCI6Y90hw43ablR144Y20BsoQLDnUo2SpKS2STTyFO3ZkajsAccSBPTk7ga7zuoebASWCQiI5GaMmUCbJayFwfj(wXK5o95Yq97edsKEDcyH1GSGwJscB5zftKtFiIO0c(P1YnI1Pp0tneL6Pqps598CCuquhS5rcYZiajsPbqyy7uN8Uo3ie7hed9lowk2tP(WpSZmrJesEQrj5OW8SdYYbWyyAQUkcosCqKhHJcnoA)AK4e29CJYUHa4edsTE9EyErxatDj(ToAhtSchHJPN0eEn(qKraz4qK(4mCiyNkU(IdJHbOsQzY8ASn3jzJUeazNf66VoNFa2tKZbFfElIZnVsotybSNmSZf4yKBqDBXZCrEtIJjqaxh5RjJ2I4Z2SB)9(Mf2To4kWXQqoynXST1yFyNRjhjKDRVq6xZ(P9ge2p7MxH9P)NWF9rWFD2NXrN9lIqE9eK)hNCKDbYAh4VbmaVBK9Yoq2WcXtkbtLTH1UWXNYdC2Ag5fHdoajnHwHK0Geh973dFEEBWH689o5NqqOYMW5JchxhHFdgTitkqS9tgYcCLUvVnbMY1XU9IOTkdjjyNpb7((2NFzqbzqdzHkYdOZT06SjKO0AuKxN1IVHDgiNtM8UVzj9R6DvCHvxUYUdCcq6xXHDL5yV1z0JotmTK0oMU1JEWkkHm2RC7tW(EASBRX(jASFJf77OX(UASFRg77RX(L)JtY(en2wASF(xiX(HASFSg7hOX(rASD08(6h9znqocgerDkSVg7LyV6PMIDS9HCJ4j5Yty0XKNqSWiDrWAsCA6R77gcjUOtA5b5Do20vouAbwEhpAEW1yfpWzGzQSZ)X77BHGWN1Jcmo9Je)81IEofBA2mDHuZWr57(rpf9dauinAZEMDJ0SFrgSlXczf(svBUR4r7AsG09mGdRAlXwGNT5(erncgyr5t8wyZFgwXP0ROwsPAnnDFyIzJz)rk8ppnzUWCu48cn2ES)uUTHsW6SmTjPvleDh4aZ6IrYIvsGoVbSJbyTa)V1bcz1DH8qrqfjPV8Lf9WbALA1LFRHBlDuGftH3BETt15dGL3lmotz)uMEZuJ1t6mskyFlw2XMc2GAA1TVtX71hk3R4CyssokAho)lvictqlEkmNE8E(e((PEAlcPPiRdRtC3UjSar2TH8BJGYCU(5HHGGSpN88UaYqbwNFn3GYVTSOKbIHKuoOEwt(wldxcAwli)OBGAmZfEnjPXZHzt4WbqzLU8Dnmebr5YcpYUSe7Tx6mSYtX(CVtnWmpEwhqdX85hBXB)ChWDoi7nrT95nRXQXwb61xM0lKTDvO8oS)5YKjtKXdgBzYLN5Cxu20njRqyBmKTmpdl5llNUHRBA5mzKj9ZEThoVlxN3hu6dtKXVGT3GDPnH2584ChsgFtTXka2EgVfiHd5HLete(FjTFRdNK6aXb9Sirvm579xRuo76kQ1fffwAP5RV2YQLlCo51YwVGcxuH6hHgRMvTu2CLvQwV8YzlOaTW)NRq18QkklvVqPQC5GaLLYV8k8UdGapgdyzLSRQup)YlMlBTKgvvMh6QYsX9m)kQQqVxNdgxJ6RuPq2AkNt(DwbwSxV2kQlbmS0sda6QkLbTyFBPDJwvi2NyxFUhjuSJLQHf246mvXQvEjOAXRF4jEV1X(vdTakYDBW3GI7VtlAmGeyJZ3RTBAuuCn90rsHOyIZasNEAUSEsTfPWoI4IfJeJ6LJXiWdAK4oJyfVibbPIBT)pN)8jjRhx91i1hnAw)YW4noTgPIJdxUwmle)L0iSKi9758EoPput9TBhsXE4EtA6rJCpcQ)asQHmV8w6boAeefK7(Hudzp5mQ3yFxz2GXfdsl7dJ5rsPE(DrTr3Dsku7U6XJ06HS7wa6dKV((Go3lo6i4Ea9Y95YdjxCeG3v)BCPh3t2RHQN5OC3JTcQh2E9i455nepaWS8qwU7RiHhuYM(UeKKUFnEYPhFuZWd99B4ZrBTVNdKUxMi5dP83yLqJdptmIKmedY2IN17Dp(tuA(9Lps0J7TyViv)FwKNa(hkXD3Fe9Hyux0a)FxmxFY))NioX4FpfV1lTvGo80wL6D1l5olIjM953j6PvrucNr(qn3I095vkAc1bwYuBp(Z6yl0gexQLOoVgrFRKsf04V7ILKyvM1dh0P33Nl9mtZu7Mp5BRWog7ZzRYwBh(Ss85foL3lViAlslY2y5k4GVHVCz(BgpOTmmSYlG88ioyFF21yRZFdbFGiXYnWZICA7DcK4(ArFDKfDnX)UhzSvn6Kub0yf7fFJk)DayQkYt9Ql8w)R)a)63NAH36V)IW1P)BP6W)sd8Vr2j5VEG)9d
```

**Comment by InfusOnWoW** [comment] 2023-07-08 23:31
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4440

**Closed by InfusOnWoW** 2023-07-08 23:31 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
