### ISSUE TITLE
preset animations override condition coloring.

### ISSUE THREAD

**Issue by krazyito65** [WeakAuras/WeakAuras2#195] opened 2017-05-21 23:10 UTC
What steps will reproduce the problem?
- create an aura with any condition to change the color
- set preset animation to 'flash'

What is the expected output? What do you see instead?
- condition coloring should stay even with the animation
- animation changes the color pre-conditioning.

What version of WeakAuras are you using?
- 2.4.2

Was it working in a previous version? If yes, which was the last good one?
- unsure

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
- no error

**Comment by InfusOnWoW** [comment] 2017-05-22 06:23
Duplicate of https://www.wowace.com/projects/weakauras-2/issues/945

**Closed by InfusOnWoW** 2017-05-22 06:23 UTC
