### ISSUE TITLE
Transmission.lua: controlledChildren (a nil value)

### ISSUE THREAD

**Issue by spamwax** [WeakAuras/WeakAuras2#2637] opened 2020-10-27 04:00 UTC
## Describe the bug
Clicking on the Update icon next to aura should bring up selection dialog box to choose how to upgrade the aura.
However it throws the following error

**Do you have an error log of what happened?**

```plaintext
12x WeakAuras\Transmission.lua:1305: attempt to get length of field 'controlledChildren' (a nil value)
[string "@WeakAuras\Transmission.lua"]:1305: in function <WeakAuras\Transmission.lua:1255>
[string "@WeakAuras\Transmission.lua"]:1704: in function `Import'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:815: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:812>

Locals:
data = <table> {
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 xOffset = 0
 groupIcon = 132347
 anchorPoint = "CENTER"
 borderColor = <table> {
 }
 url = "https://wago.io/BJqUUcobz/100"
 actions = <table> {
 }
 triggers = <table> {
 }
 internalVersion = 38
 animation = <table> {
 }
 desc = "Displays cooldowns of primary abilities. Includes lust. Made by Titâniâ @ US-Sargeras"
 version = 100
 load = <table> {
 }
 backdropColor = <table> {
 }
 scale = 1
 border = false
 anchorFrameFrame = "WeakAuras:Titiania's Warrior Duration Bars"
 regionType = "group"
 borderSize = 16
 anchorFrameParent = false
 ignoreOptionsEventErrors = true
 borderOffset = 5
 semver = "9.1.2"
 tocversion = 90001
 id = "Titania's Fury Warrior"
 borderEdge = "None"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 selfPoint = "BOTTOMLEFT"
 uid = "7rNrLEgwttH"
 borderInset = 11
 authorOptions = <table> {
 }
 conditions = <table> {
 }
 config = <table> {
 }
 yOffset = 380
}
children = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
}
target = <table> {
 authorOptions = <table> {
 }
 preferToUpdate = false
 yOffset = 224.242356
 anchorPoint = "CENTER"
 cooldownSwipe = true
 customTextUpdate = "update"
 url = "https://wago.io/BJqUUcobz/78"
 actions = <table> {
 }
 triggers = <table> {
 }
 internalVersion = 38
 keepAspectRatio = false
 selfPoint = "CENTER"
 desaturate = false
 version = 78
 subRegions = <table> {
 }
 height = 80
 load = <table> {
 }
 uid = "i55gAWEnWWD"
 zoom = 0
 animation = <table> {
 }
 regionType = "icon"
 color = <table> {
 }
 cooldownEdge = false
 displayIcon = 132333
 xOffset = -2.525302
 ignoreOptionsEventErrors = true
 frameStrata = 6
 cooldownTextDisabled = true
 auto = true
 tocversion = 80205
 id = "Battle Shout Tracker 2"
 anchorFrameType = "SCREEN"
 alpha = 1
 width = 80
 semver = "1.0.78"
 config = <table> {
 }
 inverse = false
 icon = true
 conditions = <table> {
 }
 cooldown = true
 stickyDuration = false
}
oldParent = <table> {
 authorOptions = <table> {
 }
 preferToUpdate = false
 yOffset = 224.242356
 anchorPoint = "CENTER"
 cooldownSwipe = true
 customTextUpdate = "update"
 url = "https://wago.io/BJqUUcobz/78"
 actions = <table> {
 }
 triggers = <table> {
 }
 internalVersion = 38
 keepAspectRatio = false
 selfPoint = "CENTER"
 desaturate = false
 version = 78
 subRegions = <table> {
 }
 height = 80
 load = <table> {
 }
 uid = "i55gAWEnWWD"
 zoom = 0
 animation = <table> {
 }
 regionType = "icon"
 color = <table> {
 }
 cooldownEdge = false
 displayIcon = 132333
 xOffset = -2.525302
 ignoreOptionsEventErrors = true
 frameStrata = 6
 cooldownTextDisabled = true
 auto = true
 tocversion = 80205
 id = "Battle Shout Tracker 2"
 anchorFrameType = "SCREEN"
 alpha = 1
 width = 80
 semver = "1.0.78"
 config = <table> {
 }
 inverse = false
 icon = true
 conditions = <table> {
 }
 cooldown = true
 stickyDuration = false
}
info = <table> {
 deleted = 0
 newData = <table> {
 }
 modified = 1
 added = 0
 indexMap = <table> {
 }
 unmodified = 0
 activeCategories = <table> {
 }
 mode = 1
 diffs = <table> {
 }
 oldData = <table> {
 }
}
hybridTables = nil
(*temporary) = nil
(*temporary) = <table> {
 authorOptions = <table> {
 }
 preferToUpdate = false
 yOffset = 224.242356
 anchorPoint = "CENTER"
 cooldownSwipe = true
 customTextUpdate = "update"
 url = "https://wago.io/BJqUUcobz/78"
 actions = <table> {
 }
 triggers = <table> {
 }
 internalVersion = 38
 keepAspectRatio = false
 selfPoint = "CENTER"
 desaturate = false
 version = 78
 subRegions = <table> {
 }
 height = 80
 load = <table> {
 }
 uid = "i55gAWEnWWD"
 zoom = 0
 animation = <table> {
 }
 regionType = "icon"
 color = <table> {
 }
 cooldownEdge = false
 displayIcon = 132333
 xOffset = -2.525302
 ignoreOptionsEventErrors = true
```

### To Reproduce

1. After running weakaura companion to see some updates, go to game open WA (/wa)
2. Click on WA upgrade icon
3. BugSack shows the above error

**Screenshots**

This error also appears next to _any_ icon (not group) that I click on after closing/opening WA's option window.

![LTc0QtBA8a](https://user-images.githubusercontent.com/1251233/97255225-8e2a8400-17e6-11eb-8786-70cc829765d1.jpg)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I did but since BugSack was disabled, I couldn't see the error message, However the warning icon with `Forbidden function or table: loaded` still happens.
I even deleted all my weakauras and tried it with one aura only.
**EDIT**: Having only WA, BugSack, BugGrabber throws the `controlledChildren` error.

**Which version of WeakAuras are you using?**
3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I believe so

### Additional Info
Not sure if it's related to this bug, but updating the auras (that don't throw this error) by clicking on update icon is useless since the next time I login all of them are marked again with the update icon!

**Comment by InfusOnWoW** [comment] 2020-10-27 08:53
We need your WeakAuras.lua file from your WTF folder-

**Comment by spamwax** [comment] 2020-10-27 09:36
Here you go: https://gofile.io/d/AkEaVn

**Comment by spamwax** [comment] 2020-10-27 09:48
The url (https://wago.io/BJqUUcobz/78) in the error is for a WA that I am pretty sure I had deleted a long time ago and don't have it in my current set!

**Comment by spamwax** [comment] 2020-10-28 11:47
I am also getting this the 1st time I open the config window after logging in:

![image](https://user-images.githubusercontent.com/1251233/97432031-b652d980-18f1-11eb-98e8-a56165a097a9.png)

**Comment by InfusOnWoW** [comment] 2020-10-28 21:10
I can't reproduce the issue with your settings. Only the "Multi-Class Power Orbs " aura was outdated and updating it worked correctly.

I looked at the relevant code and can't see anything that should match.

Are you sure that this is the right error message?
Also which auras are showing a update icon for you, and which one are you clicking to update?

**Comment by spamwax** [comment] 2020-10-29 08:31
In my settings, do you see an aura for Battleshout Tracker 2? for me it shows as needing update. (I am re-attaching [my WeakAuras.lua](https://gofile.io/d/8ZlbmP) just in case)
That's the one causing the `nil` error when I click on its update icon.

That aura was part of "Titania's Fury Warrior" aura group, I had moved the Battleshout tracker out of the group and then deleted the entire group. So my guess is that WA Companion sees the update for entire group but since I have only that icon it causes the issue with `Transmission.lua` when trying to import the update for entire group

With the weakaura linked in this post, I see updates only for the Battleshout Tracker 2.
Do you think resetting Compatnion's cache can remedy the issue?

**Comment by mrbuds** [comment] 2020-10-29 13:01
You seems to have 3 bugs:

- `Forbidden function or table: loaded` : deleting Zen Tracker and all associated auras should fix it

- `12x WeakAuras\Transmission.lua:1305: attempt to get length of field 'controlledChildren' (a nil value)`
This is a duplicate of https://github.com/WeakAuras/WeakAuras-Companion/issues/68
Workaround is to ignore all updates for this aura from the right click menu.

- `WeakAuras: Warning for unknown aura` message in chat
Can you include `World of Warcraft\_retail_\Interface\AddOns\WeakAurasCompanion` ziped folder and `World of Warcraft\_retail_\WTF\Account\ACCOUTNAME\SavedVariables\WeakAurasArchive.lua` ?

**Comment by spamwax** [comment] 2020-10-29 13:19
- How serious the `Forbidden` error is? Affects frame rate or performance of WeakAuras in general or causes crash... I am asking because some of Zen Tracker auras are pretty useful in dungeons.
- Ok
- Requested files: https://gofile.io/d/NMRFIe

**Comment by InfusOnWoW** [comment] 2020-10-31 17:12
You need to get a upgraded Zen Tracker aura. The "Warning for unknown aura" is probably due to Zen Tracker too.

**Closed** 2020-11-01 02:09 UTC
Labels: 🐛 Bug
