### ISSUE TITLE
Add X/Y Offset options to Text Settings

### ISSUE THREAD

**Issue by Jalopyy** [WeakAuras/WeakAuras2#1177] opened 2019-02-11 10:22 UTC
Right now the only way to customize the exact position of the text settings outside of the generalized position and inside/outside is with lua. Would be nice if the two Text Settings have X/Y sliders to better position things exactly where I want to, like a corner. It's basically impossible right now since the bigger the font is, the more the position changes.

**Comment by emptyrivers** [comment] 2019-02-11 11:03
This is a duplicate of https://www.wowace.com/projects/weakauras-2/issues/550. It’s also in progress at #913.

**Closed by emptyrivers** 2019-02-11 11:03 UTC
Labels: 🛠 Feature Request

**Comment by emptyrivers** [comment] 2019-02-11 11:05
At least, I think that branch has text positions included. I’ve forgotten, now.
