### ISSUE TITLE
Condition - Border X - Show Border partly broken

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1853] opened 2019-12-14 09:12 UTC
## Describe the bug
I expected a border to appear when adding a border element, unticking Show Border in display, and adding a "Condition - Border X - Show border [x]" condition. But it doesn't.

**Do you have an error log of what happened?**
no error

### To Reproduce
1. Make a new WA and add a border to a that WA
2. Untick "Show Border"
3. reload (otherwise condition from step 4. will work)
4. add a condition - active true then show border [x]
5. make the wa trigger and see how it doesn't show a border
6. (optional) repeat steps 1-5 but this time don't reload in step 3, notice how it works fine

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
2.15.5

**Are you on World of Warcraft Classic or Retail?**
- [x ] Retail

**Comment by InfusOnWoW** [comment] 2019-12-14 20:24
I can't reproduce that. Can you export a aura that shows the problem?

**Comment by Causese** [comment] 2019-12-14 20:30
`!nwvZYTTnq4NMmj9q1iXA32RYQYnUJcLJaDBYfkbscsIyiaf8JKLpON9U7csjANdXZOHcyXI9B)5BxKpjplNTnNvH)GLnkZH8IC2tlRRDcFE64C2XbR56YwJ9EJu7ZzZMNMnFvoR0yuvMdA2b5or(nxemVQrGwtwA0OCVv20iSoaPuc5ob4snFRapaSR)iygMZZ9bxol4eR5Qd8JoVnqMpOf7fOdWdEtuHGw6PJqLlCgBXNmvKYGvD8gXAZoHL7n2CwTux9H3)o37)f0uW9y7u8JGx0RBodqpuqGCVvulFkNXUF(IfG4DcL6UQohTkaMucXg76i09gaI5oxCMrxjrDCxSjlut2C9SPSS1SSPRG4VsuaIZOq)JZxC)TpSaHiOVKJ8OaEPxUxKffsbz6VozmEcutewnx9VqggDQ0KRIf0V8IcOCB0NZOuS1Jl6dK1DPEbuWGGSRsOnAbcWwUu)21gsZsx7BwFmDkCqjh0LsGONpZOm2iBb)LqF)n67v4xpLuxjAOe8zwL4j)AxlV6LHEh6Hc88oTIlFNRBB5phpsVAdwBV1kF(0Mph4vGpZpTj7Lyp05htgBmzSXVYyrT)6qpLelu1DnAtFiB5aKJKKLpKT4U05DY3lDYcfX4P9VOr9U005RwFZYSSLFA1D)9hZ6BK)bq)wW5L1hV0BFguM8zGQnjP)QdZSwd0RkYOCz6sWN8y4MniLxySvyhw8)1oYyjN3)gY7DA2hNfNLiWHmm23dCR40MBdk1Pn)xReir9Ayo7PenRviBAHT)o0EOmCAUh0xxsJcdkVSVvRuXDUFqk57VsOpsxV1k(EqOlpcynk56OWy1Qi49g9Y9clmRP7Gwz5JAyIbgHmVPCFFJ7FoozmCBlXRJ3NgHId8Gu)YD(o(UNg7CPtbYkpke7MIHJFf20HIWrgr9p3XpS)KgDi9NhWqL3BTW84i0SzRMppfqscVs8Hppv9L)Ov9p29xMZJv()s64qHPcb8GSY3gtWpBmBJdEWz13eJCwjxjOOgnzQ4WPniVsTRLtsRrWHhhGUkApENHu13aDbsx1YM(OdZSeNzqtvpdhn(cHUb94jKXppXUFGszRO8XHVxHo1EUvIrmy0w4rtyVki6rVLRBexmq8mi63zX3H8hPMIrjJEfR2pKnTqcKdGme3DtSdQGOG5SKrtUEeWr2diCvccA()d`

**Comment by InfusOnWoW** [comment] 2019-12-14 20:33
Ah well, seems I can reproduce with 2.15.5

**Comment by InfusOnWoW** [comment] 2019-12-14 20:40
That was fixed by b4f391590a9c9db27f4ada365884d451c99b7257

**Closed by InfusOnWoW** 2019-12-14 20:40 UTC
