### ISSUE TITLE
Failed updating aura with companion app

### ISSUE THREAD

**Issue by aegius1r** [WeakAuras/WeakAuras2#1108] opened 2019-01-17 02:27 UTC
**What steps will reproduce the problem?**
Try to update the aura "Uldir - Raidframe glows - Omega Vector 1 stack (mythic)" (https://wago.io/Uldir_GlowingFrames/24) via WeakAura Companion.

**What is the expected output? What do you see instead?**
It should be updated (like the other auras that work well with the companion app).
Instead it gave out error messages.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
2.11.0
(WeakAuras Companion version is 1.0.19 btw)

**Do you have an error log of what happened?** 
1x WeakAuras\Transmission.lua:1207: attempt to get length of field 'controlledChildren' (a nil value)
WeakAuras\Transmission.lua:1207: in function `MatchInfo'
WeakAuras\Transmission.lua:1727: in function `Import'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:759: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:756>

Locals:
data = <table> {
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 xOffset = 0
 yOffset = 0
 anchorPoint = "CENTER"
 borderColor = <table> {
 }
 url = "https://wago.io/Uldir_GlowingFrames/35"
 actions = <table> {
 }
 triggers = <table> {
 }
 internalVersion = 11
 selfPoint = "BOTTOMLEFT"
 version = 35
 load = <table> {
 }
 backdropColor = <table> {
 }
 scale = 1
 border = false
 borderEdge = "None"
 regionType = "group"
 borderSize = 16
 expanded = true
 borderOffset = 5
 semver = "2.0.0-35"
 id = "Uldir GlowingFrames"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 animation = <table> {
 }
 uid = "BMvDBy(qsiq"
 config = <table> {
 }
 authorOptions = <table> {
 }
 conditions = <table> {
 }
 cooldown = true
 borderInset = 11
}
children = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
}
target = <table> {
 outline = "OUTLINE"
 glow = false
 text1FontSize = 12
 color = <table> {
 }
 displayText = " "
 customText = "

"
 yOffset = -36.000031
 anchorPoint = "CENTER"
 customTextUpdate = "update"
 automaticWidth = "Auto"
 actions = <table> {
 }
 triggers = <table> {
 }
 text2Font = "Friz Quadrata TT"
 justify = "LEFT"
 animation = <table> {
 }
 xOffset = -542.000092
 url = "https://wago.io/Uldir_GlowingFrames/24"
 wordWrap = "WordWrap"
 text1Containment = "INSIDE"
 fixedWidth = 200
 font = "Friz Quadrata TT"
 version = 24
 text2FontFlags = "OUTLINE"
 height = 11.999958
 text1Enabled = true
 load = <table> {
 }
 stickyDuration = false
 config = <table> {
 }
 fontSize = 12
 text2Containment = "INSIDE"
 text1Point = "CENTER"
 text1Font = "Friz Quadrata TT"
 width = 6.999987
 frameStrata = 9
 text1FontFlags = "OUTLINE"
 regionType = "text"
 internalVersion = 11
 icon = true
 text2FontSize = 24
 displayIcon = 841384
 text1 = "%n"
 zoom = 0
 desaturate = false
 text2 = "%p"
 auto = false
 text2Color = <table> {
 }
 id = "Uldir - Raidframe glows - Omega Vector 1 stack (mythic)"
 text1Color = <table> {
 }
 text2Enabled = false
 anchorFrameType = "SCREEN"
 cooldownTextEnabled = true
 uid = "t8Hhv82(1fu"
 inverse = false
 text2Point = "CENTER"
 conditions = <table> {
 }
 selfPoint = "CENTER"
 authorOptions = <table> {
 }
}
oldParent = <table> {
 outline = "OUTLINE"
 glow = false
 text1FontSize = 12
 color = <table> {
 }
 displayText = " "
 customText = "

"
 yOffset = -36.000031
 anchorPoint = "CENTER"
 customTextUpdate = "update"
 automaticWidth = "Auto"
 actions = <table> {
 }
 triggers = <table> {
 }
 text2Font = "Friz Quadrata TT"
 justify = "LEFT"
 animation = <table> {
 }
 xOffset = -542.000092
 url = "https://wago.io/Uldir_GlowingFrames/24"
 wordWrap = "WordWrap"
 text1Containment = "INSIDE"
 fixedWidth = 200
 font = "Friz Quadrata TT"
 version = 24
 text2FontFlags = "OUTLINE"
 height = 11.999958
 text1Enabled = true
 load = <table> {
 }
 stickyDuration = false
 config = <table> {
 }
 fontSize = 12
 text2Containment = "INSIDE"
 text1Point = "CENTER"
 text1Font = "Friz Quadrata TT"
 width = 6.999987
 frameStrata = 9
 text1FontFlags = "OUTLINE"
 regionType = "text"
 internalVersion = 11
 icon = true
 text2FontSize = 24
 displayIcon = 841384
 text1 = "%n"
 zoom = 0
 desaturate = false
 text2 = "%p"
 auto = false
 text2Color = <table> {
 }
 id = "Uldir - Raidframe glows - Omega Vector 1 stack (mythic)"
 text1Color = <table> {
 }
 text2Enabled = false
 anchorFrameType = "SCREEN"
 cooldownTextEnabled = true
 uid = "t8Hhv82(1fu"
 inverse = false
 text2Point = "CENTER"
 conditions = <table> {
 }
 selfPoint = "CENTER"
 authorOptions = <table> {
 }
}
info = <table> {
 deleted = 0
 newData = <table> {
 }
 modified = 1
 added = 0
 indexMap = <table> {
 }
 unmodified = 0
 activeCategories = <table> {
 }
 diffs = <table> {
 }
 oldData = <table> {
 }
}
hybridTables = nil
(*temporary) = nil
(*temporary) = <table> {
 outline = "OUTLINE"
 glow = false
 text1FontSize = 12
 color = <table> {
 }
 displayText = " "
 customText = "

"
 yOffset = -36.000031
 anchorPoint = "CENTER"
 customTextUpdate = "updat

**Please provide any additional information below:**

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 

**In case you do know which aura is problematic, please export the string and paste it below.**
!fVvZYTnYr43fU1wlOmef)rswsPSRIsIsMoAjviOSQu2gKGedjNvqam4hAr7Y8EY58aKlPYHCkvUMxNuj5TiDpdWGb)XFK3TwjxYKd6UNE6(R7PNzWOxtVVUgvVtTghxRrdDnpDT6vQvRsvDTh11mX)be4e4BrTj6ADVR)nT70sxBQLZN0hPR5tEYV2vo2(A0ptaXuxxBSJLJlWvNAS)vN93gS)Ei(xFqOuV5wgl7dmRRTAiWtGNVZJHF)TR7xDTLDNmXJ4R3z)ghxPk8tJQhv7Lh9Yt01mShpZX9whQniNlA1PFREYY(U5Mg(WOii6)DT01M57p37Sdo4tgtDQqDo4oltQ7GRHXh1E6vUgps8oO(HGSh7tDS9qZHNVHRp(bUO11SCgByTA4eK6vdF1QHgbUgdi2lQCnXNjdfrlaZ(Kk2qBLx9w6ebx(Zi2WaCi)3ybakIcJevGg3aKlIn6yCge29NJMuQnnHkT)(RgYhNRgw74dQE6QHqlBXGfnYHJhUSgG(A2O6lX6hX2yKfFSoXWI4Pg9GT7xM25rI6Ivd59HN)suOtCXMUKq(StCp6smzDxn142M6saJw6whzfqY0OH18zgzATdVLd3r1p7GXo4Xre3vdDah6CaDqhJdKPUobZ9wnuHymEw8xhdXlguB4thgtTx5y1AIl5peqShVKPEvR04zyE9PiQAIdOuJOtNs88L1mFhenzSGaUzdqTSnrl8uaHhRfEaiqyiF2wMqPiBy8I7JN4bZ8XPKJzPC7RE7x5b)7h9dGo62P)QHTUSn83ZBDt37XEl(ho1Rggf)jHQzbtdM7sDCP(ltdSrMCnOMH0jPQVV2hzexA1xFNzTsQCAxemZucL((6cIEdXWAKJFeHZ4FvI0gcsV2LAEJXsinBe1tHwKi9WeKwplT1Li(ibXTSwC3vd6bdNRrOxedeRfsKFSGChG4rMyper5iZukYlLjUYEOLsOgeBIlDm4QV7kjoorWXnaImHEyrzoMikpvqP2DxbwptIRS89cMi7mQkO(cNhNdzN7jr7il6N)CsNkc(wMNxTw2ULrlxwP616PST3IuUgJBTgjnyssUqlwTyV9Tu)ZdSSoCaRl84Dxe7ZP(JWhkZ6rPTkj4ipZcmpmM4AsyuIqshlBwUdMDHtzjvzIEzwnLplYGBZH6tsB8YHMttzVYss9yppxaSEejHLL4(MdIc69Uas7YZGLtRyMXV8v(CW2qGzwAUH65JUO0toVgcHU6cxcmRlFw)sCDtk1EusO81kHGINk4SEqAzOv3wli2(kLU9MM)(w9g0R11T6m4Y2Anp)Mwxk3dRNJwD2mdx3R7D3oOxxnO(Pb3D7Ln73kj9AeFTXU05aTDTzmHiSjb2SAKu8iwtGVtWha)FLkvK4o9V57VqhtCTgM8IEKtIh2xXz49uGQYMs8ZXwlO9kQT55b((qDCx54IG64sRsZCkH4s8cS89YOCr)IOi)LZjCbwgOdHO(yvsLGPyX5xzGm2JpRn2)JOMMeBLYPHxfObO05fCXebmU7o6NiJ97J96AmWrAwOkXrKC4VuZCZsPnPlcmaY(a1XZOwWiJc2w6CdQRNYxeA3f4ZCXb4xHHO8KKBPWxWfmxU546yDESRBh7KOF9HcXiU(kHoyqElkV9sHJk)wiATpmLVBhDsHaNaWyLe40033LokWNO8d4d)HTyaJAcxqmSCem(DupkaXrqSu7qx0bt)vEB10ctg8EMa5j8zD)wlkuHrysBpgybzwkmFh1ReZy6sXKKxDglNxYXB5FoWFHzq(1gdMBJUe)ax740HVnFQFRSxGL3dDcTEcMLjopDb(arMubDmSVhazTNgLlL)SZMazfGj44fjSrVkNjgwcMIcsDQCSk464S32EIZ5lV(U2xQisOK1My5r2k5hQFt9cgPa6CL9qWsPsBin9oAPkY5K38tBVRg)YW88LByMqww7OPt5PkItFNjWUGS17VFy4fFpagJKULbAFtb8InIj)0JmiiFmTDUIDpQE9qRyx86ldj9VJGIrF4BfnKdwicQ9Dcf614c15bNI2qerotCFxByvj8AdfLDLS8oQhUcH2SHzBVMMMDTVXbwzgeSZEagiLP6U7NTeEi8xL02A07kez88u5pNvysLOfPukXuBvWv17pRiyqKzjbTVD9U4e8KYWhAvw924rz2TwSW6E5l1fTHRPizrENiYzJmHwztTsbcyX50xvt97sVtk5fqhwlxO9ooHaV32qnBOUPKoYN7Fs23VN(XDolzXWLVXOKc6aV3x7JLLCPHEPMb(oxy45RnJAt4Xfxj2h5cwlzU82N80Toows8H75DGlbBvP4UrTuZE9VVBVFBj1xghwXEiYzpIhX3pCTTIL4nj6XQPnEC3vIviY339sQawklkDotxswFkx)usHs5uwP5fSXqrU70u9kogoNzAeAAy3vKjQCb(zXCgv8Go9blrWt(bbaQL8eKYlK4mbdcPSHGI8C6Wk4TigEeLqzuExWRPhdPNxN9yC7KDdFyvv2VPP5S3qntSsuERxaAMBtll2XY4PefcKhewa6sd(zq4Waa1I8ti(sndUTCYOnoSyqeOmjQMTXfelJ5EeZSi1prn9NPoJqNotue5eeUIN9LsoiBIly0IcDQVNctaVGlGSKpYbMK8rl6JmY5uTx9xWykBry4ttsBbuc(1X8HPqFoav8kDsLs)bvMpwgxYOJ75laukrX7FGVmn23ErOvSGY75D0Rd5hvmhZ9EyJ1VZzlQp(ELeCxElxcJy(RqRWAd2ICL8dkI(cop7P8W(1kVzUC8O8jTbEvyoI9OVq4g2Jnkoi1OO83hJBw7eJrs)1saNTBgqwhgfV)(5D(4zRgIPbDyvEZp30smZJAPZ72VF3FSx7RFt)sQ7h1NVq0NQv3qnTju1yy7p)AA)U3gQMvLu0OECx0YOq8Fr0XBADfOIr91(8(AJwXFjCQCnPQqx(2RakS2grjQrzB1WdmpzQw(HnQ6QovDKQHAhvXzEQYoXq1Wtgun8KaLuoEkax(YlQw50JKoqy2JMM3JgXE0OOh1q6eZ4NlSb)r1sobFN1TnfqDZkDED1nw6jp7XHBYeMRFodVfSIS4tRn6extoyY)mxfFMzvY)8xxwan5SgcUxDtLOjV(evBc)LlOOsboR54)qa1n3T4M1Vi)R38VHcCYN81xWZg2KSKwHxL)I7Y9iHsXBYdDjSqvonPprgMf7gYcIvibNDDIgl)IdtZsyYbrwPWGY4g2V4OqzbKysIiHKOXi5SFUcAMZNs4E3yLxsLD9BwtfpzR66Gozjhed6N)sTgQ1QQ(s1d)AryCP3lJ1Nuqq4wKCGpZptFpznP53X9IusQ1oiwVFozGYxblinuMIkrZBIAkrZD51Szb0Wx5KDSYmwjz71zl2G1KttUJhMsiRI0w5UAS1KY6zMclZS9C1aJbdxLVsP22qnJtaS)h(WfZmSSi2tjEF4dJfFEFOQsdl8vTQu5DVRyLtCjXZa6nyLtMkHVnApdv(CqFm)rhy1ILAE5LBJYSvNXrAh7RIxS9oYRuY2jLFMNDxEvJXszHra7XlYj(JL3nb9oIRp5PlWx1sLWAO2EjKjF7oSXVFAgflU47If5R7S3H5hQU2DQqsNKe2hZrTyhIEfxYJolKzRCXPilq3zR27vyjvsnjLDl8JsZmXDAz2iR07Iq51v6RZ88Q8T8ZU6jX(fBKiBDIXCbLsfz7t2rLZU1LyOT0wvoZX5bpYyildokuUNy8qtyGIhRrPUZj2DNZE3yt8sGuEd4HmAvtlRWnhkClBs8oWMZ2pQ6b44u2rSP1n5S0R0ALO3H11N5n)fZOSfzu4hf2gPtwLCjM7ihSxb2DKh8fKDhzH96ZUJ80zhPpEfG7gF8uP7gpr1JUBCfTsOczANpYyrOufmPC3fexlJLXVZ3LFwfS9Zgq3zEXQXwoSW9eE3hwHBMqM3Y9juBQ3SFnE17zzBZ)DVh0lFx8vS21JFTh6lAG9XLZj6AOu11gfmzcZrBRR5X()MqcTfWZ9cgXEF50akOpPRn4IMA9hO1VzpqeSxC8Xwo2eOddh6dMbwwq6WYubnIXRUg)ehJL2TqgBuAA326MB01WH(aQ9eNi9bBiuP1(3)1)2)5F8p)3)P)Y)9F9h)F)9)moS8MtSSABIuaFdp)7qDbuIzKXpeFvkc1j(yLzNfxYcpYaqoJPtOJhWeXiWasqlrFg1VPzVF8Q7UH3dX2n)WlkYpXY5JMid7LIBZbNSBCMshRRXVCgliHTIfwgErtyxpLwm4VjA6(KJR59UgG(FV4tgb(ZCCdNcJpsXDjl1TiHjPl4V4(pYS1T7O1(Yw49DX2KkX8eh8Px5s)8QH)UadtOyzJvd7dUrimWdOtVdEFsqbwhV5mxzzm1t6Q1WxPkmaQv5u4NJoPAJtWRMdJHuALLJb7c6aL1d6uD8Jpgy5tJSFOX3gqcUS7QdJOm0m2YWZltROllxXbjODcWvAqzwutkGxhdeTKDZyO2tTax1Jl9NHEMeC7clnjJiLfNw9AnalZe(vTjdPUowKCvjjDa0O5lMxWifR2oDJrGKug2auD8p5nZwCsDLAtc4U14l5eZzuaCWXY05t24YYKqEIlkv(qd(nxILVIhvODrVwT6e2rrYr(cxLg2WRPJZSp7Iufcz34TXIci4ivSE8D5sas3craXqocTtx77Tdzf(4CmApArJinF2bYB2PQU2pbHY0jqmnUxtIlfwBuB6CYH1ACcOaOBGDjLyxFj8v8pmNnoXMhRXUpsMcwX3rg7Z3YZHq(NXpSAOchfwgVCuaaZ2W6DrbG1aLKjiirn4d07CkKBa3Ni9ohZI6o54Jp8KJo60J11EsCFZo6W6SlC2P1o6O6VSbl0FcDkpSNAJH3SriAnE0WNo(EMi1W6ELmV5JaG80etodDQxTkcjOOq4bcIRCgpdRnovGMjAtbcIs7sWurEOY8ial3EQJNvDROhJKGb3dlVmKcymJyauaPNej6IfcpFb8LdRJWf9))d

**Comment by mrbuds** [comment] 2019-01-17 12:00
duplicate of https://github.com/WeakAuras/WeakAuras-Companion/issues/68

**Closed by mrbuds** 2019-01-17 12:00 UTC
Labels: 👯‍♀️ Duplicate
