### ISSUE TITLE
Keys/Values of objects which are empty strings are not deserializeable

### ISSUE THREAD

**Issue by kevincuomo** [WeakAuras/WeakAuras2#1967] opened 2020-02-05 23:41 UTC
I have reinstalled 4-5 times, tried everything i can thing of but nothing is working. When i import a new WA it just says there are no children in the WA and its grey, most the time i have to reload UI to even delete a WA.

My existing WA's still work but i cannot add more. Any help would save my life, thank you!

![WA Error](https://user-images.githubusercontent.com/60719324/73893253-5897d200-4836-11ea-9b0a-e49d31a7ac1c.png)

**Comment by emptyrivers** [comment] 2020-02-05 23:58
Can you provide a copy of the aura you're trying to import?

**Comment by emptyrivers** [comment] 2020-02-05 23:59
And also your WeakAurasArchive SavedVariables

**Comment by kevincuomo** [comment] 2020-02-06 00:01
I tried a few Weak Auras but this one mostly
https://wago.io/4kn6801RM

Is this what you wanted?

-- all this is is a frame that ensures that the SV is a table type
local addonName = ...
local loader = CreateFrame("FRAME")
loader:RegisterEvent("ADDON_LOADED")
loader:SetScript("OnEvent", function(self, _, addon)
  if addon == addonName then
    if type(WeakAurasArchive) ~= "table" then
      WeakAurasArchive = {}
    end
    self:UnregisterEvent("ADDON_LOADED")
  end
end)

**Comment by emptyrivers** [comment] 2020-02-06 00:04
No, the files located at `WTF\Account\<Account #>\SavedVariables\WeakAuras.lua` and `WTF\Account\<Account #>\SavedVariables\WeakAurasArchive.lua`

**Comment by kevincuomo** [comment] 2020-02-06 01:18
[WA Files.zip](https://github.com/WeakAuras/WeakAuras2/files/4162768/WA.Files.zip)

**Comment by kevincuomo** [comment] 2020-02-06 01:18
thank you for taking the time to try and help me with this, i really appreciate it.

**Comment by emptyrivers** [comment] 2020-02-06 03:55
Hey, thanks for the report. I've located the source of the bug, and a permanent fix will be published soon. In the meantime, you can replace your WeakAurasArchive file that you uploaded with this doctored version:
[WeakAurasArchive.zip](https://github.com/WeakAuras/WeakAuras2/files/4163132/WeakAurasArchive.zip), and you should be able to use WeakAuras as you normally do.

Sorry about the inconvenience, and have a nice evening!

**Comment by emptyrivers** [comment] 2020-02-06 03:57
Closing as the issue is in an external dependency, issue will be tracked [here](https://github.com/emptyrivers/Archivist/issues/1).

**Closed by emptyrivers** 2020-02-06 03:57 UTC
Labels: ⬆️ Upstream Issue

**Comment by kevincuomo** [comment] 2020-02-06 04:16
It works!! you are amazing, Thank you so much for the quick fix!
I am going to make a donation to the WA's project, i don't think i could play WoW without them. 

Again. thank you so much and have a great rest of your week!
