### ISSUE TITLE
BUG: Conditional property applied even though Trigger activation criteria not met... 

### ISSUE THREAD

**Issue by Sethadon** [WeakAuras/WeakAuras2#332] opened 2018-01-04 21:17 UTC
What steps will reproduce the problem?
- unsure

What is the expected output? 
- conditional property applied ONLY when trigger activation criteria is met.

What do you see instead?
- i see conditional property applied regardless of trigger criteria

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
- yes, problem persists

What version of WeakAuras are you using?
- Interface: 70300
- Title: WeakAuras 2
- Author: Mirrored and the WeakAuras Team
- Version: 2.5.1

Was it working in a previous version? If yes, which was the last good one?
- unknown

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
- no errors returned

Please provide any additional information below:

If you know which aura is problematic, please export the string and paste it below.

d4KkpaqieQulsuuUecvztkPsgfKsNcHYQqQsVcHkmlrr1Tuq1Uef5xiujddrDmfAzQWZuctts01GK2gsX3KuACivLZPezDiurVtuqZdPQ6EscTpKQ4GivwOKQhIqMOsQ4IkrTrLu(iKqJuuGtIuALkiZusXnHeTtL6NQKgkKQLkk0tbtvQUQsQARqc(QckMlKI9s9xvQbdXHjAXkWJvrtwexg1MrWNfPrljDAcRgHQ61scMTe3wuTBv9BOgoswojpNutx46sz7iY3vjgVO05vswVcknFLuP2VI2JUBi3qIHe3nGBrr8SHRRVxdT7LneC24aDS4ddzKwumd6gcoBmUg(dqmSS3lzirOPkYvDoByGEP3jcr0b9jckCL21zI0VMXmU8Upr2xhgI7jc9sVgoB6aN35SHbcT)me4hTeBo0ezImrMif8PSmrEzoprQ4ebf5aO4sH2NagTJKjtdzILHZHMitKjYePGpLLjIoKQiZNijnLme4pZNi8lhu4KjsfNiOihafxkeHXLe8LhTVmNjwgohAImrMitebHjc)YbfozImx3vCI8IYejQY)COjYezImrMitKjYePGpLLjYzYDU4B67fOorQ4ebT6qQIjcXXejPPKHa)tKHprqro6ICgTeJytKHprwGAgohAImrMitKjYezImruC0u)ejZqN2jcrRdX5ejZMizktteDOeFAMiGv5YaTzgXltJeYSmFICMCNl(M(EbQeldNdnrMitKjc)jZH4pzo0CO5qZHm0(qjstzL7g0uCPSL5S3hKrLmnO6WG8meK4UsKMYkuItyVhnipdb(1UBqhsv4UHZMoW5gMdnhYqc(wJBFIhyqJBFIbA)GveKNmAOlj56RrZWWYkqxtj1ObLCIqIga3(enAQJZk(u6u8lbC7tYeon1qc(oN1Azk7bgsW3NnDGZ9ahomiFrUme43Dd6qQc3neROydukwZHbkfR5Wabzc7WqUu8UBGsXAomORkRa7WabXl0vD3qSIInqPynhgOuSMddeKjSdhgcLinLvUBqX5sXl(0BmfRKbwzGEm8YCw7U3JgGMsXFcRMibEIGszYZATddkoxkEXNAGgYg0uCPSL5S3hKrLmnOA4SPdC(DvrcBie5CIHMMVvCUu8Ip11n0EMe)HbzlWgAA(wxfF5676gIvuSbDiJM2atI)WaDNHa)tK1RLdkSbfllafxkBzoBafWIKjshRu8hgAA(wtXLYwMZUUbXtIvA21nORIVC9nORIVC9jcJlj4lVHMMVBViCDhgiG)WWZnfMcxmKi0uf5kApXV3JJhlrdQvAi4SXXA4pwRit1g24NnuLfPvdVxCyi4SXXA4pm8CtHPWfdfSmXDdnnFhYc)HRBq8PkCJYDd5TsiC3HddAk(0DdAXNwyVx4Wqil8hUBql(0c79ingYBLq4U3J046oCyOP57ZIuRDDdNfPw7UbT4tlSb0ZiTldDhguYt2Dd5TsiC3HddnnFhYc)XHhyirqGG4SvIvUBiVvcH7oCyqHlS7gYBLq4Udhgiipdb(D3qERec3D4WqtZ3Ak(01nqrIkKf(d3nK3kHWDhom0089joFGmCDdHSWFC4UH8wjeU79bzx37XLCDhoCy4B5DLinLvAVR0ab8hGyyzVpgneC24Gi8hsXNZFy4667aTRZYgcoBmUg(dd0rs(bkkvj8Dn9BuYjIwUbfNkWFFffBqCIFdbNngrhl(Wq9R9(vuAi4SXXA4paXWYEpsJbrIbualsMiDSsXFmrUqCnrqN2jcAP9LNHGetSjY6AIudoqHjcwnraImiErCFIZPkCWjEpAi4SXOb6QPBq2cShyi4SXHbI3PbIFthccRmq0Y7(Yz0Gmjrec8ll3HsKMYkT7Ep6UHqjstzL7guCUbun008TCGgRgGsCc76g0Tbmj(d0vmbrwda6lxtnguCUu8Ip1anguC(vkwjdSYa9urdj8Ggbc9vuSHmy5AqFT1xJHxMZA39E0a64lSAIq7tOPf43HHyffBq2usdnnF3Er46gAptI)WGSfydnnFRRIVC9DDdkoxkEXNEJPyLmWkd0tfnWK4pmqegxsWx(jc6kCQI16jcAbkUuiMbfllafxkBzoBaD8fwnrO9j00c8BOP5BnfxkBzo76g0uCPqBI2DhgAA(wX5sXl(ux3GUk(Y13GUk(Y1hLcTw8PgAVimqvKRyLbDBatI)aAeiiYA4Mi6G(n0PlJDdAkUu2YC27rYKPHSddTpuI0uw5UbnfxkBzo79izY0q2HdVpC3qOePPSYDdkoxkEXNEJPyLmWkd0tfnOBdys8hORycISga0xUMAmO4CP4fFQHfOAqtXLYwMZEpsMmnKn008TCGgRgGsCc76gIvuSbDiJM2q7zs8hgKTaBOP5BDv8LRVRBGjXFyGimUKGV8te0v4ufR1te0cuCPqmdkwwakUu2YC2a64lSAIq7tOPf43qtZ3AkUu2YC21n008TIZLIx8PUUbDv8LRVbDv8LRpryCjbF5n008D7fHRBq3gWK4pGgbcISgUjIoOFdD6Yy3q7fHbQICfRCyO9HsKMYk3nOP4szlZzVhjtMgYoC49c3nekrAkRC3qSIIniBkPbDBatI)aAeiiYA4Mi6G(n0PlJDdmj(ddzallrvd62aMe)b6kMGiRba9LRPgdAkUuOnr7Udd6Q4lxFd6Q4lxF6odbj2WlZzT7EpAafWIecyvUddTxegOkYvSYqcpOrGqFffBidwUg0xB914Wq7dLinLvU7WHddbNnow(LdkCIRB4IijQ69IddjcnXV9NHGeBqwkgcoBCqeUGvU79O3K9EH3KDyq8I4whsvWjEpA4e)jIqGFT7Ep6UHZQ8zfC3qOePPSY7ddKKkHCqHnWzPekziWFxKZgijln2aQJgWugOFhgoRk)uw7U3JUBGKS0y39E07rVp8E07fEt27k9E0HbkfMIvXkdbNnoicxWkhoC49H7goRYNvWDdHsKMYkVpmqsQeYbf2aNLsOKHa)DroBGKS0ydvwRbmLb63HHZQYpL1U79O7gijln2DVh9E07dVwLOEmEqdz6J8XIAxQ2LQ1egoQl8EH3K9UsVhDyGsHPyvSYqWzJdIWfSYHdhEVWDdNv5Zk4UHqjstzL3hgijvc5GcBGZsjuYqG)UiNnGPmq)gijln2qLlCy4SQ8tzT7Ep6UbsYsJD37rVh9(WBYEVWBYExP3JomqPWuSkwzi4SXbr4cw5W7d3nqswASRBGsHPyvSYqAbFXH3lC3ajzPXUBqJBFYDSIInGErUYGg3(ed0(bRiipz0qxsY1xJMHHLvGUMsQrdk5eHenaU9jA0uhNv8P0P4xc42NKjCAQbnU9j3NvL)ZfdOuQdw5WaLctXQyLbnU9joC4W7kD3Wzv(ScUBiuI0uw59HbssLqoOWg4SucLme4VlYzdykd0VbsYsJnSyjhgoRk)uw7U3JUBGKS0y39E0RvjQhJh0qM(iFSO2LQDPAnHHJ6cVp8AvI6X4bnKPpYhlQDPAxQwty4OUW7fETkr9y8GgY0h5Jf1UuTlvRjmCux4DLEp6WaLctXQyLHGZgheHlyLdhoC4WG2WrMqntJgi59yLhJoSb

**Comment by InfusOnWoW** [comment] 2018-01-05 08:05
You have to be more specific in describing the conditions when the aura looks different from what you expect.

**Comment by Sethadon** [comment] 2018-01-05 17:04
Specifically, the sound condition is played whether the Trigger activation criteria is met or not. :(

I hope this helps. :)

**Comment by InfusOnWoW** [comment] 2018-01-08 22:19
Fixed in the latest alpha and next release.

**Comment by InfusOnWoW** [comment] 2018-03-06 18:13
So the bug is reproducable with the exact same aura?

**Comment by InfusOnWoW** [comment] 2018-03-11 17:11
I cannot reproduce any issue with that aura and a up to date WeakAuras. Please explain how to reproduce the bug you are seeing.

For the record, so that I remember what I did when I first investigated this bug:

The original bug I fixed was that the gong sound was scheduled by the aura being visible, and wasn't canceled on the aura being hidden. Thus the steps to reproduce

1) Make sure that the aura is visible by entering void form with power infusion on cooldown. (And with no power infsion buff.)
2) Drop out of void form
3) Wait until the CD of PI is 43s, no sound should play.

**Comment by InfusOnWoW** [comment] 2018-03-15 08:22
No response from reporter.

**Comment by emptyrivers** [comment] 2018-05-16 06:56
Following a conversation in Discord, I was able to reproduce this issue, using this string (on master branch): 
```
dOtbeaGAbPAxcK8ArKzsqnxcYSf1nfc3vGWTfPDQK2lA3sTFc0pfIgMaP(nfhMsdLagSs0WLOdkKoLGehtc)LuSqLqlvqslwewoupuqPNcEmP65qMOGqtLKjlPPR6IcQCvbbxMQRt0gfOyRcuAZeQTlultj4RcszAcI67cyKckgLavgnHmEbvDsru3sqKtR48KsFwPEMav9wbIMfuriLqLqLkcw9pXUcp7TJJWuDUgsfbnHJN92Xur4AlDcOBVerqICn2CaRw0XsNjiirUgzpNlsqICn2eidoreMQZfj4XEFcH1015JPreqImbISjGezcezhv)tStq2ES3NGvEdpHSXwPIWTzV)curivM)qfppHBZEFQiKkZFOINNqDelE0L5RLkcPY8hQ45jGT6ovesL5puXZtaBYovesL5puXZtOmU82S3NkcPY8hQ45jm9gBKLurivM)qfppbXw9pMMkcPY8hQ455jm9DCBZbRJrJP5AWtOoOqx26FIDc6s0nPe0LOBsv4zVDSWM9OtqSS1)y6G7HIGlX(L4wWLpilccbx6DLa23JPvAlDcJUPj0YufE2BhJ46ceMkH7Ol4sDlYjyR15JPTznhp7TJruX1cQiC8S3oMkcxBPtWkXwcizcp27dsXINWtqtyJcknGkAOQi4XEFcHXT5lIasMWJ9(cGDXt4jaceoHfMaQ0Z5KRiQ4jGezceztajYeiYoQ(NyNqBtDevCTGqYytJsAAbxUi2dWtq2ZjuMTADmHQNqkwSsBPtimHtybcMqqyEcY(4zVDmv888eMEUg0T47vUwqq3015JPruX1cQiOlY1tIkchp7TJ5AbHylESjYobKitacX2S05AbpbDr2E7iQ4AbveITzPtfbKr2vnxBPtqGSvlbKr2vcj33XIT6UqrRvtJek0CBsrLylsibmbCCuj2IIWRJviWi7ksOOySjGguaJbjkOm7nbKr2vn6ISD7zcryr3X8ekXMshFTeqgzx55555jGieIEmHyUweYluWtc
```
To reproduce:
1. Import above aura.
2. Use Ironskin Brew.
Expected behavior: nothing happens.
Actual behavior: `Arrow Swoosh` sound is played, due to the trigger 2 active condition, even though the aura as a whole is guaranteed to never be activated.

**Comment by emptyrivers** [comment] 2018-05-16 07:10
Further information: the only affected condition is the active state of the trigger itself - i.e. if the condition in the above example is changed instead to `if trigger 2 - remaining duration - < - 1 - then ...`, then it will behave as expected.

**Comment by InfusOnWoW** [comment] 2018-05-23 16:08
Fixed the issue that emptyrivers reported.

**Closed by InfusOnWoW** 2018-05-23 16:08 UTC
