### ISSUE TITLE
BCC alpha 3.7.6-4-gd1930c4-bcc GenericTrigger error

### ISSUE THREAD

**Issue by Road-block** [WeakAuras/WeakAuras2#3437] opened 2022-01-19 14:46 UTC
### Description

It's a logon time error, not doing something in particular.

After logging in bringing up options with `/wa` fails to load a bunch of auras on the left side with a followup error of

```lua
1x ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:947: attempt to index field '?' (a nil value)
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:947: in function `Initialize'
[string "@WeakAurasOptions\WeakAurasOptions-3.7.6-4-gd1930c4.lua"]:585: in function <WeakAurasOptions\WeakAurasOptions.lua:579>
[string "@WeakAurasOptions\WeakAurasOptions.lua"]:651: in function <WeakAurasOptions\WeakAurasOptions.lua:646>

```
#3436

### WeakAuras Version

3.7.6-4-gd1930c4-bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

4x WeakAuras\GenericTrigger.lua:3537: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:3216: in function <WeakAuras\WeakAuras.lua:3198>
[string "=(tail call)"]: ?
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:3302: in function `GetOverlayInfo'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:138: in function `propertiesFunction'
[string "@WeakAuras\Conditions.lua"]:418: in function `?'
[string "@WeakAuras\Modernize.lua"]:1354: in function `Modernize'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:2547: in function <WeakAuras\WeakAuras.lua:2529>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:2706: in function `Add'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:2237: in function `load'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:2244: in function `AddMany'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:1033: in function <WeakAuras\WeakAuras.lua:1005>

### Reproduction Steps

1. Update
2. Exit the client completely
3. Restart WoW
4. Login

**Comment by mrbuds** [comment] 2022-01-19 14:49
duplicate of #3436

**Closed by mrbuds** 2022-01-19 14:49 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate, ⏱ Awaiting Response
