### ISSUE TITLE
Add option to add classcolor formatting to UnitID name anytime a trigger carries a UnitID name

### ISSUE THREAD

**Issue by DaynishWoW** [WeakAuras/WeakAuras2#1986] opened 2020-02-15 13:22 UTC
**Is your feature request related to a problem? Please describe.**
It's not easily possible for simple users to color the UnitID name (i.e. %destName) in a status-cast trigger to be colored by the unit's class if applicable 

**Describe the solution you'd like**
%destNameColored should return the same string as %destName but colored as the classcolor of the unit

**Describe alternatives you've considered**
Asakawa gave me this function to use instead:
`function()
  if aura_env.state and aura_env.state.destUnit then
    return WA_ClassColorName(aura_env.state.destUnit)
  end
end`

**Additional context**
[here's and example of how I've implemented it currently on wago.io](https://wago.io/9dqUsiWh0)

**Comment by InfusOnWoW** [comment] 2020-02-15 14:27
This is a duplicate of #1618

**Closed by InfusOnWoW** 2020-02-15 14:27 UTC
Labels: 🎨 Feature Request
