### ISSUE TITLE
Profiling - extraneous / erroneous items reported. 

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#461] opened 2018-06-22 13:58 UTC
**Describe the bug**
When using the Profiling feature lots of stuff is included that ought not be happening.  

This is the Profile Report (from beta but same is seen on Live) with no Auras loaded and after a reload. 
```
-------------------------------- 
WeakAuras: EXPERIMENTAL Profiling Data: 
Total Time:       7530.10  ms  
Time inside WA:  ERROR: count is not zero: 2 
Time inside WA:   0.04  ms  
% Time spent inside WA: 0.00 
 
Systems: 
custom text - every frame update   2.78  ms , 7293.48% 
animations   1.27  ms , 3327.63% 
generictrigger UPDATE_INVENTORY_DURABILITY  ERROR: count is not zero: 2 
generictrigger UPDATE_INVENTORY_DURABILITY   0.00  ms , 0.00% 
 
Auras: 
Total Time attributed to auras:  0 
--------------------------------
```
This was noticed because `custom text` and `animations` were being reported on Auras that should not be running those functions. Some experimentation showed that they are included even with no Auras running at all.

**Comment by InfusOnWoW** [comment] 2018-06-22 17:24
I can't reproduce that. With no auras I see a bit of load and a bit of BuffTrigger. The BuffTrigger one could be optimized away, but that feels pretty pointless.

Do note that, WA does not deregister events if they are no longer needed. E.g. if there ever was a aura with FRAME_UPDATE enabled, then deleting that aura won't deregister that. There's a reload or relogin necessary.

**Comment by asakawa-k** [comment] 2018-06-22 17:44
Yeah, I did reload for that reason (mentioned in post above). 
But, if it's not universal then I'll go and keep poking things and see if I can get to the bottom of it. Could unloaded Auras affect things?

**Comment by InfusOnWoW** [comment] 2018-06-22 17:45
They could, but shouldn't.

**Comment by asakawa-k** [comment] 2018-06-22 18:05
Okay. 

So I removed my WeakAuras.lua file from WTF and logged in to the game. 
Profiled for a few seconds and it worked but, as we'd want/expect, it showed no activity.

I opened config and closed without making any Auras. 
Same result. No activity. 

I made an Aura (`status - health`) and ticked `never` in Load. 
Profiling now showed some generictrigger activity on `UNIT_HEALTH_FREQUENT`. 

Lastly I used `%c` on that Aura (that had never been loaded outside of config). 
```
WeakAuras: EXPERIMENTAL Profiling Data: 
Total Time:       10326.82  ms  
Time inside WA:  ERROR: count is not zero: 2 
Time inside WA:   3.44  ms  
% Time spent inside WA: 0.03 
 
Systems: 
custom text - every frame update   4.81  ms , 139.62% 
bufftrigger   0.01  ms , 0.33% 
generictrigger UNIT_HEALTH_FREQUENT  ERROR: count is not zero: 2 
generictrigger UNIT_HEALTH_FREQUENT   0.00  ms , 0.00% 
 
Auras: 
Total Time attributed to auras:  0 
--------------------------------
```
After a reload UI, without opening config or doing anything with WA directly, Profiling gave the same result.

**Comment by InfusOnWoW** [comment] 2018-06-22 18:49
https://github.com/WeakAuras/WeakAuras2/pull/462 should fix that.

**Comment by InfusOnWoW** [comment] 2018-06-22 20:13
Should be fixed now.

**Closed by InfusOnWoW** 2018-06-22 20:13 UTC
