### ISSUE TITLE
Pet Unit Spellcast not registering for trigger

### ISSUE THREAD

**Issue by Lisonna** [WeakAuras/WeakAuras2#4774] opened 2023-12-25 17:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Pet Cast Bars do not appear to trigger the Cast trigger under Unit Info. When a pet casts a spell with an intuitively configured trigger, the trigger does not activate. 

Looking at etrace, there are `UNIT_SPELLCAST` events for when the pet begins casting. Additionally, when the pet is casting, `UnitCastingInfo( "pet" )` does return valid information for the pet's cast. 

I am testing this in SoD Classic, I do not know if the issue is present in other clients. 

### WeakAuras Version

WeakAuras 5.8.7

### World of Warcraft Flavor

Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
None
```

### Reproduction Steps

Log onto a Warlock that has an Imp pet (Presumably the easiest/most accessible test case). 

Create a Progress Bar Aura -> Trigger: Player/Unit Info -> Cast. Set the unit to Pet. Command pet to cast Firebolt at an enemy. The progress bar does not appear. 

For a control case, change the unit to Player, and cast a spell. The progress bar does appear. 

### Last Good Version

Unknown

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/70078996/69e81d92-b339-4990-9b3c-cb0b561d68ee)

### Export String

```Text
!WA:2!1vvtVTTrtyria3gHc)640gady0xxJMIwGKGux44(vAJOcvSsCOuPOtCsDl9sURe3gQLlwU0FDQrOhYLErh7rDUN0VGc)lyHA)bu4d9up5FbD2Lm2jbX(aXmJNz2zEM5zKvZ5hmpEE8ZxzCghjE6JOyz87DKrUDVEze5wwI9lKw)pg(3)5TRuPI4Gsd3(HZ(B)myycIffNk6KszYWgoU(oEtnPWlvIK0uMf)IVI(dsXe76B63(Kqu0t7lsZz4gPjPI7zzz1P6nU(QdLcA)(er2SFKOu8FokpJeeHYK(hWjX2s4RDoJkpolpKSlHj7M3RhD)jbnQ31pORFDpFpgAajR2X6iZ4KKexTE8qTUo0Dm5mKeJ2LMkIhFMp1gAKBHHOFr(7iiq(962XzJnu)Vv4ePjCmjtUjKSypJx2nGsCmMecvJUsfR7SrNMBUXOCwzNuJFruKKUlXVqxdh)ELX0OuwqKbgQc)DcGMebdL8qagaq7xhLrs6zaz1mddrIceRQLvv41YqYCbssI9qj8yu1xEg(yRXql4r6dzj7Exwn7uq9mKV0qVubPWWZxGpVKSVmilgHt3BRISuDKXM(ZYxHZx4uTaiYbizaVuWtshqWhxKHtl5lWVKXckxMcorJm7A21b1tkYcDFc2y8z8p8nKCDwdsi9rrhe0ljfgxhzC4NYZK0EhOMzSqVEr8bJ2UTDD4FW5LfUGer1yAv1ScO11UmTyjUSzTgBc7SPXOY0WK85AkOhU03LJWaGJwY3Np3lHwNUhx9vaXhxK3fRuu07cpFyczNPgT9sf4hjq8HpQuy6PVMEdY2nLrkFKxIQnULRRJxWgon95V)51QfAw8LophgKId0lo7C2B2LEizb(NCErGpayv0OazSa4sPj4dkXUYE065VR6QvvxB5RWuFJbju3qDb1NQwr9zptDFl1QQzu3uTMAw1xO(kd6Q(A1TuF7Ivu1v2QBVJYzsrV516UR7RAOUJQ1cQV06nS0XkfSzagfgtO9JL)F7KueUzOeLa8Xl7niprsRzde6OlR8Q5fLGYY0s2zqNQfo2WwSb3XAY4k1VZD4ZbC76y92fbtWpaTF8ieJoWCa7MEzsKq28ickJ0vkiS(Y43cAi3PynneCjqFFsKrasnoBO2p9Ou5AparznvFVXB12QFq9Jk3WEugnl(1npHYk6oiF1oMWqWkZDfimfARyB99I4xVmPS4Xcdt3C7bbvdCQqOV3aK)BQEsn1o1SHxtwZCWPBAUiISyLrMRpzumXZa6RKtXtAWB4C)oB1ATvxBkWBHrCBUjp1MyaS1nW9Te6bsUGm0oHE4Hib2Bpnn(xENIJq(f)x(h3sFqRhkIST(ejL13gj2EZwx7mTR118ZeMWIhltJ2T423BF1)Dzk(Ooe5sANxcC1(W00bwt6jGR1WeayIvpPynSP2KU7d72WZXXTSwPymH5568qhVqOx7r7xtqz6hGex8RFnoLTpjvOXydWpE92ETEsBx)6BmwpmPfiWOxCbEficGSFP(LdM2NfQA48zERE9p)6Rn)U)1w)3p
```

**Comment by mrbuds** [comment] 2023-12-25 18:17
This was fixed with https://github.com/WeakAuras/WeakAuras2/pull/4765/commits/424c89285828a199170b182d8f8d71f349e107a1 and will work as intended in next weakauras release

**Closed by mrbuds** 2023-12-25 18:17 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
