### ISSUE TITLE
Unit casts trigger does not trigger when using spellname

### ISSUE THREAD

**Issue by Dsune0** [WeakAuras/WeakAuras2#4892] opened 2024-03-01 15:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The Player/Unit info - Cast trigger does not trigger when specifying a name for a spell, works without filter, with exact spellID and when using spellID in the name field but not with just a name.

WA identifies the spell properly though.

Attached basic example

https://imgur.com/6mJdI49

![image](https://github.com/WeakAuras/WeakAuras2/assets/106332935/7c7277fa-726c-4907-b3fa-f47be22d4010)

### WeakAuras Version

WeakAuras 5.10.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Import aura
2. press Flap
3. WA dosn't trigger

### Export String

```Text
!WA:2!1vv3UTTnu4OzGouJH1u3TIMIITUI1UKnKIMaKcS)NLJDJZCLZKvBtlkGcLiLfxLjjiPsIZD1BaR3SB8JGVEx5hH8eqySNGCXEaYdWWiP0IBlAYfkNZHhE(5JNZNDAvBqnyn4RwFIGb4V4jyOm9Jp2k3njrGK76WpSqYHpSuykGeNs57qXezuJMEbn9NzVIpvcKykXHD53q)HuiYT(Jc6EAei(f950CcSbnJY32XXzNk37UBmsYX97J4Ip8o8sX)rxsOSmpWaK46UjzaMRCid5MtWswTCbkeejO8OTqGmtc27erEeAFer2lpjbF40Wg17fe2lOUFWjZDVWvJ(8WVNpX8VQ(2R72aiKJSN2gkU(1EVF7Fhz83K45jzhosNe)E70Sth1IrSmWqe)4ZIR(MPtGOiDPeORA(wn7StRh1zCoPS9QYUmiwI3hfuOBQR)AHj4ykjm2Inv0)DcIaIYqpGdGyDsthdi4bwm9((cjGlBDmciq9KCePVm99vxYLqjOzWCU1RqdKXfiDuHIrgxnvJAz3bamPL6l0xqTSAf1xQ(k1YrjycwK(2Mhfb4fVwvCCQOBkbqAcpk1hKXsbvE95LN6mrJq(O(6Kl2(QQlntRo)vV0qcLJkm8QLy1KOdLHIuaKEWUfrPYyRnZNBDBgBPZ0c13u3)HSsbFjEacEsreqzj2zs1fzxXAbKlPg0k2ox7wxREAruWhIGwJVK95VJGBIAygQpiEyysgLYtp26WVMlK4KHQlmHBgTrbAJUED9AY(SZlkmokgl0Orf1L46w34YSIfOYM1zI9AZF0hxggIKTylo(OB(l5aOgWb3miGT4RHwNTdv5naXNwe3BSqrrVVo96zO9Mz1oGYHpHdyJEsPWSZYMz0W1tp(uMKxBnFsBpVM(HDA2kG9jNxRwO5WU555Wakm0m4S38C2dFeAj2kN3nGd1BM44qzkhjsPzWHLyxzp68QpsTrf19V1TjQhyrc1xRUO6BuFR67EPkWr9dQlO(r1pPNNDvBArxvtvl1w3yb12QFw1EpL30IEZV9d2kq1r9qL)sQgoVJHosPGEtjfH7Nk)u3mka2kscY0lNx1FqEMex1vtaeFv1ZQ6hNbecJKRq3MgHtSRkUA3HMf(1RV5MSf1Kg1HMrleebFi4W0z6bxDp2LzwHfvNIjfjwRv11WqKYnCh6ZUV6ovvRQnQ5MQ(2rctsNWTBIwkiGEPvVkFQ(5eXjGShRjg0N9NwoNE0CEm6glm2sajWqKVfqk(DHgNnBUEogo1nFJOJwBFWkhS5u75BzHJVNBqRCoAKBg(OJaCO)bMDSF)dkyickoLTCBtfKaIrp3q1Ij9Db8N)O2RoxB1E2F)WET0jsA8(ff71C(Jb3cdx3dDG7ru6aNPjCn1TM)tVEu50IzJwgtMwoQxd)Mn9kRrmeIi(EnFCt)iDtMG7xLJjMaJszxPFjfBxU5RfRNSvx)2pRRxq9otPZnRgnXqNIlECg))SJRRXhNkJNZcDHAIOnU7A37URvB))E3)7
```

**Comment by InfusOnWoW** [comment] 2024-03-03 10:20
Duplicate of #4868 The actual setting is "flap", which correctly doesn't match. The bug is that it is displayed as "Flap".

**Closed by InfusOnWoW** 2024-03-03 10:20 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
