### ISSUE TITLE
Editable condition/trigger names

### ISSUE THREAD

**Issue by cloudbells** [WeakAuras/WeakAuras2#3168] opened 2021-06-25 15:02 UTC
---
**Is your feature request related to a problem? Please describe.**

For triggers, when switching between the Trigger and Conditions tabs, it is sometimes easy to forget which Triggers are for what, and sometimes there are multiple identical triggers that check for different spells. This leads to tabbing back and forth multiple times depending on how many triggers there are.

As for named conditions, it can sometimes be difficult to know at a glance which condition does what.

This is usually not as big of a problem when you're in the process of creating the aura (although it is with enough triggers and conditions), however when going back to update or change an already existing aura, this problem is real.

This problem only exists for WeakAuras with multiple conditions and/or triggers however many of my auras do have this.

---
**Describe the solution you'd like**

Being able to edit the names of each Trigger and each Condition (with a Pen icon on the right next to Move Up, Move Down, Duplicate, and Delete) would significantly decrease the amount of time spent on a WeakAura.

For example, imagine an aura for Presence of Mind (a very simple example):

_Triggers_
* Trigger 1 checks for the aura on the player. I'd like to name this "Aura Check" or something similar.
* Trigger 2 checks for the cooldown of the spell. This one I'd like to name "Cooldown Check".

_Conditions_
* Condition 1 checks for the active aura and sets glow visibility to 1, alpha to 1, and saturates. I'd like to call this "Aura Active".
* Condition 2 checks for no combat and desaturates and sets alpha to 0.33. I'd prefer this being called "No Combat".
* Condition 3 checks for spell cooldown and desaturates and sets alpha to 0.66. I'd prefer calling this "On Cooldown".

**Comment by emptyrivers** [comment] 2021-06-25 16:14
duplicate of #705

**Closed by emptyrivers** 2021-06-25 16:14 UTC
Labels: 🎨 Feature Request
