### ISSUE TITLE
Update 02/05 Blocked msgs?

### ISSUE THREAD

**Issue by jcle4** [WeakAuras/WeakAuras2#4901] opened 2024-03-06 01:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I did the curseforge update today and all incoming msgs from non realid friends were being blocked, disabled weakaura's and they came thru.  Installed the last previous version and messages worked fine. not sure what the exact issue is but found it very strange.

### WeakAuras Version

10.2.5 March 3rd version, 5th version is defunk

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
no
```

### Reproduction Steps

Enabled update, no msg's received, installed previous version, msgs came thru

### Last Good Version

10.2.5 from 3/3

### Screenshots

n/a

### Export String

```Text
none sorry.
```

**Comment by emptyrivers** [comment] 2024-03-06 02:16
"10.2.5. from 3/3" is not a version of WeakAuras that we've ever published, and I don't know what "5th version is defunk" means.

Nonetheless, this looks like a duplicate of #4898, for which a fix was submitted in #4899, which was published in the release version 5.11.2, so I'm not sure that you actually did search the existing Open & Closed issues as you claim.

**Closed by emptyrivers** 2024-03-06 02:16 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response

**Comment by jcle4** [comment] 2024-03-06 02:21
its my first time on the site perhaps i checked wrong. sorry for wasting
your time.
