### ISSUE TITLE
Model not updating unless the WA2 config window is opened

### ISSUE THREAD

**Issue by bizzy401** [WeakAuras/WeakAuras2#1683] opened 2019-09-11 13:58 UTC
**Describe the bug**
I added two 3D models. I set one to "player" and one to "target". Neither models update unless I type /wa.  I would expect the player model to update when any gear is swapped and the target model to update when I change or lose a target. 

**Do you have an error log of what happened?**
There is no error log.

**To Reproduce**

1. type /wa in the chat box
2. click New
3. Click Model
4. Name Model
5. Check the box that says "Show model of Unit"
6. Enter target in the "Model" box
7. Click animate
8. Close WA2 window
9. Target any NPC, Player or mob
10. Nothing happens at this point
11. type /wa to open the WA2 config window
12. When you close the window the new Model will be whatever you targeted. 
13. Close the window
14. Select a different NPC, player or Mob
15. Observe that the model did not update to the new target
16. Type /wa to open the WA2 config...observe the model updating when the config window is opened.

**Screenshots**
No screenshot necessary

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.14.6

**Was it working in a previous version? If yes, which was the last good one?**
I just started using this mod recently, so I have no prior experience with it

**Additional context**

``` Model ```

**Comment by bizzy401** [comment] 2019-09-11 20:26
Upon more investigation I realized that the model is updating when I close the WA2 config page, not when I open it.

**Comment by bizzy401** [comment] 2019-09-11 20:27
Here is the string to see what I did.

`!nsvxZPToq0)oTpCtWginVsioj0H6WGC6m5(Gic7126gHKR(GMWd8BVRKWan3xYaJNvRwP9SN9SIMqlOKnusL)V3uvbIzMNKCl9gkzTsxb6ByLVwPvDuYnc(UDmD1(xkukHLJUyDC6Ak5ThRRnGLMFv6yk59(v)Z4HdWyKLTk9cfxAPKPz5fzlpKQvVrZh0NNPkHsJOipj8pn8Dy47imSlgtXJZkTCL04bRXY0w0a9Y9aoyvJMM2GnUYQ5nnG2eV1IJocMV3busPZyvidyCRHTG0sC1183OKvtNqkwrkMSednSdL8aWe22tXUqdHyjlYMpNsCEqq6eS3XeC8IRDYaK)Yx3)99Ve)PbRtl3)Iv7G9FhKvhsHHswmFYZzlxH59(SIvtFys(9z32FBRIyglCRdJTSfkF9i6KSnGjscMoqiMvDyvfSglQIWrFiB(I7EAU3TtEImS9u7wOi68hy7b7Fjd870P0wnJB)xfwrR90Tf0sM4Ni1ILg2RgIhVAl2ObVUHj5By(I(820bcxQK43kNoeqFfbLkjIxmxByC5Np6JT7px82EDNXI7f0EALnc18HJgF(2rPj2RxcnhKC4XBbEtlQShna3uOyHXgKVldJpoCOONolfmJ5)51W3bF0j6E9HzSp1mGJJcM0RvUF0CB6)T9zFf(lh4j)8KepOlzcVD)KLVNfTYQAqcjpWs6qDf1fHYUpiIhJ5jxDgBGYnSKpZHExGEIRR5cygIjSt3aELKZId8p2zpXBgqu)HxaIjR)PIJC)5xSpryFi9BOhRQCBVE76bPE(3ZdfhYz8aXEATgNfWzDML55qYV5v4CBSNfFm6oFeXsNmDzwwEpCMjdOjb5ou0uZBIWpC73Yn(P7zYALNrpbXyw9Im(zL8jP05LuhZ)eYunGZWA4YjABlZi4LTVYLnxY(RLxSjnWDy3(IKrxGnKTi0gLMGEP)5d`

**Comment by bizzy401** [comment] 2019-09-11 20:30
It seems to update when I open and close the configuration window. If I change targets while the window is open and then close it it updates. So, it only updates when I open and close the options.

**Comment by emptyrivers** [comment] 2019-09-11 20:58
This is Working As Intended™, and wouldn’t really be that simple to improve. I’ll let other developers pitch in their thoughts before closing the ticket, though.

**Comment by bizzy401** [comment] 2019-09-11 22:01
After thinking about it, is there a way to force reload the aura if the condition is true? Toss that on PLAYER_TARGET_CHANGED and it should update when you change targets, no?

**Closed** 2019-09-15 15:24 UTC
Labels: 🎨 Feature Request
