### ISSUE TITLE
Not able to start 5.5.1

### ISSUE THREAD

**Issue by CLKRUN** [WeakAuras/WeakAuras2#4424] opened 2023-05-02 17:39 UTC
### Description

Not been able to open weakauras. At start the lua error appear.
5.4.4 works without any problems.

### WeakAuras Version

5.5.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
Message: Interface/AddOns/WeakAuras/Types_Retail.lua:181: attempt to call field 'InitializeViewLoadout' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types_Retail.lua"]:181: in function `GetTalentData'
[string "@Interface/AddOns/WeakAuras/Prototypes.lua"]:1278: in function `enableTest'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:607>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2966: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2876>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3044: in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2502: in function `AddMany'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1154: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1125>

Time: Tue May  2 19:35:48 2023
Count: 1
Stack: Interface/AddOns/WeakAuras/Types_Retail.lua:181: attempt to call field 'InitializeViewLoadout' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types_Retail.lua"]:181: in function `GetTalentData'
[string "@Interface/AddOns/WeakAuras/Prototypes.lua"]:1278: in function `enableTest'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:607>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2966: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2876>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3044: in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2502: in function `AddMany'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1154: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1125>

[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1202: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1277: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1228>

Locals: <none>
```

### Reproduction Steps

Load the game with 5.5.1 enabled

### Last Good Version

5.4.4

**Comment by Stanzilla** [comment] 2023-05-02 17:40
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4417

**Closed by Stanzilla** 2023-05-02 17:40 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate, ⏱ Awaiting Response
