### ISSUE TITLE
Importing specific Aura leads to Error

### ISSUE THREAD

**Issue by Nercus** [WeakAuras/WeakAuras2#1571] opened 2019-08-16 11:57 UTC
**Describe the bug**
Import of [TSU Stream 2](https://wago.io/SJOejBQhz) doesnt work (only WA I found with this problem) and leads to an error. Importing again shows *Import in progress*.

**Do you have an error log of what happened?**
WeakAurasOptions\WeakAurasOptions-2.14.0-beta5.lua:4202: attempt to index local 'data' (a nil value)
WeakAurasOptions\WeakAurasOptions.lua:4202: in function `NewDisplayButton'
WeakAuras\Transmission.lua:383: in function <WeakAuras\Transmission.lua:344>

**To Reproduce**
 
1. Go to 'https://wago.io/SJOejBQhz'
2. Import that specific WeakAura'
3. See Error

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Also happens if all other Addons are disabled.

**Which version of WeakAuras are you using?**
beta5

**Was it working in a previous version? If yes, which was the last good one?**
Release

``` !vNvJUjoss43fKgPmsepgsYKnN0oseczcRiqoSZEAvuSPTDJPNySrTBtG7MLN9R6Y2a(xyYMz1DXkg7I6R6UR)7gJwg6gAZn0Cm0cn0ARCHsl1tBDQ7LwND2uBIH2Re3G(3yOP9BJOF76)5S)TKxaZ6rtNgsfgdpR9zkQWFFUL6zx06ZacMJyMXW2xDLYvWFF(QZ)L2N32qBjLhYc8begAmy8un9jZPl8icA4MjU8GOfGSzHFlY3wWwsn0iEEgACQlGsF9cGGZAacZoHxcYMoN56s53h4qngEAlvyHq9M(qaZxyOPp6bdTioiMzcXIW)XN(KC9OWc(021ZNGPJF08eXeAmSLHgD1cIVd1X4AdTvPl0tp)YlXvK6VC(5x2(s5anhwugATuuvGfOxabvnoSPtz2rEI1OYfEGbpiGlTPY5mOdYtxq8OW8npzoXMwGyui102JegAybCe4vKJflxuHaz(X6UYh)25PdFJPGy5rrherSksYu4SGxh5N(zNy7fW9mkZDgORAFHCSeuUpX733z3bowck4ZBd6ycogA2WhdrVWe)MZuvR3xbG64WKQrINPi1SLkLi)DttrM5SDuOiaC1NI(xb(N8Xn)2MjXx)lk5LorCsOIMnXV3sqzeEsJB7pUN59)HPU2JM3(4WU69hnSbGI67aqR4cgt0xnD4OOWaxXEA6jVzODhL4blwTWilKYdC6u2kik7HEdgSJSw0uKSz3oA6MA6DgVDDygpkHcIicKU9mQ9lPIpX0LnwYFD2yjcSCTiC53WMt26vsy4N2bEb8oyWWkJHGfznEp0gCuwHKXhxJpImFlmu7PCxWdC50WWMBMWBb3CL3SK3iYB82sAYBwYBK27zmytbcWSZK6VurUaPW7GkphrfofOjMr93bTArOSiGl4eMOkiPxAuXdjSQtxjI40t2kPy9NcZoWV5EdGTxGpTVZhRwOvox(1ntMs8cPfHg7KLxsfOWPWu0VmDtZcebdc1VizlVikqT1oHNzSthbWmcgrWesAHHaj2D9mE7iPXOxr2WaI3Ize0hIhihv8rmvMeHmrl(W17CO(Q8r0rUQe9td8f36rCb))rpQpO)WEhtYErSv1qRN3Yh7VzY1Ee)xWOfi)YAPnFmMetBZKpG5zzq2Cmabi4bryEYCBmHjO94cOiHCgVh6b0Pa4pmNWFbaa84sbd9h8RSEHul4tLFJ17tfI3PIc1uhR66f1LWfQNJECYKcyMk4ZiqtMl2h)ki0aInkpfCvHWtd4GeWGQwnpxDZeNGQdj9cGeyXJpIOX2kmnuuyhrOSezxzAxk)e5ZYaR0f4h)HJNPqsG8l(HDUVN5dd6O3Z8XH91n7CZn9UPYv)BDI9xDwnU39J(DCEvusNEkm2ooYe1HmFBko33mzjZHgSzYReOXV5ehjz4vITDqKCyq7O9mIVRSZWDalBrlRleBdJlrKUqFss859NtviGSauKD0uxA588hpnDqicEe9hvBIQW761zG(D)FQgmjqAg2sdQhEeag3HZj5cVZHzoz1DLb7EYQQqMx)VKavVq4jtGdIqa1F8qe7g(3bZCEezQX)w8mGqS)O3ytOPVV2t3S7DDg(1AI(rlEs0EsptmOG1ccJhEYEH)1MtuofKwH(HY7PjpAexdd689aToLEf3wrALp5A5lFPXXc7icOkf3XOV3tB)wwf)p1AOSYjziwMp14o9Vj1J6XhUbYH)Z1HABCUSxiyc8vQymH5OJk1(WwSRmop9Al04hWuu97oAO5G(A6pjj(SIsd1VlGfICgxNrkFiAwzF0WoER7BiNWBOnHBhlRiFaZPeKFGyV2eGwBfX6mWQOZMtHnep50cm8Lntuvo)qH(5a9R7l0kb9U4IL3vJ5pwAEAIP3XhXPZUD4J(Ga5d55Ln0KjDwJDwsgHF2jdGDpdUl)SZHm54CbRFRHXddUNW0J7O0Ex3mPIMhHYo76dAZKY66FZKsliUzsXCAGa2lKi)orlC(j0OfoYDKw(PAL)OvYCgxzo4W2X7unWpepIm5Ud3FBq)1oyHKZwYjWmrExhV1nwMXypKz34k4l8F2z3EQXRbCphRGWWgphxB7723c)jpi3xT(oVrZ9T5p1Gt4uQhd2Bug27CHQkNMWEgafz(YBVsvLwUOlYiViJ(b85eV9zvvv(VFrwHnHUKLL3U4FcK394ecMJclY38DRP)uQ4lBVvX7siDVT1SrR0UQ6TIfkcts7uFZ0711rT9JHLdXURQS43FVTNNGuUx6TGgcVCa(XJvzlGbY3oaIsCWLq7MH8bKbVPBtRKJlqTPAn6HF42xEpABr63CsS5)bpY6KDZ)Xd2gEYS2uEkl(UESWzOwjRo6qv)IDVXCRDh0rtZS7ObJgR90(s8zfE1cW9OeGB1cW6OeGvj1VQT9(D7XrNS4gQpJ6uFiz5AgvLlomRUhpRwhM1YBnmNlnnUe0wJ94ecBtESaDLACqt)TDWYUMx3zCQMpv4hHDVw0h0OxlARJSP5chKr2AGfw1zB3Qz1CMVHUAyD7PjDa(s)1sKhMECTi5uNz3Ogm5p5JAyTKJ8OgU3M8w(qDsDxrQ4hRH3Dj4XNQt7wmXEfD18u2xFUzDg3yZfVgEWFDeKl3A4YkvPBvN5mFp4npYn4MPpM0R)mx33L(ZpMV1qrf)aSYlJ)7p```

**Comment by mrbuds** [comment] 2019-08-16 15:22
I can import it with no issue

**Comment by mrbuds** [comment] 2019-08-16 15:24
- Do you have any other errors before the one you copied ?
- Can you give a zip of your `World of Warcraft/_retail_/WTF/Account/<account #>/SavedVariables/WeakAuras.lua` ?

**Comment by InfusOnWoW** [comment] 2019-08-17 06:46
I can reproduce the issue

**Comment by Nercus** [comment] 2019-08-17 08:59
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3511828/WeakAuras.zip)

**Comment by InfusOnWoW** [comment] 2019-08-18 14:39
Duplicate of #1555

**Closed by InfusOnWoW** 2019-08-18 14:39 UTC
Labels: 🐛 Bug, 📊Data Issue, 🚨High Priority
