### ISSUE TITLE
Runtime error in Condition.lua

### ISSUE THREAD

**Issue by zcqiu** [WeakAuras/WeakAuras2#3591] opened 2022-04-18 04:57 UTC
### Description

An runtiome error occurred in condition.lua，line 822

Call stack：
`Interface\AddOns\WeakAuras\Conditions.lua:836: attempt to index field '?' (a nil value)
Count: 2

Call Stack:
[string "@Interface\AddOns\WeakAuras\Conditions.lua"]:836: in function `UnregisterForGlobalConditions'
[string "@Interface\AddOns\WeakAuras\Conditions.lua"]:876: in function `UnloadConditions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1735: in function `UnloadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1521: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1393>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1557: in function `ScanForLoads'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1610: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1608>
`

Code:
`function Private.UnregisterForGlobalConditions(uid)
  for event, condFuncs in pairs(dynamicConditions) do
    condFuncs[uid] = nil;
    if next(condFuncs) == nil then
      local unitEvent, unit = event:match("([^:]+):([^:]+)")
      if unitEvent and unit then
---line 822
        pcall(dynamicConditionsFrame.units[unit].UnregisterEvent, dynamicConditionsFrame.units[unit], unitEvent);
      elseif (event == "FRAME_UPDATE" or event == "WA_SPELL_RANGECHECK") then
        if (event == "FRAME_UPDATE" and dynamicConditions["WA_SPELL_RANGECHECK"] == nil)
        or (event == "WA_SPELL_RANGECHECK" and dynamicConditions["FRAME_UPDATE"] == nil)
        then
          dynamicConditionsFrame:SetScript("OnUpdate", nil)
          dynamicConditionsFrame.onUpdate = false
        end
      else
        pcall(dynamicConditionsFrame.UnregisterEvent, dynamicConditionsFrame, event);
      end
      dynamicConditions[event] = nil
    end
  end
end`

run some test code，this issue caused by following environment
1.some aura  with a TSU triger，and set event filter with “COMBAT_LOG_EVENT_UNFILTERED:SPELL_CAST_SUCCESS”
2.when another aura(https://wago.io/UCLYg_X6W/26)  load or unload，code runs to “UnregisterForGlobalConditions(uid)”
3.the local unitEvent, unit = event:match("([^:]+):([^:]+)") were set by 
     unitEvent = COMBAT_LOG_EVENT_UNFILTERED
     unit = SPELL_CAST_SUCCESS
4.dynamicConditionsFrame.units[unit].UnregisterEvent is nil cause error

the aura with “COMBAT_LOG_EVENT_UNFILTERED:SPELL_CAST_SUCCESS” has run for versions，this issue hasn't happened before 9.2 update

### WeakAuras Version

3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

Interface\AddOns\WeakAuras\Conditions.lua:836: attempt to index field '?' (a nil value)
Count: 2

Call Stack:
[string "@Interface\AddOns\WeakAuras\Conditions.lua"]:836: in function `UnregisterForGlobalConditions'
[string "@Interface\AddOns\WeakAuras\Conditions.lua"]:876: in function `UnloadConditions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1735: in function `UnloadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1521: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1393>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1557: in function `ScanForLoads'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1610: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1608>

### Reproduction Steps

1.some aura with a TSU triger，and set event filter with “COMBAT_LOG_EVENT_UNFILTERED:SPELL_CAST_SUCCESS”
2.when another aura(https://wago.io/UCLYg_X6W/26)  load or unload，code runs to “UnregisterForGlobalConditions(uid)”
3.the local unitEvent, unit = event:match("([^:]+):([^:]+)") were set by 
     unitEvent = COMBAT_LOG_EVENT_UNFILTERED
     unit = SPELL_CAST_SUCCESS
4.dynamicConditionsFrame.units[unit].UnregisterEvent is nil cause error

### Export String

!WA:2!92xFWr111HBzfQtvsADinUooPXB2eK0gluLeg8hDGoALwbkvG0VvcWeBQ0B39jTRz1UBEVNaKtCQq8LesGazZhgKnGmgWydcKXyecH6W0M(XVjZChMmPUjTZ0AR3BLYKg3sY08hD6V535CVVV)y1kSD2XAzF375EUN75R75EVN7Zfu3I7CXXwCS(kE0ertNQ50DjeL)RDFcBVX2BxKxQGrJ2LOu6oBHF7szE(27kvuPePtvAGI8bFe4L6siLpUUe4ALp1wlF18s1MqmtsUUBwsirQokvVgrjoj(aLzgYGD1E7Udwr8PIj0TA)poxQOXtl0u6ePKIutO11sOW3jA60jJLEBPAEBjYW3wMh0GexFMyagcZVv(us3wdSqX6GVTG4ORTEHoSJo4fepqXcQ)SVhnZxQlr(wfPJ8WCjIvxsUoeJliMHpzY6JfPYNQILv5tDxwNSboHeCrsYlM5T)(uEqKUeeLGbHVvsFKvi(jgJt4BL(8NTV9ip0HM56x0Fz6vl1DgESUiarQw8lY(h6xrt3vQ5fTtEYzV0PZh0(I3bhHX4fLyJTEJbCCuq6VQkIqzwIzYwtJRny1T0AdnU6wdTbGr366xxD13aWVdv7t3CtHAOHwRP6MBP1MxFn1eQ5M9n)Gx96dxDRv3utnuFOAZxWdhATnUH8c8McfU(gRT(AAT2QxB1RouE0cgGHtX1jVyr31qMZ4jb7kvcPiiVLxOxvzVyr32eillst0APmtkeRdqv8mpOnuTS2ghljAY0P4RpwBJgJpcOR3cizewtOgAQU13W4mLPwrP14uL(UOkUbXcIWQCyDXLq9PwTq6UYi0vkQSkSuIo5JzMYQQ36esawnj7(de7IjqBg6YeB)owKzKIgTM0DgHtYxdP7WbzxvB6nUjbEOXHPSTX1hTWyHuY2)MF7LUuFlmDLIYRwywDzb0cvnM8Rf2uAYVgPcRUZpUKjPYmXY8r5wL5R8YlN5rmr7SI89dbBWCGz)(KIZNsZbA7Cjf59bYpd7)KPJYL0xRL5ttKug9bQ0A1RV(A1(nQbsRc(puHHvxRA)htUvl4rairnkmvAjtyk)OKOTdUIm80d(sBprhMQN6gK2raKLtFQzSVnbcLNzG3LA6ZStVxLjpt2tCiLdCUzhCNYN4QLP0ZKkhBm1I27fKFVROr(RhStrcV0sygRLea522gq6oeHgGuuNPHwLwimxQoa)JR0xLwHY0SzuwGEf8WdEGIQ8XLkgLzIuu9PAItqQ7snelb(43flZwxGZo9jBp840EOu9UqK5IZsNKwWGeezoA059M1ddK30JQ(Lf9mZ6dSjmN9CNf((JU5GY9Dc5jVHYrUC2JVldTiyePzCGJe)o9I4No40TbwPUwQfYu)hm1uuhVf2SOI8j5JkvALl3KfUlTacMPAOrQ2hS2c0tW1xxDmkyJv3kadY)WGEq(Prj1sNCWludZtBRe6qOfoHo4LC2iGLO5eajbVSjSWUz8AGZM9ktk)AdGgDh4nLV01qYc49k9DOzM8TH4mYEPJQ0FpkJ0paQY7CyLrgtE4bN5MNr(sVJ7iE2d8EYdDegYK3D)zpWyylhChzN8Ikh9AZD0RAPzWi1GJVIY0yQLA2nNQ4lqalTeh0qJPUXyyb)EPigAbMOS0a66zA2cEWiO(AqgbLJWi5zU((bosuorjEbGB4cZ6exs5u7fkHnlFzm(L8qxGXYKhBcDiYlUgaTC)7hWYStFmLXpnWVv6)wY9Dz599Aq7bsGXwNzYjv21qmu7kZfnBaIyNtn3o2V8b2JDoMHtujQUe4efuy0vECOUKlrKgk8saTWfsUkOWpTd2ojGgxzz(E8k8flTdammuKWWGXy9apvs8(blyFjCfCZCdP8GnmFSdPCXhU35hM)erGNBlUwRBTYbN12ZwEWK)fFgCIICRTf5q5DPZmXaG2lOk2m6Mwxfo7KVKYREsQN8xj7BnGCFtQSV3q(q7tEp7w(sty29LESvpRHZRntDI6AnLRVojhIk3HNo8cLkggcnm(0z3wBQwyoH5ZKwqAT8IICDWxQRymq(YAwQ8z7v51gbyizF5ZdwWOnn1WLXwaxjkh9ukhUpG5vKlAjE4T4LpPsFh0(mJ5KfaJ6VVdveX4P3guHKqx8L5OYOXXOfI5z9oBa1DPVvAogvNDjBjfiuSjOZdeRTSvM5IZgWV9mjyq0In5RVhZ9wKriDhcG8vDgF)0Lw53jCCDjLEnjIHWqJLjpiwJDgWl(Q(A89aaR2IMEYdqbJobj7A2EaRHnqQejZJrdvijIkpVOByS929QohfiLwIlzTCDYHrG6RcRT4f92ZevvgdYYnTAVBM54kL77vLp3aYdEe1PI77OZE6ZxK9jyG1nLodvnlrkFz4siiwQPqNPlRrmGBt(qjRYzCQNLHc2tBwDBCm)577Q)BQoHt2IE1cjKsGZU5jeP7sIkF9gIyEW61njG5wYfmVy(pzIR8EuzHX5XWl7)TugAiwGLYJCE1qVUzpaOqCmYV34zNCiLbEdwyNwIu2w4avT8L7MiXiMEMRg1i6ROmFAHJBjcZeUh6cU8hvCqNXMo)RRZ1o)6pyF6U6JANPQ4Gdwmyet9RNXdWu8OwHpRPM7MAxUv)mHqbPwMxpj2ueAjhouCx75EnSL5DfKZC9bM7vhfIaEUr6z2ZUdwS9Zm5(ZURRHQzqSYV6PHONlk)CSOTPjuaNN9lXQo)zuoYfvxn707n75hyMRFrma(BDuGeWfiEpTs2FOhRK9Ev5d7FJfjBw)ZvTUfG2M7AzlaTR5rR6fZJjUOuR1yywy6v5q8OU5J(DSNtZ3Mo4(oEOhN8Sx6wzN6sYtETzNM(4EVG8(opRwNH5PjpYJiBnbklWdRBmJbiMI0cvFW4dRLpjx3UaAod6A(AS7XF5cGMcaZHeSO8wE79Q)1TwrvzCb(uMDroNlH5x2IrGQWohbHaAeEBpH1uUHIU7sUp5uLziX11n5KBm7LUS8uhMTLcWsuKp4zTXy0XOf9p0BLHAWsDdKvr1nO0bv5W3FQVkROIkYFZKzV2UbFQvM9Cd7M83i2AVuX9sfz(MAz2lDALdFzCZGU6yY77uSnZPm1v3D0RHHQOTJpQHZ03ROVFq6vXA2mx)a6OZadh9u6GXwCO5TFZd5iDBCnXM1w2a1XjULJUwN267d40bMtpEMpsh)oLtEk0m4B4gIT3BO0)aGYL8LoU(EIbmG527qFYfiURtOrlrFd1vlKY)Amv8esEhHL6XxqB(kTgKVRw(EovK(6OkxlmFZp9y(Qm)rJ7MD5mirnRh5ZCeDgV3rusjmtlMWwbErSETRvf5DyR5WF2cA3RupLdxuCzhGNFQvGZATDMGUOzRUiIo1eAwpwaeTvKFwcM9y4IhjRRm2zzpMkn4DN9PLvZVBSnS6TaN4r(qtbrmBZBb6t8qNxzKtQ0Z5y8s1LZt3VBLb7p7UpN5gkFMDL9G7XtZO8qJa4Qla)f3BM5EYvUhn3)4yfNll5fKfUtjQYXVQ8EN0IS0dX28S(yk3SgT9djNSc1JW2yVtuTGRQsBhS3crEenV6At6cM6ERf87mPa7m1zYb94pKFNll3ZnZXCv67fKLhD1x08nLLQl0vPIkt70uEymzzFPYrN)X(iqw4HhQUBawAiMfBFGrk2GB3u8WrJZhDlKIUTw6yrlDudiiF1XnLroKadddswAQv04Xsi(80uqzR8vXLQ7mlwnT3y13q6osenZJQNKkswsrpPNTYnJeuMVihfbQnATPJX)233DtKsIxifxYnWlicTTJ7UfE(mvdC9OsHXf2fFyUuj6KUeVveMU49nqkoyQ0P47LNtKhx7gj0TXF2SKaFQoKI)arYaRQJxkIyCHeP2YD0wojnJNee5JMovmXGDYLivDKVd5VGumjez1paPosOiTNivcX42lEuGBXjHyHh4xDfjmFha6e)UpeP47apgHl6w6qaujI13JKzXs8BxQvX4CXsVTNrnncZ8TOfs)cMKegmTwz5g78NAzKqdRdMWsyhJrMh0e6QjDY0cFNckOGc)awP8jBNMAIbRE9T0yMVeTqCPQi3k6gtetkEWQHhVlRJtSD(y0c3Hl0tvUrp3McXZds6eT3n5bgvinQJHP6yW1146cDhw2rUj1rjPybGzGnrLjWQwLj8fgLwwu2yyn)5)QBHFMUWchwLmsjfz2DSp5Z8Mz(6oOogZqNUSWK16(m(C0mCTTjs1EA9gEhATBlTqSnkWLP3nQ(d24CRjetejjMsNMOEk)D8gxFlHc3A46x9AAjZ3mxYsB9eoQOPEhGGgQFDMkT5eVaFG7yHdvGf2M6W6pbuPCYpY0kofS6tfqAUQLeTsY6PQgKnq2i5ziBI8D3bP1ciph5biBM8xM5R4couP1hJ89azhPnc3xGe57ui8He92QH2C4llFXJse(L3hP9cY8n8IoaZTOjqJ3cjXjjipFBKTqsssrsN5rCkkRuNhrYuzMaEHZyDNIRZerBvkoylhpDYyDt()uqFpc8fD4wLhd3WuHeoKjDzAKL8(0hAKTsjY2lWlcSkdcehjJYe(neQUwiIfq6aP7VcP7UjBRWF6D6iz6TvNa)3Rl(ur7UPptfLx1YzMbyfOJ2vNu1UnEVyrOYWDI0LKu6unUvEHKCDpkwCdu)wF5XXFRPppChAnLs4bXhJtHqtFH27Tepr0TKIxuSqAdAgMtNN9Zgsaf)fP4piOOZlepsC(eDexIlyY0CXocM9ZyMDwCer4xj5dtFkCNDLukXdroyBdJZtGj9j0qyzaquQpe5qffoAsorXIjdfeJofkyyw6Mcf2wqrqRgb6dOpdAYXWK3mArbXVH2SiYHEOf1MWlqZnvX7FubQJuQl8p)W6UZipqVAzpDBJIoRtGEVfF6IjpXki)bf27wvtd6E12kXWBLlzx8fkWM8t8rkMC626nJqAWWtQB0HD5lVCKnScgciNKCkYPlGmkc4drkjZk0pZDgbvUw3)0nZlH77xn489ybRRRoJatHukoRCaYRRMF6rHzYIKeMQHpw8I16JE12DelDvXED8(wZcDYRto7Dax5GJGgPrCkEQhgM2deGCGGuiv61Yl0bF8GOIBe2kRfa5a69UTWBdDYVO9eeM1kAMVSEMfPSVEGqDzz4iGkwyOvTf(UVT58YlcLxk(DJWY7XiYxEO5o2jJiFIrP)ZqdiFKDfHTzqypwl0hTfeZ0LBBodkb1T25afPph5YlARqNLIY3i3SnYvY8UMpveBz8u91Ihl37CELDneUHFgLXsfk2qO(A)WE6v5INHvTYrhvEOXMzY3qp5XWt3GL)yZCRbKpBVz37oZUZZHpoXj1bv5WdAo9OyzcNEtKpZ5GLiiF9(MzIbM9CNf6pYvh1iXsjtxazQ7AMW9vFTKlxiiIclMHlk)D00rPt42gzWcHArlL1qTaJFwaqbKDdSKQ6KB7DheMGldcuvDMi1NJmvgFM3Tr5dEaLJDRSN5gS9cT0SNB4aaNCfMHbZ(LdEaCNbN8CyIyrHFMPpTYoOzNfTHZD4PLVXzjxDy9DfNm9Jc0c5Vdfn)97AvK)bKgi)JWWlZJWsXF25aiFPjM7voyPkJ9wQ9DAN99mxVhqBr5sVlRZK3ZU1Pg1BlaDsf5HhKT8lgXHNWW0VYm34eQfEZJdseLJDa17TaG5ZCeg)3y7Ajt)z(kaVM83q(BbE7IaLmYpQTnqgRnOS3ICXimurE74WG5hHoaunIEbqxK8xZudxJn1qwB8rvUacYSAL(QfnRaX0yOuwyrDLIEzWs1gqHCIuz6sc7qGRc9jQ1EW9N9CxEMj3D2x(8ZCJdaFR037Xm2KpZEbDFM2oWhKN6kYV0(zcsGPn70hC2tpiYWFTritDB1TDG2KHPoTbpq8XjxLmfO3rNpHm99J6CSzxIJ2HsP7a80tUkZ5e4ndPRPBdqN6U8s3lugd6BPTL7uTaqOX0aPDlYVOGIm0)fYvVJLfednUKC0y2QWn6QPYSy1E3CftJcpv0pot0tx)fG8VDUPm1yx6zsn8Ro4yLBbX3LI4MGf3PICKDe3GIu1yPRsvvTjF6BwdmCa17eGpiMcdadRwgfaD2vYSo5roVkhW0osdwrigMAAmLTmT1eObtpQoeNBYJn7LodItt7STMPcDNIWXItCOQrwm5GJI(Uzx8kWoQq8cxabDKKlJiQlDhlBChGRVoZSuzKtcw4mBhZPZY4XHzldZtd3OTHtMOZesSfOnmn4c83H5ee46gua16KJ(LZHPCq0tUQHm5oFBt2VpKn7xA2nd2DxniYMPgJcALrTfj)un7qY)eyzqMAuSAMbeA1q(zFzY)CCYppo5)SnYVezgK)duv4R5Cihuplsi)gGlDBZhWn5)cIq8UKFnYCDFSHdmy8bUPO5HiB0PziHEMdspNeikydDDqdHbniczQCQuLEw3E4PvTLSunRcuLFrQ9agvkvCwpeALM5VwRuLLN4wGpylEbC2)MbvZmfqnYdOy(kz87vtPSp9(yQmpOJINUndwIobJr3Khue1)QfEHLkmJAncwfZ5MGnH3h0rXUsWqe4Bz(j45EPBPCG3WfcwTclocvjykM1KDMOgdCnpJggG7H6eyC6ShS4bjxLgfDkEy6S91wC2hC2gkkMB0dn3oEje9xBFz(gSLRN9chvEOx)JUzFWuAQtJn0yZEUD8r3S)iGbIYo3DvZo2vJarujFK9rUozImFvL(oM8i3yvY9pMYiV9QyHwUkwGMzEy5X2ZSJDrwKCawv2nofjGmye91NRN(vg4nHrK8lDbiIbg5GJlk1zXgptjYhCqq9F2B9sGVrA(UETzM8iMPzvr3uqF6vDWeBX5KQta0pO6iGBdnVe1bmomcBHe0yl6vBv9Hf7Kdcg4IzMGfh7hDZJxeMCTq4KaDthYqen65vbyKoxp74d6zeGj9b98Qk9DKz7z3WJm(fuclkjioddSWyRFyp7aAd8ndu8huwi(dklf)bJzEX(zxzagUaggBgH5gDKz7FCk8OvhaglNObNfcC0DYtCfKAR72DYwKcD)ZQQ5Q30OXs3QAzXjLC)ddpYwiuCYAl(9lOeSWGjaxI4d412R0hJTl4ABqOpP01KQzjHsHfBOF312Q9TZwTSvrpA(k8869isVhVLZw0EPLSKYRS9zU(ElPmAJzNRFfb8ojm8clv0odfoZXAlOqT5(RWV(oZI)vKTbmDFVKsVg(Txk9NbkYZ(2)piAD1TKkQ6z0(ZFzSM)SvUzFFBmxd1EUkBpVm1Nd4kjSAEjD)(LQE(ywid))GwO3ubnaXn6RlbEDyX68)0v8dK8Nt8B9wyRLF1(uxEk9hO7l6pqAjGLRPhM52LuILKgrfoRkamiXVnrXohA2taf1oph4s7awlthRyd0XAGImDCVQJPfe2Qpv7PTJnhzjdvFaIIVu4N0BfIn1FnfN8c7UOUcO1Q6QUu077tV69J309dJgYmv0Ssq5P6N(jQCfp1txbOHW538T3e1ndtpmdQQDD1HwKwGy1c88P0QVIkW)8BHJSricD8(TiwE9IQRLRXma7jGRSfv8HQRp2tsvP97Zh9F1Pf43MiFeINS8LbUn87QaX98V0VF3USQmXVF)wZFh1BVMPijnLdeECW52UWR54q0nDq40RbR5JpVO7Ltl3TBxZ1VaSUKI84SqHLsAKLOQh28Q85ItBlwhgckxTGPgqMqivq6pFVZl2oBrBeSXA(mr3MoLV8G4nPl5j5RnrND8hWRbJNz(fSEwt5UHNuIvTA9U3E6CeWLZpuihUcm9cZWKFG51Yu3ubBV)CyxPEnFnLyJ3tMAOLKiFMKjlJLYJ62sMqSlwog5)OL0H0AIRPL4dqPoZssRo9TglXZIHKS5Li(CPGik0W9szDLE2ixMnDiCq420d2LwM1qo1ek7)sWAIvUsVQ3nl2fD7Ihn7BF2zU(4UmJT1DHMoAPtmtp4HYuVmvS5Tzx6A2u3IAZlQDl)1NhpVU2(MbQw2ofdqQ1Tuds6ubHQl0JhScAkW431jmC2e1zpC2KGj7I31wSSq1SIqv7slyZz5Sb1v9J)uvf0LgaAioBGGzaDO8Qn8D3MhKPhzkyIcyjbSfKOz4yixCeYSHyA(8Fr5imNxnP3ivlfwhuMp)pRFMgTrHupxB2p1dgoK9o0A37oVrPtmoFof1sRq2(Cy)vcHQnTA4KQVecSSblwzrMBKvBytruGgZ6ukTKSNByyDtqu6U4SWs2hRFf5cKNJk6XDysYBAk8MP8w3J526BbJYOdBZBII1sOQk6ZbYmQnxpDUeJBaIULU10ctnTEDpJUvpRa6HTeZ67Cal6i(LhBc)6Z63SAHS2rl3qcrH(sdco587mkx9(LUlcWcTN9gVvU61roVJEnh9KNZqFpeJxUtoYpXJRJbBQU6eOePiGCwcupI1zhLrV4D5kAkMUiliqmV5gC3kd82650lEQDSCR7I9)XoerG8qpJ6MC2cbu3Udig)58wpylHdDTZOxBrPigVPSGrJFRXMAdn2DsnVP0LxPnOjMHwrEsIGGcjrgt2v6thhZh9nFxvCiuFR5iSn63ruZ5kIzq3cPBggz0TAGQwJm2uuXUodGN3R9XMyMBCa1S7x)uxMAp6hwS8qxqP)xAMBSNzUEpGcJ6TAyO(u3OvMwnL6WZ0AN7wEpV7mxFa2zWjVhTtF7J9sj4mnoWaDlnNCu1u3DL(Q0icthSwShqElJ4YbV12QoMF(RfVJLIMJGZRskjqoKeMpna8uXoYEHOonZWuXcQpa)dL2ZD4jZZ2j9PZCAEYsqro4LaiD0sm3uU)p6M9537QlvfrMzOobc7M5diOJ63)cruQY9nJuRaqLlEjSVxKILawsLKNXZLJv46xVo31ZDS8wZtuuYh2tVL4s)PFfy)DWQgZRfkIHwcbtwsou)zuPQQS2rxzPGCO6RD2C2089ErPUeNQ1y6dLNln9tSp4lnp1JEGERnz79b6n0yzpgJC930hWWeBztHRFDTOjj6Mx0Y)ARyJhXw28MAULqR1fyYRwhATn2sOCLL(A9s1BY388rfYnfQHgYtq34AQV5McfopGSPQd3YMYd4cxnenA(151VUMBP61vtOwRznv3I3W9PGIIT96OzqLuBBomPavMM2K(pOPgFz(G1(crfhrFPoMBe926q1L8BBdORnuDvV(gAHoABTUWvV2qpD1XS3VaYrNevc9G6)sNpOslhTG9Ulu4Wng221dB91hsqiTGi98jVx7ihdm2Bos)oVvMLYE)DIhluRgDMlV39CfodIs9vtzlHEMwAT5Ac3ydn0ADRFD10s9nUopP4)mxpfo3iFMLQDYhf)n3TOeFN2iNCZluTDCJzywDXfEGDqOOJ9UkJUHqoQt7fzgwRJW)Da9ZPIRNZV7yBjsoWJZECjSEZnSVeeZbCFTiiVSM4CsoeS6SRYOVWeOVLtW5NkvBGB7fCIRVL1YBSBram)3eDVuxwl40dDOzF0Y8FKqS(uW0HPIYtFl4ct9vVO6Be3sBiuRupMTwt1TeA1ngEtTQ5Tlqr2E)UvFQGCssj5zxtKs9ZMTYngS3dFlUs9hW(vp10lPZ7j0Z4bUJv2Bx0CGwas7CQfOQJxJU7b9eQqXFoujSJoG6rPQg9RD2fE3dW80(dSWuZGwyYutVCCECx8U4c5KFIrltTrntGVMNuy4Ebz54GJD5ifcK)NkWsxQhNkH(Hsy6mjmDKegr7ABjDSnVIMau0SFX8EbRMQtyIv4y2cTExDI(Y880sOV(084BBNGJTUTQC1T0ygZr3YEtWz6LJl(TUnAzw2F9a6GZin6d5M2wwUOnuBEEPmtD1cOFF8C1VuRLpL64LZEtpA4EpqU0jOUy(uIswHbLqDNNlcH61(tj64jmOdV8fzvRqFQ0pLiONCZwFLuNtv(CqOgbsCVsM26lxtAevk3i7bPeVZs)H4ju58DPL6RwUVPXsjA2(7nb1L4GycagDHJVyNRrd7LMWX7QykSLNI2Gv6cT46K2TBF5fFm8eoFVSGG)IWMs4)M8UFU3VGFV4VFb)HWFFE4V7RT3VGF)4KF8J((f819VXQj)pN6lvmzQBNDpVlUhUtmGYaVb53(Wfo3wHsJiF0rM909q(TV8LryuFhc1)fvoX4amf8u)70woqVk9mSsFhBUB(sqP3)1FuS0zNEe5Hodu3mtCfe22(1yPZ9wht(kxrh2c3ZFmfV38nvU2Pnk9xmd23ZoWvKhyVKF7N9fVwXys9kpXuZDXEvELBiVVtm7(ht5YxfG9Zm2pJI39oK8fpOspVXC9CsO0fvupgLMD8BnxphNw6GgLkV7ZdJxAP)vyPYh4K4lSWJFvySG493)NthfNUhLEohBecuYoplf0378ZDXxgl84aj8zBFcKAZUd8gxbpwsduMYoExGy1k8HxuD)yAP34cY3AGzU(BOCSdGDY)V)Vu8DM3m7HhuzW9kFZdJL(Bg89lOqqk9LmsD4)32iKpZxH8RE6Ts(jF2YAh7VEX72d5dJtuIt(3It(fXj)RTb1URDH9Zo7l7UU8CV(bqk0biF2ktrraEDkWYHA)qwTXj3(HV)SPd(cPt3zbbXlbD8rLshDRSlvoieFg)jIDB2nbJLd)3LDpBP6(yeorGLIgk06gNQT3SKaNexHKlZfMlzM4CfwvxjInEvBOYM42yLvTCUOcjsH4MpE4O6xrZXv)FpkyShrQCzl)jR6XhhV(XcSBV(dL5Ht0rQ0c8QPjti8f)bBb8TL5ps7khIRAU2eI4Dhlw8flgzzL)eLx5kw8w)jpZ))d

**Comment by mrbuds** [comment] 2022-04-18 09:39
I can't reproduce the problem with these 2 auras, none of them are trying to register COMBAT_LOG_EVENT_UNFILTERED event for condition.

Do you have an other aura with a condition with "Custom Check" and in "Additional Events" field you have COMBAT_LOG_EVENT_UNFILTERED:SPELL_CAST_SUCCESS ?

**Comment by zcqiu** [comment] 2022-04-18 09:48
> I can't reproduce the problem with these 2 auras, none of them are trying to register COMBAT_LOG_EVENT_UNFILTERED event for condition.
> 
> Do you have an other aura with a condition with "Custom Check" and in "Additional Events" field you have COMBAT_LOG_EVENT_UNFILTERED:SPELL_CAST_SUCCESS ?

the second aura with COMBAT_LOG_EVENT_UNFILTERED:SPELL_CAST_SUCCESS TSU visit: https://wago.io/14uZu4dOt

**Comment by mrbuds** [comment] 2022-04-18 09:52
> the second aura with COMBAT_LOG_EVENT_UNFILTERED:SPELL_CAST_SUCCESS TSU visit: https://wago.io/14uZu4dOt

This aura doesn't have any condition with custom check+additional events, must be an other one

**Comment by zcqiu** [comment] 2022-04-18 09:58
> > the second aura with COMBAT_LOG_EVENT_UNFILTERED:SPELL_CAST_SUCCESS TSU visit: https://wago.io/14uZu4dOt
> 
> This aura doesn't have any condition with custom check+additional events, must be an other one

it's not cuttom check . it's in triger1 , "EVENTS" filter
![无标题](https://user-images.githubusercontent.com/24290724/163792236-bb13bc40-c4c5-472f-bb95-143017ff970d.png)

**Comment by mrbuds** [comment] 2022-04-18 10:02
I can't reproduce error with that, i will need a minimal aura and proper reproduction steps, if i can't reproduce issue i can't fix it

**Comment by InfusOnWoW** [comment] 2022-04-18 11:07
Specifally UnregisterForGlobalConditions has nothing to do with any triggers. It's only used for conditions.

You really should try your reproduction steps before claiming that they reproduce the problem. Otherwise we waste a lot of time.

**Comment by mrbuds** [comment] 2022-04-21 11:47
I'm closing this until a reproducible example is provided

**Closed by mrbuds** 2022-04-21 11:47 UTC
Labels: ⏱ Awaiting Response, 🤷‍♀️ Can't Reproduce
