### ISSUE TITLE
Managing Lots of Auras Is Unwieldly

### ISSUE THREAD

**Issue by antoinne85** [WeakAuras/WeakAuras2#98] opened 2016-09-11 12:15 UTC
As you probably already know getting all of your auras set up for all of your characters can result in a lot of auras. 

 It would be nice if there were mechanism to create a hierarchy of auras.  Basically I'm just talking about nested groups.  The ability to put one group inside of another several times and for that I can better organize my auras. 

For example I might have a group for "Shaman" that then contains groups for "Shared", "Elemental", and "Resto." Under Resto I might have "Healing Stream Totem" and under that I may have several auras. 

Beyond the nesting, other behaviors should probably remain the same (like inherited triggers). 

As for how to represent the tree visually in the UI, there's probably a lot of room for interpretation. 

I realize this is much more of a feature request than an issue, but I'm willing to help implement it if this is a  direction the project is interested in going. 

 The Lua isn't my day today programming language, I'd be happy to give it a go.

**Comment by InfusOnWoW** [comment] 2016-09-11 12:56
Duplicate of 
https://www.wowace.com/addons/weakauras-2/tickets/64-nested-groups/

**Closed** 2016-09-11 12:55 UTC
