### ISSUE TITLE
Dynamic Grow doesn't account for height and width changes in conditions

### ISSUE THREAD

**Issue by phoenix7700** [WeakAuras/WeakAuras2#5360] opened 2024-08-29 10:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When making a dynamic group the built-in grow functions don't account for height or width changes that occur in conditions.
https://github.com/WeakAuras/WeakAuras2/issues/4057 this may be relevant.

### WeakAuras Version

5.17.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Setup dynamic group
2. Put auras in dynamic group
3. create condition that changes height and/or width

### Screenshots

![Wow_Yg4u05TD95](https://github.com/user-attachments/assets/74dd2e20-323d-4261-8a7a-a5108f99ea4c)

### Export String

```Text
!WA:2!fwvtZTrrt4OSeOytiXwjXKecGXMyG8cgBfYxuuu4vwY2GSKz16Vozp7UJ0o4v7UmZSw2MtOIIkhP0bsLQacrNF5I(j4tCGdDPIFb(a)a8Va6z3voFCbDy2z6PNP7NPFEALBT8c7Bp9S3D6zY3kVBE3hmBxc3PcnOP07hg7i7qUlLBqC2XLhgfnIHp7GdiC3XTcd9LSi(E1A0qqLl(fB(x)5PWF89hA47U1T(c0qNMCMR1(r0jmxTxJyF)ImUJpDBtreXHMJtCKSWaXDmfscxQB3GfWeE6g4hPEhjN1SjLlU2u8SP)ypxQDCJgQRKVyPkRuE1kgsCHjjMtk0rer99xYvOFKi2MUlnqwh9MTx)TkoxDRTQBnNPLrmE52r(K9PCZaslQq3mXv7fPeFP3jhDfofpQz9vkvPs34GSuqVVtOFCRG6keOzZjUSyXpCUUKawlIcn3boB5dPebTUKN8s(kqEJGWa6axmhvESLkJ5cQtyGROJYvfEGjnArybLHjWdatcVlCdyk875ErlMeFwZatZLwyrRo8qzYDMRhM2M0MQNtD0JipIMHFiXTSTK4JOzmZwXyrt3aFJCgd(yDthFIqOMziyhqvtgyNvRlg6hY)snnTv0Mz6BxiM52VW93KxO1ElCVzquKGvQxxb1VXkHSazpJAww1wUsPYwMchmGA9CWGs5jf)kM2PCjVEPFl52KgnA9VnMWPJxg5fJVUhts7XtaG6mh6UpwByon5HXrzNQoMMNXqeYLWK9tnLMO5YLt7yMkCbe)1WNw8sE4asS0lKxlkHIPBJV2nyn1pc)ISTazzK8fYTnNB(LwTExHKgnxqtF6BFy6nNYKFv8bUDAPUNm0z307(k5(J(tWCluL2UFdosHWsnrs06QO7RZCLEFWXKahm6Lv7QWJD9IMLkvTtSGwH1Ij9YaWsbyu0mqy22ybZLMVF65sEuTlwQQvjttF1boBpfDHLcM(SGgH8u(MohHJIzMlVZ1EW73JH(vpmM7qV(PGZKRpX9BIr05UmzVt)0fSGtdVCoyvyTboOA2nSDq92Si62hoCPQg5zOUTTHZF(PGl8Z9eEHTl6JuzX2iH8IWLHXGRbVbCD4nHlPdxvhED4kWiWOWBPhnQsCVl1kv2SCOl9)FkO4dpkIh2KtfI0C8Mx)uNgEhLM5f59V3)Tsa7giisLQI6b)VpDmi)aufOiXkAtG7dUuuEjDp5wcpccPnsRP5IUAIXKH0NXTeztGj7EYEtCdr0ipZXFkx7OuRdj)gZTQvTOlMyejDHQ6ItcnWyoC5XPbIThnLB89dsRXBMLohMSVQUWASpSwVejn1cnAuTw1sqEockLp9sC0zO2uRBgccKrJuMZoy8VoM4QiIJBz9CaFyKgKyRns8wNtI6SE2K0eyxMGzJ9MZW8ZWdJgDPQvlzUvQgpPVZGtcTsuE1meTXZfh1UjnQRTQvLLQw6Fg00pSDzo9BJPbo7VYlnZ0fUDk6uBCOAy(SwKADuRuNEGDSuggudLEyl7EkZP)b1L7RMpeADvloPTL2HOoBHHw8s88KKl5M9yo7G8yHwYbRN0YYqn1lXqfgU5OjrZiTZLThL10t(9WhvgMw1SeMjzC2KXcQXOrWOoxMclrW59IMybEWNdBdlRbFs)7x4ElVW3yEazDbSPoOJQaD4C6WRH9Mpbjgheg2kx0Lgklv8I5zccwQC9GVkRvKj2kA8cqnyLO8yelM5mQ6mrU02MTtiEWhQbL05SavFmQ3X7qXMEQ)pqAQE19G51HnU5uMoEuNDkdxqRZUeotfQod)VlZDj(X0jMDMjcJY)zChpsqtQ4Mtbp(jDqLnwTL7dpsTeEc8ttb)I6AGFf(nL)Fo84jkmd87k3)AC)hL99N6meDBd3fwl)U)9g)l
```

**Comment by InfusOnWoW** [comment] 2024-08-29 11:12
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/2190

**Closed by InfusOnWoW** 2024-08-29 11:12 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
