### ISSUE TITLE
Rip duration not updated with Ferocious Bite and Sabertooth talent with multi-target aura

### ISSUE THREAD

**Issue by Dunati** [WeakAuras/WeakAuras2#1179] opened 2019-02-11 22:31 UTC
**Describe the bug**
Using a multi-target Aura for Rip seems to work fine with a Legacy Aura, but not with the Normal Aura. The time is not refreshed when it is extended with Ferocious Bite. Converting the Legacy Aura results in the same behavior.

**Do you have an error log of what happened?**
No lua errors are created.

**To Reproduce**
1. Create a new Icon Weak Aura.
2. Select Legacy Aura.
3. Set the Aura Name to "Rip"
4. Set the Unit to "Multi-Target" (note, I know this should be in a group, but the behavior is the same in a group and this simplifies the steps)
5. Set the Aura Type to Debuff
6. In display set the text to %p.
7. Duplicate the weak aura and Press Convert to New Aura Trigger
8. The Aura name is not maintained, so set it again to "Rip"
9. Position the new Aura next to the old one.
10. On a feral druid with the talent Sabertooth apply Rip to a target and then Ferocious Bite
11. Observe that the progress timers do not match and the new aura is not correct.

**Screenshots**
[Screenshot](https://imgur.com/a/RBvdySR)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.11.3

**Was it working in a previous version? If yes, which was the last good one?**
I have not tried.

**Additional context**

Non-working:
```!nsvtVnUnq0Fn9qpSlIK)mh96vEJrtKsnv2tf0MsIsIiuKcIuXX(q(T3ziLDm82f1agY8JHdFZBEpsdOPuIGghmkmysiLyOKWVge81rusdLuG)GaS83THpRfklLSmkonAJFTGvALLioYHeahoxRLf69QuyRifltYlOFJsoKuwA4w6QPHJMmB68jHZMnpy(850YVmEgLWu516URs)PCr2lA5ywY7nwDdM6xAlywoL0p8)PqJkQ40mOCY1k8e9gELuVFPwQ7W1Di(cC9kN3UW0YZTBywHgdHPen4yfw1glRZIdk67ClU1EaWcXWHlOayk)uLwXPaYByc1ThDPqjm13C8Wjk4gMfJ1vKFwzPa57(f6(oY9Dm(1ouZdu73ssttEAZ6F8WPwk2(wjzvWTL8s6JRJJOKAUOQ2sJNoMsKAMR)NlzgdoOPxAfWahGqQ7xwei9Tk(BChJBqPXvrGhKllVQDdt4DkM8N8ods)XbbdG)glYWLqTaDGgoM21XK1FpYZsPoEmR3A1Qeays2HluVuYQoXXp2939ScGBzFSln9ITVMDE)KwEYK5bJMF)4jZVB807Nnf1YJpdL)xi3XRGY0dnNEfuXQsrLJKCW(KIn8tpwiCb7ff2AF3HjBRzy(8WLs(J2)rfZ3d70BbhvslkRm(uEuRBOX3nKtmwxyA0iu2XA4elw(U0jaF)gr7h7wdG6JDHxaKFpDfEYzLDYrVctRVejl3effdBKFcsNDxx6fSOqqypRLqGKo7Nhz3)N3)Q5VWDHgOXzaYVbDrNOQcI3hv65fWHGo9hD6(2T56EOSYq)RnVMBi169jq)W4(Fba43qxzFgiQv2N74LI3Hc65OhF0R2TWZpwrlMIS(YYFZ5HzlLGx2GeU3AZaZCOphfC8OlD2SSpVncSiEBBxUGKULKUyd(EHlwpV(WInpT6faiUWH5CMeKhe41WeL8aExGlvkxxmidW7ubTLbobBZ4Y4s(jiCIXz(hq3IMCrPiFBp2yC8EtMqXFYZw(k7r9EUzinxLz3XiqVUI77PQpBcUfyogk1V4t6cqN)LG7WDW3bfxiHnwr(Rh((WZLNFr))Y4dJEdqX4quhq)3)```

Working using Legacy Aura:
```!nwvxZjkpu4Fn7LTJGFUxATqRVJf6AO77n7encbmtdjmKqT2l83(EobPA7UZANXjaNC(6558HupAcLiOrE999g6tjgkX)ApVR7tjLusg(duWYF16)OwOSuYSGOKGLTY8c1klr8ghCay8RX55gULg5py01J71B0K(d)E)XdPK9hVjCKF)HJhnzO)4Xt8Mmzcn)QbJPeMkDRU(trivRLz6DkYorfNEdiOXy1LjqGFQkJz5usZXNDQgKvWPBaeLQvOf2ArrbV2aGiYb1JcCVUh8kH1uZay3SH)chWstEU4vkz1SPKKvKKPlbfb)gRK7r)5uIsUNZK2Tq4vc4llRUaWgzdymzRExScCO750uR4fiiMkUuopdtdqVgdFfijvKlsx5CbKXkwjO4srv7RhZyNa7P87XAUl)ipgSybuC4ymtCa5(PlFi8PfUaOobtlkG5YJKwHpOZG61vE9WBCvXafBJKNHa8zoVAkMC2LmRqJzgtjkX3viPzaWApXEkTcoZaoevyvRqdhyFaSG7lzc1xx7CHsy2(L13IeGHzX7Dv9cPE3mTux3sE4pF3zF35a8SdZh71Ujojj(HLZV7(U2CSLouYkGjH4NswmpkGs2YffBH(6rdOePM5MjsLmdwLiLnsROJPrQ7peIfCfu)QXK0GJlFsJUKAgeBGXkDnzZJiZVnWz9jGT5SbpkjSw82H1)OHLbua7W6Koq8xDe6L2ELnnwRwfdzKKT)9yFrIl9YQ0iGDgcwCOj8U)VX8FVNpx0YAEbuKBZp34RRRvRmN32b6jWbMKp0U02J7wHewddpToHmBzqq0zv12fv(dokQRRhRjwr6Z7V9yJ27KmL8TQFPwWlyP7pZp)dEhTGsEtRlPr9WLlwnovLJzfS7bu2nvJKemzFy9CaOhw3gHdR9DwaOiUQd5iWKvBBnBNid2646cXAjMNG95IIoMbkOg(h6r(CNC3IsCj6zJ94iL4SycZg8Aft(tWHiJe55HtEY8pUIgZoS8GBP6(leq2lWhd8XQk93)```

**Comment by InfusOnWoW** [comment] 2019-02-11 23:40
That's a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/916

**Closed by InfusOnWoW** 2019-02-11 23:40 UTC
