### ISSUE TITLE
When using trigger status: Cooldown Progress (Equipment Slot), hide the item cooldown when "show global cooldown" is not checked

### ISSUE THREAD

**Issue by DawnAliceRosaly** [WeakAuras/WeakAuras2#1739] opened 2019-09-27 17:33 UTC
**Problem Description**
I'm making a general WA for all my characters to track the cooldown on trinkets. This means I would like to use the trigger type;
Status: Cooldown Progress (Equipment Slot)
It's frustrating that I'm unable to hide the gcd applied to an item when using this trigger type.

**Preferred Solution**
In the trigger settings there is the extra option toggle "show global cooldown".
I believe it would make the most sense if, when unchecked, this would hide/ignore the gcd that is being applied to the item. (as it does for the spell and item versions of cooldown progress)

**Alternative Solution(s)**
I have been unable to think of any remotely sensible alternative solutions.

**Additional Context**
example trigger with unchecked show global cooldown setting;
![image](https://user-images.githubusercontent.com/55891575/65788730-fdedbb80-e15b-11e9-9464-64b37c796750.png)

**Comment by InfusOnWoW** [comment] 2019-09-27 17:40
That trigger is supposed to not show any gcds and as far as I know that works. 

Also please answer the questions from the template, e.g. the question on which version you are using.
Which wow version, etc...

**Comment by DawnAliceRosaly** [comment] 2019-09-27 18:45
I followed the template presented to me, perhaps I misunderstood the difference between bug and feature request, but lets try this again then;

**Describe the bug**
I expect my WA to not react to any gcd. It is however reacting to some gcd's, but not all. I have not been able to discern the exact pattern for this.

**Do you have an error log of what happened?**
no,
did the /console scriptErrors 1 command, installed bugsack & buggrabber, restarted the game and updated all addons through curse. no (weakauras related) bugs were reported while the unwanted behaviour was seen.

**To Reproduce**
have an on-use item
make a new icon weakaura
select trigger tab
type: status
status: "cooldown progress (equipment slot)"
equipment slot: trinket 2 (where my use trinket is)
>note that the extra option show global cooldown is not checked
find a target (I use a target dummy in orgrimmar)
cast some spells (I use fireball spam on mage)

result: the weakaura sometimes shows in time with a gcd. if cd swipe or text is enabled, the appearance is as gcd.

**Screenshots**
there are 2 trinket wa's on this screen. the large one in the middle is made exactly as described in the steps, so I will focus on that one. I cast a few consecutive fireballs, which semi-consistently causes the WA to show. in my character window the same gcd is visible. In the bottom left is my action bar, where you can see the same gcd aswell.
![](https://cdn.discordapp.com/attachments/368431871425773580/627210603618107413/unknown.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes, the same behaviour is seen.
![](https://cdn.discordapp.com/attachments/368431871425773580/627211329446477854/unknown.png)

**Which version of WeakAuras are you using?**
2.15.1
![](https://cdn.discordapp.com/attachments/368431871425773580/627213528083726357/unknown.png)

**Was it working in a previous version? If yes, which was the last good one?**
Since my creating this WA, this has never worked as expected.

**Additional context**

export of the steps-based WA showing the behaviour:
``` !nw1xZPnoq8pn3mTpCza3KB69iHZPLzO2uKZD9ErGWETTUAlrKKHqEGp73Us2bt6dTZWyK3)(Bx9BxZNYZ4mjpz60OjF4U)KZSCw0ntV7MPCwlNvq)qlQA0h574mrNRwBs37KALfv44StPLLwWXtMGQv5O6vAPcvmpojlEnNLR1nf6Jk2r5EGF)fbXfvGpO5dHJzDcJle3sPsARdNXJbP45olqOzUUrBiVXCbgLO5VbJfddpj62aE)2iGzHMY3aRcWkCDgHZJHlHmdBg(Fr(NFW)8w6j6STB3AOQhTj(MNdE2TXwlkUoJUtyXs2t67TkC83S9VM)ZZN3UsnH7hmYxoV9RDIceZIZBZUo3Jb)eFWM4d2K3eSG1)7yK6fFPbn7XS0EPhKw5Ug)L2RijZxyPpMTCrsCV8RU3xKKeVEZ9PzzPFz9Ip95SbEXpK0)RZ6KLNUCNy0o8(iZ3MssPWh88BV1tcim5lawzrbArniRQrl(d82Vrl8Sw7EiN(VTRXjh4p5ncR9hKAPG9gHUaT4bd8uhOYpHP)MO7ccdDHDDoNwLEamnIt9kQL5FxbykWMoZPZpmWl)4KOjO3gp)j4VmhvG1OSvqJaJNayfe3efUPNjbOTf2bILsRacGTcP6x36xNP(1Sh947aSFg1hDRj7PrfNrwvHf1LjGGa6ioCUrSZQn7(IUiWBcXhVx7Sb9D0W89(zd4aG3JDLLYN5SnZNXY2WYMTEe(4SPbVQafyK5SA9Xuf5(1cyw))Z7xTCj6RmGp6SvXlxgcL0bTihXdIxpNm9wpHPPzrr)MnLOf6p2P8bZVauZz9VmKTZBxz0vg8s)823f)uNCFlQ)8wkWVNCgly2EKIGnjCVZoSGd3)FoE5QhECzidJAJxHk)9aTJ8aKfmX3Bt(9PtgOOlLiJdzyH3gpN1jXv4V)D)t6SI9IxOM5lADRx1rzHRomWmSrMM8(lPvGZ8f9R71(EngvwUOb8KAkKoWsOQzFTWlR0GnlKjGRM8VhMBFGKgkv281XXjuQ(Pl9qQyPSAyZpn)86k6LGQIanw6HHh)NtufYrFq65rLp5Z9AtbqFQa1DG6Oruw4)p ```

Export of my own WA that has the same problem:
``` !DAvxVjoou0FnR0opmvHp6Qos7lfgy3rIbyWPJM9fdMetINgStTDGsFGF779ANesG2PSRek4yF89JJV3JdTdnKse0PD60nO3TFIsmus3B6C7nDOKTusm(dqKKP2txtjppBZgd3c4VlGsou92h709wkHjJsv65kH0sjdhnnC0ckjsPYIv7LK9ICoDWPjgfN4ExePK4)fgo6LHQmLgDfyfUwYY(oxBeaKPD7tjpY553BY5r2fmRqH4ysXwCSeJtJLPT4a7bWBePscpJl0oal9tA4GhJnuii3YeYRh9gHuysVA8WoI5gMfxNJr6P0leiq3VUUN9Cp7JpHnzkwVGNaw04XH(J)SDPjLb82pQ48GQWaWJRxIYp83YlFn699Nd3gfEOnwlE54QVvWIHyMDCvyBF3m4dCglWzSGZmMh9)0msDtZZ2uwDC)dHZOeTYcutOlINoB6OgXsOl1M9q4KVup)RwF5N8cF9ZcJvS5WjC1wMiEHdbB3QT(JZ36oHrSodRnDNHPCrskSCFy9mfZ1oGvG4)BlYScyGdyugZyUywd6UZM06RfgR5pvWLrhaFFd2azvr7QQ2VlOBWTECEUyDH1QKZaazSdLlKkIEuYbVcKpjxRs0WlZ18iH3i994MiaqGjbpOfjjGlovz5NWPcy5BNY2IKZF8PED6FQ0MsaZNWLCTiIKQ2pdMX4(FyzZm0ma704YpStEjUCsuSRrgSlWCOObAt(6InB8P0FpAY8XpmPUqgQgka9NcjFhhpJzfwf(QagNdzneNoJxhPdCv)o0eWQINPKLdVNeUKeE)IWtGDUhaxA3QO(4Q5LC2Xv)(ONke5BH1pUcH)b3PCw2xIBKvwUXowPRZAVS1Y2ut5KS1gLE9xvX8QzCjsJqgoOCHmz(OjtCUq2444D47wSkwsbTJTpp)LKARJ2ld3)Je1RMqxW(TleAYiVb3(QuWcol(WBX7Tkv(vLgxfBx6QlOAsSW8ZczKvSJJYiagM7LqVbDSOxpu7uY9L7UB68nKCzInfGe4opavOz52sfFujrj3isQg)Uc4EDSXAOJW7iYWfJgnfUWcNckjaTCNcrdb4ZVEgfH)SWWaHpxt7lk1wuwQxzbZaFGtIyzUuJiIDfBYhpUcLsZYtzL43lIXCd1lXT0uAUa3vYxZ)M5Pj8jFibVLhv84v2VPymsPEkP(ADlUbr5O6RJTLCwSW26wZOuE0JnBkW4EhtlWSKsun6M2XYkQoYIszYe(jZ4xBGtGnNRThADVUTrZ3Lo8Ja3OG7I)ZMo((PFUe7L6WTdr(Z5cFFAOaK7kdfSL1B0Z76VQe0ELjP7B(ktVE))4ZGR0vqZ8Fv)XrvjLhxZV2OZ5FTr7GTE79UImQ)BCG1kLeYi121m71uGaf)310z(wcBnH3uxdIJbkDmh)qx04OYsx020)9p ```

if needed I can probably set up recording a video, but I hope screenshots are enough at this time.

**Comment by DawnAliceRosaly** [comment] 2019-09-27 19:32
after casting at a dummy for a long time, I believe I've found the consistency of when the problem occurs;
when a spell is cast normally, the WA works as intended and does not show for the gcd,
however, when using spellqueing (I believe that is what it's called when you press a spell before the current cast is finished to cast it next?) the WA reacts to the gcd.
so far I've seen this consistenly for about 50 casts of each type, all firebolt.

**Comment by InfusOnWoW** [comment] 2019-09-30 19:04
Ah indeed our feature request template doesn't ask the right questions for a bug report. I'll whether I can reproduce that now.

**Comment by InfusOnWoW** [comment] 2019-09-30 19:18
I've been casting fireballs for ~10 minutes now, I can*t reproduce it.

Which is because I need to actually test with a trinket that reacts to the gcd... So yeah, another round of testing awaits.

**Comment by InfusOnWoW** [comment] 2019-10-03 09:02
This should be fixed now.

**Closed by InfusOnWoW** 2019-10-03 09:02 UTC
Labels: 🐛 Bug
