### ISSUE TITLE
Profiling Logging or Capture

### ISSUE THREAD

**Issue by wanderkiel** [WeakAuras/WeakAuras2#737] opened 2018-09-09 22:10 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to use profiling to help narrow down some Uldir lag and I have 100+ auras loaded at that time.  When I /wa pprint It will only show me maybe half of that so I cannot see the top offending resource hogs.  Chatlog does not work to capture this info, so I cannot log it and check it outside of the game yet.

**Describe the solution you'd like**
I would like to see a logging capture either in game or via something similar to /chatlog so I can read the full print out.

**Describe alternatives you've considered**
I tried /chatlog but this does not print into what chatlog captures by default.  I am not sure of another alternative.

**Additional context**

**Comment by InfusOnWoW** [comment] 2018-09-09 22:13
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/702

**Closed by InfusOnWoW** 2018-09-09 22:13 UTC
