### ISSUE TITLE
RAM escalates when opening Azerite/Heart (3.0.1)

### ISSUE THREAD

**Issue by Shadrazaar** [WeakAuras/WeakAuras2#2543] opened 2020-10-15 10:01 UTC
Heyho,

I have the issue where the game freezes and starts using most of my RAM (around 21GB of 32GB) when I want to open a Azerite item window or the Heart of Azeroth window (Shift+rightclick). I tested which addon is responsible and yes, it's WeakAuras. So I was wondering if I'm the only one with this problem and if somebody knows what this could be.
I had no issues at all before 9.0.1 and the use of RAM isn't even shown ingame, only in taskmanager of Windows and only when I open said windows ingame.
So after the freeze the RAM still doesn't calm down.
Hope yomeone knows a solution or it will be fixed. :)

Greetings
Shadrazaar

**Comment by Causese** [comment] 2020-10-15 10:07
the least you could do is export you WeakAuras.lua file located in WTF\Account\<Account #>\SavedVariables\WeakAuras.lua

Also filling out the template is important... you want something fixed without including any useful info like weakauras version number etc etc...

**Comment by Shadrazaar** [comment] 2020-10-15 10:18
So that's the LUA. I added the version number to the title. Hope that helps.
And I found out the RAM escalation happens when opening the transmogg window, too. What is kind of strange, if I'm honest

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5384082/WeakAuras.zip)

**Comment by Causese** [comment] 2020-10-15 11:03
@InfusOnWoW 
I can reliable reproduce it after opening azerite window (from gear) **and** transmog window (npc).

probably related to the "too many model frames" thing or whatever it was in that you fixed(?) in the past

**Comment by InfusOnWoW** [comment] 2020-10-15 22:38
Can you try narrowing it down to which auras is causing it? I can't reproduce the issue, for me wow stays at rougly using 3GB of RAM.

**Comment by Shadrazaar** [comment] 2020-10-16 06:05
So, after testing a bit, I can not find a specific WeakAura that's causing the troubles. It happened on the Warlock and Mage but not on my DK for example. I have no idea and I will try again later.
But I found out that something's wrong with the graphics engine. It seems  that there is a problem in WoW itself. As soon as the freeze stops, the usage of my GPU changes from "GPU - copy" to "GPU - 3D". RAM is still on 21GB and graphics card is at around 80% usage (Geforce 1060 6GB). I have to admit, my GPU is a few years old now but don't think that's the one only issue here. I know the task manager isn't very accurate but it was interesting to see the process while trying. And in every other game it works fine (DOOM Eternal, Witcher 3 and so on)
So I heard WoW has some problems since 9.0.1 and this could be one of them. Without WeakAuras it works fine so I believe I simply have to wait til Blizz manages to deal with those problems.
On Beta and PTR it works fine so it's a Retail-only problem, I guess.

**Comment by Shadrazaar** [comment] 2020-10-17 13:29
So I believe I found out ehich WeakAuras are causing the problems.
At first, as I said, I had no problems on the DK. BUT... after deleting all my WAs and downloading them again from my wago-Account, the first DK WeakAura (Frost) started to cause massive problems as soon as it's was imported. So I deleted the runes, no change. But after deleting the runepower bar, it worked fine. 
So I downloaded my Blood and Unholy WeakAuras and again... problems. And after deleting runes and runepower bars, it worked. 
And then I tried to only delete the models on the bars. And that worked, too. So that, again, seems to be causing the freezes.
If you want to try it for yourselves (maybe I'm wrong after all - i hope not)
Blood DK - https://wago.io/rEQsvl24V
Frost DK - https://wago.io/r9iSpre-G
Unholy DK - https://wago.io/kspcn_thB
DK Utilities - https://wago.io/mZTsSXImN

Everything else seems to work completely fine. But I will test more and post anything I can find.
Hope that helps :)

**Comment by Shadrazaar** [comment] 2020-10-17 13:44
So I tried agai and again and again and then activated other addons. And then... freezes. 
Now I really have no idea what is going on. I'm sorry, I don't know what to do to give you more information. :(

**Comment by InfusOnWoW** [comment] 2020-10-17 20:12
Well, I'll try to figure out once more. Any testing you do, helps in narrowing it down.

**Comment by InfusOnWoW** [comment] 2020-10-18 18:16
I just tried again on a DK with your auras and I don't see any explosive memory usage growth and certainly no 21GB usage.

At the moment I have no idea, what could cause it.

**Closed** 2020-10-25 19:48 UTC
Labels: ⏱ Awaiting Response, 🐛 Bug
