### ISSUE TITLE
Could Stacks carry ItemCount on Cooldown Progress (item)?

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#1126] opened 2019-01-25 18:35 UTC
`stacks` is currently an unused Dynamic Info on the Cooldown Progress (Item) trigger. It might require the addition of "Include Bank" and "Include Charges" in the trigger settings (like on Item Count triggers) but it would prevent some common Custom Text use.

**Comment by InfusOnWoW** [comment] 2019-01-26 11:43
That's a duplicate of #929. Being able to use text from multiple triggers is coming soon. :)

**Closed by InfusOnWoW** 2019-01-26 11:43 UTC
Labels: 🛠 Feature Request
