### ISSUE TITLE
Weakauras is gone!

### ISSUE THREAD

**Issue by helloEarth7** [WeakAuras/WeakAuras2#2065] opened 2020-03-23 19:52 UTC
## Describe the bug
too many errors comes out.
'/wa' not show any wa menu.
all the weakauras is gone and display nothing.

**Do you have an error log of what happened?**
2x WeakAuras\WeakAuras-2.16.6-54-g43a63f5.lua:3810: attempt to index field '?' (a boolean value)
[string "@WeakAuras\WeakAuras.lua"]:3810: in function `Modernize'
[string "@WeakAuras\WeakAuras.lua"]:4297: in function `PreAdd'
[string "@WeakAuras\WeakAuras.lua"]:4432: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:3966: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:3973: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1624: in function <WeakAuras\WeakAuras.lua:1596>

[string "@WeakAuras\WeakAuras-2.16.6-54-g43a63f5.lua"]:1752: in function <WeakAuras\WeakAuras.lua:1703>

### To Reproduce
don't need to do something to reproduce.
just run the game then WA doesn't work totally.
**Which version of WeakAuras are you using?**
WeakAuras-2.16.6-54-g43a63f5

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by emptyrivers** [comment] 2020-03-23 19:54
This is likely a duplicate of #2061. Please update to the latest alpha.

**Closed by emptyrivers** 2020-03-23 19:54 UTC
Labels: 🐛 Bug
