### ISSUE TITLE
Performance degradation with Azerite trait checking auras

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#738] opened 2018-09-09 22:12 UTC
**Describe the bug**

Upon entering combat in a raid/group there is a big drop in FPS happening, seems to scale with amount of actors and AoE that is done. Mostly happening on Protection Paladins.

**Do you have an error log of what happened?**
 

**To Reproduce**
 
It might require having Azerite traits and a Protection Paladin, making this very hard to test. This is very vague but I haven't nailed down yet if it requires all 3 attached groups or only the Paladin one.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

Paladin group: https://pastebin.com/y6BCXtx6
General group 1: https://pastebin.com/EaEeMHED
General group 2: https://pastebin.com/snZDk5iJ

**Comment by emptyrivers** [comment] 2018-09-10 05:59
Those are all full of buff triggers. Perhaps it's just related to the...uh...*bold* change to UnitAura that blizzard did in 8.0?

**Comment by Stanzilla** [comment] 2018-09-10 17:05
The reporter said that sometimes the lag stopped when he turned of one group, sometimes when he turned off two. it certainly seemed like something was "stacking" lag which could very well be what you said about the UnitAura change.

**Comment by InfusOnWoW** [comment] 2018-09-11 21:34
So let's see whether there's anything unusual about those auras and keep a bit of inventory
Group 1:
19 Buff triggers in 19 auras
6 Color Animation

Group 2:
50 Auras in one Dynamic Group <=== That's  insane
47 Custom Text function update on trigger update, calling SetPortraitToTexture() on the region
41 Buff auras
6 Fullscan Auras

Group 3:
87 Auras
65 Buff Auras
22 Fullscan Buff triggers
25 Color Animations

So while it'd be interesting to see the profiling log, it's pretty clearly that optimizing there are only two potential areas: Buff trigger or Dynamic Groups. I know that both are pretty suboptimal and my gut feeeling would be that it is the buff trigger.

@Stanzilla can you get him to run the profiling again? I'd be interested in seeing whether the dynamic group shows up at all.

**Comment by Stanzilla** [comment] 2018-09-11 21:36
I'd say bufftrigger as well and yeah, I can.

**Comment by Stanzilla** [comment] 2018-09-12 01:15
Another example group for monks that causes the same issue: https://pastebin.com/XQRE9y6X

FPS issues are gone after disabling it, Profiling will be done again soon, other thoughts that came up: 

```
these WA were built back and forth between beta and live legion (aka a client where blizzard changed shit and one that didn't) over various weakaura versions. is it possible they are just corrupt
and if i rebuild them on the live current client the will be ok?
```

not sure if a missing or bugged migration could cause issues like that but table data should maybe looked at?

**Comment by Stanzilla** [comment] 2018-09-12 01:53
[test1.txt](https://github.com/WeakAuras/WeakAuras2/files/2373288/test1.txt)
[test2.txt](https://github.com/WeakAuras/WeakAuras2/files/2373289/test2.txt)
Profiling Reports

**Comment by InfusOnWoW** [comment] 2018-09-12 06:47
Those profiling reports match neither setups....

**Comment by InfusOnWoW** [comment] 2018-09-12 06:52
I'd prefer a report of just the 3 groups in the original report. 

And I assume that the performance issue was reproducable with just those 3 groups. Please confirm that.

**Comment by Stanzilla** [comment] 2018-09-12 10:51
I can try. General thought though, should we batch aura checks instead of having hundreds of them? maintain a list of active buffs instead of having each aura check?

**Comment by InfusOnWoW** [comment] 2018-09-13 06:16
Well, we have a list of bufftriggers (150) and a list of buffs (40), whether we check them by iterating over triggers and checking against all the buffs. Or by iterating over buffs and then checking against all bufftriggers won't reduce the amounf of checking we do. (I suspect iterating by buff to be faster, due to calling drastically less UnitAura calls, but in essence we are still doing 150*40 checks)

There's a way to drasticly reduce the amount of checking. Built a map from "buff name"/"spell id" to "aura/trigger id". Iterate over buffs, check in the map which triggers that affects and just do the additional checking for e.g. stacks/remaining time there.

Some care must be taken to accurately figure out the state of missing/always active buff triggers, but I think I have a good plan how to get there.

I'll probably work on that on the weekend.

**Comment by emptyrivers** [comment] 2018-10-02 19:58
https://clips.twitch.tv/UninterestedBlightedLettuceCurseLit some testing that sloot did, the new code in #755 seems to improve performance noticeably.

**Comment by InfusOnWoW** [comment] 2018-10-06 21:54
The buff trigger 2 code is now finished and will be part of one the next releases. That should fix the performance problems.

**Closed by InfusOnWoW** 2018-10-06 21:54 UTC
Labels: ⚡ Regression, 🏃 Performance
