### ISSUE TITLE
custom text of icons won't show until i uncheck/check the text checkbox after each reload

### ISSUE THREAD

**Issue by githubcmass** [WeakAuras/WeakAuras2#1020] opened 2018-12-12 15:26 UTC
This issue appeared after the 8.1 update and/or the latest WA update.

I'm having a set of icons which are displaying either custom text such as 

function()
    local boolResult = "no data";
    
    local nbCharges,bsMaxCharges,bsStartTime,bsDuration = GetSpellCharges("Barbed Shot");
  
    return nbCharges;
end

or simply display stacks %s

but now, after each reload or reconnection, the text value will not be shown until i edit the wa, uncheck the "text" checkbox and then re-check it.

**Comment by AttiqusTheBear** [comment] 2018-12-12 15:33
I can confirm this issue is happening with my WA that shows quest counts as well.

**Comment by mrbuds** [comment] 2018-12-12 15:35
it seems to be related to #1017

**Comment by githubcmass** [comment] 2018-12-12 18:07
Not sure it's related but this is a WA exception i m getting on login

Message: Interface\AddOns\WeakAuras\Locales\ruRU.lua:616: unfinished long string near '<eof>'
Time: Wed Dec 12 19:05:10 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\Locales\ruRU.lua:616: unfinished long string near '<eof>'

**Comment by InfusOnWoW** [comment] 2018-12-12 18:08
That's unrelated and already fixed.

**Comment by githubcmass** [comment] 2018-12-12 18:09
Also if i edit the custom function and save it, the text show up again (until next reload)

**Comment by InfusOnWoW** [comment] 2018-12-12 18:32
That should be fixed in 2.10.8

**Closed by InfusOnWoW** 2018-12-12 18:32 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate
