### ISSUE TITLE
WA Options Frame breaks down (see #2106)

### ISSUE THREAD

**Issue by Nikio87** [WeakAuras/WeakAuras2#2108] opened 2020-04-16 12:37 UTC
## Describe the bug

Expected: The weak aura option frame and all auras should have loaded. 
Actual behavior: No auras were shown and the WA Options frame did not respond to the commands /wa or /weakauras 

**Do you have an error log of what happened?**
This is the error from BugSack: https://pastebin.com/t2nagGif

I edited my WeakAura.lua to break down which Aura was causing the issue. I put the pastebin link into the error description.

### To Reproduce

1. Import the weak aura of this pastebin: https://pastebin.com/EGuB68QE
2. Start the game on any character
3. See error in the BugSack addon

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I tried WeakAuras without the WeakAuras.lua file. This works.

**Which version of WeakAuras are you using?**

I am using WeakAuras 2.17.0

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

The version before 2.17.0 (I am updating by using the twitch tool so I would think that the last working version is the previous one (it still worked yesterday evening))

### Additional Info

https://pastebin.com/EGuB68QE
```
  ERROR HERE
  https://pastebin.com/t2nagGif
```

**Comment by mrbuds** [comment] 2020-04-16 12:55
Sorry i though you had an other issue on top of this one

duplicate of #2106

**Closed by mrbuds** 2020-04-16 12:55 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate
