### ISSUE TITLE
Actions - chat message - Send to [Focus]

### ISSUE THREAD

**Issue by Aiv3rs** [WeakAuras/WeakAuras2#4517] opened 2023-07-03 01:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Expectation:
Attempting to have a whisper message automatically delivered to focus player when buff is detected, no matter the realm of the focus.

Result:
Can't send whisper to the focus target if the target is not in same realm.

Other Attempts:
Tried using [%2.name] in the "send to" but it doesn't work if the player in "focus" is not on the same server. Was told to use [focus] however that doesn't work at all  [%2.unit doesn't either].

### WeakAuras Version

WeakAuras 5.5.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

WA currently setup for DK
1, group someone from an other server and set focus on him
2. make sure you have the talent [Cleaving Strikes] 
3. cast [death and decay] under your feet so you have the buff [188290] active on you
4. you should see a message in chat [No player named '[player name in focus]' is currently playing.

### Last Good Version

no idea

### Export String

```Text
!WA:2!1r1tVnoru8gksRKfcfcOkyzbLTikBbrPnWUArApqDvIArPTbh3)GwTYDSNXXtXEMHzg3Tzpgqahr5gx4qoWjoLBCd1pbJIq8bOFe6NaEJTZUlW25G9BEZV59(9EZ79Q1PrwdCd8p9bsEUoLYiY9pWV7o712lINYLF5IWAkMQePOH(KZ1nAotLGW8h)17hhRi6BTWuelkHl7XPmD4wT3ZVTNO5ZDJGyUmdPdebAAgPAxnr9OCLMNzrCGaJ0epYzeM(suoOfPPrhrX6e3nHTsuKMYzQ75P0iP(heVtgrPqdMBSGwRjjO0SQTUmoJiU1)dtoJoNmM6tW8GkeNiReC1eL(I53tpuqKhT9o97bb0RpxlgGeqvwBDIy5xOp(xKXu)IN)QY3V1AmugXLcaxzmqIY0qsy5)LDCcJHZujlzAKmslPdgqKQFDfzL4V5A5LhkxIADH9RsqstPy1nd34(3V1NVUXjCBW)6Klv5HfP0Essm9Cpio62Dub8DWkhxlvdTpse5v5ks7ZHSC)YtpXZYrLZtnr)8yWetd2AZ((b9930ZFcMeck9TjPTB3TxNd6ooNvrsNvmn)7zGrdS2PiDKyUTz1XpD7eR0hxiEPfhkuXLH7YXKtmoI34aGBn3kbzF5jsQckhuJS4kY7JTsrPiLk5Y5klFssM8mzZhAw1lMd5vVcSH982PDFFrJN5pBIQ0NFIzDZgo2c9tZzq12zKwO0urJQI0YWQlFans8G4ceC2DQI2vDAcljrNlznR09WnEuted3CoMh26rR6qyyXRHkSELfTo)3xqS813UKXXbsO74eXkxpOuYau0WG4uoxMm6XCj(ijsm6Okb3yotlQ3rsFsZVkhHb7HA67pbED9idSDw3CjZTNbBdrrFZaysad7MYr4oUk6til5LLNQPoUqTt0sM9CmpW(nuJsHsdR4iRd6dqFRQHdhxoCyXjYc7BRsGMRZ1xbZiisgk9qOOgo47MbT7WWJ9ffn4oI376dsHKerTxArXB)crvk4zbJNeXzyAPrLdlzZ2FXHl8slal5PWRknEOB32D8NO5rNvYM3S2p(YltXJ7rBNr1arhRiPXLd2C333F)DNglH62(ABgCXRkh81XQYgHH93YRD79cbxhth40kNINU7X71607C4bF66k55v04ph9h)Ypd0q8rxFWIhcni0OaDIKOs4P4HtlZSBvmvUwTAlob6ij4IPKF)RmLYknaegoJrmAP49mVAhOXR(feKYsBcBGo5gZWWCd7XLZ4ueBYsnYIXghM6UzikR4Ig2nmCJW8TG47(F10q5D31U7AFwJZ(RJ)Np
```

**Comment by mrbuds** [comment] 2023-07-03 12:48
This is not a bug, please use discord https://discord.gg/weakauras for asking help on how to use weakauras

**Comment by Aiv3rs** [comment] 2023-07-03 15:05
Sorry for time wasted, I got referred here by someone from the Weakauras discord community :/, I'm kinda lost on how the procedure should be :/

**Comment by mrbuds** [comment] 2023-07-03 17:49
https://discord.com/channels/172440238717665280/1113912167834583090/1125231279340781630 this should work but reporter say it doesn't

**Comment by Aiv3rs** [comment] 2023-07-03 17:55
https://www.youtube.com/watch?v=bjdRQIApDJ0
made a video to show it

**Comment by InfusOnWoW** [comment] 2023-07-08 17:59
This should be fixed in the next release.

**Closed by InfusOnWoW** 2023-07-08 17:59 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
