### ISSUE TITLE
Please add a Name/Description for Triggers

### ISSUE THREAD

**Issue by GSPortfolio** [WeakAuras/WeakAuras2#2674] opened 2020-11-04 05:28 UTC
**Is your feature request related to a problem? Please describe.**

When I make Weak Auras, I often have 4-7 triggers.
Making conditions is cumbersome, because I need to try to remember specifically what "Trigger 5" was.

**Describe the solution you'd like**

It would be nice if each trigger had a name / description field.

If left blank, things would continue like normal.
If filled out, other areas in the Weak Auras config menu, such as the Conditions tab, would refer to it by the name you provide.

**Describe alternatives you've considered**

I haven't found another way to achieve this or circumvent the problem.

**Comment by InfusOnWoW** [comment] 2020-11-04 11:24
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/705

**Closed by InfusOnWoW** 2020-11-04 11:24 UTC
Labels: 🎨 Feature Request
