### ISSUE TITLE
Groups within dynamic groups, dynamic groups within dynamic groups

### ISSUE THREAD

**Issue by Knbi** [WeakAuras/WeakAuras2#5544] opened 2024-11-22 05:54 UTC
**Is your feature request related to a problem? Please describe.**
Right now, if you want things to grow in a different way inside of a dynamic group your only way of doing that is by attaching another dynamic group to a weakaura inside of a dynamic group which creates all sorts of problems in its own way (if f.ex. the weakaura you've attached to is centered vertically while the weakaura(s) you want to attach are supposed to grow centered horizontally). Also, if you have multiple auras you'd want to group, dynamic group doesn't allow simple groups inside of them, which is also annoying.

**Describe the solution you'd like**
Allow (dynamic) group(s) within a dynamic group, where the parent dynamic group is handling sorting in one way and the child dynamic group is handling sorting in other that the user specifies.

**Comment by emptyrivers** [comment] 2024-11-22 06:02
It's on the todo list. But, don't expect anything within the next couple of expansions.

**Comment by InfusOnWoW** [comment] 2024-11-22 09:06
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/3786

Also you can use custom grows to customize the growing.

**Closed by InfusOnWoW** 2024-11-22 09:06 UTC
Labels: 🎨 Feature Request
