### ISSUE TITLE
Trigger to check against spells that have been queued up for the next swing.

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#1645] opened 2019-08-30 12:21 UTC
**Is your feature request related to a problem? Please describe.**
Currently in classic there is no trigger to check if something like Heroic Strike has been used and is currently queued up for the next swing.

**Describe the solution you'd like**
This can be done easily using `C_ActionBar.FindSpellActionButtons()` and `GetSpellInfo()` so creating a trigger for something like this would be quite hepful.

**Comment by mrbuds** [comment] 2019-08-30 13:13
i forgot that this is duplicate of https://github.com/WeakAuras/WeakAuras2/issues/1628

**Closed by mrbuds** 2019-08-30 13:13 UTC
Labels: 👯‍♀️ Duplicate
