### ISSUE TITLE
AV detected as 25 man and not battleground

### ISSUE THREAD

**Issue by redaxe11** [WeakAuras/WeakAuras2#4311] opened 2023-02-10 06:29 UTC
### Description

Alterac Valley is being detected as a 25 man raid and not battleground for the "Instance Size Type"

### WeakAuras Version

5.3.7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Go in to the AV battleground
2. in WA, select Load then Instance Size Type - select 25 man
3. You will note that the WA will load when in AV
4. Toggle 25 man off (and toggle Battleground on) and it no longer loads

### Last Good Version

not sure

### Export String

```true
!WA:2!vN5AWTXvzF8QQwsQsHjXj15cUTQHux3sQJTCSDsAsPwo2Xk1XYDLCCAgOAVDK2nE1UB2DLDKB5sm9Tyk3kgOa99LBcOuG2ciGYqhcT1eAH5DEN5PUx(a8YmTE4wl8PqNHVYZZ5SYsoXzk0mmd5lYRo7z3Z58C(9))ZZroYHBYxQ727Q9EBQyt6nPpBpZP4PnmZUqGX928IQoE6mVKkAtO7546U2KwMtpTINE8SoowbMUQtPuWj1(NZpvpJ0FQ(kESfukfy44L2nW0X2pMx505Z7ZcoDlNX3XlyOYQEM6zvuTy5xCqlf)jIlXkAAJJHr1bpu9VSyFEfD8A4M9LQ(xCx3HuSvIFawXgBBCMLv8bz61BRs(sww9B6PzXKL8Dv0yRjrjpl3nBee46VNDSdAY3UPZogxzxdvEATm2EkA85Dps(bkEbXsAABgetnp(hFJyZe4zwOaZZFlT6fE59vrNPwkF(SLDzEdnWWJo4ydNma)IKsjpLeZ47IZQu6(Xw0VKkBsMDqgS3MNOAU(7lt2CzY2NuwjBLISg6XOEmShszgDGHhwI3I6qmfRaJKLWzJQRLszM3CLSdNcXQQ5yvQODgAbg9mM2bmpBfRdJZtCPCY5uSnlQqRQEGRAqOLK2o2S5zk(SmbE8T5vTGooxPEKJM5E(mnhBD)zO(qRly7jlQyAJplSD4Mxf0oSdOd8YnE2TiPyzwWwT)bgj7asj1z(AURpz54J(l(rw3CFELkOy12yzUX29WylnXJ4nPyoUQk4sxIvGtmZ45mLyPK0YrrFq1aflme0SuXsiWfljgr1Ag2BmjneF8PRs6BonJUyoFMv(rDWia01cQHmB)owoEhmA0OJgTJ27w1tr3SK)9ELEIWcZOQaXfDlsKirL81WrmAfngfjPaWwhwsv0lJkI)oGEbM76YC8skES4dIuw8Xnmdyv84lc6zMxVmUTAQvWZPKB4tLbNNxUKLzrZG1KKKdW2vXqDEZcXMPKpBy6g1MpPSrvt0fXBJrl7GbrW0XtvQV9NASmvZ7HedU9PeOeDEr)fYSRq1NveJQsD2EhTNOsGJwyiE1t(mB1u39Qh1X6g8JpE6SdF7XhxXZYrRUc037eI3sK5kGQ0Xn1dmwZzuS1q98G0isRl1m9lnWaJuv0CyWorjt9QTjDWu90BPXVtL9Nex1tvzO0sPoA6rY23WZqVpEKuA)Q(oL80yQMfDXiqfc1mfEfvnTZ74jyvcdc4xfPjT7F22QyIDmd)jJcxo82GvhbUlCxwdTH0DMYoZuMUm55R9vA)Xij9mYWMUMwHn)YEyaEeCnidxleFbCq0my(zmCMkT9c(8)CitFFt7cW2GRh2k8UMJeWCL5nn3GmR4CdPQ7Nv0XwC98uh46BtD)9iTZU6yN9qF2XUOptSt4AIbTc3WzWbEGtGBFzewbgOO5QHRlgSf4DcTfdNBpi2sR08lNs(jmQsxmjZWeDTmGTvP)LcqeJKJSaK59XJ5hGZxJ54pPL5K4AdhVW3R76iRSjzzfMehYrN9OxcCtN8mtWyU9rIOajk(Aa3g0fAI5ReqMa4q27QGDTNMHwwafLKiIiyB9z3GBtbSteKZ3qbJWhjKuC3mVr(hInVC(HxaBFULU3wVEF312WJxxTTOO1Ac3K9nw20URN3iMjXHObnojMSp8RNrmqMNGjWZtUGGdVZWPZ887FSsyKjFzCDXHiwwSXKJKEKbGw8Wff1Nk8oQvZBi6CHRa7a31oON50XVJsk6K(kE2SlBHxBKwG32uO2BCpf3zgp8Ifw69WZiKESSdNAKbcx7nOzCxxQrgzaPCjtNnB6djL6adLT(Js(eBoCLDKLTYM003eZDk)YluWYzQb9yhVeZwR8OxgQ27wS6OBmpIehWkmmBmd1enDwqTuqGJDA0taZHuHAwKO)QQsxFNlP(R9O8qd)EhPX7LHBqMKU0GprYI06e2mF)O87pSjE964V)KcBtvdMzbJafyptoNNIPEophlg30lhzEBa3c3)M(o3wxg2h1aCRTQsAslM349jnC6(VDQX3dERbteWSLLCXK0LLRemf6vxopjbs4oPRmOdm4GGfSbmNxmO5yWgJbfAUkcMASbOmQ4i8Uf5dxEoTopm0IQlkTyb8VJ36jKClz5Z4D5Cs5bnbRhwvmix1tyE0olNOWo3DBPCBcxi9hAfHkpuOXKD3qnZjch3VPpvee6gCyyC4iH2ZRD5v9epH0ueLRGjwDnuIcVx49bzJcPJ5zAtg7yG7OrsoTJtXiq(yZuBamKQd2ZEJGzKgCmHJjZNZngz4oKZ2mwnGMHcPaoa68PhNBy5JadBgm3wrY9mIylcnecKDxhDDbMnZZut4KkVWY(6IcJ1Arc00JhzYzARzvsN1VHIxbMVrfQTPykUKBn5E1ssA8iJA(TeVf555pA4erwv8aqNCVWWzUmSTfhN3E8beTiXNRnLGC0vfViWj0zEr(9Y5G6ufm56w37(e(Xpm5hpF4e1POQsGbugTIHPH7oCwGRjr73Jb8(B02f(aCxw4dY9vHpuD7u4KZUbyMOWhgHM7f9dH)lU)hCFWhbMf(OW9Fs4Jfb(44d9jGpj29pf8a8nq4tdZbFMTFjWNf(CWdMCeC7a(cyVEOuW)De4)r(LHVun5p8LHVIb8vHVgu5QGVEe4BiEbFZiWdhf(wgWJef(2Rd(ogW3ffI3h84YjX6DzXGhlu)bpkP4GVh89PViuGKyRh4hidvLHFyDH1Qi9e8JLrSdEgXW8urqvW4w7FKJ5Q6m5XparQ)mf4jxoIVH6uv8LaD4urHFQmhVpAeeVHFUX5xEcpXskt4NCEuLyAuDtFQs5uynaB6sxZFdEAdWsUUAiCsVCrHvy1cZUXeESIjWC5lsoPujCHqpwxJDABRYYWZvvGtsmf9YeEvTq9(1uhep4U(gAkDnmBF7dNT)VG7wCBglOjmuiX8l55X4N(aMYaEwEDkW2C3un1t8r9CkGgt(XBlfkcUr40R(bUwW)Gs7mXU3D38cpsi1tND1zp4Nu5h)FYeNxuUkUuQn4nDRuLhTkXNxQ4Ad3bKfu)tqS8l2aPdVKbhSrXaY4lY9LnZBQjQp7FsEpYBrEpIa3HppY6Fr4H28fgR)SOFjFjhJ7wmngXXZKvJ65G(zcTrOTk0bdnMFC5gedpMrfDt8GBA4HqkJTQAt14yb7Tzy7YlyYlsxJXp)eE3Ra2B(3U8gUs5lBnYB7kLxJ8BetMexNhX0YYsfd(nB6s3qtxy8)rjTy3EshT3BVRH65O(K48C0IvZKPUcm7skWtfnubIA8jmib(t3GUbFZNhnZwiISf4xkJOnSirWph8Rq251GFTb8kOI4fi0NWMxLUa5UFNmH6eN7Fq43d)b4pc)jcBFESZBRcr5X7N2pi1fXYKS5pJi8Vf()jm(1nQrUeIUsORWD(V8FcWkcMNdSIamcRpcNxRdRtsKYswYpE9sHQXINhk6P57v4M2tXTqpLOCHZAlFOg2YX9BHfDOxyUQwzNCmN7ONXsoWGeaG7(c0CJC6e5Y1EReGkqte3iQBLrtQvcp34z3VzBdmB5swzl4ZA8eyvt8TBevOe34U(RKSZo64657OfnGPK5Nx7vBAVCiXFlsD3vVD3TGwUAoTqGaXyVUCT07iqCEqfcKohw5cz5ErnK1kbznsyYeEHcEs9iqmK1wwbSl)30lEIALSIugIB5Q2ME6b35UoO5qmFIWq3KNKJTivHMjKntiCSI(m3fbeR)Sbc4VZ3)lkszsBF0PMP6ZIpStbbxCtsD3Bx7E30Nj6fnOMP2Vw4sKcv(3ucw41LFZmwqccPfKzeWcvSXXkzZpWDcflRloYk(wIbcfT4(v(yIs(6FKSDOmsxjMOTDTYL8T(Z5xMf5I6v8HiLiFZsYFrMq0Uz93gXCxizcjIk6B2XFEhewTo4VYxUVgvvSPUOO(xsC4KHu8hLfi2TXTEcZeibVCII8Ag05hgGttTYzoeqq68ULVOPkPg5HMVf5)fs9SQyHarJhfOy)d35e5B74h6atSICX8yi9FNNaGaOlBacGW6(RN1bNRRqgNqsO9ZjJdTtsom8ZLI(eygMEXQR35sPDMsqkuP2g88nxxSZkDZ9SKbIaPiMqyGupDd3T50RE(tt1p9SusT3G37NxCscQQiQ6hQIQxahJvi)0BX40fZEt9e6nvTojsYRclXHwcXEUQhFKokvUx9DRzogHzNLb1Ah3K(FA5voo9REvapGncRNQHFUfIgFQiIsHr(SPjFXJ8po
```

**Comment by mrbuds** [comment] 2023-02-10 06:44
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/3300

This is a bug on blizzard side

**Closed by mrbuds** 2023-02-10 06:44 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
