### ISSUE TITLE
Request to add an offset option for text

### ISSUE THREAD

**Issue by zeru0** [WeakAuras/WeakAuras2#499] opened 2018-07-20 13:15 UTC
Please consider adding an offset option for text that shows in WeakAuras. For example, if a text anchor is set to "Bottom Right", it would be great to still be able to fine tune the text position with additional X and Y offsets.

Currently, when using both Text 1 and Text 2 in the same weakaura, there are often text overlap issues on smaller weakaura sizes (icon).

**Comment by InfusOnWoW** [comment] 2018-07-20 13:21
Duplicate of https://www.wowace.com/projects/weakauras-2/issues/550

**Closed by InfusOnWoW** 2018-07-20 13:21 UTC
