### ISSUE TITLE
Strange behavior from auras. Error on every frame in options.

### ISSUE THREAD

**Issue by phoenix7700** [WeakAuras/WeakAuras2#1276] opened 2019-04-01 12:33 UTC
**What steps will reproduce the problem?**
Created this (https://wago.io/hhg8-lIlc) weak aura group.
type /wa to bring up options with /console scriptErrors 1
get an error and every frame when the aura is visible.

Message: ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:368: invalid option in `format'
Time: Mon Apr  1 07:27:45 2019
Count: 1993
Stack: ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:368: invalid option in `format'
[C]: in function `format'
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:368: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:348>
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:401: in function `TimerTick'
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:450: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:450>

Locals: (*temporary) = "%.-0f"
(*temporary) = 5.878995

I believe this is causing strange behavior for the aura group. Some of them will appear at times they shouldn't or not disappear when they should.

**What is the expected output? What do you see instead?**
I expect not to get an error when the aura's are visible.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, I also re-installed WA using the twitch app.

**Which version of WeakAuras are you using?**

2.11.6

**Was it working in a previous version? If yes, which was the last good one?**

This was never tried in a previous version.

**Do you have an error log of what happened?** 
 

**Please provide any additional information below:**

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 

**In case you do know which aura is problematic, please export the string and paste it below.**
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3029361/WeakAuras.zip)

``` HERE ```

**Comment by emptyrivers** [comment] 2019-04-01 12:40
??? This is a duplicate of a previous ticket. You have corrupted data in that aura, reset the remaining time precision to revive it.

**Comment by emptyrivers** [comment] 2019-04-01 12:41
Can you describe how you managed to create that aura?

**Comment by phoenix7700** [comment] 2019-04-01 12:47
using the custom trigger editor in the options

**Comment by phoenix7700** [comment] 2019-04-01 12:49
like new>trigger>status>cooldown progress(spell)
type the name of the spell. etc. Using the checkboxes and pre-filled forms

**Comment by phoenix7700** [comment] 2019-04-01 12:51
I did a bit more testing and noticed that the error was only showing up when either cloak, vanish or adrenaline rush went less than 60 sec left on the timer. the timer got stuck at "1:00" and errors started

**Comment by phoenix7700** [comment] 2019-04-01 12:54
I switched remaining time precision back to 12.3 option and the errors are no longer appearing. but when I choose the 12 option (which is the one that i wanted) the errors occur

**Comment by phoenix7700** [comment] 2019-04-01 12:56
seems to be a problem with that option under General Text Settings>Remaining TIme Precision>12
I've switched all aura to use the 12.3 option for now

**Comment by mrbuds** [comment] 2019-04-01 14:05
Are you playing on a Mac or Linux ?
Also if you change precision to 12.3 and then change it back to 12 do you still get the issue?

**Comment by mrbuds** [comment] 2019-04-01 14:11
And do you use elvui/addonskin ? If yes, can you try with them disabled ?

**Comment by phoenix7700** [comment] 2019-04-01 14:20
Im on Windows 10 and Im getting the errors with all other addon's disabled. If I set the precision back to 12 no errors until I either reload or hide the auras and make them show up again

**Comment by mrbuds** [comment] 2019-04-01 14:43
Which CPU are you using ? Do you use any exotic or very new hardware ?

**Comment by phoenix7700** [comment] 2019-04-01 15:18
Intel i7-7700K EVGA GTX 1080. I'm using and acer monitor with G-sync? dunno how or if that would cause it. I just remembered that I also have TSM's Desktop Application idk if that would interfere in anyway. Also I'm using a VPN

**Closed** 2019-04-02 18:50 UTC

**Comment by emptyrivers** [comment] 2019-04-02 19:00
So, this turned out to be an issue introduced by Blizzard. We’ve implemented a workaround which will be available in the next release.
