### ISSUE TITLE
Weakaura interface bugged 

### ISSUE THREAD

**Issue by alylin-stormrage** [WeakAuras/WeakAuras2#4341] opened 2023-03-10 23:11 UTC
### Description

When I first login into WoW weakaura and my imported weakauras work fine. But when I open the weakaura interface(I open the interface by clicking on the icon on minimap) all the weakauras that I have imported stop showing up/stop working. All the imported weakauras are all up to date, and so weakaura itself. I have /reloaded my game, to see if it would clear the the error, it does and all my imported weakauras work again. But then when I open the interface again for weakaura, all the imported weakauras stop working again.

### WeakAuras Version

5.3.7-33-gc0554aa

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Lua Error

```true
1x [string "local newActiveConditions = {};"]:59: attempt to index local 'state' (a nil value)
[string "local newActiveConditions = {};"]:59: in function `?'
[string "@WeakAuras/Conditions.lua"]:794: in function <WeakAuras/Conditions.lua:785>
[string "@WeakAuras/Conditions.lua"]:810: in function <WeakAuras/Conditions.lua:802>
[string "@WeakAuras/Conditions.lua"]:927: in function `RegisterForGlobalConditions'
[string "@WeakAuras/WeakAuras.lua"]:1881: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1677: in function <WeakAuras/WeakAuras.lua:1524>
[string "@WeakAuras/WeakAuras.lua"]:1870: in function `Resume'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:208: in function <...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:188>
[string "=[C]"]: in function `Hide'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:618: in function <WeakAurasOptions/WeakAurasOptions.lua:616>

Locals:
region = Frame {
 0 = <userdata>
 iconSource = -1
 AnchorSubRegion = <function> defined @WeakAuras/RegionTypes/Icon.lua:152
 subRegionEvents = <table> {
 }
 Expand = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:844
 yOffset = -47.799953
 anchorPoint = "CENTER"
 GetColor = <function> defined @WeakAuras/RegionTypes/Icon.lua:443
 icon = Texture {
 }
 SetOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:280
 keepAspectRatio = false
 SendChat = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:228
 SetInverse = <function> defined @WeakAuras/RegionTypes/Icon.lua:507
 toShow = false
 UpdateFrameTick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:393
 SetRegionHeight = <function> defined @WeakAuras/RegionTypes/Icon.lua:502
 UpdateIcon = <function> defined @WeakAuras/RegionTypes/Icon.lua:467
 Color = <function> defined @WeakAuras/RegionTypes/Icon.lua:414
 cloneId = ""
 Update = <function> defined @WeakAuras/RegionTypes/Icon.lua:636
 regionType = "icon"
 GetRegionAlpha = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:349
 relativePoint = "CENTER"
 SoundPlay = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:210
 zoom = 0
 UpdateTimerTick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:379
 color_b = 1
 UpdateTexCoords = <function> defined @WeakAuras/RegionTypes/Icon.lua:332
 alpha = 1
 color_r = 1
 SetXOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:289
 SetGlow = <function> defined @WeakAuras/RegionTypes/Icon.lua:643
 SetRegionWidth = <function> defined @WeakAuras/RegionTypes/Icon.lua:497
 triggerProvidesTimer = false
 RealClearAllPoints = <function> defined =[C]:-1
 RunCode = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:235
 GetYOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:301
 SetAnimAlpha = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:353
 ColorAnim = <function> defined @WeakAuras/RegionTypes/Icon.lua:429
 SetIcon = <function> defined @WeakAuras/RegionTypes/Icon.lua:450
 Collapse = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:822
 SetYOffsetRelative = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:318
 ClickToPick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:693
 OptionsClosed = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:688
 scaley = 1
 cooldownSwipe = true
 GetXOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:297
 SetYOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:293
 SetCooldownEdge = <function> defined @WeakAuras/RegionTypes/Icon.lua:523
 color_g = 1
 SetZoom = <function> defined @WeakAuras/RegionTypes/Icon.lua:531
 GetYOffsetRelative = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:326
 SetAnchor = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:268
 GlowExternal = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:243
 cooldownEdge = false
 SetRegionAlpha = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:339
 finishFormatters = <table> {
 }
 GetXOffsetRelative = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:322
 SetDesaturated = <function> defined @WeakAuras/RegionTypes/Icon.lua:493
 Scale = <function> defined @WeakAuras/RegionTypes/Icon.lua:484
 subRegions = <table> {
 }
 height = 59.999870
 startFormatters = <t
```

### Reproduction Steps

1.Login onto your character
2.Open the weakaura interface by clicking on the icon your mini map
3.Imported weakauras stop working

### Last Good Version

yes. 5.3.7-32-gf8e51c7

**Comment by mrbuds** [comment] 2023-03-10 23:13
duplicate of #4340

**Closed by mrbuds** 2023-03-10 23:13 UTC
Labels: 🐛 Bug, ⏱ Awaiting Response
